### ISSUE TITLE
Invite User Functionality

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1005]
## Test plan
GIVEN the user management page
WHEN the user is a superuser, admin, org admin, or org user manager
THEN a new button should appear in the top right corner

GIVEN the new 'invite' button
WHEN clicked
THEN a modal should appear in which it is possible to add and delete rows (invited users) with an email address, organisation, and group

GIVEN that a user or multiple users have been fully filled in
WHEN the invite button is clicked
THEN the user should receive an email that he or she is invited to use RSR
OR the user should receive a notification that his new employment is approved (in case of an existing user)

GIVEN that a user or multiple users have not been fully filled in
WHEN the invite button is clicked
THEN the missing fields should get a red border

GIVEN that the user is a superuser or RSR admin
WHEN the user wants to invite a new user
THEN all organisations and roles can be chosen

GIVEN that the user is not a superuser or RSR admin
WHEN the user wants to invite a new user
THEN only the 'Users' and 'Project editors' roles can be chosen
AND the organisations that they're connected with
AND the organisations that these organisations 'content own'
AND, in case of a paying partner, the organisations that are implementing partners on their projects

GIVEN that the invite has been sent to a user
THEN the fields in the modal should become green
AND after 3 seconds the row should disappear
AND if it's the last row, the modal should disappear

GIVEN that a user receives a new invite
WHEN the activation link in the mail is clicked
THEN the user should be directed to an activation page where it is possible to fill in first name, last name and a password

GIVEN that the activation link is expired (after 7 days)
THEN the user should see an appropriate message _(not sure how to test this easily)_

GIVEN that the activation link is incorrect
THEN the user should see an appropriate message

GIVEN that the invited user has activated his or her account
THEN the user that invited the new user should get a confirmation mail that the invitation was accepted

## Issue description
We need the ability for Organisation Admins or User managers to add users based on their email address, or for superusers and RSR admin to add a user to any organisation.

- [x] Option for Organisation Admins or User managers in MyRSR to invite users to their organisation
- [x] Option to enter one or more email addresses, and set the organisation (organisation + implementing partners for paying partners) and the permissions (User or Project editor) for every email address
- [x] If email address, send an email inviting them to join RSR and complete registration (e.g. fill in first name, last name, password) after email confirmation
- [x] If known email address, send a message to user notifying them that they have been added to an organisation
- [x] Notify the inviter when the invitee has activated his/her account

**Comment by zzgvh** [comment]
I don't think the workflow differs if you "know" the email address or not. You have to have an email address to begin the workflow, but you can't be sure it's correct. What might be an option is for the admin to enter the user information, but the email verification needs to happen in all cases before the user is accepted.
Also to consider for this workflow is the unlikely but still possibility of the wrong email being used, whereby the wrong person is given an account. :smiling_imp:
