### ISSUE TITLE
Add a default Organsiation Logo image

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1007]
- [ ] Finalise image decision
- [ ] Implement new image

**Comment by adriancollier** [comment]
Here's the image from Linda:
![rsr_no-logo-v2](https://cloud.githubusercontent.com/assets/1426234/5776542/5ab10b4a-9d89-11e4-8a6c-1e47dc25d155.jpg)

**Comment by adriancollier** [comment]
Maybe we should also use one of these for when a project has no image:
![screen shot 2015-03-04 at 13 38 16](https://cloud.githubusercontent.com/assets/1426234/6483706/57a5edb6-c274-11e4-9bfb-cea0e7fae4d9.png)

**Comment by KasperBrandt** [comment]
Let's ask @loicsans and/or @gabemart what they think.

**Comment by rumca** [comment]
default missing org logo now works as intended
