### ISSUE TITLE
Upgrade Django to latest 1.6 release

### ISSUE THREAD

**Issue by carlio** [akvo/akvo-rsr#1011]
We have Django pinned to 1.6.5 but the latest release is 1.6.9. Most of these are small bugfixes but 1.6.6 is a security release: https://docs.djangoproject.com/en/dev/releases/1.6.6/

**Comment by carlio** [comment]
There's now a 1.6.10 release: https://www.djangoproject.com/weblog/2015/jan/13/security/

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the Django version in RSR
WHEN RSR is started
THEN the Django version should be 1.6.10
