### ISSUE TITLE
Enable debug toolbar

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1018]
The Django debug toolbar is really useful. We should enable usage by installing the app and document how to enable it while developing.

**Comment by kardan** [comment]
My local conf looks like this:
```python
if DEBUG:
   INTERNAL_IPS = ('127.0.0.1', '0.0.0.0', '192.168.50.101', '10.0.2.15')
   MIDDLEWARE_CLASSES += (
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        )
   INSTALLED_APPS += (
        'debug_toolbar',
        )
```

**Comment by kardan** [comment]
Besides this we should add django-debug-toolbar to requirements

**Comment by kardan** [comment]
After some usage we realised that the DDT is a bit slow so better to disable by default and provide commented out settings - so it's easy to enable.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the Vagrant environment
WHEN a new box is setup
THEN the local config file should contain a commented out section for the Django debug toolbar
