### ISSUE TITLE
Akvo Icons

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1033]
Linda has created a set of icons that we can use within RSR:
https://www.dropbox.com/sh/5tqnxjjuogktwni/AADaT9xE9HFqHnOCrFb-Vd88a?dl=0

We need to determine if these are suffienct or if we need further icons developed.

**Comment by loicsans** [comment]
https://www.dropbox.com/sh/5tqnxjjuogktwni/AADDaf6nQtaMZ3-sHteEoPHMa/Akvo%20app%20icons?dl=0
Those icons aren't readable.

**Comment by adriancollier** [comment]
I've added .icon to the end and I think this now works, they render in Finder for me now.

**Comment by adriancollier** [comment]
@loicsans have we implemented these now? Do we still need this issue open?
