### ISSUE TITLE
New User Process

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1042]
We need to ensure that we have a stable process for bringing new users onto the platform.

Problems with the current process:
- Everyone from Akvo gets an email
- Not certain who is responsible for approving
- All done via email outside of RSR
- No overview of pending or rejected users

With the v3 changes we have split up the new user process into 2 sections. Creating an account and connection to an organisation.

**Create a new account**
- A new user signs up on RSR
- User receives an email with a link
- User clicks on link
- Account is activated<sup>1</sup>

**Connect to an organisation**
- A user requests to be added to an organisation
- A message is sent to the correct admins<sup>2</sup>
- Admin confirms or declines the user within the MyRSR section
- An email is sent to the user to confirm the action and informing them of the admin that carried this action out

<sup>1</sup> An activated account can log in and view elements within RSR, but has no permissions on any project so cannot create, edit or update any content.

<sup>2</sup> A correct Admin is determined by one of the following:
- Being an administrator for the organisation
- Being an administrator for the organisation that is the content owner of the organisation the user registered to
- Being an administrator with the support option enabled<sup>3</sup>  

<sup>3</sup> A new option should be created on the user that allows them to be defined as a support user. This should only be used for Akvo Staff, and this will determine if they have access to all organisation data and not just their own network. If the support option is not selected then no new user emails are received.

Additional elements:
- Add a comment field to the Employment record that Akvo and Partner admins can use to mark the status of the registration. E.g. Requested confirmed from Head Office on 1-3-2015, awaiting response.
- We need to ensure we have content for the following emails:
    - New account
    - Confirmed registration
    - Employment request (to Partner Admin)
    - Employment request (to Akvo Support Admin)
    - User employment approved
    - User employment declined

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the RSR admin
WHEN a User is viewed as a superuser
THEN it is possible to set this user as support user

GIVEN the user management page
WHEN an RSR admin with support user rights visits the page
THEN all users should be visible

GIVEN the user management page
WHEN a user visits the page
THEN the page is paginated

GIVEN the user 'join organisation' process
WHEN a user requests to join an organisation
THEN all RSR admins with support role will get an email
AND all organisation user management or admins with support role will get an email
