### ISSUE TITLE
Advanced Filter - long dropdowns (Partner in particular)

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1052]
When trying to select an organisation on the advanced filter in v3 we still have the very long list containing 2500+ organisations.

![screen shot 2015-01-23 at 11 36 31](https://cloud.githubusercontent.com/assets/1426234/5873201/41c8f9d8-a2f4-11e4-98e6-9492a51171c3.png)

We should implement the same list options as we have done in MyRSR for the Employment selections:

![screen shot 2015-01-23 at 11 36 39](https://cloud.githubusercontent.com/assets/1426234/5873203/470da7c2-a2f4-11e4-95c7-ffb209841e65.png)

**Comment by adriancollier** [comment]
Some other thoughts from the product meeting on Thursday:

- When making a selection from the filter, the sidebar closes automatically, yet there is a button that says to close the filter options - this button is therefore almost never needed.

It seems to make sense either to change the button into a "Apply Filters" type button to allow a user to enter more than a single filter (such as Sector & Country) before then retrieving the results.

Alternatively we could change the sidebar so it remains on the page after the selection and application of a filter, so the user could again select another filter.

I prefer option 1, but I think both are reasonable.

@loicsans / @gabemart - thoughts?

**Comment by gabemart** [comment]
@adriancollier I agree that option 1 sounds better. I think it makes sense to be able to select more than one filter option before seeing the results of the filter

When we first discussed implementing typeahead, the consensus was that it was important to stay away from jQuery and use a react-based solution. Is this still an important requirement? At the time, I hadn't realized that the currenty typeahead system used for the main search input on the project directory page is jQuery-based, and jQuery is also currently used for submitting the django-filter based filter options in the side panel.

**Comment by adriancollier** [comment]
Thanks @gabemart 

AFAIK the React vs JQuery  requirement comes from an architectural simplification point of view and was provided by @iperdomo here: https://github.com/akvo/akvo-rsr/issues/1100

**Comment by loicsans** [comment]
The close button on the sidebar was just added to close the panel if you triggered it and you don;t need it.
First option is definitely better, also we need to first reimplement the filtering system totally. For now, each time you select one parameter the whole page reloads, so the sidebar disappears.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the projects listing page
WHEN using the advanced filter
THEN it should only search when the 'apply filters' button is clicked

GIVEN the projects listing page
WHEN searching for an organisation in the advanced filter
THEN it should be possible to type an organisation to filter
AND a dropdown with matching organisations should appear underneath the box
AND once an organisation is selected and the filter applied, the page should filter on that organisation

**Comment by rumca** [comment]
@KasperBrandt I might be missing a step here, but the second test plan listed above doesn't pass successfully for new organisations, it does pass for old ones though. When I create a new project linked to a new org:

![screen shot 2015-05-07 at 14 47 07](https://cloud.githubusercontent.com/assets/3003031/7516594/54b36ae4-f4c8-11e4-8d3f-4b0c51699205.png)

and then search for projects in RSR by organisation, nothing is returned:

![screen shot 2015-05-07 at 14 47 30](https://cloud.githubusercontent.com/assets/3003031/7516616/723f8606-f4c8-11e4-8df7-cfb7ad25fb71.png)

**Comment by gabemart** [comment]
the typeahead stuff is navigating to the correct URL:

http://rsr.uat.akvo.org/projects/?title=&location=&status=&organisation=2764&sector=

It's just not showing the project - weird

**Comment by KasperBrandt** [comment]
It shows one project for me, that is correct, right?

**Comment by rumca** [comment]
@KasperBrandt that's really strange - it definitely wasn't working yesterday but looks fine now

**Comment by gabemart** [comment]
Yep - was showing 0 projects at the time of posting but now correctly showing 1 project
