### ISSUE TITLE
Difficult to add countries

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1065]
With an empty database it's difficult to add countries. We end up having to copy our current table data to get it in.

**Comment by adriancollier** [comment]
@kardan is there a suggested solution for this? Surely we should ensure that countries are included within the data set in vagrant?

**Comment by kardan** [comment]
I think @KasperBrandt solved this by the country refactor, true?

**Comment by lauraroverts** [comment]
@KasperBrandt is this still an issue?

**Comment by KasperBrandt** [comment]
@lauraroverts Yes and no. It's still not possible to add a country, but when a new country is added, Annabelle usually informs me and I add the country.

However, we now have our own country list in RSR, and IATI also uses a country list (which we also use for some fields, such as recipient country). I think we should completely switch to the IATI country list, but that also involves some other changes (filters on RSR pages, etc).
