### ISSUE TITLE
Admin expects a user to have an organisation

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1066]
Trying to add a new project without having a connected organisation crashes the admin (at http://rsr.localdev.akvo.org/admin/rsr/project/add/). 

line 638 in admin.py   initial=[{'organisation': request.user.organisations.all()[0]}],

**Comment by adriancollier** [comment]
Should we look at removing the option to login to the Admin unless you are connected to an organisation?

**Comment by lauraroverts** [comment]
@KasperBrandt is this still relevant now we have the project editor?

**Comment by KasperBrandt** [comment]
No, we should use the project editor from now on..
