### ISSUE TITLE
Return to homepage on Akvo Page

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1088]
When clicking on the logo in the header navigation on an Akvo Page, the user should be redirected to the return url (partnersite.return_url).

For core RSR, this should stay the same (redirect user to home/project list).

**Comment by kardan** [comment]
Testplan: 

There are three different host scenarios:
1. On the RSR_DOMAIN -> "/"
2. On parter page but on subdomain of RSR_DOMAIN
3. On another CNAME

And in case 2 & 3 two config scenarios (configured return_url).
If a rsr_page.return_url exists we should use that otherwise point to "/"
