### ISSUE TITLE
Replace third party JS components with React components

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-rsr#1100]
We have a mix of UI components from [Boostrap](http://getbootstrap.com/components/) and [react-bootstrap](https://react-bootstrap.github.io/components.html). The user accessing RSR page needs to load too many JS libraries.

We need to replace the Tooltips and alerts from Bootstrap with `react-bootstrap` ones

We're also using [Twitter's typeahead](https://twitter.github.io/typeahead.js/) that should be replaced with a React component, e.g. https://github.com/fmoo/react-typeahead or http://tonyspiro.com/dev/react-typeahead-search/

**Comment by kardan** [comment]
React based libs:
https://github.com/eliseumds/react-autocomplete
https://github.com/fmoo/react-typeahead

**Comment by punchagan** [comment]
Related to #2653
