### ISSUE TITLE
Maximum Image Upload

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1114]
I think that when you try to upload an image that is bigger than 2MB, you are presented with this error message:

![screen shot 2015-02-16 at 13 17 05](https://cloud.githubusercontent.com/assets/1426234/6231125/eed9dc3a-b6c4-11e4-9e86-615ca9efe0f5.png)

Ideally, users would be able to upload large images and we resize them down to a reasonable size (whilst also storing the originals somewhere). If this is not practical due to storage limits, then we should at least swap the error message for an RSR message that explains that a smaller image needs to be uploaded (with a link to an online image resizing tool).

**Comment by kardan** [comment]
Dependent on https://github.com/akvo/akvo-provisioning/pull/129
