### ISSUE TITLE
Add created_at timestamps to all projects and organisations

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1116]
To make RSR KPI generation easier having created_at timestamps for all projects and organisations would help a lot. Since @Lynngre has made a pair of spreadsheets holding this data for almost all objects that don't have it in RSR a simple data migration will do nicely to accomplish this task.

**Comment by zzgvh** [comment]
Bah, bug in the migration. Need to try again.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the projects in RSR
WHEN this migration has been done
THEN all projects should have a created_at date filled in

GIVEN the organisations in RSR
WHEN this migration has been done
THEN all organisations should have a created_at date filled in
