### ISSUE TITLE
Remote typeahead resource

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1161]
At the moment we're prefetching typeahead and store the data in local storage. Local storage is limited in size. The limit is different on different devices & can also be set by the user. The data we have to store is increasing with the number of projects, organisations, updates and so on we gain. Hence we need to create a remote resource for queries.

https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote

**Comment by adriancollier** [comment]
Is this related to https://github.com/akvo/akvo-rsr/issues/1052

**Comment by kardan** [comment]
@adriancollier nope. 

At the moment the typeaheads for different collections (projects, organisations, sectors....) on a page is downloaded when the page is loaded. For the project list page this is a fairly large download. We essentially download all projects, all organisations and so on. This data is cached in the user brower local storage. But since it's still a big download so we really need to implement that for each typeahead the client asks the server for possible suggestions.

However the server needs to respond fast, since otherwise it will be odd (and we have issues with this..). There is also a max size of the local storage, I'm not sure how big the current slimed down cache is. But before we tweaked it to only cache relevant fields it was big. And default max size in local storage is 5 mb (depends on what browser) but it's also configurable by the user. 

So with a remote typeahead resource we would not need an initial big download + would not have the possible problem with filling the users local storage.

**Comment by adriancollier** [comment]
OK it sounds like you both know what the problem is and how to solve it!

**Comment by KasperBrandt** [comment]
We currently have multiple typeahead resources.
