### ISSUE TITLE
No visible close button on map pop-ups

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1169]
Functionally it works to close the box by clicking in the top right hand corner, but I cannot see an X or other visual element to show this.

![screen shot 2015-02-23 at 9 22 20](https://cloud.githubusercontent.com/assets/1426234/6326218/c3a1c340-bb4f-11e4-967d-8a829f928cc8.png)

**Comment by KasperBrandt** [comment]
Fix here: http://stackoverflow.com/questions/16708324/google-maps-infowindow-close-button-is-hidden @loicsans can you add it to top-level CSS?
