### ISSUE TITLE
Stylesheet not found if using a CNAME

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1178]
We have setup an Akvo Page instance at http://akvoprojects.adrian-collier.com/projects/

This is rendering incorrectly as the core stylesheet is referenced as a relative value, we should change this to an absolute value so that the page can find it even when using a CNAME.

![screen shot 2015-02-23 at 14 07 14](https://cloud.githubusercontent.com/assets/1426234/6328225/86c55c3c-bb65-11e4-858b-ba35eb8f6597.png)

**Comment by kardan** [comment]
It's an Nginx config issue, talked to @carlio about it and he's on the issue!
