### ISSUE TITLE
Remaining ui issues 

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-rsr#1180]

**Comment by rumca** [comment]
minor one - but all the footer items except the akvo.org logo have a rollover effect:

![screen shot 2015-02-24 at 08 38 19](https://cloud.githubusercontent.com/assets/3003031/6346075/84f30fcc-bc04-11e4-80bd-90bd8484dcaf.png)

please disregard if intentional!

**Comment by rumca** [comment]
another minor one - when clicking on one of the top tabs the text disappears until the tab is loaded:

![screen shot 2015-02-24 at 08 57 46](https://cloud.githubusercontent.com/assets/3003031/6346095/a9847aec-bc04-11e4-9819-6ae9dcb545f2.png)

**Comment by loicsans** [comment]
I don't see that myself. It strange as there is no image loading going on there whatsoever.

**Comment by KasperBrandt** [comment]
I do see that, if you click on one of the tabs and then move your cursor away, they become white.

**Comment by loicsans** [comment]
I still cannot see that, could it be related to network performance?

**Comment by KasperBrandt** [comment]
See: https://dl.dropboxusercontent.com/u/11205536/Disappearing%20tab.mp4
