### ISSUE TITLE
Can't remove search options

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1191]
Safari on iphone (iOS 8.1.3):
Accessing home on http://rsr.uat.akvo.org
To reproduce: 
- typed DWA in search box and automatically the first possible result was filled out (at least that is what it looks like e.g. same font/colour)
- can't delete the text that is added 
- note: when i ignore the filled out text and hit go it seems to search for just DWA.

![img_1470](https://cloud.githubusercontent.com/assets/8478175/6351755/6422a76e-bc3e-11e4-947f-54d517cd02d8.PNG)

**Comment by KasperBrandt** [comment]
So the text after 'DWA' is actually a suggestion, but because it's the same color as the typed text it looks like it's already filled in. We should change the text color of the suggestion, similar to the My details page.
