### ISSUE TITLE
Sorting issue in location filter

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1192]
Safari on iphone (iOS 8.1.3):
Accessing home on http://rsr.uat.akvo.org
To reproduce:
- open advanced filters and select location, scroll down
![img_1471](https://cloud.githubusercontent.com/assets/8478175/6351903/93a2cfb8-bc3f-11e4-9dad-74630edb180e.PNG)

**Comment by KasperBrandt** [comment]
It is correct that the locations aren't in alphabetical order, we'll have to make a decision on how we actually want this. Several options possible:
- Alphabetical
- Typeahead (search by text)
- Hierarchical (e.g. World, - Africa, -- Eastern Africa, --- Burundi, etc)
