### ISSUE TITLE
Full data report alignment issue

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1194]
Safari on iphone (iOS 8.1.3):
Accessing home on http://rsr.uat.akvo.org
To reproduce: 
- go to http://rsr.uat.akvo.org/project/2089/report/
- 2 issues: data not shown (lower table) and alignment (the one above)
![img_1474](https://cloud.githubusercontent.com/assets/8478175/6352223/5f30caf8-bc41-11e4-9b2f-ecbd7d1e149a.PNG)

**Comment by loicsans** [comment]
This is supposed to be used for printing, not to be looked in small devices.
This needs complete rewrite of the markup, bigger issue to fix in an upcoming release or we can simply remove the link to this page on mobile phones
