### ISSUE TITLE
Facebook sharing: link not found

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1195]
Safari on iphone (iOS 8.1.3)
To reproduce:
- go to http://rsr.uat.akvo.org/project/2089/report/
- choose share on facebook
![img_1475](https://cloud.githubusercontent.com/assets/8478175/6352315/faf198e6-bc41-11e4-9351-75f93ac9857d.PNG)

**Comment by KasperBrandt** [comment]
Could not reproduce this one. When I try on my mobile, it does show the link and on web as well.

**Comment by adriancollier** [comment]
I also cannot replicate, I have tried on my mobile, ipad, Firefox and Chrome on my laptop.
