### ISSUE TITLE
Alignment of data

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1196]
Safari on iphone (iOS 8.1.3)
To reproduce:
- open http://rsr.uat.akvo.org/project/2089/finance/
- issue: field and data not alignment, sometimes with extra space (e.g. total) and alignment logo and name of org
![img_1477](https://cloud.githubusercontent.com/assets/8478175/6352416/c749286e-bc42-11e4-8075-ccf5111ac881.PNG)

**Comment by adriancollier** [comment]
I think it would be really helpful to have commas in large amounts like this, so:

€186,000.00 rather than €186000.000 as it makes the values much easier to read.

**Comment by loicsans** [comment]
fixed
