### ISSUE TITLE
Org logo display issue on map

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1198]
Chrome 40.0.2214.115 on mac 10.9.5

To reproduce:
- open http://rsr.uat.akvo.org/organisation/2563/
- result: logo not fully visible
(note: same seen on mobile)

![screenshot 2015-02-24 16 44 15](https://cloud.githubusercontent.com/assets/8478175/6352678/a79335c6-bc44-11e4-85a2-e7eb171c8514.png)

**Comment by loicsans** [comment]
fixed
