### ISSUE TITLE
layout of my projects

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1204]
Safari on iphone (iOS 8.1.3):
- see my projects: alignment issues:
1. details per project (2nd screenshot)
2. 'add update' button (1st screenshot)
![img_1479](https://cloud.githubusercontent.com/assets/8478175/6354787/0d874cc0-bc52-11e4-8b69-0e3ab6d99ac9.PNG)

![img_1478](https://cloud.githubusercontent.com/assets/8478175/6354752/e334027e-bc51-11e4-9495-d316fe2ee7c7.PNG)

**Comment by loicsans** [comment]
This requires a rewrite of the markup, therefore for now, the best compromise is to trim long strings on small devices, and should be fixed as part of a next release or hotfix
