### ISSUE TITLE
View project button

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1205]
Safari on iphone (iOS 8.1.3):
Below the project description there are a butch of things people can do. However accessing the project would be the most logical/used option. It is not superevident that this can be achieved by clicking on the project title so I suggest to either change the project title to the default light blue for links or to add a view project button (or both)
![img_1484](https://cloud.githubusercontent.com/assets/8478175/6354878/ac1af3aa-bc52-11e4-9bb1-a4eac45be75b.PNG)

**Comment by loicsans** [comment]
After discussion, the link to the project is prominent enough and is not a UX killer.
