### ISSUE TITLE
hidden cells in full data report

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1206]
Chrome 40.0.2214.115 on mac 10.9.5

to reproduce:
- go to http://rsr.uat.akvo.org/project/17/report/
- scroll to the right in the 'locations' table
![screenshot 2015-02-24 18 32 16](https://cloud.githubusercontent.com/assets/8478175/6355055/9b211a9c-bc53-11e4-8902-dc62514737ad.png)

**Comment by adriancollier** [comment]
I don't see an error here - we know that you need to scroll to view some of the fields, there are few other options available that still provide a good visual layout.

Have raised the thought of not displaying empty columns, but this will ship like this for now.
