### ISSUE TITLE
"Total budget" figure on projects page extends beyond container on 1000px viewport

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-rsr#1212]
![screenshot from 2015-02-25 09 15 45](https://cloud.githubusercontent.com/assets/2589977/6367847/fc391cbe-bcce-11e4-8a1f-6a2eaebd4f8e.png)

Cross browser on http://rsr.uat.akvo.org/projects/ when viewport is ~1000px wide

fix: 

    @media (min-width: 768px and max-width: 1200px) {
      .dl-horizontal dd {
        margin-left: 80px;
      }
    }

**Comment by loicsans** [comment]
fixed
