### ISSUE TITLE
Dismiss previous bubble when selecting a new point

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-rsr#1251]
When clicking one of the points in the map, you get a _bubble dialog_ with a link to the project's details. If you then click another one, the previous _bubble_ doesn't get dismissed.

## Steps to reproduce

* Visit http://rsr.akvo.org
* In the search box type: Honduras
* From the available list, select the option below __Location__ 
* Click a point in a map
* Click other available points in the map
* As a user I expect the previous bubbles are dismissed

![honduras](https://cloud.githubusercontent.com/assets/178474/6393845/b7a94cae-bdcd-11e4-9897-dd3f017afbf3.png)

**Comment by gabemart** [comment]
# Test Plan

1) Open the "Projects" tab

2) Click on a marker. A bubble dialog appears

3) Click on a different marker. Verify the first dialog disappears.
