### ISSUE TITLE
Page load time

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1258]
At the moment load page load time is too high. Needs to be cut!

**Comment by kardan** [comment]
- [ ] Get a more production like dataset
- [ ] Set baseline benchmark
- [ ] Enable stats for test / uat?
- [ ] Clean up JS deps
- [ ] Identify and fix slow paths
- [ ] Enable caching

**Comment by kardan** [comment]
http://www.postgresql.org/docs/current/static/pgstatstatements.html via @iperdomo

**Comment by kardan** [comment]
log_min_duration_statement at http://www.postgresql.org/docs/current/static/runtime-config-logging.html seems valuable to enable on the test server.

**Comment by KasperBrandt** [comment]
## Test plan
I've done a short performance test on the Test server;
- Project list: 3480ms - 11420ms = -7760ms
- Update list: 2848ms - 3356ms = -508ms
- Organisation list: 2132ms - 2216ms = -84ms
- Project main: 1518ms - 2728ms = -1210ms
- Update main: 1036,2ms - 1129,8ms = -93,6ms
- Organisation main: 1636ms - 1500ms = 136ms

So in general RSR has become a bit faster, but especially the project listing page has become a lot faster.
