### ISSUE TITLE
Error on view data from Partner website

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1259]
Not sure if this is something within our control or not - can anyone shed any light on this?
![schermafdruk 2015-02-27 10 58 26](https://cloud.githubusercontent.com/assets/1426234/6410486/0d2742b0-be70-11e4-9f12-21194a76980e.png)

**Comment by KasperBrandt** [comment]
I don't think we can do much about it, it's probably something in their PHP script. But the API endpoint they're trying to access (http://rsr.akvo.org/api/v1/project/1605/?format=xml&depth=2) is still working.

**Comment by KasperBrandt** [comment]
Fixed in #1289

**Comment by KasperBrandt** [comment]
## Test plan
No testing needed, the VEI website is up and running again.
