### ISSUE TITLE
All Updates for a project

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1260]
We're currently missing a view that shows all project updates from a single project.

In a couple of places you can see the most recent or latest, but we don't have the option to see all of them.
![screen shot 2015-02-27 at 11 13 18](https://cloud.githubusercontent.com/assets/1426234/6410707/bc05b1da-be71-11e4-8cf5-efb6b49ce516.png)
![screen shot 2015-02-27 at 11 13 30](https://cloud.githubusercontent.com/assets/1426234/6410708/bc068ad8-be71-11e4-9d2f-c74cbff389eb.png)

**Comment by KasperBrandt** [comment]
We've already got a page for this (e.g. http://rsr.akvo.org/project/2/updates/), but it's not styled and there's no link to it on the project page:

- [ ] Add styling for all updates page
- [ ] Add link to all updates page of project main page (if any updates)

**Comment by KasperBrandt** [comment]
**Test plan:**

There should be an all updates page on /project/<project_id/updates/. This page should be accessible from the project main, update main and add an update pages. Unless there are no updates, then this link should be hidden.
