### ISSUE TITLE
Budget Label Other

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1261]
We provide the option for users to add a custom label to the Other option of Budget Type, but we do not visualise this, we're showing the underlying label at the moment:
![screen shot 2015-02-27 at 11 14 33](https://cloud.githubusercontent.com/assets/1426234/6410730/f779eff6-be71-11e4-9f81-be36c1ce25ca.png)
![screen shot 2015-02-27 at 11 15 02](https://cloud.githubusercontent.com/assets/1426234/6410731/f77a24a8-be71-11e4-9f94-12af0de4a54f.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN a budget item with the other 1, 2 or 3 type and 'other_extra' filled in
WHEN viewing the project finance page
THEN 'other_extra' of the budget item should be displayed
