### ISSUE TITLE
Markup lost

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1262]
We seem to lose all formatting that is applied to the text within the description fields.

![screen shot 2015-02-27 at 11 16 04](https://cloud.githubusercontent.com/assets/1426234/6410755/27f87756-be72-11e4-9a78-befc812a0f44.png)
![screen shot 2015-02-27 at 11 16 28](https://cloud.githubusercontent.com/assets/1426234/6410756/28017acc-be72-11e4-87d4-918ee9cee012.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the accordion on the project main page
WHEN one of the descriptions has a line break
THEN the line break should be visible in the accordion as well
