### ISSUE TITLE
Goals Overview missing

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1264]
We seem to have forgotten about the Goals Overview section of RSR.

We have it in the Admin, but it's not listed on the project page. We should add this to the set of description fields.
![screen shot 2015-02-27 at 11 23 50](https://cloud.githubusercontent.com/assets/1426234/6410873/2733ad80-be73-11e4-93a7-851fc1570e7a.png)
![screen shot 2015-02-27 at 11 24 01](https://cloud.githubusercontent.com/assets/1426234/6410874/273498ee-be73-11e4-97f0-7ef20f3f299e.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the accordion on the project main page
WHEN the goals overview has been filled in
THEN the goals overview should be shown in the accordion
