### ISSUE TITLE
Fix donations

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1265]

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN a project with the possibility to donate
WHEN a user visits the donate page
THEN a page should be shown that gives the user the option to choose between iDeal and PayPal

GIVEN the user has chosen a payment option
WHEN the user fills in the form correctly
THEN the user should be shown a confirmation page

GIVEN the user has chosen a payment option
WHEN the user fills in the form incorrectly
THEN the user should be shown what is missing or incorrect

GIVEN the user views the confirmation page
WHEN the user wants to edit the donation
THEN the user should be able to edit the donation
AND the user should be redirected to the form page with the form filled in as it was previously

GIVEN the user views the confirmation page
WHEN the user confirms the donation
THEN the user should be redirected to the bank's or PayPal website

GIVEN the user has donated
WHEN the user returns to RSR
THEN the user should be shown a thank you page

**Comment by rumca** [comment]
@KasperBrandt not sure how big an issue it is, but the bottom test case doesn't pass. The user is just redirected back to the main project listing page.

**Comment by adriancollier** [comment]
How tough is it for us to get this fix in? The final step ius quite important for user experience.
