### ISSUE TITLE
Results data from v2

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1267]
We made a data migration to move the benchmarks into results, but as previously Benchmarks were "attached" to a category, it gave some contextual information that is now missing.

A suggestion to help this is to add the previous category information into the indicator text.

So what used to be:

X people trained (linked to the Cat Water & Sanitation)

would become:

X people trained in Water & Sanitation.

**Comment by KasperBrandt** [comment]
As @JosjeS suggested, we should add the names of the categories to the result title, e.g.:

- Water and Sanitation
  - X People trained

This resolves the issue of indicators with an empty result, so that we can display the results nested in RSR as well. That should also be part of this issue.

**Comment by KasperBrandt** [comment]
Also we noticed that the relation in the related projects model is switched when compared to IATI. Since we need a data migration for the results, we should also fix and migrate the existing related projects (on the hierarchy page as well).

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the project main page
WHEN the accordion is viewing (at the bottom)
AND the project has results
THEN the results should be shown in the accordion in a nested manner:
- Result title
  - Indicator title (indicator period) actual value / target value
