### ISSUE TITLE
Add number of updates to project list

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1281]
Feedback from Charlotte:
When searching for a project, it is currently not possible to see whether the project has any updates. Think it is good to see that.

**Comment by adriancollier** [comment]
2 data elements are relevant here:
- Date of most recent update
- # updates on a project

After discussion it seems if there is only enough space for a 1 of these then the Date of most recent update is the most valuable.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the project list
WHEN a project has an update
THEN the date of the last update should be shown
AND it should be possible to click the date to go to the last update
