### ISSUE TITLE
no. of result pages shown (twice)/sort, even when no results

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1283]
chrome 40.0.x on mac (10.9.5).

To reproduce:
- open RSR main projects page
- enter keyword that does not exist in RSR
- number of result pages shown twice.
(suggestion: bring the '0 results' forward a bit with e.g. larger font. Add search suggestions?

![screenshot 2015-03-02 15 37 35](https://cloud.githubusercontent.com/assets/8478175/6442736/5492c76c-c0f2-11e4-9026-0ddf690dda10.png)

**Comment by adriancollier** [comment]
This has been resolved in #1280 and will be part of the next release.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN all pages with pagination
WHEN no results are shown on the page
THEN the pagination parts should not be shown
