### ISSUE TITLE
server error on search

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1284]
chrome 40.0.x on mac (10.9.5).
to reproduce:
- type 'Ma Santé' in search box on http://rsr.akvo.org/projects/ (note: project with this name is in RSR but at time of testing in unpublished status)
- 'internal server error' (url: http://rsr.akvo.org/projects/?title=Ma+Sant%C3%A9&location=&status=&organisation=1994&sector=)

**Comment by adriancollier** [comment]
I think was also picked up by Sentry http://sentry.support.akvo-ops.org/rsr/live/group/267/

**Comment by mato74** [comment]
Can still reproduce it, although the project is published. nb not by clicking the correct result from the list, but by copy pasting the project name and hitting 'update'.

**Comment by adriancollier** [comment]
The issue here is the character encoding - I don't think it's complicated to fix it, but I don't know how that's done....

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the search function of the project list page
WHEN using a special character (é)
THEN no error should be shown
AND projects with the special character should be shown
