### ISSUE TITLE
Organisation Page - links to content

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1285]
We are missing 2 links on the organisation page.

1 link should be there to direct the user to a list of projects that the organisation is linked to.

1 link should be there to direct the user to a list of updates that have been posted by users of the organisation.

Potentially further to show a list of all users?

**Comment by mato74** [comment]
This type of pop-up (like on project pages) could work nicely!
![screenshot 2015-03-02 16 36 49](https://cloud.githubusercontent.com/assets/8478175/6443947/dafe20d2-c0fa-11e4-801d-ab979e539241.png)

**Comment by adriancollier** [comment]
It's likely to have many more results than could fit into a pop-up. Cordaid for example has hundreds of both projects and updates.

Using a Cordaid as an example, it would be easy for us to link to these pages:
http://rsr.akvo.org/projects/?title=&location=&status=&organisation=273&sector=
http://rsr.akvo.org/updates/?title=&location=&partner=273&sector=

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the organisation main page
WHEN viewing the Project in RSR and Updates in RSR section
THEN these headings should be clickable and redirect to the projects or updates of the organisation
