### ISSUE TITLE
'number of projects in euros'

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1286]
chrome 40.0.x on mac (10.9.5).
to reproduce:
- open http://rsr.akvo.org/organisation/411/
- funding: projects: '2 in euros'? not clear. Guess it means 2 project with budgets in euros?
![screenshot 2015-03-02 16 21 42](https://cloud.githubusercontent.com/assets/8478175/6443638/608d16d4-c0f8-11e4-90f8-f819e3502a24.png)

**Comment by adriancollier** [comment]
Agree, it is slightly clearer where multiple currencies are present: http://rsr.akvo.org/organisation/42/

But we should refine this to make it clearer.

**Comment by gabemart** [comment]
Tried a couple of different approaches, this is the one that felt cleanest and easiest to understand:
![1286_project_currency](https://cloud.githubusercontent.com/assets/2589977/6894776/eb8184bc-d6d0-11e4-9feb-7659b06c40e1.png)

I also set the "Projects" label to always be plural, even when there is just a single project. I think "Projects: 1" sounds more natural in English than "Project: 1".

**Comment by adriancollier** [comment]
I like the solution btw :smile:

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the organisation main page
WHEN viewing the funding information
THEN there should be 2 separate lines for projects and currency used
