### ISSUE TITLE
Explanation to maps: this map shows the projects listed on this page.

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1288]
## Test plan
GIVEN the project, organisation, update listing pages on core RSR
WHEN viewing the map
THEN a message should be shown on the bottom of the map that not all objects are shown

GIVEN an Akvo Page
WHEN the 'All points on maps' setting is set to True
THEN the message should not be shown

## Issue description
There are mixed opinions on the use-case for what pins to display on the maps within RSR - particularly the project map, but this also goes for updates and organisations.

At the moment the map only displays the points that are being shown within the results in the list - so the first page of results. Some users are requesting to be able to see all these elements on the map.

One challenge with this is that this is costly from a system resources point of view.

One potential solution is to provide an option on the listing page(s) to allow the user to choose to add all the results to the map rather than just the first page.

Would need to ensure the wording on this option is clear.

**Comment by Lissyvn** [comment]
What is the status of the potential solution? I got another request from a partner who would like be able to see all the project/updates pins on the map.

**Comment by adriancollier** [comment]
As far as I know this isn't making the cut for the post version 3 changes, so it's not likely to be implemented for some weeks/months due to the pressures for other features such as Paperless Reporting.

**Comment by Lissyvn** [comment]
Could we in the meantime add an explanation on this page explaining that people only see the project pins of the first page?

**Comment by lauraroverts** [comment]
Add explanation to map at rsr.akvo.org to say: This map shows the projects listed on this page.

**Comment by lauraroverts** [comment]
The same also applies to the Organisation and Updates listing pages.
