### ISSUE TITLE
Organisation IATI identifier

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1293]
See e.g. http://rsr.akvo.org/organisations/?name=iicd&location= 
One can see the identifier here. I suggest to also show it on the organisation page.

![image](https://cloud.githubusercontent.com/assets/8478175/6465993/f16c57a6-c1c4-11e4-85e3-e6b5fdc63340.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the organisation page
WHEN the organisation has a IATI organisation identifier
THEN the ID should be shown in the details section
