### ISSUE TITLE
Add a 404 page matching akvo.org's

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#1294]
Update the 404 page to look like Akvo.org's.
![screen shot 2015-03-03 at 16 51 25](https://cloud.githubusercontent.com/assets/2675262/6479905/19e38ff0-c24d-11e4-8ab6-0776014e2108.png)

**Comment by adriancollier** [comment]
I think it's important that we have a standardised feeling to the page, but I don't recommend that we have exactly the same 404 page as Akvo.org.

We have done lots of work in v3 to give RSR it's own distinct branding as a product - and I would like to continue this throughout the way it works. It should be as clear to users if they are on RSR or Akvo.org as it is clear when they are currently using FLOW.

**Comment by Lynngre** [comment]
Sure totally understand that :-)  Your own funky 404 is good enough!

**Comment by damienallen** [comment]
Test plan:

Open invalid URL and compared 404 page to those on the main Akvo website.
