### ISSUE TITLE
Forgotten password pop-up blocked

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1295]
As mentioned here https://github.com/akvo/akvo-rsr-up/issues/161 it seems that the forgotten password window is blocked when using some plugin/browser combinations.

I cannot replicate this with any pop-up blocking plugins on my mac, but I think there are combinations of OS, browser and plugins that will reproduce this.

Windows + Firefox + Adblock Pro appears to be one.
Is this something we can/should do something about?

**Comment by stellanl** [comment]
Another UI element that also gets blocked is the form for applying to to join an organisation on the My Details page.

**Comment by KasperBrandt** [comment]
Review if we can display a message when someone has Adblock Pro running.
