### ISSUE TITLE
results text cut off

### ISSUE THREAD

**Issue by mato74** [akvo/akvo-rsr#1304]
see http://rsr.akvo.org/project/2603/

![image](https://cloud.githubusercontent.com/assets/8478175/6503687/aa1b5b60-c32f-11e4-9813-66bf6acdf6be.png)

**Comment by KasperBrandt** [comment]
This is a legacy problem (due to RSR v2). In v2, it wasn't possible to have goals with more than 100 characters. These goals have been migrated to results in v3 (max chars: 255). In other words: these results were already cut off in v2 unfortunately.
