### ISSUE TITLE
Piwik tracking for CNAME Akvo Pages not working after upgrade to V3.0

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#1305]
There is currently no tracking happening for the partner Akvo Pages ( CNAMES)

Last stats were from the Thursday of the upgrade.  Was the JS code included in the upgraded pages?
#630

**Comment by Lynngre** [comment]
@adriancollier not sure when this could be fixed, the data is not recoverable, so for as long as it's not being collected there will be no data - not sure how bad that is for partners (which partners were notified of this being available).  Either way there will be a hole in what we can provide.

**Comment by adriancollier** [comment]
We should add this back into the code. If I remember correctly, it's not a big fix and should be easy enough for us to fix it before the next release.
@KasperBrandt can you take a look?

**Comment by KasperBrandt** [comment]
It seems the code hasn't changed from v2, so I'm not sure what's causing this.

@Lynngre, do you get tracking from regular Akvo Pages? It seems like we fill in site id=1, regardless of core RSR or an Akvo Page, everywhere..

**Comment by Lynngre** [comment]
Akvoapp.org is no longer tracked as part of akvo.org or rsr.akvo.org as per the issue https://github.com/akvo/akvo-rsr/issues/630

So any *.akvoapp.org or CNAME for those should be using their allocated SITEID as per list here:

https://docs.google.com/spreadsheets/d/1pfwOmf4aMWx4YEwYqD7SFYkc7-Z3hApcTVTQgZ5lARY/edit?usp=sharing

**Comment by adriancollier** [comment]
All of the IDs are present within the data at rsr_partnersite.piwik_id so we just need to add the code to put this into the right templates.

**Comment by Lynngre** [comment]
Great, thanks guys!

**Comment by Lynngre** [comment]
So this was removed from the last update?  We seriously need this to be done asap.

**Comment by kardan** [comment]
@Lynngre it's getting into the next release, thanks for the bump!

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN Akvo Pages (also with CNAME)
WHEN a Piwik code is filled in for the Akvo Page
THEN this code should be filled in at the Piwik tracking part of the code
