### ISSUE TITLE
Preview project

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1319]
Often the partner team wants to show a project that has not been published yet to someone from outside of Akvo.

Now, they have to be an admin or project editor of one of the organisations of the project in order to see the project. It would be nice to have a preview link that can be viewed by anyone.

**Comment by lauraroverts** [comment]
Is this still relevant now we have the project editor?

**Comment by KasperBrandt** [comment]
Yes, but not a high priority. Although it also ties in with Akvo IATI and RSR Impact I believe. Pure IATI projects for instance will never be published, so how will these be accessible for anyone? We need time to think about that, so for now I think it's good if we keep this in the same milestone as the Akvo IATI / RSR Impact issues.

**Comment by punchagan** [comment]
Closing super old issue
