### ISSUE TITLE
All projectupdates in the directory?

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1323]
Should we show all project updates in the projectupdate directory? Or is it odd that we have project updates in that list whose parent project is not public? One maybe also argue for not showing project updates for archived or cancelled projects.

**Comment by adriancollier** [comment]
I think these projects should be displayed in the list. If a project is archived / cancelled, we recommend that they post an update to inform the public of what happened. This should be presented in the list of updates in the normal way.

However we should ensure that we are only displaying updates for Published projects.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the updates page
WHEN viewing the updates
THEN no updates of unpublished projects should be shown
