### ISSUE TITLE
Upgrade to Django 1.7

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1324]
- [x] Check removed features: https://docs.djangoproject.com/en/1.7/releases/1.7/#features-removed-in-1-7
- [x] Upgrade TastyPie to v0.12.1: http://django-tastypie.readthedocs.org/en/latest/release_notes/v0.12.0.html
- [x] Upgrade from South: https://docs.djangoproject.com/en/1.7/topics/migrations/#upgrading-from-south

**Comment by adriancollier** [comment]
Any estimate on the effort needed here?

**Comment by KasperBrandt** [comment]
Without checking the removed features, this can be done in an hour. However, we have to make sure that there are no other South migrations in the same release, since all migrations have to be removed (they're replaced by Django's internal migrations). So we should move to Django 1.7 at the beginning of a new milestone so that from that point on we can use the new migrations instead. I'll discuss with @kardan if it's possible for the 3.2 release.

**Comment by kardan** [comment]
@KasperBrandt do you see any value in preserving the south table? Otherwise maybe nuke that.

**Comment by KasperBrandt** [comment]
## Test plan
No testing needed.
