### ISSUE TITLE
Sector codes correct case

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1330]
We should standardise the text for sectors as at the moment we have some with capitals and some normalised.

All should be the same, I recommend normalised for this (First letter capital followed by small letter for each word).

**Comment by adriancollier** [comment]
![screen shot 2015-03-11 at 14 56 15](https://cloud.githubusercontent.com/assets/1426234/6597735/ccd54070-c7fe-11e4-8fb6-7502366d9ae3.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the projects listing page
WHEN the sectors are shown (in the listing itself and in the filters)
THEN they should be capitalised

GIVEN the project page
WHEN the sectors are shown
THEN they should be capitalised
