### ISSUE TITLE
Donation Process - User Registtration

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1332]
It makes sense for us to add the user registration process to the existing donation process.

As a user is not required to add any employment information in order to become a member of RSR, users who donate can become members. The aim of this is that users will (eventually) be able to see the history of their donations and follow and receive updates about the projects that they have donated to.

Process to follow:

- User sees a project they would like to donate to
- User clicks on the Donate button
- User is informed of the different payment methods
- User selects a payment method
- User is asked to sign in to their account or register
- User signs in to their account
    - User is presented with the donation form with their known details prefilled
    - User can edit the identification information to be displayed alongside the donation
    - User cannot edit the email address on this form
- User registers for a new account
    - User is asked to enter their email, name and password information
    - User submits this information
    - User receives activation link in their email
    - User clicks on activation link
    - User is presented with the donation form with their known details prefilled
    - User can edit the identification information to be displayed alongside the donation
    - User cannot edit the email address on this form

**Comment by lauraroverts** [comment]
Not relevant anymore. Donation button will removed from RSR in August 2016.
