### ISSUE TITLE
Gulp errors are not intuative

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1333]
@loicsans reported that the gulp errors from example broken scss files are really difficult to debug. So maybe turn on source maps might be something we should do https://www.npmjs.com/package/gulp-sass ?

**Comment by kardan** [comment]
https://github.com/floatdrop/gulp-plumber ?

**Comment by KasperBrandt** [comment]
## Test plan
No testing needed. Our local conversion tool for sass and jsx files will now give errors for incorrect files, instead of just breaking.
