### ISSUE TITLE
Uppercase before lowercase

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1338]
In general, uppercase characters are listed before lowercase characters since we switched to postgres.

For example, if you want to add the organisation 'Amref Flying Doctors' to a project, it first shows all 'AMREF ..' organisations (and all other organisations with multiple capitals). This is confusing for end users, since the order is not alphabetical.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the sorting of organisations
WHEN upper and lower case is mixed
THEN upper case should be ignored
AND 'aaa' should be shown above 'ZZZ' for example

**Comment by rumca** [comment]
This is fixed in the admin, but still looks a bit odd in the main RSR org listing page
