### ISSUE TITLE
Clean up client side assets

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1340]
At the moment we included unused javascript libraries. Something that adds to the time for the loading time of the pages.

There is also a lot of old directories in rsr/static which is unnecessary (got feedback on this). Would be valuable to clean up this after the v3 release so it's easier to understand whats what.

**Comment by KasperBrandt** [comment]
## Test plan
No testing needed, it's only cleanup of (a lot of) old files. In general we should check if all JS scripts are still working and all images are displayed for instance.
