### ISSUE TITLE
List of organisations with partner type

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1341]
In v2, we used to have a page containing all support partners, as well as field, funding and sponsor partners. At /organisations/support for example. We should add this again.

**Comment by adriancollier** [comment]
We should also add in a list of "Reporting Organisations" and this should be aligned with the website content so that we direct users ot a list of reporting organisations as those they can contact to become a member of RSR.

**Comment by KasperBrandt** [comment]
After a talk with Laura we decided that especially a list of reporting organisations is important, so that we can show anyone who wants to get their project(s) online a list of partners with whom they can get in contact.

**Comment by kardan** [comment]
Testplan:
- All organisation that was set as reporting on an organisation should be enabled as reportable in the admin.

- Only a superuser should be able to set an organisation as reportable in the admin

- Only reportable organisations should be in the reporting organisation dropdown in the project admin

**Comment by kardan** [comment]
The actual listing of reporting orgs are a bit hidden at the moment. One needs to add "?reporting=true" to the url. We should add a proper UI for this moving forward - to be regarded as an easter egg feature
