### ISSUE TITLE
Footer Email Spam

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1350]
We are receiving Spam in the RSR Feedback email address since we added this to the footer of RSR.

In order to attempt to reduce this, we need to hide the email address in the HTML.

We will continue to monitor this to see if this resolves the issue or we need to act further on anti-spam, or if we need to remove the button altogether.

@kardan suggested:

we have a js snippet that generate the markup:
```
<script type="text/javascript">document.write(
"<n uers=\"znvygb:efe\056srrqonpx\100nxib\056bet?fhowrpg=EFE srrqonpx\"><v pynff=\"sn sn-pbzzrag-b\"><\057v> Cebivqr srrqonpx<\057n>".replace(/[a-zA-Z]/g, function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);}));
</script>
```

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the feedback email button in the footer
WHEN viewing the source code
THEN there should be javascript instead of the direct email address

**Comment by rumca** [comment]
I could have misunderstood this one, but we still seem to have the actual feedback email address in the source?

![screen shot 2015-04-14 at 15 58 28](https://cloud.githubusercontent.com/assets/3003031/7139638/366cbdd0-e2bf-11e4-9384-921c303cdd6c.png)

**Comment by kardan** [comment]
Where is that? Sure it's not just when you inspect?

**Comment by KasperBrandt** [comment]
Yup, it is.. since the javascript actually writes the code you can see it when inspecting the page.
