### ISSUE TITLE
Let an unemployed-user aware Up log in

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#1352]
As intended in #1228 old versions of Up are prevented from logging in to V3 if user is unemployed.
We need to allow an updated Up to log in and also get full information about all orgs user is employed at.
This will let the Up user:
1) Get an appropriate message/link directing him/her to the employment request web page.
2) Implement the user lifecycle functionality inside Up.

**Comment by stellanl** [comment]
Trying to log in gets me a 500.
<h1>AttributeError at /auth/token/</h1>
  <pre class="exception_value">&#39;QuerySet&#39; object has no attribute &#39;all_projects&#39;</pre>
  <table class="meta">
Something is wrong in https://github.com/akvo/akvo-rsr/blob/develop/akvo/rsr/views/account.py#L138

**Comment by KasperBrandt** [comment]
Yeah, I saw that earlier this week too. It's fixed here: https://github.com/akvo/akvo-rsr/pull/1411/files#diff-4c5b9ece6f175ab22792e65776ff2b5bR47
