### ISSUE TITLE
Partners of a project

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1358]
We have some feedback that some of the partners on a project are now much more hidden than they used to be, and this is not appreciated by all partners.

One thing that seems to be important is being able to see the logos of the organisations.

![screen shot 2015-03-19 at 17 16 50](https://cloud.githubusercontent.com/assets/1426234/6735016/c895ee7a-ce5b-11e4-92bd-fd1494580e9f.png)

A solution would be to make the current hover over list, also clickable, and in this next page we create a list of all partners on the page along with their role on the project in a new page.

@loicsans @gabemart - what do you think?

**Comment by adriancollier** [comment]
Thoguhts on this one? Need to get back to the partner with our ideas.

**Comment by loicsans** [comment]
@adriancollier 
I think this implementation is still correct and it's easy to justify why we only display the main partner there. One thing we could do is to add the logos on the org inside the tooltip. Adding a partner page, displaying the full list and roles is definitely a good idea.

**Comment by gabemart** [comment]
I will look into adding logos inside the tooltip as a first step

**Comment by gabemart** [comment]
Tooltip with partner logos:

![1358 partner tooltip](https://cloud.githubusercontent.com/assets/2589977/6846614/633e5a6a-d3b7-11e4-98fc-0c9afab2744e.png)

**Comment by gabemart** [comment]
Reduce partner logo size:

![reduce width](https://cloud.githubusercontent.com/assets/2589977/6846827/48912f60-d3b9-11e4-91ed-cef56570c061.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the project main page
WHEN hovering over the '+.. partners' button
THEN the logos of the partners should be shown

GIVEN the project main page
WHEN clicking the '+.. partners' button
THEN the partners overview page should be shown
