### ISSUE TITLE
Missing permissions for Akvo Pages

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1365]
At the moment it is not possible to give a user permissions to be able to edit their own Akvo Pages instance without providing access for all instances.

This should be added to the Admin role.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN an Admin of an organisation
WHEN the partersites admin is visited
AND the organisation has an Akvo Page
THEN the user should be able to view only the Akvo Pages of the organisation
