### ISSUE TITLE
Akvo Pages front Map and About Box

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1366]
In v2 Akvo Pages has an About Box on the left hand side of the page where partners could display an image, text or html code as additional branding for their website.

In v3 we removed this and we have had some feedback from partners that this was an essential element of the branding of these sites.

We should look at an alternative layout design for these that will shrink the map and provide the previous about box on the listing pages for those partners that wish to have this functionality.

**Comment by adriancollier** [comment]
After speaking with Krijn from CommonSites it seems that the issue here is not specifically the box as it was previously implemented, but the partners are missing a space to add some custom text to explain what the site is being used for.

One suggestion that came up is to add a space on the listing pages where partners can add a couple of lines of text and maybe also display some partner logos.

This could go between the header and the map or between the map and the list results (I think the first is a better option).
![screen shot 2015-04-08 at 15 48 37](https://cloud.githubusercontent.com/assets/1426234/7046590/3703de52-de07-11e4-9e99-79be7257a752.png)

We would need to decide:
How many fields are present? 1 text plus X logo spaces for example.
What is the size of the box?
What styling can be added to the text?
Is it always visible or can it be hidden by the user?

**Comment by KasperBrandt** [comment]
The about box fields of akvo pages have been removed.
