### ISSUE TITLE
Organisation page needs responsive design improvements

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-rsr#1375]
The [organisation page](http://rsr.akvo.org/organisation/42/) could make better use of space on narrow viewports. It should be updated to more closely match the finance sub-page. 

Current organization page:
![org_page_narrow](https://cloud.githubusercontent.com/assets/2589977/6894397/5c786ebe-d6cd-11e4-8db1-7e4017c1acb1.png)

Text alignment should be made more like the finance page:
![finance_page_narrow](https://cloud.githubusercontent.com/assets/2589977/6894403/6fe9d0a0-d6cd-11e4-8e3e-eaea79fd68e2.png)

We should also right-align currency amounts and remove the space between the currency symbol and the currency amount

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the organisation main page
WHEN resizing the page
THEN the page should be responsive
AND the currency amounts should be right-aligned
AND the space between the currency symbol and the currency amount should be removed
