### ISSUE TITLE
Improve user management page

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1398]
- [x] Add search function
- [x] Do not display users without an employment

**Comment by adriancollier** [comment]
We are very likely to find it useful to be able to see some users without employment (to prevent the need to use the "old" admin for this) so maybe we might consider having an option to filter the User page to only show users without employment, available to support.

**Comment by KasperBrandt** [comment]
Yup, I actually think it's better to show only active users there instead. Since all these spam accounts are not activated.

**Comment by adriancollier** [comment]
I'm wondering if there is also a need to display the non-activated users at some point. I can imagine the support situation that someone has registered and cannot complete for one reason or another, it would probably be handy to see their inactive account in the list along with the inactive status so we can provide a definitive answer to the status of their account.

**Comment by adriancollier** [comment]
We should also ensure that the buttons on this page line up, and the table of data is visually well represented.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the User Management section in MyRSR
WHEN viewing the users
THEN users without an employment should not be visible in the list

GIVEN the My Projects, My Updates and User Management sections in MyRSR
WHEN viewing the sections
THEN it should be possible to search for projects, updates or users
