### ISSUE TITLE
email=username is not made clear to users

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#1399]
In V3, the registration page asks for email, first and last names. You then go to the login page, which asks for Username. Users then ask themselves, "what is my username?".
Either the registration page should mention that the email address will be used as their username or the login page should say "Email or username:", at least in the hint text.

As reported by Isha.

**Comment by stellanl** [comment]
Facebook, for instance, now prompts for just email at login, even though they still support the legacy usernames.

**Comment by adriancollier** [comment]
We have made this same change (usernames to email) but yes we need to update the messaging so this is clear.

I think we should stick to "email" in the messaging, but allow users to use this for their username if they have and know it.
