### ISSUE TITLE
Amount needs funding

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1401]
## Test plan
GIVEN a project
WHEN it has less than ($/€) 1 funds needed (= total budget - total funding by funding partners)
THEN the funds needed amount is set to ($/€) 0

his is accomplished by using a management command:
```manage.py funds_needed [option] value```

GIVEN the funds_needed management command
WHEN there's no value parameter for the command to run
THEN an error is shown

GIVEN the funds_needed management command
WHEN only a value and no option is provided
THEN all projects with funds needed less than the indicated value should be printed to console

GIVEN the funds_needed management command
WHEN the ```--zero``` option is provided
THEN all projects with funds needed less than the indicated value should set their funds_needed to 0

GIVEN the funds_needed management command
WHEN the ```--complete``` option is provided
THEN all projects with funds needed less than the indicated value should set their status to 'Complete'

## Issue description
From the product meeting, it became clear that we have to look at 2 things regarding funding:

- [x] There are quite a few projects with $1 funding needed, these need to be set to completed.
- [x] How much funding is needed? This is only visible on the project funding page and on the second page of donations, but it should be apparent on the project list already, if relevant.

**Comment by adriancollier** [comment]
It's worth checking out the thoughts and comments in these 2 issues:
https://github.com/akvo/akvo-rsr/issues/440
https://github.com/akvo/akvo-rsr/issues/120

**Comment by lauraroverts** [comment]
To add: http://rsr.akvo.org/project/1588/finance/ This project has received money from funding (via admin) and via donation (via PayPall or iDeal). Due to the fee you pay to pay via our donation button, the project budget leftover is now 18 cents. This is also the problem with a lot of the Mars projects, like this one: http://rsr.akvo.org/project/739/

**Comment by zzgvh** [comment]
Not sure what to do here... Anyway here's a list of projects with less than 1 funding needed:
```text
id   |funds_needed |
-----|-------------|
42   |0.40         |
43   |0.38         |
49   |0.40         |
54   |0.05         |
56   |0.14         |
61   |0.05         |
74   |0.42         |
75   |0.35         |
94   |0.18         |
107  |0.13         |
108  |0.23         |
120  |0.10         |
121  |0.13         |
132  |0.25         |
135  |0.18         |
138  |0.36         |
141  |0.21         |
149  |0.18         |
174  |0.18         |
179  |0.25         |
187  |0.18         |
204  |0.15         |
210  |0.18         |
211  |0.18         |
245  |0.06         |
247  |0.18         |
248  |0.18         |
249  |0.08         |
250  |0.18         |
251  |0.18         |
252  |0.18         |
253  |0.18         |
256  |0.18         |
257  |0.18         |
258  |0.18         |
263  |0.18         |
264  |0.18         |
265  |0.36         |
268  |0.03         |
273  |0.18         |
274  |0.46         |
297  |0.36         |
298  |0.25         |
304  |0.08         |
332  |0.18         |
348  |0.36         |
397  |0.12         |
450  |0.45         |
453  |0.30         |
483  |0.29         |
511  |0.01         |
512  |0.01         |
513  |0.02         |
538  |0.01         |
540  |0.01         |
591  |0.44         |
592  |0.38         |
594  |0.14         |
597  |0.19         |
610  |0.27         |
612  |0.18         |
660  |0.33         |
690  |0.01         |
695  |0.01         |
1340 |0.01         |
1365 |0.25         |
1588 |0.18         |
1897 |0.11         |
2203 |0.01         |
2228 |0.49         |
2330 |0.08         |
3187 |0.01         |
```

**Comment by lauraroverts** [comment]
Are these budget leftovers due to the fee a donor pays by using PayPall? I think this is a problem, becuase then a budget can never be fully funded if it's by online donations. 
If I look at the projects in the list above, I think you can't see these less than 1 euro leftovers anymore, since we removed decimals, e.g. http://rsr.akvo.org/en/project/107/finance/

**Comment by zzgvh** [comment]
Does the --complete option set all projects with funds_needed == 0 to Complete? If so, that seems dangerous. If not the --zero option needs to be used carefully since when projects are set to 0 they cannot be completed en masse.

**Comment by KasperBrandt** [comment]
The --complete option sets all __selected__ projects to complete. Same for --zero.

So if you do needing_funds --complete --zero 5, it'll set all projects that have funds needed in between 0 and 5 to 0 and to complete. Not all projects that are currently 0.

The idea was to actually print out the projects you're going to do something to first (by not supplying the --complete or --zero option), and when you're ok with those projects being set to 0 and/or to complete, run the script again.

**Comment by zzgvh** [comment]
Ok, that makes sense. You still have to take care so that you don't set funding to 0 for projects that you later realize should be complete too.
