### ISSUE TITLE
Make organisation name unique

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1406]
We need to figure out what to do with the difference between organisation name and long name. However, if we want users to be able to add organisations, we should first make sure that we don't get any double entries of organisations.

## Test plan
GIVEN the organisation admin
WHEN adding a new organisation OR changing an organisation's (long) name
THEN it should not be possible to add an organisation with a name that already exists in the database

GIVEN the organisations in RSR
WHEN looking the organisations directory
THEN all organisation names should be unique
AND all organisation names that weren't unique before, should have an '(2)' or '(3)' attached

Note; since the name sometimes became too long (e.g. organisation.name only allows 25 characters), the organisation names could have been shortened as well. E.g. "Catholic Relief Services" become "Catholic Relief Serv (2)".

**Comment by kardan** [comment]
Beside unique fields it's trivial to enforce unique pairs (name + long name)
https://docs.djangoproject.com/en/1.7/ref/models/options/#unique-together. Think it will be tricker to be unique over two columns. 

We need to do a proper review of the current org name & long names in the db.

**Comment by KasperBrandt** [comment]
Fixed in #1705
