### ISSUE TITLE
Link to Project Page in MyRSR - My Projects

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1413]
At the moment only the image is a link, but it does make sense to also make the title of the project a link to the project page also.

Should also be carried over to the My Updates page.

![screen shot 2015-04-07 at 17 11 36](https://cloud.githubusercontent.com/assets/1426234/7026497/48428ce4-dd4a-11e4-8265-d4fae88be358.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the My Projects and My Updates sections
WHEN the title is clicked
THEN the user should be redirected to the respective project or update page
