### ISSUE TITLE
Move donate button to financial overview page

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1414]

**Comment by adriancollier** [comment]
If we hide the Donate button then this will not be used any more...people won't know it's there.

We do need to ensure that more funding information is present alongside the donate button though, as at the moment it's unclear what amounts are needed for the project.

Options (from my point of view):

- Make a section (box) to put the total and remaining amounts with the donate button
- Make an expandable section with further details but less info (maybe just funding bar) visible
- Expand the donate button in size and use the space inside the button to display the figures
- Make a "funding graphic" like a pie chart or something that encourages interaction

Remember that the donate button is a call to action so it should receive a prominent space on the page. It is only present when necessary, so there should be no project with a donate button where we do not want to highlight this action.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the project main page
WHEN it's possible to donate to the project
THEN the budget needed should be displayed
AND the donate button should be shown in a highlighted section with the budget needed
