### ISSUE TITLE
Alignment of Financial figures

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1416]
Related to https://github.com/akvo/akvo-rsr/issues/1292 we need to ensure that all figures displayed are right aligned with 2 decimal places so that they can be easily evaluated.

This has been completed on the fiunancial pages, but this should also be applied to the figures on the organisation page: 
![screen shot 2015-04-08 at 11 36 38](https://cloud.githubusercontent.com/assets/1426234/7042637/9e1e9146-dde3-11e4-9f5e-f32baa847dae.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the organisation main page
WHEN the funding information is displayed
THEN the amounts should be right aligned, with 2 decimals
