### ISSUE TITLE
MyRSR - My Projects - Draft projects

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1418]
Within the MyRSR section, all the projects a user can access are displayed. At the moment it is tough to tell the difference between draft and published projects.

Eventually additional filtering should be applied, but we can achieve a lot with some visual differentiation between published and draft projects to ensure that users can easily see their portfolio.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the My projects section
WHEN a project is not published
THEN the project should be visually different (grey background) from the published projects
