### ISSUE TITLE
MyRSR Action buttons

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1420]
Sometimes the text inside the call to action buttons on the MyRSR sections are cut, and so it is not possible to see what the button will do:
![screen shot 2015-04-08 at 11 52 28](https://cloud.githubusercontent.com/assets/1426234/7042934/d4e7adb4-dde5-11e4-998c-b6bb75250660.png)
![screen shot 2015-04-08 at 11 52 17](https://cloud.githubusercontent.com/assets/1426234/7042936/d58c2b46-dde5-11e4-91d0-9c8e48c42136.png)

We should fix this so that buttons are always displaying the correct data to assist our users in making the right decisions.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the My projects and My updates sections
WHEN viewing the action buttons
THEN the text in the buttons should be fully visible

**Comment by rumca** [comment]
@loicsans this one still isn't fixed for me. 

On chrome the `My projects` page always has the button text visible, but the `My updates` page still looks like this:

![screen shot 2015-04-14 at 13 14 55](https://cloud.githubusercontent.com/assets/3003031/7136628/a0536dbc-e2aa-11e4-9137-db7be2e881b4.png)

On firefox the same issue is present but the layout on `My projects` and `My updates` has gone a bit crazy:

![screen shot 2015-04-14 at 13 34 23](https://cloud.githubusercontent.com/assets/3003031/7136657/00409344-e2ab-11e4-8863-5f86108660eb.png)
