### ISSUE TITLE
Mark all strings as translatable for Transifex import

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#1421]
We need to do a review of all the strings within RSR to ensure that they are marked for translation.

When we have done this we can arrange for the content to be translated to reinstate the mulitlingual functionality of RSR.

**Comment by KasperBrandt** [comment]
## Test plan
Not needed, all texts on RSR should've stayed the same. Although they're now all translatable. Translations will be added in one of the next releases.
