### ISSUE TITLE
All projects on org map experiment

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1422]
We should investigate how expensive it is to add all projects on the organisation page

**Comment by kardan** [comment]
Think about to limit the data that is needed!

**Comment by lauraroverts** [comment]
If the experiment fails, please add an explanation to the map that says only the 10 projects/updates visible at this page are visible. Otherwise it's not clear to people why they only see a selection of pins

**Comment by kardan** [comment]
Related https://github.com/akvo/akvo-rsr/issues/1580

**Comment by lauraroverts** [comment]
Duplicate of #1288
