### ISSUE TITLE
Review middleware & local_settings

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1432]
Turns out that the RSR_DOMAIN & AKVOAPP_DOMAIN is set differently than I thougth so need to review how this plays out with the new Middleware. It's not broken at the moment but might redirect traffic from rsr.akvo.org -> rsr.akvoapp.org.

**Comment by kardan** [comment]
Fixed by @orifito https://github.com/akvo/akvo-provisioning/issues/155

**Comment by KasperBrandt** [comment]
## Test plan
RSR and especially Akvo Pages should work.
