### ISSUE TITLE
Map in responsive design

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-rsr#1433]
Map in responsive design
When you reach a particularly narrow display, for example on a normal iPad with a retina display you loose the map in portrait mode and no way to get access to it.
 
My suggestion would be that you really should be able to choose to see the map in this display mode. The iPad can handle it.
 
Map to be enabled on high resolution - responsive settings

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the project list
WHEN making the screen smaller
THEN the map should still be visible on iPad size
AND it should only be hidden on the narrowest size
