### ISSUE TITLE
search field drop down tidying up

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-rsr#1434]
The search field dropdown has a very tight layout. The results text touches the borders of the box.
 
The contrast of the results text (light blue) is very poor and hard to read.
 
The difference in point size between the Headlines (Project, Organisation, Country) and the results text feels too big.
 
Would it be possible to show number of hits in the Country list? For example:
Kenya (5)
As it is often that one searches on a country that exists, but has no results. Alternatively hide countries with no projects.

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the search field on the project list
WHEN searching
THEN the layout should be cleaner
