### ISSUE TITLE
Minor issue - missing thumbnails for video updates on some pages

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1497]
When an update contains a video, we show the thumbnail on certain screens but not others. For example the latest updates list has the thumbnail correctly displayed:

![screen shot 2015-04-14 at 13 01 34](https://cloud.githubusercontent.com/assets/3003031/7201311/b5e12412-e4fd-11e4-980d-4b8705288342.png)

However the previous updates side bar (when a user is adding a new update) does not have the thumbnail:

![screen shot 2015-04-14 at 13 01 46](https://cloud.githubusercontent.com/assets/3003031/7201327/d2a2b9d0-e4fd-11e4-9801-46c3a9a63aac.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the add update page
WHEN viewing a previous update with video
THEN the video thumbnail should be displayed correctly
