### ISSUE TITLE
Really minor issue - search text display when there are no results

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1498]
This one is really minor, but when a user searches for something on MyRSR and no results are found. Then the text detailing the search still has the `?q=` query string in it, just for the sake of clarity i think we should strip that out:

![screen shot 2015-04-15 at 12 26 21](https://cloud.githubusercontent.com/assets/3003031/7201375/39b83af0-e4fe-11e4-832b-d4574772890c.png)

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN all MyRSR sections with a search box
WHEN performing a search without results
THEN only the query should be displayed on the page (without '&q=')
