### ISSUE TITLE
Links broken 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1506]
At http://akvo.org/help/help-support/rsr-help/ some links are broken: 
the links 'register here'  and 'reset your username and password' in the foldout of the first question is broken: 
- http://rsr.akvo.org/accounts/register1/
- http://rsr.akvo.org/accounts/password/reset/

Furthermore: 
Content of third and fourth foldout need to be updating according to how it works with RSR 3.0. (how do I edit a project, how do I put my project online)

**Comment by KasperBrandt** [comment]
@lauraroverts Could you add this to the web repo? We can't do much about this in RSR. Btw, the correct links are:

- http://rsr.akvo.org/register/
- http://rsr.akvo.org/myrsr/password_change/

**Comment by lauraroverts** [comment]
Added to web repo
