### ISSUE TITLE
Donate amount not clear

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1507]
If you look at the projects that have a donate button, for example at http://rsr.akvo.org/projects/?organisation=610, it is not obvious how much funding a project needs. You see the donate button, but not the amount that is left for finance. 

If you then click on the donate button, you see this page http://rsr.akvo.org/project/431/donate/. Here it is still not visible how much money you can donate. 

When you click the 'donate with PayPal' button, it becomes clear the project needs 1 dollar funding http://rsr.akvo.org/project/431/donate/paypal/

**Comment by KasperBrandt** [comment]
- [ ] Add 'FUNDS NEEDED' to project in project list when donate button is active
