### ISSUE TITLE
Organisation page

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1509]
## Test plan
GIVEN the organisation page

WHEN the organisation has a name and long name
AND the long name differs from the name
THEN the long name will be displayed in brackets behind the name

WHEN the organisation has an URL filled in
THEN clicking on the organisation logo will take the user to the organisation URL
ELSE the logo is not clickable

WHEN the organisation has no logo
THEN the default 'Partner logo is missing' logo will be displayed

## Issue description
- Organisation page doesn’t show the long organisation name.

- When you click on organisation's logo, a page opens with the same logo. Has no added value. --> make  unclickable

**Comment by KasperBrandt** [comment]
Oh, didn't notice there's another element to this issue:
- [ ] Organisation page doesn't show long organisation name

I would suggest we display the long organisation name when available, and the short one otherwise.

**Comment by lauraroverts** [comment]
I would suggest show the short name and the long name underneath the short name. E.g. if you look at http://rsr.akvo.org/en/organisation/1686/, you see NWP, but it would make sense to also show Netherlands Water Partnership underneath the header, slightly smaller.

**Comment by kardan** [comment]
I'm handing this to the design team

**Comment by KasperBrandt** [comment]
@lauraroverts Note that in your example, the long name of NWP is also NWP. This looks a bit weird, so when the name and long name are similar, we don't display the long name.
