### ISSUE TITLE
Start- and end date of project missing

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1514]
## Test plan
GIVEN the project main page
WHEN a project has a start or end (actual / planned) date
THEN these dates should be displayed underneath the STATUS heading

## Issue description
At a project page, the start- and end date (planned and actual) are not indicated.

**Comment by zzgvh** [comment]
@gabemart I've made an initial effort adding dates, but I leave it to you to deem it worthy or not :wink: At least the logic is in place.

**Comment by gabemart** [comment]
I propose displaying the dates in the same formate as the current "Status" display, and also right-aligning the dates and status text. I think it makes parsing the information and comparing the different dates easier.

<img width="1195" alt="screen shot 2015-08-07 at 15 34 20" src="https://cloud.githubusercontent.com/assets/2589977/9138156/05efbada-3d1a-11e5-94c2-2433593c7449.png">

**Comment by lauraroverts** [comment]
All makes sense. 
Only wondering what happens if one or more dates have not been filled out in the backend. Then nothing will be displayed?

**Comment by gabemart** [comment]
@lauraroverts Yes exactly, nothing is shown if there are no dates in the backend.

**Comment by gabemart** [comment]
![a1](https://cloud.githubusercontent.com/assets/2589977/9161665/3c6c95c0-3f3a-11e5-9e77-6b51fe7d8022.jpg)
![a2](https://cloud.githubusercontent.com/assets/2589977/9161670/3f80218c-3f3a-11e5-9398-1a048c6c7def.jpg)
![a3](https://cloud.githubusercontent.com/assets/2589977/9161672/41bae0a4-3f3a-11e5-9317-5f15cd3555d0.jpg)

**Comment by lauraroverts** [comment]
Seems good to me

**Comment by KasperBrandt** [comment]
Should we always display planned and actual dates? Maybe we should only show the planned dates if there's no actual date, so show the actual dates by default. Saves some space. And maybe we can also remove the '(actual)' part, but only show '(planned)'. What do you think @lauraroverts?

**Comment by lauraroverts** [comment]
I think it makes sense to show both dates if there is a planned and actual date cause it also says something about if the project started in time or that there was a delay.

**Comment by gabemart** [comment]
Even if we always show both planned and actual dates, perhaps we should remove the "(Actual)" text and only show (planned) as @Kasper suggests? On reflection I agree that "(Actual)" is a bit redundant and clutters things up.

**Comment by lauraroverts** [comment]
Ok, agree.
