### ISSUE TITLE
Finance info not clear 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1533]
Looking at http://rsr.akvo.org/project/2506/finance/ there are a few unclarities. 
See screenshot below. 
![screen shot 2015-05-04 at 12 12 31](https://cloud.githubusercontent.com/assets/4179989/7451921/ea2affa2-f256-11e4-8c4c-5d7999f34537.png)

- The project budget is 6600. It says funds needed 3511.23. It is not clear who funded the 3088.77. 
- Curren funder is Wilde Ganzen. But what is the amount? 
- The donations at this moment are a total of 2498.77. But is this money part of the 3088.77 funded?
- What is the total amount of the project that needs to be still funded? 3511,23? Or 3511,23 minus 2498,77?

**Comment by KasperBrandt** [comment]
- The project budget is 6600. It says funds needed 3511,23. It is not clear who funded the 3088,77.
  - The 3088,77 only comes from donations. However, pending donations were also taken into account, so these have now been removed from the funds.
- Current funder is Wilde Ganzen. But what is the amount?
  - The amount is not displayed when there is no amount filled in (so amount is 0).
- The donations at this moment are a total of 2498,77. But is this money part of the 3088,77 funded?
  - Yes, so in this case the project is only funded by donations.
- What is the total amount of the project that needs to be still funded? 3511,23? Or 3511,23 minus 2498,77?
  - The total amount should be 6600 - 2498,77. One of the budget items of this project will have to be changed in order for the funds needed to be updated.
