### ISSUE TITLE
Up could use a way in the REST API to get a list of modified projects

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#1544]
To refresh data in Up, the app currently fetches the following resources:

* project (one by one, all those published by orgs the user is employed by, as was fetched at login) 
* country (all, only if not done already)
* project_up (one list per project, filtered to get only those changed since last refresh)
* user (one by one, only those not fetched yet)
* organisation (one by one, only those not fetched yet)

The only part that is not optimized is fetching the projects. A way to ask for "all the published projects by organisations that user NN is employed by" filtered by last_modified time would speed up a refresh.

**Comment by stellanl** [comment]
Such a project fetch would almost always return an empty list, except for the first time after a  user logs in.

**Comment by KasperBrandt** [comment]
@stellanl This should now be possible with the generic filters that @zzgvh built in #2095. I'll close this issue for now.
