### ISSUE TITLE
Extend location filter

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1545]
We now have the IATI fields 'recipient country' and 'recipient region' in RSR. These indicate in which country or region a project is taking place.

However, in our location filter on the listing pages, we only take into account the RSR locations (markers on the map). We should extend this to include at least the recipient countries.

If we can establish a mapping between the recipient regions and the locations as well, we should include the recipient regions as well.

**Comment by punchagan** [comment]
Fixed in #2619
