### ISSUE TITLE
MyRSR User search filter lost on pagination

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1560]
On the User Management section of MyRSR, when a user searches for a name which returns multiple results (for example 'test') and is therefore paginated, when they click to navigate to the next page of results the search term is dropped and the second page of all results is returned instead.

**Comment by zzgvh** [comment]
## Test plan
GIVEN the MyRSR user management
WHEN making a search broad enough to return enough results to paginate, e.g. search for **a**
THEN the result should retain pagination when browsing the results
