### ISSUE TITLE
Name and organisation not displayed in request organisation email

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1564]
In the request for an organisation email, the name of the user and the organisation of the request are not displayed.

**Comment by KasperBrandt** [comment]
In addition, the screen after registering also does not display the name of the user.

**Comment by kardan** [comment]
Still not displayed, this is the printout I got:

MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [Akvo RSR] Your request to join  has been approved
From: noreply@rsr.akvo.org
To: user@localdev.akvo.org
Date: Tue, 26 May 2015 13:19:16 -0000
Message-ID: <20150526131916.2764.56394@localhost>




Dear ,

Your request to join  on Akvo RSR has been approved.

Please visit the MyRSR section to view your projects and add updates to the projects here:
http://rsr.localdev.akvo.org/myrsr/

Thank you,
Akvo.org

**Comment by KasperBrandt** [comment]
@kardan Updated now, could you check again?

**Comment by rumca** [comment]
@KasperBrandt I'm not sure if it's a result of anything related to this issue, or just an environment issue with UAT - but the email functionality no longer seems to be working when I create new users, or submit a password reset request. The users are being created correctly in UAT, so it's simply the email part that's not working currently. Also checked on Live and everything is working as expected there.
