### ISSUE TITLE
indicators do not show when results are added (using RSR admin to add a project)

### ISSUE THREAD

**Issue by CharlotteSoed** [akvo/akvo-rsr#1568]
Hi guys

I think I've added this same issue before (several months ago), with the same partner, but can't find it in this huge list of outstanding issues. I also can't remember whether it had been resolved then. However, I am getting this message from a partner (Plan Finland):

"I’m having an issue in the RSR back end, in that once I have added results for a project and saved it, the fields to input indicators do not show up. FYI, I am using Chrome browser.
The project I am working on is this one: http://rsr.akvo.org/admin/rsr/project/3086/
Charlotte, I believe I had this same issue during one of our Skype sessions, which remained unresolved."

Can you please look into it and let me know how to go about this?

Cheers,
Charlotte

**Comment by KasperBrandt** [comment]
@CharlotteSoed I think this has been resolved in the previous release. Thijs Merton had the same problem and can view/add indicators now. Can you check with Plan Finland if they can as well?

I'll close the issue. If they're not able to, please re-open this issue.
