### ISSUE TITLE
Change accordion on project page

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1572]
We should change the following:

- [ ] Open the first item of the accordion by default
- [ ] Add an something (arrow, or +/-) that indicates whether the panel of the accordion is open or not

**Comment by gabemart** [comment]
I have added some very simple indicators - just a '+' and '-' sign - using CSS

![screenshot from 2015-05-15 15 16 35](https://cloud.githubusercontent.com/assets/2589977/7654498/795870c6-fb15-11e4-8057-01833f4fe7a0.png)
