### ISSUE TITLE
Errors adding an update with VMW file using the API (estimate: 8)

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1577]
Adding project update via the API with a WMF file will cause errors. We should really give a proper error message and not error.

http://sentry.support.akvo-ops.org/rsr/live/group/406/

**Comment by kardan** [comment]
We need to research the possibility to support wmf or make sure we give feedback if not.
http://stackoverflow.com/questions/14103891/convert-emf-wmf-files-to-png-jpg
http://pillow.readthedocs.org/en/latest/handbook/image-file-formats.html#wmf

**Comment by nadiagorchakova** [comment]
Error message should read "WMF files not supported".
Was decided at the RSR backlog meeting that we should not support WMF format files.

**Comment by punchagan** [comment]
Closed in #2399
