### ISSUE TITLE
Directory pages not scrollable on some viewport sizes

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-rsr#1578]
On my Android tablet, directory pages (e.g. the project listing page) can't really be scrolled because the map takes up pretty much the entire viewport and captures any touch input, meaning trying to scroll the page just scrolls the map. 

Using the stock browser on Android 4.4.2

**Comment by gabemart** [comment]
https://github.com/akvo/akvo-rsr/blob/develop/akvo/templates/inclusion_tags/maps.html#L10

The "draggable" value isn't reaching the template because dynamic is true

**Comment by punchagan** [comment]
New UI should fix this - #3116
