### ISSUE TITLE
Enable tests in CI

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1581]
Team City should run new tests.

**Comment by KasperBrandt** [comment]
@kardan Added it to CI, waiting for DevOps to grant RSR user permission for creating a database on Test and UAT.

**Comment by kardan** [comment]
https://github.com/akvo/akvo-provisioning/issues/169

**Comment by kardan** [comment]
Closing since tests are now running, work done in https://github.com/akvo/akvo-provisioning/issues/169
