### ISSUE TITLE
Minor UI issue with translations header on small windows

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1596]
@gabemart @loicsans not sure who to assign this to, or if it's worth addressing?

Due to the fact the button labels are slightly longer when they are in French or Spanish, the following happens with a smaller browser window:

![screen shot 2015-06-03 at 10 24 02](https://cloud.githubusercontent.com/assets/3003031/7956952/ab5673d2-09db-11e5-85c4-18afb7fe3d75.png)

If you resize to whatever is presumably the max width for the english labels then you get the expected collapse behaviour:

![screen shot 2015-06-03 at 10 25 20](https://cloud.githubusercontent.com/assets/3003031/7956958/c0882c82-09db-11e5-92cf-116311a0d5d9.png)

Also with the collapsed menu, when you click to swap the translation it looks a little wacky:

![screen shot 2015-06-03 at 10 32 14](https://cloud.githubusercontent.com/assets/3003031/7956969/ed6a426c-09db-11e5-8eed-46c40b0c0fbd.png)

**Comment by gabemart** [comment]
@rumca I'm having trouble reproducing the first problem - on my machine the collapse behaviour is correct even when using spanish or french labels. What browser width triggers the improper behaviour for you?

Agreed on the second point, behaviour is not as expected

**Comment by KasperBrandt** [comment]
@rumca @gabemart Same for me, collapsing behaviour of the header seems fine with French and Spanish. 

Although I do notice that the language selector is acting strangely when the navigation is folded.

**Comment by gabemart** [comment]
I've fixed the language dropdown issue, but it involves changing the vertical overflow on the nav container to `initial`. As far as I know this doesn't have any side effects as the nav menu has a fixed amount of content, but I'm not sure

![rsr-lang](https://cloud.githubusercontent.com/assets/2589977/7958709/c6e10082-09e9-11e5-83ac-6fb5505ac491.png)

**Comment by rumca** [comment]
@gabemart with the first issue I'm using Chrome (v43) and widths from 1025-1200px with Spanish translations result in the header appearing like that.

**Comment by gabemart** [comment]
@rumca ha, I was testing when logged in, which doesn't trigger the overflow, because "Desconexion" is shorter than "Inicio de sesion"

should be a straightforward fix, either by bumping the width of the container or reducing the width of the logo
