### ISSUE TITLE
Organisation double counting

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1608]
See screenshot: project page says 'reporting partner ICCO + 2 other partners'. If you hover over the (+2 partners) it shows 2 organisations, of which ICCO is also part. It seems that partners with multiple roles are counted double. 

It would make sense to show 'ICCO + 1 other partner'

![screen shot 2015-06-04 at 10 29 50](https://cloud.githubusercontent.com/assets/4179989/7977978/7d4b24e6-0a90-11e5-9392-a9fa2d1dcee3.png)

**Comment by kardan** [comment]
Testplan:
On http://rsr.test.akvo.org/en/project/1636/ make sure the <reporting partner> + <x> partners. Says correct number of partners. It should state the total number, which can be seen in the list hovering the more - the one that is "outside" the hovering.

**Comment by rumca** [comment]
test plans pass :+1:
