### ISSUE TITLE
Wiki pages status

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1612]
## Test plan
No testing needed, only update of documentation.

## Issue description
@KasperBrandt could you review the pages below. I'm finding it difficult to know if it's up to date, what's missing or what to do with them. 

1. https://github.com/akvo/akvo-rsr/wiki/RSR_Partner-API-Write-Cordaid

2. https://github.com/akvo/akvo-rsr/wiki/RSR_Partner-API-Write-RAIN

3. https://github.com/akvo/akvo-rsr/wiki/RSR_Partner-IATI

4. https://github.com/akvo/akvo-rsr/wiki/Sample-XML-Files-for-API-Load

Maybe a quick call when you looked at it will be a next action

**Comment by KasperBrandt** [comment]
@karden I'll update the wiki pages mentioned above with up-to-date information, including API usage and IATI import / export.

**Comment by KasperBrandt** [comment]
Fixed, see [wiki](https://github.com/akvo/akvo-rsr/wiki).
