### ISSUE TITLE
Small user interface enhancements

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1615]
See https://github.com/akvo/akvo-product-design/issues/104

**Comment by gabemart** [comment]
- [ ] Change 'Update list' into 'Search'


- [ ] Financial overview page
  - [ ] Remove cents display
  - [ ] Add total amount funded
  - [ ] Add project budget start and end dates


- [ ] Full data report changes
  - [ ] Fix alignment
  - [ ] Add 'Target group'
  - [ ] Rename "Current situation"
  - [ ] Change "other" labels
  - [ ] Export data button


- [ ] Project page - add budget amount and money needed


- [ ] Behaviour of enter key in when writing a project update


- [ ] "Upd..." issue

- [ ] Replace myrsr iati text

**Comment by gabemart** [comment]
Here is my proposal on how to reorganize the finance page. It is slightly different than what you suggested @lauraroverts - I think it might be a bit redundant to include "total funding" in both the 2nd and 3rd column. I propose moving Donations + Current funders to the second column, then showing the total funding + the breakdown of that figure in the 3rd column

![funding mockup](https://cloud.githubusercontent.com/assets/2589977/8212527/15b9b6b0-1514-11e5-92bb-ec4d4484d0d4.png)

@lauraroverts @KasperBrandt thoughts?

**Comment by KasperBrandt** [comment]
@gabemart Looks great!

**Comment by lauraroverts** [comment]
Perfect! Makes much more sense than what I proposed. 
One remark: In the 3th column it now says 'budget' for the total amount of the 'project financial details'. Is that obvious? Shouldn't we than also change 'Project financial details' and 'Budget'  into 'Project budget'?. To use exactly the same words?

**Comment by gabemart** [comment]
@lauraroverts I like that idea, I agree it would be clearer

**Comment by gabemart** [comment]
![pb_mockup](https://cloud.githubusercontent.com/assets/2589977/8226835/2401ff4e-159a-11e5-9b67-e76b1303c384.png)

**Comment by lauraroverts** [comment]
Nice! 
One remark again: In this example it is possible to fund more than the project actually needs (2 dollar). That should not be possible. But I believe there is another issue for that.

**Comment by gabemart** [comment]
Yep - previously when a project was funded over its budget, the "funds needed" showed up as a negative figure (in this example it would have shown as $-2.00). I have changed that to show as $0 needed when a project is over funded.

As for not letting a project get over funded in the first place, I suspect that may need some backend work to implement. 

Things I haven't done yet:

i) displayed start and end dates for each budget item. We need to decide how best to display this information as it will take up quite a lot of screen space

ii) displayed original vs revised budgets. As there can be an arbitrary number of revised budgets, I think this also needs some discussion on how to display previous budgets in an intuitive and elegant way

**Comment by rumca** [comment]
One extremely extremely minor comment, we've removed the cents from everything on the actual project page - but they're still present on the project directory page. Not sure if we want to get rid of them there too?
