### ISSUE TITLE
Add tag to project page to show part of larger consortium/campaign

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1616]
See https://github.com/akvo/akvo-product-design/issues/94

To clarify:
- Add setting on keywords: logo and boolean for showing logo
- Only for core RSR (not on Akvo Pages): 
  - Add logo on project page (in the header?) if the project is linked to keyword, and the keyword has a logo and the boolean for showing logo is true.
  - In case of multiple keywords, multiple logos should be shown

## Test plan
1. In the Keyword admin, there should be the possibility to add a logo
2. If a project is linked to a keyword that has a logo selected, this logo should be displayed in the project header on core RSR
3. The logo should not be displayed in the project header on Akvo Pages
4. If a project is linked to > 2 keywords with logos, only 2 logos should be shown

**Comment by KasperBrandt** [comment]
@lauraroverts I've now implemented it like this, with a maximum of 2 logos, you think that's ok?

![screen shot 2015-06-16 at 09 46 57](https://cloud.githubusercontent.com/assets/1497367/8178278/c8763ed0-140c-11e5-827d-5b46543fa6ba.png)

**Comment by lauraroverts** [comment]
In theory it's possible that a project is part of more than 2 campaigns/consortia, but let's do it like this with a maximum of 2 logos.

**Comment by lauraroverts** [comment]
Lissy raised an issue: Aqua for All has got an Akvo Page showing all their projects. Amongst these projects, there are also Walking for Water projects. However, the logos are not visible at Akvo Pages, and therefore she had to create a new sponsor partner in order to show that some of the Aqua for All projects are part of the Walking for Water campaign. If we are going to remove the sponsor partners in the future, there is no way to show these logos at Pages. Is it easy to add logos to Pages too with the possibility to turn them on/off?

**Comment by rumca** [comment]
logos work as intended on akvo pages now (when enabled) :+1:
