### ISSUE TITLE
Locations position & country .v.s filters issue

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1621]
When trying to filter project updates on location (country) you will not get many updates. That is since most project updates locations don't have country filled in, but only lat, long. This is very confusing for the user.

In the large there's issues with countries & stored coordinates. Ideally the country would be filled in automagically with reverse geolookup from lat/long. 

Maybe we could mitigate part of this by just adding a country selector to the add update form.

**Comment by punchagan** [comment]
Already fixed.
