### ISSUE TITLE
Add Piwik page statistics to RSR

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1624]
We should add Piwik statistics of (at least) the page views to RSR. These stats can be picked up through the Piwik API: http://piwik.org/docs/analytics-api/

## Test plan
GIVEN the footer of the project page
WHEN the page is visited
THEN a page view counter should be shown

Note; the page views should not add up on every refresh, since they're collected from Piwik and should be unique visitors.

**Comment by kardan** [comment]
@Lynngre I guess you're the one to ask about urls & feasibility of this?

**Comment by kardan** [comment]
From discussion with @Lynngre got an example request for a single url

http://analytics.akvo.org/index.php?module=API&method=Actions.getPageUrls&idSite=26&period=month&date=2015-05-01&format=json&filter_limit=5000&flat=1&token_auth=XXX&segment=pageUrl==http%3A%2F%2Fundp.akvoapp.org%2Fprojects%2F

Looks like this will not work without a defined period (day, week, month, year, range). Need to review if a broad range will work or if a smaller period is preferred.

**Comment by Lynngre** [comment]
The Akvo Pages were added individually to Piwik as of the end of last year (projects.CNAME.CNAME & Partnername.akvoapp.org).

This means that if we want data from before that time we need to, initially, get these from the Akvo.org Piwik data.  Store them & then add these additional stats to those numbers.

 Example API from Piwik:

* CommonSites CNAME - http://analytics.akvo.org/index.php?module=API&method=Actions.getPageUrls&segment=pageUrl%3D%40http%253A%252F%252Fprojects.commonsites.net%252F&idSite=30&period=month&date=2015-05-30&format=json&filter_limit=5000&flat=1&token_auth=3ae549f4e3fb9dbaa02e48f0d3aceb23
*  CommonSites Akvoapp.org - http://analytics.akvo.org/index.php?module=API&method=Actions.getPageUrls&segment=pageUrl%3D%40http%253A%252F%252Fcommonsites.akvoapp.org%252F&idSite=30&period=month&date=2015-05-30&format=json&filter_limit=5000&flat=1&token_auth=3ae549f4e3fb9dbaa02e48f0d3aceb23

The useful data is:
* label:  "label":"widgets\/project-small\/2092\/?style=light", "label":"project\/659\/index", label":"project\/1880\/updates - these are page titles
* url:  "url":"http:\/\/projects.commonsites.net\/project\/1880\/updates\/", "url":"http:\/\/projects.commonsites.net\/project\/2092\/", "url":"http:\/\/projects.commonsites.net\/widgets\/projects\/map\/?organisation_id=360&style=dark&state=dynamic&width=313&height=220" - the full url
* AND/OR segment: "segment":"pageUrl==http%3A%2F%2Fprojects.commonsites.net%2Fwidgets%2Fprojects%2Fmap%2F%3Forganisation_id%3D360%26style%3Ddark%26state%3Ddynamic%26width%3D313%26height%3D220", "segment":"pageUrl==http%3A%2F%2Fprojects.commonsites.net%2Fproject%2F2092%2F", "segment":"pageUrl==http%3A%2F%2Fprojects.commonsites.net%2Fupdates%2F" - the encoded url
* nb_visits:  These are the unique pageviews defined as the first time an IP/visitor hits the particular page in question

Do we need unique visitors (amaybe the partners are just happy to have pageviews) as only pageviews were shown previously?

**Comment by Lynngre** [comment]
The above examples are to pull data for the period of a month.

To pull all data since inception of recording use *period=range&date=2013-05-30,yesterday* for example:

http://analytics.akvo.org/index.php?module=API&method=Actions.getPageUrls&segment=pageUrl%3D%40http%253A%252F%252Fprojects.commonsites.net%252F&idSite=30&period=range&date=2013-05-30,yesterday&format=xml&filter_limit=5000&flat=1&token_auth=3ae549f4e3fb9dbaa02e48f0d3aceb23

**Comment by Lynngre** [comment]
I guess another consideration is how do the partners want the CNAME stats & the akvoapp.org stats shown?  ie.  I know that some partners are concerned with how many views were made purely via their site so using the CNAME or do we just combine them and keep it simple?

**Comment by Lynngre** [comment]
Here's a list of the siteid's for the Akvo Pages i am aware of https://docs.google.com/spreadsheets/d/1pfwOmf4aMWx4YEwYqD7SFYkc7-Z3hApcTVTQgZ5lARY/edit#gid=345212309

We should pull a new list from RSR so that I can check if there are any we are not tracking right now.

**Comment by kardan** [comment]
@lynn the simplest (as I could think of) was to just ask for the stats for the current url (https://github.com/akvo/akvo-rsr/blob/e64a7602e3a748be6a2b78aa1f2080b041756dfc/akvo/rsr/static/scripts-src/rsr.js#L171)

My gut is telling me that it's either that or serving hits per item (project, update...) and not care about url. But I guess (without knowing at all) that will be difficult with Piwik.

**Comment by kardan** [comment]
Now using something like this:
http://analytics.akvo.org/index.php?module=API&method=Actions.getPageUrls&segment=pageUrl==http%3A%2F%2Fcommonsites.akvoapp.org%2Fwidgets%2Fproject-narrow%2F807%2F%3Fstyle%3Ddark&idSite=30&period=month&date=2015-07-2&format=json&filter_limit=5000&flat=1&token_auth=3ae549f4e3fb9dbaa02e48f0d3aceb23&callback=

**Comment by Lynngre** [comment]
Ok but you're tracking widget use here, not a project view.

**Comment by kardan** [comment]
@lynn not sure if I'm missing something. But the example was just one url I randomly picked. Or is there a difference between widgets and project view as there is with RSR pages and normal RSR (with IdSite)?

**Comment by kardan** [comment]
So at the moment this aggregates stats over languages but not over different hosts. So the same project served from different hosts would get different stats. Using Piwik it would be too complex to get the aggregated data over different hosts.

**Comment by KasperBrandt** [comment]
Fixed in #1639

**Comment by lauraroverts** [comment]
@KasperBrandt is still still relevant?

**Comment by KasperBrandt** [comment]
@lauraroverts I think so, RAIN for instance asked about their site statistics this week again. However, there's no easy solution unfortunately, since it's not straightforward to add up visits on RSR + each of the Akvo Pages separately.

@kardan You've looked at this the last time. What needs to be done to make this work properly and how much time do you think we'd need to make it?

**Comment by kardan** [comment]
At the moment the data from normal RSR and the different Akvo pages are in different buckets. To get the data from an aggregate. Without talking to @Lynngre (who know way more about Piwik than me) I would guess that options are:
- Start to collect everything in one bucket (we would have to deal with past data in some way) & would might loose the ability to get one Akvo page stats.
-  Run some external aggregate scripts querying the Piwik database & storing that somewhere
- Use some other stats software that supports our needs better (if there is any)

**Comment by Lynngre** [comment]
Checking whether the 'meta sites' option in Piwik could provide pageview/visit numbers aggregation for the same project across individually tracked Piwik sites.

http://dutchforeignaffairs-ice.akvoapp.org/en/project/2671/ 
http://projects.earthwater.nl/en/project/2671/
http://cordaid.akvoapp.org/en/project/2671/
http://cordaid.akvoapp.org/fr/project/2671/
http://rsr.akvo.org/en/project/2671/

Right now it seems to only allow for an overall of all traffic & selecting to look at the dashboard doesn't provide what's expected. I've contacted Piwik support & will update.

**Comment by Lynngre** [comment]
@piwik support guys are upgrading our version & adding a new fixed version of the 'meta sites' plugin to allow us to combine two sets of data for individual urls for reports. This can only be done the second week in October @kardan should this be handed over to @zzgvh instead?

**Comment by kardan** [comment]
@Lynngre sounds like a good idea to hand over this.

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#166
