### ISSUE TITLE
Logo consortium too small

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1631]
Added the WASH Alliance logo to http://rsr.akvo.org/en/project/475/. It's quite small. Would it be possible to display it slightly bigger, like the logo that is being used at the Akvo Pages http://washalliance.akvoapp.org/en/project/475/?

**Comment by rumca** [comment]
Looks like this now:

![screen shot 2015-07-15 at 10 12 15](https://cloud.githubusercontent.com/assets/3003031/8694910/044cb630-2ada-11e5-991f-b179343cf930.png)

which I assume is a passing test :+1:

**Comment by KasperBrandt** [comment]
Not the best design, but I guess the times that we have to display 2 logos are rare anyway.. At least the text is readable, that's more important.

**Comment by lauraroverts** [comment]
Looks a bit weird having the logos stick to each other. Size seems good.
