### ISSUE TITLE
Replicate right_now_in_akvo API endpoint in the DRF API

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1636]
In the old Tastypie API we have a custom endpoint, http://rsr.akvo.org/api/v1/right_now_in_akvo/?format=json, that returns stats we use on http://akvo.org/seeithappen.

This endpoint should be replicated in re DRF based API at rsr.akvo.org/rest/.

When doing this, the total number of project updates in RSR should be added to the endpoint as the field ```number_of_project_updates```.

**Comment by lauraroverts** [comment]
@zzgvh is this still relevant?
