### ISSUE TITLE
Project status automatically change 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1641]
It would be very practical if the project status would automatically change from 'Needs funding' to 'Active' when money has been donated to a project and the project is then fully funded. Or when the total project budget is exactly the same as the total amount that is funded by a funding partner, like http://walkingforwater2015.akvoapp.org/en/project/2616/

In addition: for projects where the project budget matches the amount funded, it should not be possible to have a donate button. Ideally the donate button would disappear. E.g. http://walkingforwater2015.akvoapp.org/en/project/2764/ has got a project budget of 50.000. The amount funded is also 50.000, but there is still a donate button. 

![screen shot 2015-07-07 at 13 48 09](https://cloud.githubusercontent.com/assets/4179989/8545444/11f8fed2-24af-11e5-8866-fe1a6b8761a8.png)

**Comment by kardan** [comment]
This is a feature that I had suggested in the past but was then told that we need a manual step since there is tasks outside of RSR that needs to be done. Not sure if this is the case any longer.

**Comment by mtwestra** [comment]
We are removing the donate functionality, so this is no longer relevant. Closing.
