### ISSUE TITLE
Partner logos are displayed very large

### ISSUE THREAD

**Issue by Lissyvn** [akvo/akvo-rsr#1667]
## Test plan
GIVEN the project main page
WHEN viewing the '+ more' partners tooltip
THEN the organisation logos should be appropriately sized (not too big as in the image below)

## Issue description
Project pages on rsr.akvo.org , Akvo pages and Akvo sites are showing very large partner logos. I guess this happened after the last RSR release. Screenshots attached below. 
![screen shot 2015-07-17 at 13 58 51 2](https://cloud.githubusercontent.com/assets/4972211/8746697/411e141a-2c8c-11e5-9927-480db2cd4024.png)
![screen shot 2015-07-17 at 13 59 14 2](https://cloud.githubusercontent.com/assets/4972211/8746702/48776392-2c8c-11e5-98c7-dcacf8a73a4a.png)
![screen shot 2015-07-17 at 13 59 36 2](https://cloud.githubusercontent.com/assets/4972211/8746707/52176c8a-2c8c-11e5-904f-bba5cf566f87.png)

**Comment by KasperBrandt** [comment]
Fixed in #1702
