### ISSUE TITLE
Project partner alignment

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1674]
## Test plan
GIVEN the project partners page
WHEN viewing the partners
THEN there should be an organisation logo or placeholder displayed for every partner

## Issue description
Project partners should all have same alignment. Now some align left, while others centre, see screenshot

![screen shot 2015-07-21 at 11 43 02](https://cloud.githubusercontent.com/assets/4179989/8797777/f709132e-2f9d-11e5-99f7-a6c6edb5b56c.png)

**Comment by KasperBrandt** [comment]
Merged in #1703
