### ISSUE TITLE
Psql-related operational error

### ISSUE THREAD

**Issue by orifito** [akvo/akvo-rsr#1677]
We are experiencing the following error:
```
OperationalError: could not connect to server: Connection refused
    Is the server running on host "XXX" (x.y.z.w) and accepting
    TCP/IP connections on port N?
```
It's an intermittent issue, occurred 16 times in last 5 months.
It seems dns resolution fails. In that case, the application is trying to connect to a wrong host where our wildcard cname points to.

**Comment by orifito** [comment]
Applied on test env. Finally decided to move wildcard dns entry to point to server hosting psql (this was the setup before moving RSR to another server)

**Comment by orifito** [comment]
Apart from this workaround, just realized of an "ugly" configuration with regard to DNS resolvers. I would propose to modify this configuration to always use our nameservers on each environment.

**Comment by orifito** [comment]
Test and UAT enviornments configured to use our internal NS as a DNS resolver. Let's see how it evolves on those envs

**Comment by orifito** [comment]
Reverted "wildcard" workaround applied, should be enough if we set the right DNS resolvers.

**Comment by KasperBrandt** [comment]
@orifito I get the same right now when I try to run pg_dump on UAT or Live.. Any clue?

**Comment by KasperBrandt** [comment]
@orifito I haven't seen these errors for a while on Live, but I do get some errors from UAT every now and then. What do you think about it, close this issue or investigate a bit more?

**Comment by orifito** [comment]
We are no longer receiving those errors and thus this issue could be closed. However, I prefer to investigate further, and maybe apply some changes with regard to nameservers we are using.

**Comment by orifito** [comment]
There are no further problems when using default cloudvps nameservers. So, just restored default configuration in all environments.
