### ISSUE TITLE
Photo credit field character length

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#1682]
The 'photo credit' field currently only allows for 25 characters (although according to @KasperBrandt  it's set to 50).

http://rsr.akvo.org/en/project/projectid/add_update/

This field should allow for more characters not only because it's  even too short of full name right now, bu also often a website may be added as a photo credit. (eg. http://microlancer.lancerassets.com - is the one I was trying to add http://rsr.akvo.org/en/project/3324/update/10642/ ).

## Test plan
GIVEN the add update page
WHEN filling in a new update
THEN it should be possible to enter 75 characters in the 'photo credit' and 'video credit' fields

**Comment by KasperBrandt** [comment]
Fixed in #1701
