### ISSUE TITLE
Add a new project button in MyRSR is hardcoded

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1707]
The **Add a new project** button on the My projects page of MyRSR is hardcoded to http://rsr.akvo.org/admin/rsr/project/add

**Comment by KasperBrandt** [comment]
Yeah, correct :(.. @gabemart noticed that too when we were working on the admin. It has been fixed in the develop branch, but we can take it along in this small release too.

**Comment by KasperBrandt** [comment]
Will be fixed in #1525
