### ISSUE TITLE
Issue layout project update

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1722]
Christien got a message from Commonsites. They added this update: http://rsr.akvo.org/en/project/2092/update/10887/

In the admin you can see they used ' - ' as bullet points in the textfield. See screenshot:
![screen shot 2015-08-12 at 14 40 48](https://cloud.githubusercontent.com/assets/4179989/9224129/60479efa-4100-11e5-9526-74e42d835690.png)

But in the project update listing, you see boxes with a grey line around it in the update, see screenshot: 
![screen shot 2015-08-12 at 14 40 30](https://cloud.githubusercontent.com/assets/4179989/9224124/5b17d332-4100-11e5-8f13-613378e13153.png)

Christien has now removed the ' - ' and the boxes have disappeared.

**Comment by gabemart** [comment]
# Test Plan

1) Create a new update in the admin with the following bullet point syntax:

     Text
      - point 1
      - point 2

2) Verify the bullet points display correctly in the "excerpt" view on the Update tab

![screen shot 2015-09-16 at 17 41 11](https://cloud.githubusercontent.com/assets/2589977/9911474/393112c8-5c9a-11e5-8b1b-71d4a8a85d8f.png)

3) Verify the bullet points display correctly in the full view

![screen shot 2015-09-16 at 17 41 26](https://cloud.githubusercontent.com/assets/2589977/9911480/3d895ba0-5c9a-11e5-93c4-630b11b18814.png)
