### ISSUE TITLE
Locations data migration fails in some cases

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1736]
## Test plan
GIVEN the RSR database
WHEN considering all location models (project, project update and organisation)
THEN there should be no objects with the project, project update or organisation set to NULL

## Issue description
Migration 0015_auto_20150714_0853 fails for me when run on my vagrant with data from the live server. Seems there's an unclosed transaction that triggers the failure.

The fix for this is to split the migration in two parts, one that only does the data migration and one that does the schema migration.

**Comment by KasperBrandt** [comment]
Fixed in #1737
