### ISSUE TITLE
Partnerships with no organisations should not be allowed

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1750]
## Test plan
GIVEN the project editor
WHEN the project has a funding partnership without an organisation
THEN an error should be displayed that the organisation field isn't filled in

**Comment by zzgvh** [comment]
Actually I think I disagree with the solution here. Is there any scenario where it's valid to have a funding amount without a funding organisation? If not then there should be validation preventing this data from being entered.
