### ISSUE TITLE
Filter on long and short name in typeaheads

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1752]
In all organisation typeaheads, it should be possible to filter on (and show?) the long and short names.

**Comment by gabemart** [comment]
Currently, the organisation typeahead gets data from `/rest/v1/typeaheads/organisations?format=json` - this does not return a long-name and a short-name, just a name. Is there an API call that returns both formats of name?

**Comment by gabemart** [comment]
Uncommenting https://github.com/akvo/akvo-rsr/blob/develop/akvo/rest/serializers/typeahead.py#L33 seems to work, and not immediately break anything

**Comment by gabemart** [comment]
Merging with #1751
