### ISSUE TITLE
User account cleanup

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1753]
We should:
- [x] Remove all non-admin/superuser user accounts without an employment older than a week
- [x] Remove all non-activated user accounts older than a week
- [ ] Set a clean-up rule for deleting an account when not activated within a week

With the upcoming change in mind that a user **has** to select an organisation upon registration, this will prevent spam accounts.

**Comment by damienallen** [comment]
- Script can be ran using '**sh manage.sh user_cleanup**'
- Command with '**-v 2**' flag will list users to be removed
- Command with '**-d**' flag will delete listed users
- Run 'sh manage.sh help user_cleanup' will list all options

# Test plan
- Check if inactive accounts older than 7 (default) days are filtered correctly
- Check if accounts lacking employment (also older than 7 days) are filtered correctly
- Check if admins and superusers are excluded from the filters
- Check that the -d flag actually removes those users
