### ISSUE TITLE
Remove Zepto (and jQuery) from project editor

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1765]
As a first step to completely remove jQuery from RSR, let's remove it completely from the project editor. As far as I know we only use Zepto, but that should also be rewritten to regular Javascript.

**Comment by gabemart** [comment]
# Test Plan

The test procedure should ensure the functionality of the project editor does not change when merging in this change.

1) Enter the project editor with an active project

2) Verify that adding new subsections works properly. E.g. "Related project" in section 1.

3) Verify that clicking on the small info icons (i) toggles the appearance of the appropriate help text for the particular icon. Verify this behaviour is also correct in newly added subsections.

4) Verify the autocomplete feature works for the appropriate inputs - E.g. "Related project" in section 1. Verify this behaviour is also correct in newly added subsections.

5) Verify the datepicker works for date inputs, including date inputs in newly added subsections - e.g. "Indicator period" in section 5.

6) Verify character limits work for appropriate inputs, including in newly added subsections - e.g. "Target Value" in section 5

7) Verify the image upload facility operates correctly in section 1

8) Verify that removing subsections using the red trashcan icon works correctly

9) Verify that the "save" functionality works correctly, including correclty storing the removal or addition of subsections

**Comment by KasperBrandt** [comment]
Fixed in #1805
