### ISSUE TITLE
Budgets per period

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1771]
## Test plan
1) Verify that the budget period is displayed on the project finance page, when available

## Issue description
It is currently possible to indicate a budget period in the project editor, but this isn't shown on the project finance page. This should be added.

**Comment by gabemart** [comment]
Is it also required to show the "Budget item value date"?

**Comment by gabemart** [comment]
Proposed approach:

![image](https://cloud.githubusercontent.com/assets/2589977/9931498/191fd88a-5d34-11e5-9d8b-92e7641653b7.png)

As you can see, if we only have one date for budget period, we show it by itself, but I imagine it is not intended to have only one date?

**Comment by KasperBrandt** [comment]
Two small things;
1. Add a ':' after budget period
2. Would there be a way of increasing the character limit on the budget item name? Since it's often shortened now.. Although this might be hard if we take the smaller viewports into consideration.

**Comment by gabemart** [comment]
I've made the alterations you suggest. On full width viewport I have bumped the width of the budget item name to 60%. On narrower viewports this is overridden by the existing code.

![image](https://cloud.githubusercontent.com/assets/2589977/9937520/05a8efe2-5d59-11e5-97bd-a6f6f48254b4.png)
