### ISSUE TITLE
API crashes when a non-valid date is entered

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1774]
E.g. ```http://rsr.akvo.org/rest/v1/project_update_extra/?created_at__gt=2015-07```

**Comment by damienallen** [comment]
Test plan:

Open: http://rsr.localdev.akvo.org/rest/v1/project_update_extra/?created_at__gt=2015-02-01
No error should be raised

Open: http://rsr.localdev.akvo.org/rest/v1/project_update_extra/?created_at__gt=2015-02
Date will be changed to yyyy-mm-01 (internally), no error should be raised

Open: http://rsr.localdev.akvo.org/rest/v1/project_update_extra/?created_at__gt=2015-99
400 error should be raised for values not matching yyyy-mm(-dd)

**Comment by KasperBrandt** [comment]
Date-time values are no longer accepted for the filter parameters

**Comment by stellanl** [comment]
As a result, Up fetching of Updates is broken, as it uses a URL like this:
http://rsr.test.akvo.org/rest/v1/project_update/?format=xml&project=1336&last_modified_at__gt=1970-01-01T00:00:00

which returns:
400 BAD REQUEST
<?xml version="1.0" encoding="utf-8"?>
<root><detail>created_at and last_modified_at dates must be in format: yyyy-mm-dd</detail></root>

**Comment by KasperBrandt** [comment]
## Test plan
Try http://rsr.localdev.akvo.org/rest/v1/project_update/?format=xml&project=1336&last_modified_at__gt=1970-01-01T00:00:00, or any other valid datetime.

**Comment by KasperBrandt** [comment]
Fixed in #2204
