### ISSUE TITLE
Minor UI issue on project editor

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1776]
## Test plan
GIVEN an unpublished project in the project editor in Chrome
WHEN the window size is decreased
THEN the publish button shouldn't overlap with the border of the legenda box

## Issue description
@gabemart this is really quite minor, but when the window size is decreased on the project editor with chrome the publish button doesn't look quite right:

![screen shot 2015-08-26 at 16 12 01](https://cloud.githubusercontent.com/assets/3003031/9497567/81ffd298-4c0d-11e5-9ac3-c87508972db9.png)

**Comment by KasperBrandt** [comment]
Oh, that's my doing.. But it's probably good that @gabemart takes a look at this anyway :)
