### ISSUE TITLE
Add a ?body= on the feedback button to provide the user with a feedback template

### ISSUE THREAD

**Issue by akvotender** [akvo/akvo-rsr#1784]
## Test plan
GIVEN the project editor
WHEN feedback button on the right is clicked
THEN the email should contain a body with the text as specified in the issue description

## Issue description
By giving the user a template we can expect more valuable and structured feedback.

"
Thanks a lot for giving us feedback about the new project editor. This helps us with the continuous improvement of RSR. Please provide us at least the following information:

Your project:
Positive about the new project editor:
This could be improved:
General remarks:
"

**Comment by Geerts** [comment]
So Akvotender in this case was me.
