### ISSUE TITLE
Amusing UI issue - save button evades clicking

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1791]
When filling out a field which has a character limit (e.g. Photo caption or Photo credit) when a user goes to click the save button - the on focus loss event or which event is responsible for removing the character count fires before the onclick even on the button:

![screen shot 2015-09-02 at 14 03 51](https://cloud.githubusercontent.com/assets/3003031/9631852/a2fa3664-517b-11e5-8e06-4884b18eb68e.png)

![screen shot 2015-09-02 at 14 03 59](https://cloud.githubusercontent.com/assets/3003031/9631858/a8a2a088-517b-11e5-8ec3-98171e2755a5.png)

This means that from the user's perspective they seem to be clicking the button twice before it actually saves.

**Comment by gabemart** [comment]
I can reproduce and can confirm, it's amusing. 

Should be a simple fix using a setTimeout for the listener. I'll make the change once I'm done rewriting the zepto stuff in vanilla js.

**Comment by gabemart** [comment]
# Test Plan

1) In the Project Editor, select the "Photo caption" input and add some characters

2) Verify the "characters left" help text appears"

3) Click the "Save" button.

4) Verify the save button is activated on the first click

5) Verify the "characters left" help text disappears shortly after the first click
