### ISSUE TITLE
API endpoint to get server information/configuration needed.

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#1798]
AN API endpoint that would return server settings would be useful for:
 * Getting the setting for update edit grace period.
 * Getting a server description string ("Production server", "Test server" etc)
 * Verifying that there is a working API on the server. (For Up, verifying that the user has spelled the server URL right)
Other data items could be added over time.

**Comment by zzgvh** [comment]
## Test plan

* Go to http://rsr.test.akvo.org/rest/v1/server_info/
* The response should be similar to this:
```json
{
    "CANONICAL_HOST_NAME": "rsr1.localdev.akvo.org", 
    "DEPLOY_BRANCH": "", 
    "DEPLOY_COMMIT_ID": "", 
    "DEPLOY_TAG": "", 
    "PROJECT_UPDATE_TIMEOUT": 20
}
```

CANONICAL_HOST_NAME should be rsr.test.akvo.org or similar, the DEPLOY_... fields should contain data corresponding to the branch running on test.
