### ISSUE TITLE
Reporting organisation vs project partner

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1800]
In general, the reporting organistion is not seen as a partner of a project, which causes issues when the reporting organisation of a project is actually not specified as one of the partners. For example;

- When filtering on organisation in the project list, the reporting organisation is not taken into account.
- On the organisation page, the projects of which the organisation is a reporting organisation are not counted.

**Comment by zzgvh** [comment]
Seems to me the solution is to create a new partner type, Reporting organisation, and assign the reporting org in the same way as other project partners. We can then remove the sync_owner field.

We'd have to handle reporting orgs separately when exporting to IATI and also make sure there's exactly one reporting org for each project. This will also drive editing rights (I think). It'll make for a cleaner handling of project partners in general.

Not all projects have a sync_owner currently. This must be fixed when doing this change.

**Comment by KasperBrandt** [comment]
@zzgvh Yeah, I was thinking in the same direction. I believe we should keep the ```sync_owner``` field so that it actually indicates what it says, though. During imports, we can check if the project can be edited based on the reporting organisation, but we can display a message in the project editor such as "This project has been automatically imported, be aware that any manual changes might be overwritten in the future."

As for the reporting organisation, making it a partner type makes sense. And we need an additional check that there is only 1 reporting organisation per project indeed. I'm not sure if it should be a requirement that every project has a reporting organisation though. It would make checking for editing rights easier, but at the moment we don't really know the reporting organisation for a lot of projects. 

Maybe we can think of an intermediate solution for now, and enforce the reporting organisation in a later release. What do you think?

**Comment by zzgvh** [comment]
Closing this as the discussion continues in #1826.
