### ISSUE TITLE
Move to IATI country list by default

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1804]
We now have our own country list in RSR, and IATI also uses a country list (which we also use for some fields, such as recipient country). I think we should completely switch to the IATI country list, but that also involves some other changes (filters on RSR pages, etc).

- [x] Projects
  - [x] Remove the rsr_projectlocation.country field from the project editor
  - [x] Remove all mentions of rsr_projectlocation.country in the validation sets
  - [x] Do not hide recipient countries and regions in the RSR validation set
  - [x] Convert any country of a project location to a recipient country
  - [x] Remove the country field as a mandatory field for publishing in RSR
  - [x] Update project page
    - [x] Project header
    - [x] Full report tab (remove country field from location)
    - [x] Donation thanks page
  - [x] Update projects list
    - [x] Update mention of country per project
    - [x] Update location filter
  - [x] Update IATI import
  - [x] Add comment to state that location.country is legacy
- [x] Project updates
  - [x] Remove project update location countries (not used)
  - [x] Remove location filter on updates list
- [x] Organisations
  - [x] Add new iati_country field
  - [x] Convert existing countries to IATI countries
  - [x] Replace country field in 'old' organisation admin
  - [x] Add comment to state that location.country is legacy
  - [x] Update location filter on organisations list
  - [x] Update organisations list
- [x] Employments
  - [x] Convert the employment countries to IATI countries
  - [x] Update 'Request to join an organisation' module
- [x] Make all migrations reversable

**Comment by stellanl** [comment]
Don't forget the API.
Bumping the modification date for projects and updates will make them reload, but Up currently assumes the country list will almost never change. If all the countries suddenly have different IDs it will be very confusing. Maybe we need a mechanism in the API for indicating an invalidation of cached data.

**Comment by KasperBrandt** [comment]
@stellanl I'm planning the following changes, let me know if you are ok with that:

- The _country_ field for a project location stays in the model and API as it is right now. Basically, as a legacy field.
- The location field gets removed from the project editor and all countries are mapped to a _recipient country_.
- All filters etc are based on the _recipient country_ and _recipient region_ fields.

**Comment by stellanl** [comment]
Should be ok, I only display the country, so the old Up apps should be ok as long as the field stays around. It is maybe an hour's work to switch to a new country field for some an Up release

**Comment by stellanl** [comment]
There is also a country id field in the employment application API.

**Comment by KasperBrandt** [comment]
## Test plan
To do.

**Comment by KasperBrandt** [comment]
After merging into test, it seems that the migrations are failing:

```
[14:04:33][Step 3/7]   File "/var/akvo/rsr/versions/deploy-RSR_Deploy-830/code/akvo/rsr/migrations/0071_auto_20160525_1036.py", line 121, in convert_locations_to_recipient_countries
[14:04:33][Step 3/7]     RecipientCountry.objects.get_or_create(project=project, country=country_code)
[14:04:33][Step 3/7] __fake__.MultipleObjectsReturned: get() returned more than one RecipientCountry -- it returned 2!
```

**Comment by KasperBrandt** [comment]
User management is now broken, see http://rsr.test.akvo.org/en/myrsr/user_management/.
