### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1808]
Below you'll find a list of smaller issues that can be handled in one release:

- [x] #1069
- [x] #1288
- [x] #1465 
- [x] #1500
- [x] #1677 
- [x] #1849 
- [x] #1851 
- [x] #1866

**Comment by gabemart** [comment]
Checkbox list:

- [ ] #1251 
- [ ] #273 
- [ ] #1465 
- [ ] #1069 
- [ ] #1577 
- [ ] #1677 
- [ ] #1796 
- [ ] #1578 
- [ ] #1500 
- [ ] #1510 
- [ ] #1066 
- [ ] #1722 
- [ ] #1288

**Comment by KasperBrandt** [comment]
All items done. See list above.
