### ISSUE TITLE
Mapping issue, countries not shown?

### ISSUE THREAD

**Issue by siemvaessen** [akvo/akvo-rsr#1821]
From http://rsr.akvo.org/en/projects/ I am trying to find out if any projects are set in Egypt. Mapview provided 0, but when I search for Egypt I get a single result: http://rsr.akvo.org/en/project/705/

Some hickup?

**Comment by lauraroverts** [comment]
At this moment the map only shows the 10 projects that are listed at the page you are looking it. An explanation text will be added to the map: https://github.com/akvo/akvo-rsr/issues/1288
