### ISSUE TITLE
Create reporting organisations for all projects

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1826]
We currently have a Project.sync_owner field that is used both to control who is allowed to edit the project but also has take the role of designating the IATI reporting organisation for the project.

Both those roles can be fulfilled by adding a new choice to the Partnership.iati_organisation_role field. In addition we need a is_secondary_reporter field on the Partnership model to be able to handle the needs of the IATI reporting-org@secondary-reporter attribute.

When doing this we need to make sure all projects have or get a reporting organisation partnership object as these will drive both the editing rights of the project and designates the reporting-org IATI field. The default way of doing this is to set the Support partner as the Reporting organisation. However, there are probably projects with more than one Support partner (Accountable in IATI parlance). For those we need to decide on one of the organisations as the reporting org.

**Comment by zzgvh** [comment]
The management script outputs info on all projects, in two sections, CSV-formatted. One with projects where there is a sync_owner and either no support partner or exactly one, and it is the same org as the sync_owner. Those projects should be fine to migrate, the organisation in question becoming the reporting-org.

The second listing are projects with problems:
* projects with no sync_owner and no support partner
* projects where sync_owner and support partner don't match
* projects with more than one support partner

**Comment by zzgvh** [comment]
Updated the script after realizing more possible states. The script now determines a reporting organisation as follows:
* if there is no support partner
  * if there is a sync_owner then the sync_owner is set as reporting-org
  * if there is no sync_owner report the problem
* if there is exactly one support partner:
  * if there is no sync_owner then set the support partner as reporting-org
  * if there is a sync_owner, make sure it is the same org as the support partner and if so set as reporting_org
  * otherwise report the mismatch
* if there is more than one support partner:
  * if there is a sync_owner set that org as the reporting_org
  * otherwise report the problem

[I'm including a preliminary run of the script](https://github.com/akvo/akvo-rsr/files/5081/reporting-org_problem_projects.txt) (the dataset is a couple of weeks old) where there are around 150 projects that don't get a reporting-org according to the above algorithm. Note that the file is saved as a .txt because GH won't allow a .csv :stuck_out_tongue:

**Comment by zzgvh** [comment]
[Heres a new version](https://github.com/akvo/akvo-rsr/files/5789/reporting-org_problem_projects_published.txt) of the problem projects with only published projects. Unfortunately the list isn't that much shorter. :disappointed:

**Comment by zzgvh** [comment]
[List of reporting orgs where the algorithm above selects an organisation](https://github.com/akvo/akvo-rsr/files/5968/reporting-org_projects.txt)

**Comment by zzgvh** [comment]
After more discussion we've come to the realization that we need a separate way of indicating which organisation "owns" a projects in terms of publishing and also who can create new projects. This can, at least initially be the same field.

Suggested changes:
* Add a boolean field ```Organisation.project_creator``` indicating that users of the organisation are allowed to create new projects and publish projects where they are accountable partner and/or reporting organisation.
* Set ```Organisation.project_creator``` for the appropriate partners
* Add a new choice, ```(200, 'Reporting organisation')```, to ```Partnership.iati_organisation_role.choices```. This allows us to create new partnership objects indicating the reporting-org of a project.
  * Migrate using an extended version of the algorithm above:
    * if there is no accountable partner
        * if there is no sync_owner report the problem
        * if the sync_owner is not a project_creator report the problem
        * otherwise sync_owner is set as reporting-org
    * if there is exactly one accountable partner:
        * if the accountable partner is not a project_creator report the problem
        * if there is no sync_owner then set the accountable partner as reporting-org
        * if there is a sync_owner, make sure it is the same org as the accountable partner and if so set as reporting-org
        * otherwise report the mismatch (alternatively we might allow the mismatch as long as exactly one of the two organisations is a project_creator)
    * if there is more than one accountable partner:
        * if more than one organisation among the accountables that is project_creator report the problem
        * if there is a sync_owner:
            * if the sync_owner is either among the accountable organisations and is not a project_creator set it as reporting-org
            * otherwise report the problem (alternatively make sure only one among the accountables + the sync_owner is project_creator)
        * otherwise report the problem (i.e. we can't determine who's reporting-org, altho we could allow multiple accountable orgs as long as only one is project_creator)

A related issue that this results in is how do we manage changes on a published project? If a project is published, can a user from an organisation that is not a project_creator make changes? And if so, is the project automatically unpublished? Either way there are corner cases...

**Comment by zzgvh** [comment]
Referring to #1800, I think you're right @KasperBrandt, that we keep the sync_owner (altho I'd like to rename it to content_owner or publisher) to clearly indicate who is the publisher of the project. This in turn means that all projects should be assigned a content_owner and the content_owner must be a project_creator organisation.

**Comment by KasperBrandt** [comment]
@zzgvh Completely agree :)

**Comment by zzgvh** [comment]
A result of removing the "overloaded" Project.sync_owner field, we need a way to designate the organisations that can create and publish projects. For this we create the field Organisation.project_creator. The field is populated using a list from @lauraroverts and the partner team.

**Comment by zzgvh** [comment]
[Here is a CSV](https://github.com/akvo/akvo-rsr/files/11737/cannot_publish.txt) (saved as .txt because of GH...) that lists all projects that won't have a "publishing" partner, i.e. a parnter organisation where ```Organisation.can_create_projects == True``` unless the project has an "akvo" partner, that is an organisation with Akvo in its name. The list also indicates the current sync_owner if there is one. Since the list is over 700 projects long it seems to me we might want to consider what to do before doing this migration.

**Comment by zzgvh** [comment]
[New version of the CSV](https://github.com/akvo/akvo-rsr/files/11827/cannot_publish.txt) with projects without a publisher, based on the current live database.

**Comment by zzgvh** [comment]
[New version of listing of projects' reporting-org after migrating the live DB of yesterday.](https://github.com/akvo/akvo-rsr/files/13153/reporting_org_migration.txt)
[New version of the projects that don't get a reporting-org.](https://github.com/akvo/akvo-rsr/files/13157/no_reporting_org.txt) The list is now now nicely short!

**Comment by zzgvh** [comment]
# Test plan

To be able to test this issue the data needs to be migrated. Since that operation is a rather long-running operation I have made it a managment command instead of a migration, that can be run after deploying the branch so that the database schema is migrated.

To run the data migration use the django manage.py command thus:

```manage.py reporting_orgs --migrate```

The command can also be run without the --migrate flag. It will then only output the outcome of a migration without actually making it.

It is recommended that the result of running ```reporting_orgs``` is saved when running the actual migration as a reference to how the data was migrated. The output can be copied into a CSV or empty spreadsheet (haven't tried with google spreadsheet).

When the data has been migrated most projects should have a reporting organisation partner assigned. Refer to the ```reporting_orgs``` output for projects with and without a reporting-org.

### Testable changes

In the  RSR admin, the Project form and in the MyRSR project editor section 3, the section Reporting organisation is removed, and instead most projects have a Project partner with the Reporting organisation role.

In the project partners page of a project (```/project/NNNN/partners/```) most projects will have an organisation listed with the Reporting organisation role.

The REST API for projects (```/rest/v1/project/```) should only see the reporting organisation as an addition in the list of partners, but the sync_owner and sync_owner_secondary_reporter fields should remain, to maintain the API stability. The values for sync_owner and sync_owner_secondary_reporter will remain the same for most projects, excepting the ones on the list of projects that couldn't be migrated from the ```repoting_orgs``` output.

The next batch of Coraid IATI import projects should be tested before deploying it to live. I'm reasonably confident it works, since it does with the last batch, but it might be good to make sure once more.
