### ISSUE TITLE
Reports for results framework

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1831]
Using ReportServer, we should be able to create a PDF version for the results framework.

**Comment by stellanl** [comment]
My understanding so far:

A PDF report for a single project, with results, indicators and periods, formatted along the lines of the PPP_Report_2014_2015.05.21_final.pdf

Parameters would be
- Project ID
- Time span? (Including only the indicator periods that fall within it.)

**Comment by stellanl** [comment]
The Result section is now hidden if totally empty, but looks weird for a project that has Results but no Indicators or Periods: the periods etc are output as (null) fields.

**Comment by stellanl** [comment]
Selecting * for a dataset with a join creates aliases for duplicated names (such as id) like id_9 and id_28. If the table is later changed (such as adding more columns) these aliases will change and break a report that relies on them.
