### ISSUE TITLE
It should be possible to add keywords for anyone

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1832]
## Test plan
1. Login to the project editor as an organisation Admin or Project editor
2. You should see and be able to add or edit keywords in section 10 of the project editor

## Issue description
Currently in the project editor, it only possible for Akvo staff to add keywords. However, it should be possible for partners as well, since it will influence which projects will be shown on their Akvo Page.

**Comment by gabemart** [comment]
Code checked
