### ISSUE TITLE
CSS Akvo Pages

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1847]
In the CSS template for Akvo Pages nothing can be found about the MyRSR section. If you login to MyRSR at http://aquaforall.akvoapp.org/en/projects/ there are some issues with the layout. E.g. you can't read the text in the box below: 

![screen shot 2015-10-07 at 09 09 27](https://cloud.githubusercontent.com/assets/4179989/10331141/2a402ba2-6cd3-11e5-87bc-f6c8f3d3b787.png)

The same applies for http://iggwater.akvoapp.org/en/myrsr/

![screen shot 2015-12-30 at 10 19 00](https://cloud.githubusercontent.com/assets/4179989/12048719/e41b2c96-aede-11e5-8541-02f549724679.png)

It is very likely that this is the case for other Pages as well.

**Comment by lauraroverts** [comment]
@Anna-Marthe is this something you could help with?

**Comment by Anna-Marthe** [comment]
@lauraroverts I'll have a look at this later this month!

**Comment by lauraroverts** [comment]
Hi @Anna-Marthe do you have time to look at this this week?

**Comment by Anna-Marthe** [comment]
**Done** and new code is added to the template file.

CSS code is as follows:
/* MY RSR SECTION (login) */

.btn-success {
    color: #fff;										/* add new project button */
    background-color: #cce0f1;
    border-color: #ccc;
}

.btn-success:hover {								/* add new project button - hover */
    color: #fff;
    background-color: #01689b;
    border-color: #ccc;
}


.myRsrMenu nav[role=navigation] {						/* change background navigation bar left */
    background: #cce0f1;
}

.myRsrMenu nav[role=navigation] ul li a {				/* change text colour navigation bar left */
    background: #cce0f1;
    color: #CCC;
}

.myRsrMenu nav[role=navigation] ul li a.active {
    background: #01689b;								/* change background colour navigation bar left of active tab */
}

.myRsrMenu nav[role=navigation] ul li a:hover {
    color: #CCC;									/* change text colour navigation bar left when hovering */
    background: #01689b;								/* change background colour navigation bar left when hovering */
}


.twoColumns a {
    background: #cce0f1;							/* edit button in project list */
    color: white;	
}

.twoColumns a:hover {
    background: #01689b;							/* edit button in project list - hovering */
    color: white;
}

.myProjectList tbody tr.notPublished {				/* background of non-published projects */
    background: #eaebee !important;
}


Both A4A and IGG have been fixed.
<img width="1278" alt="screen shot 2016-01-21 at 13 49 20" src="https://cloud.githubusercontent.com/assets/5310896/12472772/98a2676a-c046-11e5-82b1-81715aeed347.png">
