### ISSUE TITLE
Optimize logo lay-out of keywords

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1855]
## Test plan
GIVEN the project page
WHEN a project has 2 or more keywords with a logo attached
THEN two logos should be shown in the project header
AND they should be horizontally aligned
AND there should be spacing in between the two logos

## Issue description
At Akvo Pages you can now show 2 logos, e.g. http://aquaforall.akvoapp.org/en/project/3322/
But it doesn't look very nice. 

![screen shot 2015-10-09 at 15 32 57](https://cloud.githubusercontent.com/assets/4179989/10395020/0c26f8de-6e9b-11e5-85e4-9d27bc1f86a7.png)

**Comment by lauraroverts** [comment]
This might also influence #1948

**Comment by gabemart** [comment]
@lauraroverts I suggest it is enough to just align the logos evenly in this case

![image](https://cloud.githubusercontent.com/assets/2589977/12359150/bfae631a-bba8-11e5-95c6-d0fd0486b956.png)

**Comment by lauraroverts** [comment]
Wouldn't ik look better to display the logos next to each other? Otherwise this is okay.

**Comment by KasperBrandt** [comment]
Yeah, maybe that's nicer indeed :+1:, could you have a go at that @gabemart?

**Comment by gabemart** [comment]
![image](https://cloud.githubusercontent.com/assets/2589977/12417693/b9340a7a-bea1-11e5-9861-ce4eff92276f.png)

:+1:
