### ISSUE TITLE
Can't save organisations

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1859]
## Test plan
See issue description below. Step 4 should not give a validation error.

## Issue description
1. Create a new organisation in the old admin ```/admin/rsr/organisation/``` with a name, long name and IATI org ID filled in
2. _Organisation created_
3. Edit the organisation - but not the name, long name or IATI org ID
4. _Error saying that organisation name, long name or IATI org ID already exist_

**Comment by KasperBrandt** [comment]
Closed in #1861

**Comment by osgl** [comment]
Replicated on Live and verified fixed on UAT.
