### ISSUE TITLE
Remove donations (estimate: 4)

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-rsr#1885]
The idea is to remove the donation functionality from RSR. However, this will have some impact on partners that use this feature a lot. Therefore, we need to look at what we will replace this functionality with. For example, there might be 3rd party providers that provide an easy payment / crowdfunding plugin that could be used. This needs to be investigated.

**Comment by KasperBrandt** [comment]
Some quick stats on donations:
- 13 donations in 2015 (11 additional attempted donations that did not complete through iDeal or Paypal).
- Total amount received in 2015 approximately €9200.
- All Walking for Water projects.

We should discuss this, although my feeling is that the donations part might stop working any time now. We use an old library and have received warnings that it won't be supported forever anymore.

However, if partners could provide us with a donation link of their own to be displayed on the project page, that would be an easy fix.

**Comment by lauraroverts** [comment]
Discussed this with Lissy. 
We need to keep the donation button until Juli 2016. Reason for this is that we've got a contract with Commonsites and the Walking for Water campaign is making use of it in March. Lissy is going to explain to Aqua for All that we will remove the donation button summer next year and ask them if they want to link to their own donation platform as an alternative.

**Comment by KasperBrandt** [comment]
Instead of fully removing donations, we should allow for entering a URL to an external donation platform.

**Comment by KasperBrandt** [comment]
Some up-to-date statistics on the donations.

Months of 2016:
- **August 2016:** No donations
- **July 2016:** 1 donation _(Walking for Water)_
- **June 2016:** 6 donations _(CommonSites - 2 projects)_
- **May 2016:** 8 donations _(1 Walking for Water, 7 CommonSites)_
- **April 2016:** No donations
- **March 2016:** 1 donation _(Walking for Water)_
- **February 2016:** No donations
- **January 2016:** 1 donation _(Walking for Water)_

Years:
- **Total 2016:** 17 donations
- **Total 2015:** 15 donations
- **Total 2014:** 93 donations

**Comment by nadiagorchakova** [comment]
A bit more context for you, @punchagan: 

Right now the 'Donate Button' field is located in the Finance section of the Project Editor. It has a dropdown with two values Yes/No. If the field is set to Yes in the Editor, the Donation Button is activated on the project page. All the donations would go to Akvo bank account.  

- [ ] I believe the donation button and arrangement with Akvo bank account was partially deactivated (in Live) already. Needs to be checked again and fully deactivated.

- [ ] In the Project Editor please rename field 'Donation Button' to 'Donate here'. The field should accept free text and links to external websites.

- [ ] On the Project page this new 'Donate here' field should be shown in the Summary tab and in the Finances tab. The link to the external website should be clickable. It should only be shown if the user has input an external link in this field.

- [ ] The Finance tab on the Project page still has the 'Donations' field. It previously showed an accumulated amount of all donations done through this page. This feature should be disabled.

User story: as an RSR user, I should be able to add an external link to donations platform in the Finance section of the Editor. Then, I will be able to attract donations through the right channel.

**Comment by punchagan** [comment]
> In the Project Editor please rename field 'Donation Button' to 'Donate here'. The field should accept free text and links to external websites.

Does this need to accept free text?  Or does it just need to accept a single URL?

**Comment by nadiagorchakova** [comment]
Let's make it accept just a single URL
