### ISSUE TITLE
Project editor refactor and RSR / IATI split

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1895]
## Test plan
As this is a large change (a complete refactor) of the project editor, it should be tested thoroughly. The following points should definitely be tested:

__Editor basics:__
- All sections should save accordingly.
- After saving, a green border is shown around the fields that have been saved. Only fields that were edited will be saved.
- If fields cannot be saved, a red border is shown around the fields.
- If the user has no permission to save the project, this should be shown in an error message _(this can be faked by editing a project and removing the user's organisation from the project)_.
- If clicked on any help icon, the help text should display.
- Fields that have a max length should show the number of characters left while the user is typing.

__Special cases:__
- Only a superuser should have the 'superuser options' on top of the screen. When these options are selected (e.g. private or impact project), the project should immediately be changed (to a private or an impact project).
- It should be possible to switch between an 'RSR related project' and a 'Related project IATI identifier' for related projects.
- It should not be possible to remove the last partner. The delete icon will then be hidden.
- It should not be possible to select multiple reporting partners.
- When the reporting partner is chosen, the 'Secondary reporter' field is shown. For all other partner roles, the 'Funding amount' field is shown. However, the 'Funding amount' field is only active when the partner is a funding partner.
- The 'Other label extra info' for budget items should only be enabled when the 'Other' budget item is selected.
- It should be possible to switch between uploading a document and specifying the URL of a document for project documents.

__Validation sets and progress bars:__
- It should be possible in the 'old' admin to set the validation sets _(see /en/admin/rsr/projecteditorvalidationset/)_. By default the RSR and IATI validation sets have been created.
- Superusers, RSR admins and organisation admins of a paying partner should be able to select or delete any validation set (called progress bar in the editor) of the project in the project editor, except for the RSR validation set.
- The RSR validation set should be selected for all projects by default and for all new projects, and it should not be possible to change any field of the RSR validation set.
- It should be possible to select a progress bar on top of the project editor and the progress bars per section should respond to the selected progress bar.
- It is possible to have 'OR'-mandatory fields, meaning that only one of multiple fields needs to be filled in for the progress bar to respond _(see start date planned and actual in the RSR validation set)_.
- Mandatory fields in a related object _(with the slightly yellow background)_ should only be taken along when one of the fields of the related object is filled.
- Related objects themselves _(e.g. 'sectors')_ can also be mandatory, indicated by the red * behind the header of the related object. This means that at least one of these related objects should be filled _(e.g. at least one sector should have a field filled in)_.
- The combination of the above rules could lead to a full progress bar when nothing is filled in, but a partly filled progress bar when the user starts to fill in a related object _(e.g. in IATI a related project is not mandatory, but when you fill in a related project, you should fill both the project and the relation fields)_.

## Issue description
For an overview of the discussion around the RSR and IATI editor split, see [this document](https://docs.google.com/document/d/1d-9ogB9WoVvHoP_sYXzLGMfByqE2xRvlBatrdn__oMU/edit).

- [x] Code refactor
- [x] Better photo and document upload (see #1760)
- [x] Improve error handling: add the fields that not saved correctly to message
- [x] Add country / latitude / longitude as mandatory fields in the 'Add new organisation' modal
- [x] No default organisation type (Plan Finland request)
- [x] Change 'Add new organisation' to 'Save' (A4A request)
- [x] Add 'Private' checkbox for superusers
- [x] One progress bar with combined validation sets
- [x] Mandatory indicators of underlying objects only show when object is filled in

**Comment by lauraroverts** [comment]
Background
At this moment the Project editor is confusing for partners who do not publish according to the IATI standard.Therefore the Project editor will be split so that for partners who want to publish their projects to RSR, only RSR related fields will be visible. Partners who choose to publish their project to the IATI standard, will be able to thick a checkbox and compulsory and non-compulsory IATI fields will become visible.

Decisions:
- A partner can now choose if they want to publish their project to RSR or RSR + IATI. This means that every project that will be published in RSR can only be published if all mandatory RSR fields are completed. 
 - There will be two progress bars that indicate your progress. One for RSR and one for IATI

**Comment by mtwestra** [comment]
Two questions for @lauraroverts and @KasperBrandt 

1) what are the current ideas for letting the user choose which 'standard' she wants to follow?
2) which standards do we use? RSR, IATI full, IATI minimal, IATI DGIS?

**Comment by KasperBrandt** [comment]
1) Currently my idea is to show the RSR editor by default (no IATI fields at all), and have an 'Advanced editor' option. That will show all IATI fields + an additional IATI progress bar. My idea is that we can also add another progress bar that the user can choose. E.g. 'Add another progress bar' or something similar. This could be used to select DGIS validations (or other validations that we might have in the future).
2) So far, we only have "RSR" and "RSR + IATI full".

My two main question right now is how to differentiate between the different mandatory fields. How do we show what fields influence each of the progress bars? RSR mandatory fields are indicated with a red *. So far the only thing I can think of is to indicate the other mandatory fields with a different color *, but @lauraroverts thinks this will get confusing.

Also; we now show a progress bar in every section header. There's no room for more than 1 progress bar there. So it will be hard to make the same differentiation per section.

**Comment by mtwestra** [comment]
@KasperBrandt and what is the role of the 'show advanced IATI fields'?

And in terms of numbers: I think when a user selects IATI, there are actually only one or two extra fields in RSR, right? So it doesn't make much sense to hide those, they just become not-mandatory, right?

**Comment by stellanl** [comment]
The worst choice for "IATI mandatory" fields would be a green *. (Lots of colour-blind people out there.) There are other symbols, like § ▲ ⊙ ¹ .
Alternatively, show/hide the relevant red asterisks depending on mode.

**Comment by mtwestra** [comment]
@KasperBrandt, @lauraroverts,

I have been looking at https://docs.google.com/spreadsheets/d/1iwnT5XIdmxhVKJfenF03jjyDbdyJV5oj19O1M-EJZ-Y/edit#gid=0, and I have a few questions about that:
1) Could we also show which fields we show for IATI when 'show advanced IATI fields' is selected? And how do we determine what is 'advanced'?
2) In the results & indicators section, we seem to not show a lot of fields that seem relevant to the results framework, such as 'Result description', and 'indicator description'. That seems odd?

**Comment by mtwestra** [comment]
@KasperBrandt, @lauraroverts 
In preparing for the IATI-only editor, it might be unwise to structure the editor as 'RSR by default', IATI as 'advanced editor' mode. Perhaps an alternative is let people select which 'project template' for mandatory fields to use for a project, RSR or IATI or Both, and in addition to have a checkbox for 'advanced IATI' fields, as we do now? Or, a more fancy solution, the ability for organisations to select their own selection of non-mandatory fields to show.

**Comment by mtwestra** [comment]
@KasperBrandt, @lauraroverts, a proposal for the requirements:
1) The editor should support publishing to these combinations:
    * RSR only
    * IATI only
    * RSR and IATI
2) The editor should support different selections of IATI mandatory / non-mandatory fields, both to support organisations' own preferences, and to incorporate IATI-publishing flavours from DGIS, DFID, etc. 
3) If the project is RSR only, the progress bars should show RSR progress. If the project is IATI only, the progress bars should show IATI progress. If the project is both, The user should be able to easily switch between the RSR and IATI progress bars.
4) Publishing to either IATI or RSR should only be allowed if the project adheres to the standards selected.

**Comment by lauraroverts** [comment]
Regarding how to structure the editor: If you add a new project, you first have to indicate if you are going to publish your project to RSR or 'RSR + IATI'. (It was decided to skip publishing to IATI without RSR.) So depending on what you choose here, the Project Editor shows you the relevant fields. If you publish to RSR, you won't see IATI identifier for example. RSR + IATI shows all fields. 
Depending on what you have chosen, the progress bar will 'know' which fields are compulsory and shows the progress.

**Comment by KasperBrandt** [comment]
That is an interesting option, which brings other questions to mind though:

1) To what publishing rules will we set the current existing projects? Only 'RSR'?
2) Do we make a distinction between publishing to RSR and to IATI? E.g. a project that has been set to 'RSR + IATI' could be published __only in RSR__ when all RSR mandatory fields have been completed, even though some IATI information is missing. Will that be allowed?

**Comment by mtwestra** [comment]
@lauraroverts, ok, clear.
@KasperBrandt, on question one: yes. If people than want to publish to IATI, they need to go through them and check if they adhere to the standard, which is fine.
On question 2: yes, publishing to RSR and publishing to IATI are two different things. You can publish to RSR and not yet to IATI. In fact, that will be a case that happens a lot: People start with RSR, and publish their project, and later want to publish to IATI as well.

**Comment by KasperBrandt** [comment]
@mtwestra Hm, yes, that's what I was thinking too. That leaves us with the same issue on progress bars though. If we show one for RSR (if completed, it's possible to publish project in RSR) and one for IATI (if completed, it's possible to publish to IATI) on a 'RSR + IATI' project, what would be wise in order to distinguish the RSR or IATI mandatory fields?

**Comment by lauraroverts** [comment]
Why distinguish? If you choose to publish to RSR + IATI, there will be just a few more fields with a red asterix. If there is one progress bar, the bar knows which fields are mandatory, so you can easily see when it is ready to publish to RSR + IATI. 

If you choose to publish to RSR, you won't see these IATI mandatory fields.

**Comment by mtwestra** [comment]
In the case of an RSR only project, the situation is clear.

Say we have and RSR+IATI project, in which all mandatory RSR fields have been filled in, but not all mandatory IATI fields. What should we show? If we use a 'combined' progress bar, the user might conclude that the project cannot be published to RSR, while that is not the case.

**Comment by lauraroverts** [comment]
Decision regarding progress bars when selecting RSR + IATI: 

1) have two overall progress bars at the top - IATI and RSR: you can switch between these. If you do, the mandatory fields of the selected progress bar are indicated on the page (and also reflect in the section progress bars)
2) for the progress bars per section allow switching between RSR and IATI at the top (like having two tabs) to give you the 'RSR compliancy view' and the 'IATI compliancy view'

**Comment by mtwestra** [comment]
I would probably show both overall progress bars at the same time - it is quite clear I think.

**Comment by KasperBrandt** [comment]
Yup, this makes sense. Another question; where would we set if a project is RSR or RSR + IATI? And who has the permission to set or change this?

**Comment by lauraroverts** [comment]
Before we can request the partnerteam and partners to test the new functionality, I've got a few comments that we need to discuss. If I look at http://rsr.test.akvo.org/en/myrsr/project_editor/4236/, then:

- I can choose a progress bar from the dropdown menu and switch between the bars. However, once I delete a bar, by clicking the red cross, I can't get it back anymore, unless I refresh the page.

- More than one bar is going to be confusing. E.g. If I click the 'Plan and target' bar, it is not obvious anymore that the RSR mandatory fields are still mandatory. When I fill in a project title, I see the progress on each bar changing, including the bars I didn't select. 

- The idea is we can create a dataset according to the DGIS IATI requirements for example. Does this mean that not ALL IATI fields are shown in the project editor? What if a partner also wants to fill in fields that are not mandatory?

- How can we make sure that an organisation specific ruleset / custommade progress bar can only be choosen by that specific organisation?

**Comment by KasperBrandt** [comment]
- Yup, that's how it works now.. Didn't have enough time to actually implement that the progress bar is selectable after you remove it. But if we return to the 'one progress bar' implementation, it's not needed anyway.
- Same as above, that's how it works now, but if we opt for one progress bar, then that will probably change.
- That depends on how you setup the progress bar now. You can hide or show any field you'd like.
- That's an interesting feature. We could add a feature that some progress bars are only selectable by certain organisations.

Since we've got some time before next release, I'm wondering what to do now? 
- Switch to one progress bar?
- What to do about the publishing button?
- Who should be able to create a new ruleset? Should it be possible to make these organisation specific / how would that work?
- Who should be able to select a progress bar for a project? And where?
