### ISSUE TITLE
Create some simple example reports

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#1899]
To make it easier to get started with RSR reports in BIRT, it is useful to have some that are less complex than the result framework one.

**Comment by lauraroverts** [comment]
See a first list of reports: https://github.com/akvo/akvo-product-design/issues/127

**Comment by stellanl** [comment]
Here are some sample queries.

Reports without photos:
> select rsr_project.id, rsr_project.title
> from rsr_project
> where current_image is null or current_image = ''

Project and updates totals:
> select 
>   count (distinct rsr_project.id) as project_count,
>   count (distinct rsr_projectupdate.id) as update_count
> from
>   rsr_project left join rsr_projectupdate on rsr_project.id = rsr_projectupdate.project_id

There is something strange about the DB connection from (at least) Report Designer.
The following query is perfectly fine in psql (the DB console) but fails from RD:
> SELECT
> (SELECT COUNT(DISTINCT id) FROM rsr_project) AS project_count,
> (SELECT COUNT(DISTINCT id) FROM rsr_projectupdate) AS update_count
