### ISSUE TITLE
REST API: project_extra with organisation filter gives duplicates

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#1909]
The ```project_extra``` REST API endpoint shows duplicate projects when it is filtered on organisation.

**Comment by zzgvh** [comment]
# Test plan
Make a query to the REST API filtering on an organisation with a fair number of projects e.g. ```http://rsr.test.akvo.org/rest/v1/project_extra/?partnerships__organisation=42``` when running the develop branch. Note the count field in the JSON header.
Make the same query with the #1909-duplicates-project-extra branch and compare the count. It should now be smaller.
