### ISSUE TITLE
Results framework - headings overlapping text

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#1934]
When I visit this link in Firefox - http://rsr.akvo.org/en/project/2081/#report  (takes a long time to load) & when select 'summary' to the left of 'Full report' the heading text is overlapping the paragraphs.

![screen shot 2015-11-26 at 15 15 29](https://cloud.githubusercontent.com/assets/2675262/11424941/771af9ac-9451-11e5-80b9-5b2cd7896c46.png)

If I select the heading the problem is correct. (ie. select '+background' etc)

**Comment by Lynngre** [comment]
Chrome & Safari do not have this issue.

**Comment by lauraroverts** [comment]
@Lynngre can you check again? When I do the same in Firefox it looks fine.

**Comment by Lynngre** [comment]
This seems ok now.
