### ISSUE TITLE
Rename or remove Organisation.all_users()

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1943]
Organisation.all_users() is mis-named since it returns Employee objects. I suggest renaming it all_employees. Alternatively one could consider ditching it. Not sure if all_employees is a huge improvement over employees.all :wink:.

It also looks like there might be a bug lurking because of this in [rsr.permissions.py](https://github.com/akvo/akvo-rsr/blob/560d3433f5459dba2db2b334dc63bc6b955e40e1/akvo/rsr/permissions.py#L32) where we compare a User object with the result of Organisation.all_users(). (And again on [line 97](https://github.com/akvo/akvo-rsr/blob/560d3433f5459dba2db2b334dc63bc6b955e40e1/akvo/rsr/permissions.py#L97))

**Comment by KasperBrandt** [comment]
Already fixed in an earlier branch :smile:
