### ISSUE TITLE
Optimise RSR for I-frames

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1952]
Request from Lars: 

To make the integration of RSR with Akvo Sites more user friendly, a piece of javascript code needs to be added to indicate RSR is used as an I-frame and automatically scale within the website where it is published. At this moment this is not the case. As a result you see two scroll-bars that make it obvious that RSR is embedded within an I-frame. 

E. g. http://eha-ci.org/projets-rsr/region-de-lagneby-tiassa/.  

Lars included this link to an explanation of making i-frames responsive. https://benmarshall.me/responsive-iframes/.

**Comment by KasperBrandt** [comment]
This solution can not be handled from RSR's side, but should be implemented on the parter's website.
