### ISSUE TITLE
Target and indicator values don't show on project page

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1953]
## Test plan
GIVEN the display of a result on the project page

WHEN the result has no indicators
THEN only the result title should be shown

WHEN the result has a (or multiple) indicator(s)
THEN the indicators should be shown

WHEN an indicator has a (or multiple) period(s)
THEN each indicator period should appear on a new line

WHEN an indicator period is shown
THEN the dates are only shown when either the start or end date is filled in
AND the values (if present) are always shown, even though there are no dates filled in

## Issue description
If I fill in a target value of an indicator in the Project Editor section 05 Results & Indicators, the value doesn't show up on the project page. 

Screenshot target value: 2 Water facilities
![screen shot 2015-12-16 at 10 55 56](https://cloud.githubusercontent.com/assets/4179989/11837848/b25f214a-a3e3-11e5-8f69-9b82cd28d8f3.png)

Screenshot project page: Water facilities without number
![screen shot 2015-12-16 at 10 56 08](https://cloud.githubusercontent.com/assets/4179989/11837857/b66db6b6-a3e3-11e5-9ee8-d8e72b76a670.png)

**Comment by lauraroverts** [comment]
In addition. Commonsites noticed that also actual indicator values do not show on the projectpage, e.g. http://projects.commonsites.net/en/project/2092/ 

Projectpage: values are missing
![schermafbeelding_2015-12-23_om_11 09 11](https://cloud.githubusercontent.com/assets/4179989/11974723/0d42f928-a967-11e5-8d14-a5b984885efc.png)

Commonsites uses the old admin to fill in values:
![schermafbeelding_2015-12-23_om_11 07 43](https://cloud.githubusercontent.com/assets/4179989/11974726/1303ef48-a967-11e5-8219-e8015d179e8b.png)

**Comment by KasperBrandt** [comment]
The issue was that the indicator period values would not be shown if there were no indicator period dates (e.g. start or end date). This has been fixed now:

<img width="628" alt="screen shot 2016-01-15 at 15 23 22" src="https://cloud.githubusercontent.com/assets/1497367/12355375/75356772-bb9c-11e5-8999-f7901872f3e1.png">
