### ISSUE TITLE
Transactions in Project editor can't be deleted

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1954]
As an Aqua for All administrator, I prepare a new project in the Project Editor for my partner to be able to fill in the project information. I share the link of a new project with them, so that they can add information to the basics I already filled in for them. Since the Transactions section is not mandatory and not a requirement from us to our partners, I want to delete 'transactions' in the Project editor (see screenshot) so that it doesn't show up and thus avoid confusion. If I delete this section and the page gets refreshed, the section appears again. 

![screen shot 2015-12-16 at 10 59 50](https://cloud.githubusercontent.com/assets/4179989/11837961/5671916e-a3e4-11e5-8235-b1ee6f152fb5.png)

**Comment by KasperBrandt** [comment]
@lauraroverts I think this can be already be resolved currently by using a custom validation set without transactions (so that you never see any transactions). Can we close this issue?

**Comment by lauraroverts** [comment]
Yes, I'll ask Aqua for All which fields they want to have mandatory in their validation set.
