### ISSUE TITLE
My details - change password

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1955]
In My RSR, there is a separate section to change your password 'Change password'. It makes more sense to include that in My details.

**Comment by KasperBrandt** [comment]
Based on the wireframes of the new results framework backend, this functionality will remain on a separate page, but on a new location (in the top navigation):

<img width="159" alt="screen shot 2016-01-13 at 11 49 17" src="https://cloud.githubusercontent.com/assets/1497367/12292197/c666c896-b9eb-11e5-9a00-dc675dc75243.png">

**Comment by KasperBrandt** [comment]
Fixed in #1965
