### ISSUE TITLE
Random order indicators

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1956]
- [x] Add an `order` field for results and for indicators.
- [x] It should be possible to set the order of results and indicators in the project editor. Preferable by drag and drop, otherwise by 'Move up' and 'Move down'.
- [x] The results framework (both My results and on project page, but that's the same code) should adhere to this ordering.
- [x] Preserve ordering for imported child results and indicators
- [x] Initial ordering should match order of entry

I created two test projects: 
- Parent http://rsr.test.akvo.org/en/project/4239/
- Child http://rsr.test.akvo.org/en/myrsr/project_editor/4240/ 

In 05 Results and Indicators I started to create a results framework with one result and multiple indicators. I named the indicators Indicator 1, 2 and 3. After I save it and go back to that section, the indicators appear in a random order (2-3-1) in the backend and frontend: 

![screen shot 2015-12-22 at 09 48 17](https://cloud.githubusercontent.com/assets/4179989/11951443/2a433b9a-a891-11e5-975d-c1fd683869e6.png)

![screen shot 2015-12-22 at 09 45 58](https://cloud.githubusercontent.com/assets/4179989/11951396/ea0254d0-a890-11e5-8059-05bfcf6a8ebf.png)

If I now import my results framework at my child project, the imported result and indicators do have a different order again (1-3-2): 
![screen shot 2015-12-22 at 09 42 47](https://cloud.githubusercontent.com/assets/4179989/11951332/606ad832-a890-11e5-8b49-6d530717134f.png)

This is going to be complicated and confusing when I add a results framework with multiple results and indicators.

I would expect the same order/structure of how I enter my framework and after importing or viewing in the frontend. I also want to be able to change the order with the ability to move results and indicators up and down.

**Comment by damienallen** [comment]
### Test plan

- Ordering buttons for results and indicators
 - [ ] Buttons displayed if there is more than one item
 - [ ] Top item shouldn't have up button and bottom item shouldn't have down button
 - [ ] Buttons should adjust if items are created (once saved) or deleted

- [ ] Manual ordering should be preserved for imported results
- [ ] Manual ordering should be reflected on project page results section
