### ISSUE TITLE
PDF report progress should be counted from baseline

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#1957]
Baseline should be the starting point for calculating progress percentage.

**Comment by stellanl** [comment]
I'll also fix the dates to correspond to RSR Results Framework format: d-MMM-YYYY

**Comment by stellanl** [comment]
Now uploaded to the test server

**Comment by stellanl** [comment]
Strangely, the dates now formatted by the BIRT function Formatter.format() show end dates that are on the last day of the year (2015-12-31) as one year later (2016-12-31)!

**Comment by stellanl** [comment]
Other remaining things to fix:
- [ ] The project start and end dates are unclear, need more labelling.
- [ ] Percentages above 100 or below 0 should be allowed in the numerical display.
- [ ] The sort order of results and indicators needs to be defined, both here and in the web UI.

**Comment by stellanl** [comment]
Uploaded and testable at http://rsr.test.akvo.org/reports/project_results/2849?format=html&download=false

**Comment by KasperBrandt** [comment]
Uploaded to Test server, can be tested there now.
