### ISSUE TITLE
Can't delete projects

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#1959]
## Test plan
GIVEN the RSR project admin
WHEN a user deletes a project
THEN no IntegrityError should be shown
AND the project should be deleted accordingly

GIVEN the My projects page in MyRSR
WHEN a user clicks the 'Create new project' button
AND the project editor for the new project is opened
THEN the RSR validation set should be selected by default

## Issue description
The new validation models make it impossible to delete projects. When trying to do it in the admin I get the following error:

IntegrityError at /en/admin/rsr/project/1516/delete/

insert or update on table "rsr_project_validations" violates foreign key constraint "rsr_project_valida_project_id_2ae411aff8f8055_fk_rsr_project_id"
DETAIL:  Key (project_id)=(1516) is not present in table "rsr_project".

Deleting the offending constraint allows deleting. I haven't looked deeper into the problem than that...

![screenshot_97](https://cloud.githubusercontent.com/assets/142613/12017582/dd0b94a4-ad58-11e5-812d-e9f2d7a9d567.png)

**Comment by zzgvh** [comment]
Additional info. When I remove the index to be able to delete I get two deletion notices in the admin:
![screenshot_98](https://cloud.githubusercontent.com/assets/142613/12031594/2ef7afae-ae0e-11e5-9ace-1504fa86d255.png)
This is fishy, and might be connected to the original problem.

**Comment by KasperBrandt** [comment]
This is due to a saving action after the project has been deleted from the DB. See these lines: https://github.com/akvo/akvo-rsr/blob/develop/akvo/rsr/models/project.py#L388-L391

**Comment by zzgvh** [comment]
Code reviewed. Small fix added so I'd like @KasperBrandt to check that and then merge.
