### ISSUE TITLE
Add My Reports section to My RSR

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1960]
## Test plan
GIVEN MyRSR
WHEN the user is logged in
THEN the 'My reports' section should be visible

GIVEN the My reports page
WHEN a report is selected
THEN the other form parameters should respond accordingly (e.g. project or organisation parameter is shown, and the correct formats are shown)

GIVEN the My reports page
WHEN all parameters are filled in
THEN the 'Download' button becomes enabled
ELSE the 'Download' button is disabled

GIVEN the user is a superuser or RSR admin
WHEN the user has selected a report template
THEN the organisation or project parameter should be a typeahead with all organisations or projects
ELSE the organisation or project parameter should be a dropdown with all organisations or projects that the user has access to

GIVEN the 'Download' button is clicked
THEN all fields should be disabled for 5 seconds
AND the report should be downloaded _(cannot be tested locally, needs ReportServer)_

## Issue description
Add My Reports section to My RSR where users can export reports about their project(s). Reports created with reportserver.

@Geerts is working on templates for: 
- Financial report: shows budget related info
- Quality report: showing overview of actions that need to be done after project expiry date
- Overview report: shows the status of projects. 

Design team is creating a UI design according to:

User story 33
As an authorised user I want to choose a report template. 

Scenario 33 
An a PME manager I want to be able to choose a report template from a pre-set list of templates. In this way I can create a report about my results framework, but also about financial transactions, all RSR updates made to a project or an overview of all active projects that my organisation is showing online. 

User story 34
As an authorised user I want to choose the report format. 

Scenario 34
As a PME manager I want to be able to export my format to Word (to be able to edit), PDF (standard design), Excel (raw data file) or ODT (open document) or HTML. 

User story 35
As an authorised user I want to create a report about a specific project.

Scenario 35
As a program manager I want to be able to create a report for a specific project, because I want to share the progress we are making with everyone involved in order for internal program steering. 

User story 36
As an authorised user I want to create a report about a set of projects using the same (inherited) results framework.

Scenario 36
As a program manager I want to be able to create a report about a set of child projects, because I want to give an overall overview about the progress my organisation is making. I therefore need to be able to select multiple projects for the same report. 

User story 37
As an authorised user I want to create a report about a specific time period. 

Scenario 37
As a program manager I want to be able to create a report about the last year, since I need to send an annual report to my donor. Therefore I need to be able to select a specific period of time. 

User story 38
As an authorised user I want to export the template and be able to add and edit data, and save it. 

Scenario 38
As a PME manager I want to export a report to a format e.g. DOC in which I can add photos and additional text myself, and to match it with the branding of my organisation.

User story 39
As an authorised user I want to export the report and save it.

Scenario 39
As a project officer I want to export a report and save it, so that I can share it via email or internally. 
progress my organisation is making. I therefore need to be able to select multiple projects for the same report.

**Comment by lauraroverts** [comment]
Titles and descriptions for: 

- Results & indicators overview
This report gives an overview of the status of your project's results and indicators.

http://rsr.test.akvo-ops.org/en/reports/data_quality/42?format=pdf&download=false
Title: Data quality overview
Description: This report gives an overview of your organisation’s projects that have passed the planned end date, need funding or that haven’t been edited or updated for 3 months.  

http://rsr.test.akvo-ops.org/en/reports/project_overview/42?format=pdf&download=false
Title: Projects overview
Description:  This report provides information about your organisation’s projects: amount of updates, country, total budgets, project statuses, start- and end dates. 

http://rsr.test.akvo-ops.org/en/reports/organisation_summary/42?format=pdf&download=false
Title: ???
Description: This report provides basic information about your organisation’s projects: titles, subtitles
Note: We might skip this report, because it is not finished yet.

**Comment by KasperBrandt** [comment]
I get a unicode error when trying to open the page on Test:

<img width="796" alt="screen shot 2016-01-14 at 16 01 35" src="https://cloud.githubusercontent.com/assets/1497367/12327682/2604a29a-bad8-11e5-87be-3bd3078c0255.png">

**Comment by KasperBrandt** [comment]
Closed in #1970
