### ISSUE TITLE
Creating reports for the RSR MyReports section

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-rsr#1964]
- project overview
- financial overview
- data quality report

**Comment by stellanl** [comment]
I'll make a small addition to the nginx configuration to put the id from the URL into a report parameter called simply "ID". Currently it ends up in "TheProjectId", which is a legacy from when there was only a project_results report..

**Comment by KasperBrandt** [comment]
Would the ID parameter be either the project id or the organisation id for the different templates?

**Comment by Geerts** [comment]
Yes, those are the two options we have right now.

**Comment by stellanl** [comment]
About organisation_summary:
* There is a duplicated table.
* The report parameter is not named "ID".

About project_overview:
* Using multiple header rows of a table for data items from different data sets is not a good idea. A grid is better.
* Having several labels in the same cell makes it very hard to work with vertical alignment.

**Comment by stellanl** [comment]
For organisation_summary, I think w should reverse the order of tables; have the very long "all projects" at the end, and the counts up top. Adding labels to the sections will make things clearer.

**Comment by stellanl** [comment]
For project_overview I think that the "updates per country" should have the country name column first, and the name of the organisation somewhere up top.

**Comment by stellanl** [comment]
For data_quality I think that it too needs a label with the organisation it concerns.
The values in the URL columns should be made into clickable links.
Also, two of the three sections are hardcoded to report on org 42, Akvo...

**Comment by lauraroverts** [comment]
Feedback to:

http://rsr.test.akvo-ops.org/en/reports/data_quality/42?format=pdf&download=false
In all formats:
-	Add Report title 
-	Add Name of the organisation report applies to
-	Add report overview: what information can I find in this report if I scroll down? 
-	Does it make sense to also include the actual start date?
-	Change Name into Country
-	Not clear what the order is of the projects/how the list is sorted
-	Not clear if project budget is in Euro or Dollar

In PDF:
-  words are cut off: e.g. budg data)start_pla….. 

In Excel:
-	there might be confusion about the date format: DD/MM/YY

In Word:
-	is it possible to change the page setup into landscape size?
-	Suggest to show the table gridlines

**Comment by lauraroverts** [comment]
Feedback to: 

http://rsr.test.akvo-ops.org/en/reports/project_overview/42?format=pdf&download=false
In all formats: 
-	Add Report title 
-	Add Name of the organisation report applies to
-	Add project status (active, needs funding, completed, archived, cancelled)
-	Also include: total of unpublished projects
-	Don’t understand how the updates are counted and what updates excactly means: Statistics > Total of updates = 48 ; Projects per country > adding up all update counts gives me 1126 updates. 
-	Don’t udnertand how total of published projects is calculated:  Statistics > `Total of published projects = 127 ; Adding up all Projects per year = 216 ; Projects per year > Adding up all Projects per country > project count = 189
-	Does it make sense to also include the actual start date?
-	Not clear what the order is of the projects/how the list is sorted

In Excel: 
-	Is it possible to name the different sheets? They are now called sheet 1, sheet 2 etc. 
-	Apparently sheet 1 – 5 show the projects sorted per country. Every sheet contains 5 letters of the alphabet. Suggest to show them in one sheet
-	Sheet 1: don’t understand how the info in row 1 – 4 relates to 5 and further
-	there might be confusion about the date format: DD/MM/YY
-	
In Word: 
-	Don’t understand what the information on page 3 ‘Projects per country’ tells me or why it’s there. I only see Viet Nam and Zambia.
-	is it possible to change the page setup into landscape size?
-	Suggest to show the table gridlines

**Comment by lauraroverts** [comment]
http://rsr.test.akvo-ops.org/en/reports/organisation_summary/42?format=pdf&download=false

In all formats: 
-	I actually don’t understand the added value of this report. It only provides title and subtitle. 
-	At the last page of the pdf I see for some projects the name (= organisation?), title and date last modified.  Why do only a few projects appear here?
-	Add Name of the organisation report applies to
-	Add project ID

In PDF: 
-	I don’t understand the first few lines of the report: Looks like random words and numbers spread out over the page
-	Insert headers
-	Lot of open spaces / blank rows

In Excel: 
-	Lot of open spaces / blank rows. Eg row 13, 15
-	Suggest to combine sheet 1, 2 and 3 in one sheet: not clear why it’s in 3 sheets

In Word: 
-	Insert headers
-	I don’t understand the first few lines of the report: Looks like random words and numbers spread out over the page
-	Lot of open spaces / blank rows

**Comment by stellanl** [comment]
The hyperlinks in the data_quality report need to point to the live server, not the test one.

**Comment by stellanl** [comment]
I'll add a "projects without photo" table to the data quality report.

**Comment by stellanl** [comment]
The project_overview report still misses a total projects count and the total updates count is wrong.
Also the status column should be mapped from letters to words.

**Comment by stellanl** [comment]
The data_quality report fails when outputting Excel files. Error is:
 java.lang.IllegalArgumentException: Address of hyperlink must be a valid URI
caused by:
 java.net.URISyntaxException: Illegal character in path at index 3: row["project_url"]

Looks like the Excel emitter does not evaluate that expression correctly. Perhaps using it as a literal URI. It works when using the BIRT engine in Excel Report Design. Will check versions and release notes.

**Comment by stellanl** [comment]
My Report Designer is version 4.4.2 (Geert has 4.5)
RS2.1.5 had Birt 4.3.1
The test ReportServer installation is 2.2.0-5692, and contains BIRT 4.4.1

**Comment by stellanl** [comment]
I made a small test report (org_test) with a URL data field in a table and uploaded it to the Test RS. It works with both Excel and Word formats. So there is something about the data_quality report that breaks some of the RS BIRT emitters. Will cut parts out of data_quality until I find the problem.

**Comment by stellanl** [comment]
Now the Excel data_quality report works, but the wide tables are still squashed horizontally in Word.

**Comment by KasperBrandt** [comment]
Report available on the Test server.
