### ISSUE TITLE
Front-end Results framework view

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1966]
## Test plan
GIVEN the project page
WHEN the project has results
THEN a 'Results' tab should be visible

GIVEN the 'Results' tab
WHEN browsing through the results framework
THEN there should be no actions (place update, lock or unlock period, etc.)
AND only 'Approved' indicator updates should be shown

GIVEN the 'My results' tab in MyRSR
WHEN searching for a project
THEN unpublished and private projects should not be selectable in the list

## Issue description
A public view of the results framework needs to be designed that will be visible at an RSR project page. This allows a project page visitor to see the progress of a project. 

User story 41
- [x] As a user I want to be able to see the results and indicators I am expected to achieve in my project

User story 42
- [x] As a user I want to be able to see the progress and history of the indicators.

User story 43
- [x] As a user I would like to see how my organisation contributes (with indicators) to the overall results.

User story 45
- [x] As an authorised user I want to be able to add comments to the attached final report. 

User story 46
- [x] As a non-RSR Impact user I want to be able to see my results and indicators at a project page. 

User stories and scenarios can be found in https://docs.google.com/document/d/1AbiHHkbmQLEMLXIJAe0j5fqJlfVKzvLt65JdzbGRvyM/edit

**Comment by KasperBrandt** [comment]
- [ ] Make all projects 'RSR Impact' projects
- [ ] Remove 'Activate results framework' option from project editor
- [ ] Only make actuals in project editor non-editable when project has indicator data
