### ISSUE TITLE
Visualisation private projects

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1975]
Private projects are only visible in the project editor in My RSR. We should look at at way to visualise private projects the way we do with the public projects.

**Comment by KasperBrandt** [comment]
To prevent confusion; private projects are now also visualised, similar to draft projects. But you can only access the project page when you're a project editor or admin of the project, or a superuser.

See here for an example:

<img width="1305" alt="screen shot 2016-01-15 at 15 42 01" src="https://cloud.githubusercontent.com/assets/1497367/12355681/a499e40a-bb9e-11e5-900d-e1822e77d54f.png">

**Comment by lauraroverts** [comment]
Wasn't aware of that. I'l close the issue.
