### ISSUE TITLE
Reset My RSR Password confirmation dialog

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1981]
As an RSR user who is trying to log in but forgot her password, I click 'I forgot my password' in http://rsr.akvo.org/en/sign_in/. I get a popup where I fill in my email, then I click 'Reset password'. 

I would expect after clicking 'Reset password' I would see a message 'You will receive an email with a link to reset your password'. Then I would expect to receive an email with a link to reset my password (which is already the case).

**Comment by nadiagorchakova** [comment]
add clarification text for the user
