### ISSUE TITLE
Unable to share projects with special character in title via social media

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1986]
For projects with a special character in the title I'm unable to share an the project page or RSR update via the twitter-sharing button. If I click the button, nothing happens. Facebook works. 

E.g. 
At project http://rsr.akvo.org/en/project/3790/ it's not possible to share the page via twitter. The title contains a special character in "d'Eau"
At project http://rsr.akvo.org/en/project/2842/ I am able to share the page via twitter, because the project title doesn't have special characters.

**Comment by damienallen** [comment]
Test plan:

1. Open project with special character(s) in title.
2. Try opening Twitter share button
