### ISSUE TITLE
Add explanation user roles in User Management

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1989]
User roles and permissions are not clear for all RSR users. We need to add an explanatory text to indicate the different user roles and permissions. Or link to http://rsrsupport.akvo.org/article/show/user-roles-and-permissions 

![screen shot 2016-03-01 at 09 44 58](https://cloud.githubusercontent.com/assets/4179989/13422011/4987c844-df92-11e5-83d8-ff637f89fa9d.png)

**Comment by KasperBrandt** [comment]
We'll have to look into this to see if it is still necessary after the updated user roles and permissions in #2115.

**Comment by AkvoAnt** [comment]
A link to the User Management support page is now in place.
