### ISSUE TITLE
MyRSR - API key

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#1990]
API key is unavailable via the new Admin area.

**Comment by KasperBrandt** [comment]
@damienallen We should add the API key of a user to the 'My details' page in MyRSR. Underneath the 'My organisations' box would be a nice place, just a header with a short description and the API key underneath.

Short description: "For more information on how to use the RSR API, please check the [support page](https://akvorsr.supporthero.io/container/show/api)."

**Comment by damienallen** [comment]
Test plan:

Open myRSR and check for API Key section on "My Details" page.
