### ISSUE TITLE
Add organisation pop-up

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1995]
Add new organisation pop-up:
- [x] Show mandatory fields.
- [x] Check layout issue.
- [x] Organisations disappear after adding organisation.
- [x] Update country list to IATI countries.

**Comment by KasperBrandt** [comment]
## Test plan
1. Open the project editor and add a new partnership (section 3) with an existing organisation
2. **Don't save**
3. Add another partnership and add a new organisation (type until there is no matching organisation, a green 'Add new organisation' link should appear)
4. *Result:* The labels in the pop-up should appear above the input fields, and some fields should have a red 'mandatory' asterisk
5. Fill in the mandatory fields and save the new organisation
6. *Result:* The partnership that was added first should still have the same organisation selected
7. *Result:* The new organisation should be selected in the other input field

**Comment by KasperBrandt** [comment]
- [ ] Latitude, longitude and country need to be filled in. Add a new check.

**Comment by KasperBrandt** [comment]
## Test plan (2)
1. In the add organisation modal, these fields should be always mandatory: name, long name, organisation type, latitude, longitude and country.
2. In addition, the latitude and longitude fields are not allowed to have a ','.
