### ISSUE TITLE
My IATI

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1996]
If I go to My IATI and select my organisation, I get to see an overview of all projects that are linked to my organisation. However, it could be the case that not all of my projects comply with IATI. I don't need to include 'non-IATI' projects in my IATI xml export file. 

We need to think of something to indicate which projects are IATI projects and which not. Suggestion: mark the projects that are linked to an IATI related validation set. 

![screen shot 2016-02-10 at 16 16 24](https://cloud.githubusercontent.com/assets/4179989/12951316/0e11332a-d012-11e5-9de0-8aadb76236e9.png)

**Comment by KasperBrandt** [comment]
Fixed in #2102
