### ISSUE TITLE
Recipient organisation mandatory IATI field

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1997]
As an Akvo super user I want to add a recipient country in the project editor. 

![screen shot 2016-02-10 at 16 41 06](https://cloud.githubusercontent.com/assets/4179989/12951985/2d505ae2-d015-11e5-91b9-2d36f3efc0f0.png)

When I select a country, a red asterix appears since this is a rule in IATI. Also the field 'recipient country percentage' then becomes mandatory. 

![screen shot 2016-02-10 at 16 41 14](https://cloud.githubusercontent.com/assets/4179989/12952014/4914ce66-d015-11e5-8b91-b1417707c3e1.png)

This does not work for an organisation's administrator. E.g. when Leonie Hoijting from SNV selects a country, only the 'recipient country' becomes mandatory. For 'Recipient country percentage' this red asterix doesn't appear. As a consequence, when I save this section the progress bar turns orange and it's not clear to me that I need to fill in the percentage too.

**Comment by KasperBrandt** [comment]
This depends on the validation set, so it's not a bug.
