### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2000]
Atm French and Spanish translations for My RSR and RSR project pages are partly in place. Not everything is translated. Suggestion to turn of the translation or include a google translate until we've updated the translations in transifex. 

See example of partly spanish translation below. 

![akvo_rsr_-_myrsr_-_project_editor](https://cloud.githubusercontent.com/assets/4179989/13004199/5e1c14b6-d17a-11e5-96cb-7e08b6b8743d.png)

**Comment by mato74** [comment]
Added priority labels to the French and Spanish items to translate first. 

French: 
https://www.transifex.com/akvo-foundation/akvo-rsr/translate/#fr/akvo-rsr-ui/86301877?tags=prio 

Spanish: 
https://www.transifex.com/akvo-foundation/akvo-rsr/translate/#es_CL/akvo-rsr-ui/86301877?tags=prio 

Next: follow up with the people who indicated they are willing to help translating.

**Comment by KasperBrandt** [comment]
Spanish translations still to be done, see #2310.
