### ISSUE TITLE
Empty projects

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2003]
Similar to #1753, we should add a management command for deleting empty and stale projects. 

We should remove all non-published projects without any data (except a partnership, which will usually be present) older than a week.

**Comment by damienallen** [comment]
### Description

- Script can be run using `sh manage.sh project_cleanup`
- Command with `-v 2` flag will list projects to be removed
- Command with `-d` flag will delete listed projects
- Runing `sh manage.sh help project_cleanup` will list all options

###Test plan

- [ ] Check if empty projects older than 7 (default) days are filtered correctly
- [ ] Confirm projects with partially filled mandatory fields are not included
- [ ] Check that the `-d` flag actually removes those projects
