### ISSUE TITLE
Disable add updates or make edits to Completed projects

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2006]
To be further discussed: 

Note from Thomas when we talked about pricing for RSR: 
"Only active projects will be charged for. Completed projects, Archived and a Cancelled projects are kept online for free.

When we update how we track use vs how much they have paid for, then we need to set a requirement that says that a project that is set to Completed the you shouldn't be able to update or edit it any more. Also you shouldn't be able to switch back and forth its status to edit the project."

**Comment by damienallen** [comment]
Test plan:

Open "My projects" in MyRSR. "Edit" and "Update" buttons should be disabled for complete projects but only for org admins and not superuser.

**Comment by damienallen** [comment]
Access to linked pages should also be restricted, see #2149

**Comment by KasperBrandt** [comment]
@mato74 @JosjeS What do you think about this issue?

**Comment by JosjeS** [comment]
If you look at the IATI status types http://iatistandard.org/201/codelists/ActivityStatus/ 
I think we should close update and edit button for cancelled and completed projects. 

For the rest of the statuses I would keep it open.

Agree also that everything should stay open for superusers so if anything needs to be changed in a project a superuser can re-open it for the administrator (and for example put it on post completion)

**Comment by mato74** [comment]
Agree.
