### ISSUE TITLE
New functionalities for defining results framework in Project Editor

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2007]
Based on the user stories in https://docs.google.com/document/d/1AbiHHkbmQLEMLXIJAe0j5fqJlfVKzvLt65JdzbGRvyM/edit the defining of the results framework can be improved by implementing the following: 

User story 4
As an authorised user I can see the indicators of a parent project, when my project is linked to a parent project. 

User story 5
As a project manager I would like to see which of my child projects have assigned which of my projects results and indicators to their project.

User story 6
As an authorised user I want to be able to ‘lock’ the results framework to avoid changes made by other persons. 
--> E.g. in the project editor. Since multiple users with editor rights can make changes. The person who is  overall responsible (ME manager) should have the ability to lock the framework at all levels.

**Comment by KasperBrandt** [comment]
Fixed in #1966
