### ISSUE TITLE
New functionalities for data entry in My Results 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2008]
Based on the user stories in https://docs.google.com/document/d/1AbiHHkbmQLEMLXIJAe0j5fqJlfVKzvLt65JdzbGRvyM/edit the defining of the results framework can be improved by implementing the following:
- [ ] User story 13
  As an authorised person I want to be able to assign persons to indicators per project and send a notification. 
- [ ] User story 14
  As an authorised user I want to receive a notification when a project officer submits or makes changes to data at child project level. 
  --> Important: now a ME manager receives a notification for every single data entry. See how we can minimize the amount of emails, e.g. per project instead of per data entry. 
- [ ] User story 18
  As an authorised user I want to see the history of the data that have been submitted or edited for an indicator in the result framework. 
- [ ] User story 19
  As an authorised user I want to be able to send out a notification to those who are responsible for data entry. 
- [ ] User story 20
  As an authorised user I want to be able to send out a reminder to my project officers who need to submit their data.  
- [ ] User story 27
  As an authorised person I want to be able to see an overview of all the indicator value entries in my results framework. 
- [ ] User story 28
  As an authorized user I want to be able to add/edit data for more than one indicator at a time.
- [ ] User story 29
  As an authorised user I want to be able to publish my final results and indicators values. 
- [ ] User story 30
  As an authorised user I want to be able to not publish my final results and indicators if it’s a private project. 

In addition, after conversation with Angela of the WASH Alliance:
- [ ] There needs to be a role in between the PO (who has editor rights) and ME manager: In the WASH Alliance Angela is the ME Manager. She is responsible for the final results and indicators. POs from different implementing partners are responsible for actual value data entry. At this moment, after a PO submits an actual value, Angela with an ME manager role, has to approve. But in the WASH Alliance, there is a contact person in between, e.g. a PO who works for Simavi or RAIN. This person checks the data submitted by the implementing partner. And then it goes to Angela. If this process doesn't replace the webforms (jotforms) we created for the WASH Alliance, data entry via My Results is an extra burden.
- [ ] At parent project level I want to see how the actual value of an indicator is divided over my child projects.

**Comment by punchagan** [comment]
Too many features in a single issue, some of which have been implemented.  Feel free to open separate smaller issues.
