### ISSUE TITLE
Change analytics URL to use https protocol

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-rsr#2013]
The current piwik analytics code use a hardcoded `http://` protocol for including the js file.

https://github.com/akvo/akvo-rsr/blob/v3.10/akvo/templates/piwik/tracking_code.html#L5

The analytics server supports https:// and we should use it to avoid an extra (301) http request.

**Comment by KasperBrandt** [comment]
@iperdomo Changing ```http://``` to ```//``` should be enough, right?

**Comment by iperdomo** [comment]
@KasperBrandt I would encourage use a fixed `https://` instead of a relative protocol.

Not sure if the change you introduced in the `PIWIK_URL` breaks the template as we append the `/piwik.js` dynamically.

https://github.com/akvo/akvo-rsr/blob/v3.10/akvo/templates/piwik/tracking_code.html#L6
