### ISSUE TITLE
Typo in mobile version of the hierarchy screen

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-rsr#2023]
As reported by Marten:

Current:
Screen to small to 

Desired:
Screen too small to 

![image1](https://cloud.githubusercontent.com/assets/13657774/13347489/63bcc6aa-dc6e-11e5-9ad2-7a36f5878a82.png)

**Comment by akvotender** [comment]
https://akvoo.reamaze.com/admin/conversations/hierarchy-on-mobile

**Comment by damienallen** [comment]
1. Open the following page on mobile (or with inspect -> mobile res): http://yepprogrammes.akvoapp.org/en/project/3928/hierarchy/

2. Check for typo.
