### ISSUE TITLE
CSS Akvo Pages

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2025]
We need to find a way to maintain the CSS of the Akvo Pages. When a new feature or section is added to RSR, the code in the Pages CSS is missing. Pieces of code need to be added to every Akvo Page stylesheet manually. 

If you now look at http://undp.akvoapp.org/en/project/548/, you can't read the headings in the top menu. 

If you look http://undp.akvoapp.org/en/project/548/#finance the financial information is invisible, because both background and font are white. 

![screen shot 2016-02-26 at 13 52 01](https://cloud.githubusercontent.com/assets/4179989/13353284/93a2ea0a-dc93-11e5-981b-b79803e5c267.png)

![screen shot 2016-02-26 at 13 52 07](https://cloud.githubusercontent.com/assets/4179989/13353286/97ac367e-dc93-11e5-9882-e6b9b36166bc.png)

**Comment by AkvoAnt** [comment]
This was mostly resolved with Loic and Geert.
