### ISSUE TITLE
Export IATI button at project page

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2033]
At the bottom of a project page you see a few buttons to export data. The one to export IATI is confusing for some partners, because it gives the expectation that I export my data to IATI. That is not the case. 

![screen shot 2016-03-01 at 16 45 24](https://cloud.githubusercontent.com/assets/4179989/13432251/15f39036-dfcd-11e5-8193-73b9ee32c44e.png)

**Comment by damienallen** [comment]
I propose changing the section to "download data" would clear up this ambiguity. Thoughts?

**Comment by damienallen** [comment]
Kasper and I decided it is best to remove links to XML and IATI instead.

**Comment by damienallen** [comment]
Test plan:

Open project page. Only 'RSS' and 'JSON' links should be shown in the footer.
