### ISSUE TITLE
Akvo Pages 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#2053]
When RSR 3.0 was launched, the layout of the Akvo Pages changed too. In  http://rsr.akvo.org/en/admin/rsr/partnersite/add/ there are quite some fields that are not relevant anymore with this new layout. 

E.g. 'About box text' and 'About box image' are not relevant anymore. These are not visible at the current Akvo Pages.

**Comment by damienallen** [comment]
Test plan:

Check admin page for Akvo Page. "Project selection" should now be the second section and deprecated fields should be removed.
