### ISSUE TITLE
Search in RSR

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2076]
In general, we use a lot of different mechanics for searching within RSR. We need to align the searches so that it is clear what the user searches on. This includes the following pages:
- [ ] Project, update and organisation listing pages
  - [ ] Unpublished projects now show in public projects list
- [ ] Organisation search in Project editor
- [ ] User search in User management

**Comment by nadiagorchakova** [comment]
There's also some feedback from partners related to search function:

"Just got some feedback from Aqua for All on the search function in RSR. When you search via the search bar you will only find projects that have your search term in the Title of the project. I think it’s hard to search for a project based on it’s title - especially when you’re not looking for one specific project but for something more general. People would like to be able to search on other things (especially countries). This is possible through advanced filters, but this is not very straight forward.

May be good to have a look at the search function to see how we can improve it/make it more user friendly. This isn’t the first time I’ve heard this feedback.

Cheers, 
Annabelle Poelert 
Project Officer"

**Comment by punchagan** [comment]
Related to #2548 #2552 #2598

**Comment by punchagan** [comment]
Lots of search related improvements since this issue was opened. Closing stale issue.
