### ISSUE TITLE
Styling improvements data quality / project overview report

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-rsr#2096]
Based on Laura's hand written comments.

**Comment by loicsans** [comment]
Do we have any more detail on this?

**Comment by nadiagorchakova** [comment]
@stellanl could you please review the code?

**Comment by zzgvh** [comment]
I think this issue has been committed/deployed, if so then I guess we should as Geert about the comments he refers to.

**Comment by nadiagorchakova** [comment]
Geert said Laura's comments are not particularly relevant anymore. 
Would be good to at least check the code for styling improvements Geert prepared.

**Comment by stellanl** [comment]
Minor font fix and left-aligning of a number of fields. One db query change that was then fixed in #2416.
