### ISSUE TITLE
Widget map pins

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#2100]
Blue (project) pins are not working for widgets.

Green (updates) pins work fine.

http://programmes.akvoapp.org/en/project/2079/widgets/?widget=map

**Comment by zzgvh** [comment]
### Test plan
The pins on the maps widget display a link popup, and the popup goes away when a new pin is clicked. Suggested link, use the one above but on the test server (Can't remember the partnersites URL on test).

**Comment by KasperBrandt** [comment]
Closed in #2101
