### ISSUE TITLE
User roles and permissions

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2115]
We should create a new user roles and permissions system in which it is at least possible to grant specific users access to a project and not necessarily all projects of an organisation.

The new user roles and permissions also needs a new UI, probably replacing the old 'User management' section of MyRSR.

**Comment by nadiagorchakova** [comment]
I'm closing this issue because it duplicates https://github.com/akvo/akvo-product-design/issues/129
