### ISSUE TITLE
Organisations listing details

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2128]
On the organisations listing page, not everything is nicely lined out or has correct styling:

- [x] The IATI organisation ID has no styling
- [x] The social media buttons have different compared to the other columns
- [x] The Facebook icon is missing (we should have local copies of the Facebook / Twitter / LinkedIn icons).

<img width="1199" alt="screen shot 2016-04-29 at 10 51 09" src="https://cloud.githubusercontent.com/assets/1497367/14911872/8cf83084-0df8-11e6-9cbd-52188510f2ee.png">

**Comment by damienallen** [comment]
Test plan:

Open organisation listing page and find organization with social media links and IATI org ID. Compare formatting to the original screenshot.
