### ISSUE TITLE
Public custom fields

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2148]
Currently we have the option to add custom fields to your project. However, these fields will always be private (e.g. only visible in the project editor, nowhere else).

It should also be possible to make the fields public, by showing them on the project page. Probably on the full report tab, but possibly also in the accordion on the summary tab (to be discussed).

**Comment by akvotender** [comment]
+1, also useful for Plan Finland :)

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#155
