### ISSUE TITLE
RSS feeds give a 504

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2155]
For example: 
- http://rsr.akvo.org/rss/org-updates/273/
- http://rsr.akvo.org/rss/updates/788/

**Comment by damienallen** [comment]
Number of items currently limited to 50 most recent updates but only ~35 items will load reliably before timeout. A limit of 25 is suggested and included in PR.

**Comment by damienallen** [comment]
Test plan:

Open the following feeds for organizations/projects with more than 50 updates:
http://rsr.akvo.org/rss/org-updates/<org-id>/
http://rsr.akvo.org/rss/updates/<proj-id>/
http://rsr.akvo.org/rss/all-updates/
