### ISSUE TITLE
My IATI feedback

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2159]
By Annabelle:

- [ ] "+ Add a new IATI export" button is not visible enough. The main reason to go to "My IATI" is to generate a new IATI set, but you really have to look for a place to do so right now;
- [ ] "It is possible to generate both an IATI activity file for project information, and an IATI organisation file for organisation information” --> this sentence can be removed (for a better overview and less text);
- [ ] "Set as latest file" I think it’s confusing that you can set something as a "latest" file, even when it's not the latest. Can we try to think of another terminology for this? Maybe we can leave out "latest"… so it would become "Set as organisation activity file";
- [ ] I notice a lot of partners are confused with the difference in creating an IATI file and publishing an IATI file. Maybe we can add a warning next release? When partner creates new file, maybe we can have a pop-up: "You've successfully created your IATI file, please make sure to register your file at the IATI registry"; 
- [ ] Would it be possible to keep the colours with the IATI checks? They used to become orange or red. Thought the whole feature disappeared at first and now only saw that you can check errors. Can only imagine that partners who don’t know about this functionality will now completely overlook it. Think it will help if 5 errors (or more) become red and below 5 orange;
- [ ] "Show latest activity file on the organisation page of Akvo Foundation". There is already a lot of text there. Maybe we can set this as an option at the organisation page for consistency? Or set it as an option by default? Who would create an IATI file and not want to show it? For that rare occasion we can change it in the back-end for the organisation.

By Josje:

- [ ] An interesting feature for the future might be to organise on the number of errors, so that you can easily see the ones with 0 errors on top;
- [ ] Some errors in the IATI checks seem to be in there twice;

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#163
