### ISSUE TITLE
/auth/token/ endpoint could be improved

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#2168]
Two improvements would be useful to Up:
* Deciding if a user has rights to submit Indicator Period Data in Up is complicated and relies on the names of user groups. If the endpoint returned another list of projects the user may post IPD to, (beside the current list of projects that updates may be posted to) the rights system can later be changed without breaking the API.
* The endpoint could have the new additions added in JSON format, leaving the current XML format for backward compatibility.

**Comment by KasperBrandt** [comment]
- [ ] Provide a JSON endpoint similar to the current ```/auth/token/``` endpoint at ```/auth/token/?format=json```.
- [ ] The endpoint should provide an additional list of project IDs that the user is allowed to edit.
- [ ] The XML endpoint should still be available by default at ```/auth/token/```.

**Comment by stellanl** [comment]
Is "allowed to Edit"  the same as "may submit Indicator Period Data to"?

**Comment by KasperBrandt** [comment]
@stellanl yes 😄

**Comment by KasperBrandt** [comment]
## Test plan
- Submit a request to ```/auth/token``` with a valid username=.., password=.. and handles_unemployment=True as POST data.
  - Without ```?format=json``` or ```?format=xml```, this should return an XML response with username / user_id / organisations / allow_edit_projects **(new)** / api_key and published_projects.
  - With ```?format=json```, this should return a JSON response **(new)** with username / user_id / organisations / allow_edit_projects / api_key and published_projects.

**Comment by stellanl** [comment]
I have verified backwards compatibility; the new item in the XML variant does not break the parser in old Up versions.
