### ISSUE TITLE
Unnecessary parameters in API cause MultipleObjectsReturned

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2171]
See http://sentry.support.akvo-ops.org/rsr/live/group/887/.

- ```/rest/v1/project_extra/2649/``` works fine.
- ```/rest/v1/project_extra/2649/?partners=1``` returns a MultipleObjectsReturned error.

In these cases, the parameter should be ignored. There are exceptions though, such as the ```limit``` parameter (and maybe more?).

**Comment by damienallen** [comment]
### Test plan

API calls for where PK is specified should no longer raise an error when unnecessary query strings are appended to the URL (they are simply ignored). The following pages should both load without issue:

- `/rest/v1/project_extra/2649/`
- `/rest/v1/project_extra/2649/?partners=1`
