### ISSUE TITLE
Disaggregation of results

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2178]
Total value - in indicators and results - should be able to be split up:

- people trained: total, option split up total: male and female participants

**Comment by nadiagorchakova** [comment]
I'll move this one to Product and Design repository. There were some related requests from Henry about the same thing. Needs to be investigated a bit more.

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#186
