### ISSUE TITLE
Add default indicator periods to all indicators

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2179]
Set standard indicator periods to import.

- [x] Add new fields for results framework: default start and end dates as indicator periods of a project;
- [x] Add these period(s) to every indicator when it is not present yet;
- [x] Add these period(s) as well when an indicator is saved and the period is not present yet.

**Comment by damienallen** [comment]
### Test plan

- [ ] It should now be possible to "Set periods as default" at indicator level
- [ ] This should prompt if default periods should be copied to existing indicators
- [ ] Only start and end dates should be copied
- [ ] Newly added indicators should be populated with default periods (user recieves message to refresh)
- [ ] "Remove default indicators" button should also work correctly
- [ ] Ensure text is clear and self-explanitory
