### ISSUE TITLE
Disable aggregation of results

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2182]
Currently, we always aggregate the results to a parent project. However, it would be nice to have a setting to disallow this.

**Comment by KasperBrandt** [comment]
@mato74 Not 100% clear on how to implement this.

**Comment by KasperBrandt** [comment]
- [ ] Add a new checkbox on project level to allow / disallow aggregations between parent / child projects (checked by default)
- [ ] Only show this checkbox when there is a link between parent and child (on both levels)
- [ ] When unchecked on parent project level: none of the child projects will aggregate to the parent project
- [ ] When unchecked on child project level: this project will not aggregate to the parent project

**Comment by damienallen** [comment]
### Test plan

In project editor (section 5):
- [ ] Parent projects should have option to toggle aggregation of child values
- [ ] Child projects should have option to toggle inclusion in parent's aggregate
- [ ] Projects which are both child and parent should display both options
- [ ] Ensure styling is appropriate
- [ ] Ensure option titles and help text are also appropriate

Aggregation:
- [ ] Aggregations should work with any hierarchy (children, grandchildrem, etc)
- [ ] Indicators using percentage should be ignored
- [ ] Text values should not be aggregated
- [ ] Editing an indicator period update value should propage to parent's aggregate
- [ ] Switching (editing indicator update) to/from text values should add/subtract from parent's aggregate
- [ ] Upon switching from text to decimal value, child indicators should be aggregated
- [ ] Updates to child values should only propagate until a parent with child aggregation disabled is reached
