### ISSUE TITLE
Move to IATI statuses

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2189]
This is probably a bigger issue than we expect, but we should replace the current project.status with the IATI entries. A mapping will be done like this:

```
STATUS_TO_CODE = {
    'N': '6',
    'H': '1',
    'A': '2',
    'C': '3',
    'L': '5',
    'R': '6',
}
```

- [x] Convert status codes
- [x] Update IATI import / export
- [x] Update project editor
- [x] Update project page and project entry in projects list
- [x] Cancelled and completed projects can't be updated (see https://github.com/akvo/akvo-rsr/issues/2006#issuecomment-218499657)
- [x] Check where else in RSR the project's status is used

**Comment by damienallen** [comment]
Report templates (project overview) will need to be updated to use IATI codes:

`STATUS_NONE = '6'`
`STATUS_NEEDS_FUNDING = '1'`
`STATUS_ACTIVE = '2'`
`STATUS_COMPLETE = '3'`
`STATUS_POST_COMPLETE = '4'`
`STATUS_CANCELLED = '5'`
`STATUS_ARCHIVED = '6'`

@Geerts @stellanl

**Comment by KasperBrandt** [comment]
After a short discussion this morning, @damienallen and I decided to keep the current ```project.status``` field as is for legacy reasons (e.g. API, ReportServer, etc) and create a new field ```project.iati_status``` which stores the IATI statuses.

**Comment by damienallen** [comment]
### Test plan (WIP)

IATI import/export:
- [ ] Functionality preserved

Organisation page:
- [ ] Check that project status labels and counts are correct
- [ ] Check whether the counts link to appropriate filters
- [ ] Confirm that sizing/styling of labels is correct

Project list:
- [ ] Check status labels
- [ ] Check that both `?status=` and `?iati_status=` filters work correctly

Project page:
- [ ] Check status label and coloring
- [ ] Check whether the donate button is disabled for suspended, cancelled and completed projects

Widgets:
- [ ] Check whether the new IATI statuses are displayed
- [ ] Check whether the widgets are formatted correctly (especially for status 1)

Management commands:
- [ ] Make sure `funds_needed` command still marks projects as complete

**Comment by KasperBrandt** [comment]
Small layout issue, the actions in the My projects list are not on one row anymore (probably due to the pipeline/identification status):

<img width="1136" alt="screen shot 2016-06-01 at 12 25 00" src="https://cloud.githubusercontent.com/assets/1497367/15706470/094027ea-27f4-11e6-85e9-d21abc9d24e2.png">

**Comment by KasperBrandt** [comment]
Just discussed with Marten and Mark;

Map None -> No status
Map Archived - > Completed or Cancelled (check list manually).

**Comment by KasperBrandt** [comment]
## Test plan (2)
1. Re-migrate 0075 and 0076 (backwards and forwards)
2. Check that the status can be empty in the project editor, and that it is stored in the DB as an empty string
3. On Test/UAT: Check [this list](https://docs.google.com/spreadsheets/d/1PWkJxrmFYvJvZMwPjEALqxQlW4ae6-8xNnTEvz0cXvY/edit#gid=0) for an overview of archived projects and their new status.

**Comment by KasperBrandt** [comment]
- [ ] Change status dropdown in advanced filter on ```/projects/```
- [ ] Hide __Status__ if not available on projects list and project page
