### ISSUE TITLE
Edit and remove updates

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2191]
Currently, when you've added a project update, there is an 'Edit' button on the update page itself for 20 minutes. However, it should always be possible to edit your own updates, so this time limit should be removed. In addition, it would be nice to have the 'Edit' button on the 'My updates' page in MyRSR as well.

- [x] Remove the 20 minutes limit for editing project updates.
- [x] Remove the 'Edit' button from the update page.
- [x] Add 'Edit' and 'Delete' action in My updates section of MyRSR.

**Comment by damienallen** [comment]
### Test plan

- [ ] Check updates section on project page to confirm 'Edit' button is removed (including references to time limit)
- [ ] Check that 'Edit' and 'Delete' buttons are added to 'My Updates' in MyRSR
- [ ] Confirm that updates older than 20 minutes can be edited (also see code changes)
- [ ] Delete button should ask for confirmation first
- [ ] Errors should be displayed below title (try opening 2 tabs and delete the same update without reloading the 2nd tab)
