### ISSUE TITLE
Add reporting template for Plan Finland

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2194]
We should add the reporting template that @stellanl and @Geerts are working on to the "My reports" section. Preferably so that only superusers / admins / Plan Finland employees can see this, but we might need a little hack for that.

**Comment by stellanl** [comment]
There are no Plan Finland "secrets" in the report template, but as it will be almost useless if you don't have a 3-level hierarchy under the selected project, it could be confusing to other users.

**Comment by KasperBrandt** [comment]
Yup, @mato74 requested it to be Plan Finland visible only. We will need to see what's possible there.

**Comment by KasperBrandt** [comment]
Had a short chat with @stellanl earlier, but not all parameters are clear at the moment:

- What will be the key of the report (e.g. 'plan-finland')?
- Which formats will be supported (only PDF, or Excel / Word / HTML as well)?

**Comment by stellanl** [comment]
Key can be anything we want as long as it is unique on the reportserver. These are currently defined:
        <keys>projects_monthly_total</keys>
        <keys>projects_and_partners_cumulative</keys>        
        <keys>projects_and_partners_new</keys>        
        <keys>project_funding_cumulative_eur</keys>        
        <keys>project_funding_cumulative_usd</keys>                
        <keys>project_monthly_total_filterable</keys>                        
        <keys>rsrquery</keys>                        
        <keys>flowquery</keys>                        
        <keys>project_results</keys>                        
        <keys>project_results_simple_table</keys>                        
        <keys>project_overview</keys>                        
        <keys>data_quality</keys>                        
        <keys>restest2</keys>

**Comment by KasperBrandt** [comment]
## Test plan
1. Login as a superuser / RSR admin / member of Plan Finland and check that the Plan Finland report is available in the reports dropdown list.
2. Login as a non-superuser / non-RSR admin / non-member of Plan Finland and check that the Plan Finland report is not available in the reports dropdown list.
3. On Test: check that the report itself is working.

**Comment by stellanl** [comment]
PF wants to use a special font "Veneer" for headings. The Reprtserver BIRT engine has the following font path:
        <font-paths>
                <path path="C:/windows/fonts" />
                <path path="d:/windows/fonts" />
                <path path="e:/windows/fonts" />
                <path path="f:/windows/fonts" />
                <path path="g:/windows/fonts" />
                <path path="C:/WINNT/fonts" />
                <path path="d:/WINNT/fonts" />
                <path path="e:/WINNT/fonts" />
                <path path="f:/WINNT/fonts" />
                <path path="g:/WINNT/fonts" />
                <path path="/usr/X/lib/X11/fonts/TrueType" />
                <path path="/usr/share/fonts/default/TrueType" />
                <path path="/usr/openwin/lib/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/euro_fonts/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/iso_8859_2/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/iso_8859_5/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/iso_8859_7/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/iso_8859_8/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/iso_8859_9/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/iso_8859_13/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/iso_8859_15/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/ar/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/hi_IN.UTF-8/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/ja/X11/fonts/TT" />
                <path path="/usr/openwin/lib/locale/ko/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/ko.UTF-8/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/KOI8-R/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/ru.ansi-1251/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/th_TH/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/zh_TW/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/zh_TW.BIG5/X11/fonts/TT" />
                <path path="/usr/openwin/lib/locale/zh_HK.BIG5HK/X11/fonts/TT" />
                <path path="/usr/openwin/lib/locale/zh_CN.GB18030/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/zh/X11/fonts/TrueType" />
                <path path="/usr/openwin/lib/locale/zh.GBK/X11/fonts/TrueType" />
                <path path="/usr/X11R6/lib/X11/fonts/TrueType" />
                <path path="/usr/X11R6/lib/X11/fonts/truetype" />
                <path path="/usr/X11R6/lib/X11/fonts/tt" />
                <path path="/usr/X11R6/lib/X11/fonts/TTF" />
                <path path="/usr/X11R6/lib/X11/fonts/OTF" />
                <path path="/usr/share/fonts/ja/TrueType" />
                <path path="/usr/share/fonts/truetype" />
                <path path="/usr/share/fonts/ko/TrueType" />
                <path path="/usr/share/fonts/zh_CN/TrueType" />
                <path path="/usr/share/fonts/zh_TW/TrueType" />
                <path path="/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" />
(in file fontsConfig.xml in jar org.eclipse.birt.runtime-4.4.1.jar)
so I put the file "Veneer W01 Two.ttf" on the server as
 /usr/share/fonts/default/TrueType/pf/Veneer-W01-Two.ttf
