### ISSUE TITLE
Inviting and accepting users of content owned organisations

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2196]
The ```organisation.content_owner``` field is used in some parts of RSR, but not fully yet. This is the most obvious in the "invite user" functionality (User management in MyRSR) and when approving a user of a content owned organisation.

- [x] In the 'invite users' dropdown, the organisations of which the user's organisation is content owner should also be populated in the list.
- [x] Once a user requests to join an organisation, the users of the content owner (and their content owner, etc) should also receive an email. But only when they're Admin or User manager and when they're user account has 'is_support' set to True.

**Comment by damienallen** [comment]
### Test plan

- [ ] Check if content owned organisations are listed in 'invite users'
- [ ] Check if support users of content owner are notified if user requests to join child orgnaisation

**Comment by KasperBrandt** [comment]
## Test plan (2)
1. Setup an organisation with can_create_projects (a paying partner).
2. Add a user to this organisation with is_support (a support user).
3. Create a new project with the paying partner and several implementing partners.
4. Check if the support user can invite users for the implementing partners.
5. Register as a new user and request to join one of the implementing partners; check if the mail is sent out to the support user.

**Comment by KasperBrandt** [comment]
Feedback by @Geerts: 
- [ ] When inviting a user to my organisation I could only give the role project editor, afterwards also admin.
- [ ] As the project editor I was still able to invite people for other organisations.

**Comment by KasperBrandt** [comment]
## Test plan (3)
1. Superusers or organisational admins should have the permission to invite users with any role or change an existing role to any role in User management
2. User managers and M&E managers should have the permission to invite users with any role except 'Admins' or change an existing role to any role except 'Admins' in User management
3. Users and project editors should have no permission to go to User management

**Comment by damienallen** [comment]
### Issues

- [ ] M&E managers lack access to User Management
- [ ] User managers (and probably M&E managers) cannot invite/change role to 'Admins' as intended _but_ can demote Admins to other user groups
