### ISSUE TITLE
Add test scripts for current API calls for Up app

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#2205]
These should test the basic functionality of the API endpoints that Up uses.

Requirements:
* [x] A test user account in RSR so we can obtain an API key and access non-public functions. It must be connected to an organisation with at least one project for which at least one update is posted. Both project and update should have photos.

**Comment by stellanl** [comment]
Minimal read-only session URL usage:
If all return 2nn codes it is successful.
1. Logging in

POST /auth/token
with a body of
username=<testuser>
password=<pwd>

2. Fetching project data (nnn is one of the published projects ids returned in (1))

GET /rest/v1/project_up/nnn/?format=xml&image_thumb_name=up&image_thumb_up_width=100
GET /rest/v1/country/?format=json&limit=50
GET /rest/v1/project_update/?format=xml&project=nnn&last_modified_at__gt=1970-01-01T00:00:00
 Up then fetches data for users referenced by the updates:
GET /rest/v1/user/uuu/?format=json&depth=1
 and the organisations the users are employed by
/rest/v1/organisation/ooo/?format=json

**Comment by KasperBrandt** [comment]
## Test plan
Wait for the tests to run and successfully complete.
