### ISSUE TITLE
Bugs with budget item totals and labels

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2217]
### Totals

Unknown format code 'f' for object of type 'str'

In:
```
/var/akvo/rsr/code/akvo/rsr/models/project.py in budget_currency_totals_string
        totals = self.budget_currency_totals()
        total_string = ''
        for t in totals:
            print type(totals[t])
            total_string += '%s %s, ' % ("{:,.0f}".format(totals[t]), t) ...
        return total_string[:-2]
```

### Labels

AttributeError: 'NoneType' object has no attribute 'label'

```
File "akvo/rsr/models/budget_item.py", line 116, in get_label
    if self.label.label in self.OTHER_LABELS:

```

**Comment by damienallen** [comment]
### Test plan

Add budget item in project currency (select project currency, _not_ blank/default) and another budget item in another non-project currency.

- [ ] Make sure total for project currency is displayed on Project Page -> Finances Tab
- [ ] Make sure project editor loads without raising an error
