### ISSUE TITLE
Alignment of error message during publishing a project

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2224]
When trying to publish a project in the project editor, but this fails, an error is shown. However, the alignment isn't correct:

<img width="467" alt="screen shot 2016-06-06 at 12 43 03" src="https://cloud.githubusercontent.com/assets/1497367/15819561/33ccef68-2be4-11e6-8a78-8d888533896c.png">

**Comment by damienallen** [comment]
### Test plan

Force a publishing error in project editor and ensure error text is aligned with the progress bar.
