### ISSUE TITLE
Add a login layer to Test and UAT

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2225]
Having test data (test and uat) online is not a good practice. People may stumble upon it without noticing that it’s old/test/fake. Need to add a login layer.

**Comment by mato74** [comment]
includes reportserver reports hosted on e.g. akvo-ops

**Comment by KasperBrandt** [comment]
## Test plan
1. (On localdev, change 'uat' or 'test' to 'localdev' in ```cookie.jsx```);
2. Check that a modal appears for when accessing RSR the first time;
3. Password is ```TesTing!``` (not sensitive data, so we can share it anyway);
4. Check that an error is shown when password is incorrectly filled in;
5. Check that the cookie is added for one week when the password is filled in correctly.
