### ISSUE TITLE
Warn the user when they lose editing rights of project

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2226]
When removing an organisation from a project, it is possible that the user loses the right to edit the project altogether. In this case, we should warn the user that they will lose the editing rights.

**Comment by KasperBrandt** [comment]
## Test plan
- [ ] Check that superusers will always have all the rights to delete any partnership
- [ ] Check that organisation admins / project editors can't delete their (last) own partnership in the project editor --> delete button should be hidden

E.g. an admin of Org1 and Org2 should be able to delete any partnership when a project is linked to both Org1 and Org2. When it is only linked to one Org1 or Org2 partnership, then it should not be possible to delete this partnership.

**Comment by damienallen** [comment]
Only hidden for admins and M&E managers, not project editors.
