### ISSUE TITLE
Buggy behavior when adding documents in project editor

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2228]
### Adding documents changes URL/upload switch
To reproduce:
1. Go to editor and in section 9 upload a new document.
2. Click the 'Add another document' link
3. _Result:_ The first document switches back to show the URL instead of upload field

### Trying to save an invalid URL will populate blank documents with the incorrect URL
To reproduce:
1. Go to editor and in section 9 add a new document
2. Enter an invalid url (ex. 'http://test.c') in one document url field and try to save
3. Correct the url (ex. 'http://test.com') and save again
4. Upon reloading the page, there will be an additional 'Untitled Document' with the incorrect url  ('http://test.c')

**Comment by damienallen** [comment]
### Test plan

Attempt to reproduce bugs using steps detailed above. The described behavior should no longer occur.
