### ISSUE TITLE
Test reports indexed by Google (estimate: 2)

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2232]
See https://www.google.nl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=rsr+test+akvo&safe=off&start=10.

This link has been indexed by Google: http://rsr.test.akvo-ops.org/en/reports/organisation_summary/42?format=pdf&download=false.

**Comment by mtwestra** [comment]
Add path to robots file

**Comment by punchagan** [comment]
Need to check if this is already done as a part of https://github.com/akvo/akvo-provisioning/issues/79 or https://github.com/akvo/akvo-provisioning/issues/158
