### ISSUE TITLE
API - Security

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#225]
We need to do some work on Security on API calls to ensure the data is transmitted and received/stored securely.

Most information will be truly open, but there will be times when user information could be sent and received using the API so it needs to be secured to ensure this data is not available to the wrong hands.

Not sure on the options here, would be good to get an idea of the possibilities available to us. Maybe we need to talk about this as a team?

**Comment by KasperBrandt** [comment]
I think https will cover for the security of the API. See #634.
