### ISSUE TITLE
Remove 'end date' check for user invitations

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2250]
Currently, when a user gets an invite we check whether the invite was sent within the last week. However, there have been multiple occasions in which the user clicks the activation link after one week and then it's not easily possible to re-send an invitation.

As a simple solution, we will remove the check on the date so that users can accept the invitation at any time.

**Comment by damienallen** [comment]
### Test plan

- [ ] 7 day expiration window should no longer exist for invitations
- [ ] References to expiration time limit should be removed from emails and help text
- [ ] Activation codes themselves should still be validated and rejected if incorrect
