### ISSUE TITLE
Styling actual value comments in results framework

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2257]
The styling of actual value comments is not correct in the results framework (project page and My results):

<img width="1174" alt="screen shot 2016-06-22 at 11 52 52" src="https://cloud.githubusercontent.com/assets/1497367/16262457/f9289cac-386f-11e6-997e-cbcbb04709bb.png">

**Comment by damienallen** [comment]
### Test plan

Check an indicator period with target/actual comments of noticeably different length. Add an indicator update and confirm that the container no longer clips through the comments. Also, there should now be (15px) padding between the two comment columns.
