### ISSUE TITLE
Look into performance of Tastypie

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2262]
We should look into the Tastypie API and see whether it causes some of RSR's performance issues.

**Comment by damienallen** [comment]
Calls to the old API can result in unfiltered queries for all projects and/or users. The following line is one likely source (akvo/api/fields.py line 98):

'foreign_obj = getattr(bundle.obj, self.attribute)'

**Comment by KasperBrandt** [comment]
## Test plan
- [ ] Check that ```/api/v1/``` returns the same output as previously. One exception: ```offset``` is not supported in DRF, so that has been taken out:
  - [ ] For ```format=xml```
  - [ ] For ```format=json```
  - [x] (Default format in DRF is HTML, which was never supported by Tastypie, so no need to check)
- [ ] Check that the ```/api/v1/right_now_in_akvo/?format=json``` returns the same as previously (see #1636).
