### ISSUE TITLE
Alignment in report tab

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2266]
The width of the description 'headers' in the report tab is not big enough. See:

<img width="885" alt="screen shot 2016-06-28 at 10 16 16" src="https://cloud.githubusercontent.com/assets/1497367/16408543/958868f4-3d19-11e6-828a-4cb14d3db03a.png">

**Comment by damienallen** [comment]
### Test plan

Confirm that wrapping no longer occurs mid-word in the 'Description' section of the 'Full Report' tab. Due to responsive layout this was most likely to occur with lengthy description texts.
