### ISSUE TITLE
Allow 0 as value for funding amount in partnerships

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2269]
It should be possible to fill in 0 as a funding amount in the project editor, and then publish a project. This is based on Plan Finland feedback:

"Are you able to give us an estimate on when the suggestions we made to Geert could be published (the changes to the results section and possibility for 0€ budget project)."

**Comment by damienallen** [comment]
### Test plan

Add a funding partner with '0' funding amount and a budget item with '0' value. Upon publishing the project, no errors should be raised. Confirm that blank values still result in the following errors (publish button might need to be manually enabled):

`All funding partners should have a funding amount.`

`Project needs to have at least one budget item with an amount.`
