### ISSUE TITLE
Internal server error for API call

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2273]
This URL currently gives an internal server error: http://rsr.akvo.org/rest/v1/project_extra/787/.json

Part of the stacktrace:
```
IOError Root Cause
image file is truncated (48 bytes not processed)

...
akvo/rest/fields.py ? in to_native
    default_thumb = get_thumbnail(value, default_width, quality=99)
sorl/thumbnail/shortcuts.py ? in get_thumbnail
    return default.backend.get_thumbnail(file_, geometry_string, **options)
sorl/thumbnail/base.py ? in get_thumbnail
    thumbnail)
sorl/thumbnail/base.py ? in _create_thumbnail
    image = default.engine.create(source_image, geometry, options)
sorl/thumbnail/engines/base.py ? in create
    image = self.colorspace(image, geometry, options)
sorl/thumbnail/engines/base.py ? in colorspace
    return self._colorspace(image, colorspace)
sorl/thumbnail/engines/pil_engine.py ? in _colorspace
    return image.convert('RGB')
PIL/Image.py ? in convert
    self.load()
PIL/ImageFile.py ? in load
    "(%d bytes not processed)" % len(b))
```

**Comment by damienallen** [comment]
### Test plan

Add an update with a corrupt image (for example, [this image](http://rsr.akvo.org/media/db/project/787/update/11316/ProjectUpdate_11316_photo_2015-08-27_01.15.42.JPG)). Run an API call which requires a thumbnail of the image, for example:

http://rsr.akvo.org/rest/v1/project_extra/**<project_id>**/.json

The call should not display an IOError and for the added update the following should be returned:

`photo: null`
