### ISSUE TITLE
Invite existing users gives an IntegrityError

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2274]
See http://sentry.support.akvo-ops.org/rsr/live/group/797/.

**Comment by damienallen** [comment]
### Test plan

Add a second employment for a user and attempt to change the group to the same value as an existing employment. An IntegrityError should no longer be raised, and a message below the dropdown should inform the user that the employment group already exists for the user. The error message should disappear if a valid group is selected.
