### ISSUE TITLE
Non unicode location data

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2275]
Filling in this data for locations will give an UnicodeDecodeError: ```28.2118Â°``` or ```81.7131Â°```.

**Comment by damienallen** [comment]
### Test plan

Copy non-unicode lat/long from [mygeoposition](http://mygeoposition.com/) into project location. Uncaught exception should no longer be raised and user should be prompted to enter a decimal value. Other non-unicode values submitted in project editor will no longer be returned in error text (they will be stripped).
