### ISSUE TITLE
Countries in the project editor

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2278]
Some users are confused by the country codes in the 'add organisation' modal. We should remove these and only show the country name. And also sort by country name.

- [x] Country fields in project editor should just display only the country name
- [x] Don't forget the country field in the 'add organisation' modal
- [x] Sort by country name

**Comment by damienallen** [comment]
### Test plan

Ensure countries are correctly listed (no code, alphabetical) for:
- [ ] Transactions
- [ ] Organisation document countries
- [ ] Organisation recipient country budgets
- [ ] Organisation location (add organisation modal)
- [ ] Employment countries
