### ISSUE TITLE
Show comma display for indicator data

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2280]
- [ ] When a user fills in an indicator update like ```1,000```, it should be converted to an integer (```1000```).
- [ ] When a user fills in an indicator update like ```2.1415```, it should remain a decimal.
- [ ] Other updates, such as ```Developed, but not implemented```, should remain a string.

**Comment by KasperBrandt** [comment]
Like @bjelkeman said, this is actually harder than I thought.. It depends on localisation to know which separator is being used (, or .) and then still there might be situations in which you'd like to keep the separator. 

E.g. we can't guess what a user means when they fill in 2,012 or 2.012. Could be a decimal or an integer.

Any thought @mato74?

**Comment by mato74** [comment]
Let’s stick to , separator. So for example 1,000.00
Reasoning: consistent with the implementation of financial figures in RSR. 
See e.g. http://rsr.akvo.org/en/project/4328/#finance <http://rsr.akvo.org/en/project/4328/#finance>


> On 06 Jul 2016, at 16:18, Kasper Brandt <notifications@github.com> wrote:
> 
> Like @bjelkeman <https://github.com/bjelkeman> said, this is actually harder than I thought.. It depends on localisation to know which separator is being used (, or .) and then still there might be situations in which you'd like to keep the separator.
> 
> E.g. we can't guess what a user means when they fill in 2,012 or 2.012. Could be a decimal or an integer.
> 
> Any thought @mato74 <https://github.com/mato74>?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/akvo/akvo-rsr/issues/2280#issuecomment-230785693>, or mute the thread <https://github.com/notifications/unsubscribe/AIFd30kxg4rbdGHmvc4selux8zi5oNHOks5qS7k7gaJpZM4JB6cS>.
> 


___

Marten Schoonman 
Technical account manager 
Akvo Foundation  

W www.akvo.org 
T +31 (0) 20 820 0175 
T +31 (6) 4843 1680 
M marten@akvo.org 
S marten.schoonman 
T @mato74

Recent Akvo articles:

 <http://akvo.org/akvo-lumen/> <http://akvo.org/akvo-lumen/> <http://akvo.org/akvo-lumen/>-  <http://akvo.org/akvo-lumen/>Akvo Dash becomes Akvo Lumen <http://akvo.org/blog/akvo-dash-becomes-akvo-lumen/>
- What’s new in Akvo RSR <http://akvo.org/blog/whats-new-in-akvo-rsr/>
- The unique landscape of the Akvo West Africa hub <http://akvo.org/blog/five-particularities-about-the-akvo-west-africa-hub/> (en Français <http://akvo.org/blog/le-champ-daction-unique-du-pole-akvo-afrique-de-louest/>)

**Comment by KasperBrandt** [comment]
Merged with #2272
