### ISSUE TITLE
Invalid query parameters cause internal server error

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2291]
```
  File "akvo/rest/filters.py", line 61, in filter_queryset
    queryset = getattr(queryset, param)(**args_or_kwargs)
```

In the new API filtering, you get an internal server error when the query is not correct, e.g.: http://rsr.akvo.org/rest/v1/project/?filter={'incorrect':'code'}. 

We should catch this and return the error message in a dict with detail as key. E.g. ```{detail: 'Related Field got invalid lookup: incorrect'}```

**Comment by damienallen** [comment]
### Test plan

Attempt API call with invalid filter. Error should now appear as "detail" in API view.
