### ISSUE TITLE
Upgrade to Django 1.9

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2297]
- [ ] Pre-upgrade steps for 1.8
  - [ ] Upgrade to Django REST Framework 3.2.5 ( #2298 ) 
  - [ ] Test API (especially UP)
- [ ] Upgrade to Django 1.8 (#2186)
- [ ] Pre upgrade steps for 1.9
  - [ ] Test Django 1.8
  - [ ] Upgrade to Django REST Framework 3.4.X
- [ ] Upgrade to Django 1.9

**Comment by damienallen** [comment]
## Deprecated functions

### 1.9

- **get_model**
- IPAddressField

### 1.8

**Comment by damienallen** [comment]
## Libraries

BeautifulSoup==3.2.1
defusedxml==0.4.1
Django==1.7.7
django-bootstrap3==4.11.0
django-counter==0.1.6
django-crontab==0.6.0
django-debug-toolbar==1.3.0
django-embed-video==0.11
django-filter==0.9.0
django-markup==0.4
-e git://github.com/peeb/django-mollie-ideal.git@d7da9c4a40f734101cb41c4405e35b92053a2d6a#egg=django_mollie_ideal-master
django-nested-inline==0.3.6
-e git://github.com/zzgvh/django-notification.git@c55f57cb356d76d71e1a0a7422dc7a7ba1ea0106#egg=django_notification-master
django-pagination==1.0.7
django-paypal==0.1.3
-e git://github.com/zzgvh/django-permissions.git@87b6fa1831d9a9c797998fec61c1b1e0b7f15b10#egg=django_permissions-master
django-pipeline==1.3.26
django-piwik==0.1
-e git://github.com/akvo/django-registration.git@d1ff9eba18854fc41892de5a16562db77b93a25a#egg=django_registration-master
-e git://github.com/pySilver/django-rest-swagger.git@9be124e17d6c2200c0953eefc51d2e39c822cb55#egg=django_rest_swagger-dev
django-smtp-ssl==1.0
-e git://github.com/lukeman/django-sorting.git@d3456924ff2140c2a3466a2dd9d674486500393e#egg=django_sorting-master
django-statsd-mozilla==0.3.15
django-tastypie==0.12.1
django-templatetag-handlebars==1.2.0
-e git://github.com/zzgvh/django-workflows.git@095b4c23f76e48a566c505f25668c5385242b2fd#egg=django_workflows-master
-e git://github.com/akvo/djangoembed.git@3a1d6b955bcff4b2ec04eefca79a0b2ebb31289a#egg=djangoembed-master
djangorestframework==2.3.13
futures==2.2.0
gunicorn==18.0
httplib2==0.9
lxml==3.3.5
Markdown==2.4
mimeparse==0.1.3
MySQL-python==1.2.5
Pillow==2.7.0
psycopg2==2.6
py-mysql2pgsql==0.1.5
python-dateutil==2.2
python-memcached==1.53
python-mimeparse==0.1.4
pytz==2014.3
PyYAML==3.11
raven==4.2.3
requests==2.3.0
rules==0.3
six==1.9.0
sorl-thumbnail==12.2
South==0.8.4
sqlparse==0.1.19
statsd==3.1
tablib==0.9.11
template-utils===0.4p2
termcolor==1.1.0
Unipath==1.0
xmlunittest==0.3.2

**Comment by punchagan** [comment]
Django 1.10 has been released, and it may be worth upgrading to it, instead of stopping at 1.9. 

Also, a lot of time when running tests is actually spent in running migrations.  I think it would be worth looking into [squashing migrations](https://docs.djangoproject.com/en/1.9/topics/migrations/#migration-squashing).

**Comment by zzgvh** [comment]
Ya, of course we should move to 1.10 when we upgrade. And reducing out migration count is a very good idea.

**Comment by punchagan** [comment]
Superseeded by #2384
