### ISSUE TITLE
Upgrade to Django REST Framework 3.2.5 (remaining work: 16)

### ISSUE THREAD

**Issue by damienallen** [akvo/akvo-rsr#2298]
Pre-requisite for #2297 
#### Pagination breaks in 3.3.0+

DRF versions 3.3.0+ use different pagination which may require some rewriting of the current code.

http://www.django-rest-framework.org/api-guide/pagination/
#### Update Notes

http://www.django-rest-framework.org/topics/3.0-announcement/
#### Packages
- djangorestframework updated (3.3.3)
- djangorestframework-xml added (1.3.0)
- django-rest-swagger updated (0.3.10)

**Comment by damienallen** [comment]
### Test plan

Don't forget to run `vagrant provision` on check in/out

- [ ] API calls should produce the same results as DRF2 (check IATI fields especially)
- [ ] Ensure the legacy API still functions correctly
- [ ] Ensure UP still functions correctly

**Comment by nadiagorchakova** [comment]
At the standup today we agreed to push the issue to the next release. It still requires some work and thorough testing.

**Comment by zzgvh** [comment]
The results of the log analysis looks like this:

```
***** List of /api/... calls *****
274 /api/v1/iati_activity/
72 /api/*/store/
3 /api/v1/project_update/
2 /api/v1/project_update_extra/
1 /api/v1/right_now_in_akvo/

***** List of /rest/... calls *****
10323 /rest/v1/project/*/project_editor/
3820 /rest/v1/project_update/
2135 /rest/v1/project/*/step_1/
1902 /rest/v1/partnership/
1512 /rest/v1/project/*/step_5/
1221 /rest/v1/user/*/update_details/
1196 /rest/v1/user/*/request_organisation/
1179 /rest/v1/goal/
1163 /rest/v1/project/
1050 /rest/v1/project/*/step_3/
1027 /rest/v1/project/*/step_6/
980 /rest/v1/internal_organisation_id/
890 /rest/v1/project/*/step_7/
701 /rest/v1/employment/*/approve/
654 /rest/v1/project/*/add_validation/*/
517 /rest/v1/invite_user/
506 /rest/v1/project/*/upload_file/
472 /rest/v1/project/*/step_4/
471 /rest/v1/project_location/
454 /rest/v1/indicator_period_data_framework/
423 /rest/v1/project/*/log_project_addition/
403 /rest/v1/organisation/
354 /rest/v1/employment/*/set_group/*/
349 /rest/v1/user/*/change_password/
330 /rest/v1/project/*/step_8/
242 /rest/v1/project/*/step_9/
233 /rest/v1/organisation/*/add_logo/
210 /rest/v1/project/*/step_2/
195 /rest/v1/organisation_location/
102 /rest/v1/project/*/reorder_items/
86 /rest/v1/project_custom_field/
80 /rest/v1/project/*/step_10/
71 /rest/v1/project/*/import_results/
42 /rest/v1/project/*/delete_photo/
39 /rest/v1/iati_export/
28 /rest/v1/
28 /rest/docs/trackback/
22 /rest/v1/indicator_period_data_comment/
13 /rest/v1/indicator_period_data/*/upload_file/
8 /rest/v1/indicator_period_framework/
6 /rest/v1/recipient_country/
5 /rest/v1/project/*/default_periods/
5 /rest/v1/project_map_location/
3 /rest/v1/iati_check/
3 /rest/v1/publishing_status/*/
3 /rest/v1/results_framework/
3 /rest/v1/project/*/
1 /rest/v1/invoice/
1 /rest/v1/budget_item_label/*/
1 /rest/v1/*/login/
1 /rest/v1/project_update/*/
1 /rest/v1/project_update/*/upload_photo/
```
The number is how many calls to that endpoint was made.

**Comment by zzgvh** [comment]
Sorted by path:
```
***** List of /api/... calls *****
    72 /api/*/store/
   274 /api/v1/iati_activity/
     3 /api/v1/project_update/
     2 /api/v1/project_update_extra/
     1 /api/v1/right_now_in_akvo/

***** List of /rest/... calls *****
    28 /rest/docs/trackback/
    28 /rest/v1/
     1 /rest/v1/*/login/
     1 /rest/v1/budget_item_label/*/
   701 /rest/v1/employment/*/approve/
   354 /rest/v1/employment/*/set_group/*/
  1179 /rest/v1/goal/
     3 /rest/v1/iati_check/
    39 /rest/v1/iati_export/
    13 /rest/v1/indicator_period_data/*/upload_file/
    22 /rest/v1/indicator_period_data_comment/
   454 /rest/v1/indicator_period_data_framework/
     8 /rest/v1/indicator_period_framework/
   980 /rest/v1/internal_organisation_id/
   517 /rest/v1/invite_user/
     1 /rest/v1/invoice/
   403 /rest/v1/organisation/
   233 /rest/v1/organisation/*/add_logo/
   195 /rest/v1/organisation_location/
  1902 /rest/v1/partnership/
  1163 /rest/v1/project/
     3 /rest/v1/project/*/
   654 /rest/v1/project/*/add_validation/*/
     5 /rest/v1/project/*/default_periods/
    42 /rest/v1/project/*/delete_photo/
    71 /rest/v1/project/*/import_results/
   423 /rest/v1/project/*/log_project_addition/
 10323 /rest/v1/project/*/project_editor/
   102 /rest/v1/project/*/reorder_items/
  2135 /rest/v1/project/*/step_1/
    80 /rest/v1/project/*/step_10/
   210 /rest/v1/project/*/step_2/
  1050 /rest/v1/project/*/step_3/
   472 /rest/v1/project/*/step_4/
  1512 /rest/v1/project/*/step_5/
  1027 /rest/v1/project/*/step_6/
   890 /rest/v1/project/*/step_7/
   330 /rest/v1/project/*/step_8/
   242 /rest/v1/project/*/step_9/
   506 /rest/v1/project/*/upload_file/
    86 /rest/v1/project_custom_field/
   471 /rest/v1/project_location/
     5 /rest/v1/project_map_location/
  3820 /rest/v1/project_update/
     1 /rest/v1/project_update/*/
     1 /rest/v1/project_update/*/upload_photo/
     3 /rest/v1/publishing_status/*/
     6 /rest/v1/recipient_country/
     3 /rest/v1/results_framework/
   349 /rest/v1/user/*/change_password/
  1196 /rest/v1/user/*/request_organisation/
  1221 /rest/v1/user/*/update_details/
```

**Comment by Geerts** [comment]
If I want to delete one of my own roles I get a 403 forbidden. 

Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
rsr-my-user-management.min.js:1 undefined "error" "FORBIDDEN"

**Comment by Geerts** [comment]
As a user in RSR with only the "M&E" role I am able to edit a project when I'm in the My results tab.

**Comment by Geerts** [comment]
Creating an indictor update results in: 

POST http://rsr.test.akvo.org/rest/v1/indicator_period_data_framework/?format=json 500 (INTERNAL SERVER ERROR)
c @ my-results.min.js:1
addNewUpdate @ my-results.min.js:5
addNewUpdate @ my-results.min.js:3
r @ react-0.14.7.min.js:14
i @ react-0.14.7.min.js:12
u @ react-0.14.7.min.js:12
p @ react-0.14.7.min.js:12
f @ react-0.14.7.min.js:12
r @ react-0.14.7.min.js:15
processEventQueue @ react-0.14.7.min.js:12
r @ react-0.14.7.min.js:14
handleTopLevel @ react-0.14.7.min.js:14
i @ react-0.14.7.min.js:14
a @ react-0.14.7.min.js:14
perform @ react-0.14.7.min.js:15
batchedUpdates @ react-0.14.7.min.js:14
a @ react-0.14.7.min.js:15
dispatchEvent @ react-0.14.7.min.js:14
VM1943:2 Uncaught SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.u.onreadystatechange (my-results.min.js:1)

**Comment by Geerts** [comment]
Logged in as "M&E manager" I shouldn't be able to access my projects and my iati. This results in 403's.

**Comment by Geerts** [comment]
As an M&E manager for SNV I requested access to Akvo. Without this request being approved I was able to see the projects of Akvo in myreports. Eventually this leads to a 403 which we could avoid.

**Comment by Geerts** [comment]
Myreports, location in the report stays empty. It is still using countryname, I think it should be recipient country in the future.

**Comment by punchagan** [comment]
@mato74 reported an issue with [IATI view file](https://rsrsupport.reamaze.com/admin/conversations/iati-view-file-issue).  The bug occurs because some paths that were relative with old DRF, are now absolute.
