### ISSUE TITLE
Revision History on RSR Data

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#232]
- As a member of the public I need to
	- See previous versions of public information
	- Have changes highlighted in a UI
	- See who saved the revision
	- See when the revision was saved
	- See clearly on a public record how many revisions there are
	- View any public explanation given for the revision
- As a generator/revisor of public content on RSR I need to
	- Check content easily before publishing
	- Edit my own content
	- Provide a public reason for any change
	- Provide an internal comment about any change
	- Be notified about any changes made to my content
- As a project administrator I need to
	- Set revision availability on project/update content
	- Be notified to changes made on project/update content
- As a partner administrator I need to
	- View analytics on revisions
- As an Akvo server I need to
	- Not fall over when the database fills up with all that metadata (Hint for DevOps crew: @osgl @carlio @nehafish )

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#161
