### ISSUE TITLE
Creating a project can take a while

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2337]
It can take more than 10s before a project is created (on the 'My projects' page). There is no loading icon or status shown, so therefore the user also does not get any feedback of the progress.

**Comment by nadiagorchakova** [comment]
As discussed at the backlog refinement session, we split this issue into two:

- investigate performance issue (could it be related to https://github.com/akvo/akvo-rsr/issues/2184 ?)
- create an icon with loading status  (https://github.com/akvo/akvo-rsr/issues/2388)

**Comment by punchagan** [comment]
![rsr-project-creation-timeline](https://cloud.githubusercontent.com/assets/315678/20624140/28caf8ce-b331-11e6-8376-03aa0969594a.jpg)

Looks like 3 or 4 queries are made:
- creation of project
- creation of partnership
- creation of a log entry for project creation
- **opening the project editor** (after a redirect) [ takes the longest time ]

**Comment by punchagan** [comment]
Looks like a bulk of time is spent in figuring out [whether a rule](https://github.com/akvo/akvo-rsr/blob/2d4fb36f5add5f5580775ca6b7ae765c47551e3d/akvo/templates/myrsr/project_editor/section_1.html#L23) is [present in validation sets](https://github.com/akvo/akvo-rsr/blob/2d4fb36f5add5f5580775ca6b7ae765c47551e3d/akvo/rsr/templatetags/project_editor.py#L215) or not.

**Comment by AkvoAnt** [comment]
Improved through various performance improvements since issue was created.

**Comment by punchagan** [comment]
We create projects differently now, and a few things have been moved from the front-end to the backend. Closing as stale issue. Please create a new issue if there are specific problems, still.
