### ISSUE TITLE
Show all user information in one row (estimate: 6)

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2340]
On the user management page, we should:
- [ ] Show all user information (all employments, etc) in one row;
- [ ] Also show users without an employment;
- [ ] Easily select multiple roles for one user.

The current implementation shows one employment per row, and therefore the users without an employment will not be shown.

**Comment by nadiagorchakova** [comment]
Agreed at the planning poker session today that we go with the most straightforward solution for this iteration. We sort by the user name (and possibly also the organisation). The bug with "ghost" users with no employment should be dealt with as well. The estimate for both actions is 6.

**Comment by punchagan** [comment]
There are whole bunch (5-6x of users with at least one employment) of users with spammy email ids with no employments in the database currently.  Showing them in the user management interface would make the interface pretty useless.  

Given that users can be invited from the user management page, I vote for this being the standard way to add users and to get rid of the "Register" button on the site.  The new user creation form is being spammed.

**Comment by nadiagorchakova** [comment]
Agreed with @punchagan that sorting by username would complicate user experience for partners as they might want to see new users first for user management purposes. So we don't make any changes there.

Following our discussion on bot users in RSR database - I created a new issue https://github.com/akvo/akvo-rsr/issues/2454 about adding a captcha to the registration page. 

Also we need to check if we have any mechanism for deleting new users if they haven't activated their account in a certain timeframe. If we don't have that - that might become a new github issue too.
