### ISSUE TITLE
Copy update text to actual value comment field

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#2342]
When placing an update in the results framework, the text of the (latest) update should be copied to the ```actual_comment``` field of the indicator period.

**Comment by nadiagorchakova** [comment]
A bit of context:

Currently, the IATI field 'Actual Value comment' (actual_comment) is not available for input through My RSR - My results. Instead, there is a field 'Value Description' there. If a user inputs comment for a chosen indicator value in 'Value Description', it does not update actual_comment. Since these two fields have similar purpose, user input in 'Value Description' should be defaulted in 'Actual Value comment' (actual_comment). This way, it can be further used in IATI reporting.

**Comment by nadiagorchakova** [comment]
Hi @punchagan , I'll try to answer your questions:

**Question:** The requirement states that the text of the latest update should be copied to the actual_comment field of the indicator period.   
1) Not sure if copy here means, an overwrite of the older text or an append to the existing text.

**Answer:** There will be no text in the actual_comment before copying as it was not made available for user input through My RSR - My results. So actual_comment should be defaulted from 'Value Description' field in My Results

**Question:** Results can have child results, and Indicators for these results therefore have corresponding children.  Parent Indicator values can get aggregated from child Indicator values.  But, this doesn't happen with comments.  So, I presume this behavior shouldn't change and the actual_comment of only the Indicator Period should get updated without any changes to any of its parents.

**Answer:** Yes, you're right. Only the actual_comment of the corresponding Indicator Period should get updated.

**Comment by punchagan** [comment]
> Question: The requirement states that the text of the latest update should be copied to the actual_comment field of the indicator period. Not sure if copy here means, an overwrite of the older text or an append to the existing text.
> 
> Answer: There will be no text in the actual_comment before copying as it was not made available for user input through My RSR - My results. So actual_comment should be defaulted from 'Value Description' field in My Results

Once the functionality of copying the text from an update to the Indicator Period is added, there will be text in the `actual_comment` field of the Indicator Period.  (Even before, text could be added when the Indicator Period was created from the Project Editor). 
![mon sep 12 16 43 26 ist 2016](https://cloud.githubusercontent.com/assets/315678/18433984/2764ecf0-7908-11e6-9ecb-1fd9c896db38.jpg)

Once the update (with the text `More Amazing things happened`) is approved, should the original text `Something amazing happened` be appended to or overwritten?

**Comment by nadiagorchakova** [comment]
Our original assumption was that project officers would add one update per period (hence only one actual comment). But since there is a technical possibility to add multiple updates per period, let's agree that we append them.
