### ISSUE TITLE
RSR Test URLs in reports from RSR Live

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2348]
That's how you can reproduce the bug:
- In Live RSR go to My RSR, then to My Reports tab
- Select 'Data Quality Overview' from the dropdown and pick an organisation (I spotted the issue in Wash Alliance International report)
- In the generated report go to section 'Projects than need funding'. You will see that 'Project URL' column shows RSR Test URLs. It should show RSR Live URLs instead.

**Comment by stellanl** [comment]
File is uploaded to the live ReportServer.

**Comment by stellanl** [comment]
Can this be closed? It works for me, and there have been no comments for 2 months now.
