### ISSUE TITLE
Postgres key constraint violation

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2354]
A few times we've seen errors like [this](http://sentry.support.akvo-ops.org/rsr/live/group/975/) on live. According to Kasper we had more of them on UAT and Test for a time. See the [handover document for more info](https://docs.google.com/document/d/1fxxNc9J68gFsyBUvQ1iRBZ7mDfOzIYL8j2NAgZpcVPA/edit#heading=h.uk8hd0sx0shw).

As the root cause of this is unknown (and I think Kasper tried to figure it out) but we have a fix if it becomes a more regular problem, I suggest we leave this in the backlog for now.

**Comment by zzgvh** [comment]
Hmm, [this](http://dba.stackexchange.com/a/78027) might be a clue to the problem...

**Comment by punchagan** [comment]
This error seems to have been resolved - couldn't find any instances of this in the error logs on Live.
