### ISSUE TITLE
Arrows overlap in Project Hierarchy (investigate)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2366]
When Project Hierarchy is viewed from a child project page - arrows appear a bit messed up.
See http://rsr.akvo.org/en/project/4398/hierarchy/

![screen shot 2016-09-16 at 14 15 17](https://cloud.githubusercontent.com/assets/21127166/18585597/2c92a3d0-7c18-11e6-89e8-425afecde491.png)

**Comment by nadiagorchakova** [comment]
- [ ] investigation is required

**Comment by punchagan** [comment]
We have #2392 merged as a stop-gap fix for this.  What do we do with this issue?

**Comment by nadiagorchakova** [comment]
The code with some small changes to arrows view was already deployed as part of the previous release. No need to investigate it further for now.
