### ISSUE TITLE
Prevent duplicate employments to same organisation (estimate: 6)

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2374]
Do this search: http://rsr.akvo.org/en/admin/rsr/employment/?o=2&q=WaterNet and sort on the User column. We see that Jean-Marie is employed twice. That should not be allowed.

![screenshot_132](https://cloud.githubusercontent.com/assets/142613/18669760/d9bce404-7f3c-11e6-8eb5-a0151c5d18d6.png)

**Comment by punchagan** [comment]
The `Employment` model already has a uniqueness constraint `unique_together = ('organisation', 'user', 'group')`.  So, I'm not sure this is really a bug.  The admin interface isn't showing the Group of the user and this is a UX bug, definitely.

**Comment by zzgvh** [comment]
Yep that's a UI/UX bug, good catch. But I think there was an original problem that was solved by removing the "duplicate" employment, meaning that the user was in two groups. So it could be we have a problem when a user is in multiple groups. I don't recall what the original issue was, do you @nadiagorchakova ?

**Comment by nadiagorchakova** [comment]
@zzgvh @punchagan, as far as I remember, the original problem was with the Up app, here: https://github.com/akvo/akvo-rsr/issues/2364. That's where the entire discussion about multiple employments started, I think

**Comment by nadiagorchakova** [comment]
And could this issue be relevant to the discussion? https://github.com/akvo/akvo-rsr/issues/2122. It was created way earlier but seems to address the same problem of multiple/duplicate employments

**Comment by punchagan** [comment]
@nadiagorchakova thank you! @zzgvh #2122 does seem like the bug that is triggering this, or atleast one issue.  We could either have an `Unassigned` group as you mentioned in the other issue, or we could just make `Users` be the default group.  Any changes to the group can be made during approval?

**Comment by zzgvh** [comment]
I think we have to have a Unapproved group or similar, since we otherwise approve a user implicitly by assigning them to the Users group.

**Comment by punchagan** [comment]
@zzgvh Doesn't look like it.  As far as I could see, `Employment`s have an `is_approved` flag, and approving is just flipping that flag.
