### ISSUE TITLE
Indicator description - breaks in text not shown

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2379]
Indicator description field is populated through Project Editor.
When filling in this field, a partner often includes breaks in the text. Like that:
![indicator descr 1](https://cloud.githubusercontent.com/assets/21127166/18718113/9325a706-8022-11e6-9fcb-2b3f53eb4179.png)

The content of this field appears without breaks however, when viewed via the Results tab:

![indicator descr 2](https://cloud.githubusercontent.com/assets/21127166/18718156/b4f92434-8022-11e6-99c2-419f5e642520.png)

The partnerships team has requested to look into that.

**Comment by zzgvh** [comment]
Looks like we're not converting those fields to markdown. Should we do a full investigation of this, meaning look at all text fields and determine where markdown is appropriate? (It may be that markdown conversion is already the default and I just don't know it, and this is a bug...)

**Comment by nadiagorchakova** [comment]
Yes, we should check for markdown conversion in text fields. Please note that the incident has low priority for now...
