### ISSUE TITLE
Legacy API user organisation may be unapproved (estimate: 3)

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#2381]
#2364 fixed the problem where Up version 1.5 shows random organisations for Update authors. However, the org id supplied may be for an organisation for which the user is not (yet) approved, which is potentially confusing. It would be be better if the legacy org was chosen only from those approved.

**Comment by zzgvh** [comment]
Do newer versions of up try to figure out the "correct" organisation, i.e. an org the user is employed by that is actually a partner of the project the update is made for? I see this isn't relevant for old version of Up, but if we fix this we might as well look at the whole of this issue.

**Comment by punchagan** [comment]
The latest app does seem to behave correctly w.r.t what projects are shown to a user -- projects from unapproved organisations don't seem to be shown. I tested this on the app, but @stellanl, please correct me if I'm wrong

**Comment by stellanl** [comment]
Which organisations are shown in the app list depends only on the list that is returned as "published_projects" from /auth/token
