### ISSUE TITLE
Upgrade to Django 1.11 (estimate: 64)

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2384]
We should upgrade all the way to Django 1.10 when we do it, unless there is a blocker of some kind, most likely a dependency that doesn't support 1.10.

See #2297 and #2186 for previous work.

**Comment by iperdomo** [comment]
We should aim for Django 1.11 (LTS) that has support until April 2020.

https://www.djangoproject.com/download/#supported-versions

**Comment by punchagan** [comment]
Merged to develop.
