### ISSUE TITLE
Report server upgrade

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2386]
Report server upgrade (v3)
Some functions are not being handled well at the moment, e.g. custom fonts

**Comment by stellanl** [comment]
I have run an OOB V3 server for some time beside the test server. No problems so far.
Upgrade plan:
1. Clone the test DB and V2 test server.
2. Upgrade the clone to V3.
3. Once the upgraded server works ok, swap it in as the test server (rename old test server to /reportserver2 ), and let others test.
4. If no issues, do the same for live server.

**Comment by stellanl** [comment]
So far no attempt to upgrade an old database have worked. I created a clean 3.0.2 server and started to transfer the reports manually.

**Comment by stellanl** [comment]
The 3.0.2 server seems to be working, and was swapped in as the primary test server. The nginx rewrite rules had to be changed, and the Puppet module for RSR was modified to include this.

**Comment by stellanl** [comment]
Next step to a live RS3 server is to make Puppet create the (local) Postgres 9.4 database.
Peeking at the Unilog module, this can be done in config.pp
    database::psql::db { $appname:
        psql_name  => $postgres_name,
        password   => $database_password
    }
...in params.pp:
    $base_domain         = hiera('base_domain')
    $main_domain         = hiera('unilog_main_domain', "unilog.${base_domain}")
    $postgres_name       = hiera('psql_name')
    $postgres_host       = "${postgres_name}.${base_domain}"
    $postgres_port       = hiera('psql_port', '5432')
    $postgres_clients    = hiera_hash('unilog_psql_clients')
    $database_password   = hiera('unilog_database_password')

and in akvo-config a host config file has 
    "psql_version": "9.4",
    "psql_name": "psql-unilog",
    "psql_backup_password": "?????",

See issue akvo/akvo-config#334

**Comment by stellanl** [comment]
Deployed V3 server to live, and copied database from the test server.
Next step is installing some custom fonts.

**Comment by stellanl** [comment]
Brandon fonts now installed on live server
