### ISSUE TITLE
'NULL' in the last update column (akvoapp page)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2401]
Project 'Akvo PPP Phase 3 2014-2017' on [this](http://iggwater.akvoapp.org/en/projects/) website shows zero updates, whereas it has a number of updates linked to it. 

Lynn investigated the issue and it looks like all the projects shown under 'IGG' are showing 'NULL' in the last update column in the table 'rsr_project'. Only 'Akvo PPP Phase 3 2014-2017' project has updates so far and that's how the bug was detected.

<img width="1237" alt="screen shot 2016-10-10 at 10 35 31" src="https://cloud.githubusercontent.com/assets/21127166/19232510/6ad03b46-8ee0-11e6-8f21-31c13824a730.png">

**Comment by zzgvh** [comment]
This is part of 3.17
