### ISSUE TITLE
Standardize on one country codelist

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2405]
We currently have two lists of countries: [ISO_3166_COUNTRIES](https://github.com/akvo/akvo-rsr/blob/806930ac46b02f033c8c83d711334adc2dc41145/akvo/rsr/iso3166.py#L9) that is a hand crafted list based on the ISO 3166-1 alpha-2 list, and [COUNTRY](https://github.com/akvo/akvo-rsr/blob/806930ac46b02f033c8c83d711334adc2dc41145/akvo/codelists/store/codelists_v202.py#L89) that is part of the IATI codelists.

We should only use one codelist and I suggest standardizing on the IATI codelist.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/enhancement-geolocation-question-type
