### ISSUE TITLE
Faulty link in account activation email

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2406]
A new user reported a faulty link in RSR account activation email. 
User email: e.nartey@cgiar.org
Organisation: http://gnwp.akvoapp.org/en/projects/

Here are the screenshots user provided:
![screen shot 2016-10-14 at 14 04 14](https://cloud.githubusercontent.com/assets/21127166/19386898/374753f6-9217-11e6-8588-c98e66bfa08b.png)
![screen shot 2016-10-14 at 14 04 39](https://cloud.githubusercontent.com/assets/21127166/19386899/3b6da962-9217-11e6-9a56-674d60671be0.png)

**Comment by nadiagorchakova** [comment]
@Lynngre is it an akvo sites issue?

**Comment by Lynngre** [comment]
@nadiagorchakova it's not related to Akvo Sites. They're trying to access RSR via an Akvoapp page (Akvo Pages) which is actually just a cname for rsr.akvo.org.

If I remember correctly the links do timeout.  From the screenshots it looks like there were quite a few hours between receiving the mail & activating the link?

I tried registering & it worked ok for me immediately after receiving the mail.

**Comment by punchagan** [comment]
If expiry is the reason, we should probably have a note in the email itself about it.  Also, the error message could mention that may be?

**Comment by punchagan** [comment]
Closing super old issue since no more reports of this in the recent past.
