### ISSUE TITLE
Image shows dark background if not in JPG format

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2407]
When partners upload project pictures in .png format, the image appears with distorted colours on the project site.

The image appears normal in Project Editor:

<img width="1162" alt="screen shot 2016-10-14 at 15 54 47" src="https://cloud.githubusercontent.com/assets/21127166/19390016/940af138-9226-11e6-871a-efe44b4711ed.png">

On the front end the colours are completely off:

<img width="1079" alt="screen shot 2016-10-14 at 15 55 50" src="https://cloud.githubusercontent.com/assets/21127166/19390056/c1390c8a-9226-11e6-81d6-36cddc180596.png">

To be fair, the help text to this field does say that the image should preferably be in JPG format, but I bet none reads that.

**Comment by punchagan** [comment]
The image on the project page is actually a .jpg. http://rsr.akvo.org/en/project/5082/
Does some conversion happen somewhere that is broken?
