### ISSUE TITLE
Employment confirmation email should mention Up (estimate: 2)

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#2415]
Now that a user can apply for a connection/employment from the Up app, the email that is sent out when it is confirmed should mention that alternative, and could also mention that the user needs to log out and in again to see the new connection(s).

**Comment by punchagan** [comment]
@nadiagorchakova  all the email text is here: https://github.com/akvo/akvo-rsr/tree/develop/akvo/templates/registration 
approved_request_email_message.txt is something that definitely needs to change, not sure if there are other emails that could change too.

**Comment by nadiagorchakova** [comment]
thanks @punchagan for the link. not sure if approved_request_email_message.txt needs to change though. isn't it an email sent out after the user has been successfully linked to an organisation? the way I saw it is that activation_email.txt needs to be reworked. but let's discuss.

**Comment by nadiagorchakova** [comment]
Coordinating changed text with Comms is taking longer than expected.

My proposed text for activation_email.txt:

"Someone, hopefully you, signed up for a new account at rsr.test.akvo.org using this email address. If it was you, and you'd like to activate and use your account, click the link below or copy and paste it into your web browser's address bar:

(link)

Note: After you have activated your account, we will review your application and possibly contact you to ensure that the account was created correctly, before the account is enabled. **When you are ready to connect with your organisation, you can do so via RSR website or RSR mobile application, which you can download from Google Play Store**.

If you didn't request this, you don't need to do anything and you won't receive any more email from us."
