### ISSUE TITLE
Incorrect number of countries in RSR report 'Projects overview' (estimate: 8)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2416]
A new partner organisation [Netherlands Space Office](http://rsr.akvo.org/en/organisation/3802/) has 41 countries listed in the RSR report 'Projects Overview', section 'Published project statistics by country'. However, they have only one project set up in RSR so far. 

Steps to reproduce:
- Go to My RSR - My reports
- Select report 'Projects Overview', organisation 'Netherlands space office', and generate a report

**Comment by punchagan** [comment]
The organisation page only shows published projects, while the report also includes projects which haven't been published yet.  Hence, the discrepancy.  Not sure if that is expected, or if the report needs any modifications to indicate the fact that projects are unpublished.

**Comment by punchagan** [comment]
Oh, I take that back. The statistics section actually indicates the number of published and unpublished projects.  More visual cues to indicate this may help?

**Comment by stellanl** [comment]
Ok, the country counts was a simple case of missing parameter - we always showed counts for Akvo org...
There is also something wrong with projects-by-start-year counts.

**Comment by stellanl** [comment]
Same problem fixed for budget table, too

**Comment by stellanl** [comment]
Deployed to the test reportserver and tested

**Comment by punchagan** [comment]
Closed with #2438
