### ISSUE TITLE
RSR user management in French

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2421]
When a user changes to French interface, the User Management screen just says 'Gestion des utilisateurs'. It does not load the actual list of users. 
The search field doesn't seem to work either in the French version.
If some translations for this page are missing, we should use Google Translate for now.

<img width="1234" alt="screen shot 2016-10-24 at 17 42 21" src="https://cloud.githubusercontent.com/assets/21127166/19652495/43fd65a2-9a11-11e6-93a2-d7cdc91501d0.png">

**Comment by nadiagorchakova** [comment]
Annabelle will be doing a training on 8-10 of November with the French version of RSR, so would be great to have it fixed until then...

**Comment by punchagan** [comment]
The issue is with translations strings with line-breaks in them not being handled correctly.  

If any translations are missing, the default is to show English strings for them. It won't break the site.

**Comment by punchagan** [comment]
[3.18 Vilnius](https://github.com/akvo/akvo-rsr/milestone/80) is scheduled to be released on Nov. 10. So, we should probably do a hot-fix release for this.

**Comment by nadiagorchakova** [comment]
yes, a hot fix would be best.
