### ISSUE TITLE
Data quality reports counts are wrong

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#2434]
For the same db query reasons as in #2416 
The joins with rsr_partnership produces extra lines when the project has more than one relationship with the same org.
An EXISTS () subselect in the WHERE clause is a better way to pick projects that the org is involved in:
exists ( select 1 from rsr_partnership where rsr_project.id = rsr_partnership.project_id
and rsr_partnership.organisation_id = ?)

**Comment by stellanl** [comment]
Test plan:
 * Run report from test server
 * Check that first count matches first table (count at end of first table is not the same, project in more than one sountry are listed multiple time).
 * Check that title of first table says "date", not "data"

**Comment by punchagan** [comment]
Closed with #2436
