### ISSUE TITLE
Aggregation of result values in % in My Results (estimate: 16)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2446]
M&E Managers would like to see 'raw data' behind result values in %, namely,  numerator and denominator. This would help them to draw conclusions from results data. For instance, without knowing the sample size (denominator), the % value is fairly abstract. 

- "raw data" - numerator and denominator should be displayed in brackets next to the % in the Actual value field, e.g. 15% (15/100)
- for a parent project, the value in brackets should show how all numerators and denominators from each child project sum up, e.g. 30% (15+15)/(50+50). Denominators, or in other words, the size of a target community, can vary per child project. That's why it's important for M&E managers to see the actual numbers behind % points.
- a denominator for individual project can change over the duration of the project. For instance the community of HIV patients has increased/decreased over 1 year. Therefore, the system should recalculate the actual % value every time an update is added.

Here are the mockup screens that Loïc created (approved by Henry and Ethel) - based on the old RSR Results design:

![01](https://cloud.githubusercontent.com/assets/21127166/20344171/f2f72696-abf1-11e6-8b23-e1c574d419f8.jpg)
![02](https://cloud.githubusercontent.com/assets/21127166/20344168/f2ee8d7e-abf1-11e6-8153-88c4b0bedeeb.jpg)
![03](https://cloud.githubusercontent.com/assets/21127166/20344169/f2f00d8e-abf1-11e6-81dd-894599ec4dcc.jpg)
![breakdown_2](https://cloud.githubusercontent.com/assets/21127166/20344170/f2f2397e-abf1-11e6-91bc-ee108d42e6e6.jpg)

For more background information see https://github.com/akvo/akvo-product-design/issues/187

**Comment by nadiagorchakova** [comment]
Was talking to Annabelle today and she provided some additional feedback:

Limiting the user to just numerator and denominator at the results update screen might not work for all the partners. Some partners who work in compliance-related projects (KYC, for example) need just a percentage value, e.g. 25%. They do not need a numerator and denominator. 

It should be considered then, if on the update screen, users should have a choice to input either a simple % or numerator & denominator.

**Comment by nadiagorchakova** [comment]
Had a call with Gabriel and Puneeth and, based on partner team feedback, agreed on the following:

- keep the 'simple' % Indicator measure, since some partners still prefer to use % value in a fairly abstract level (without inputing numerator and denominator)

- add a new Indicator measure in the Project Editor called 'Calculated percentage'. When user selects this measure, numerator and denominator will be mandatory for input during indicator update (see mockup screens above). The indicator measure currently called 'Percentage' should be renamed into 'Simple percentage' to differentiate between these two options better. Right now the dropdown for Indicator Measure looks like this:

<img width="1077" alt="screen shot 2016-11-21 at 11 56 46" src="https://cloud.githubusercontent.com/assets/21127166/20480352/61d356e0-afe2-11e6-8d57-dd3eb59f23d9.png">

- the logic behind aggregation at the parent level will only change for indicators where 'calculated percentage' was selected. It will show how all numerators and denominators from each child project sum up, e.g. 30% (15+15)/(50+50). If 'simple percentage' indicator value was selected, the aggregation will take the average from % in all child projects, as it does now.

- Migration. We assume that all percentage measures which were input until that point were 'simple percentage' and do not change them. However, we need to check which projects currently have % values in 'Actual value' for Indicator and notify those partners about the upcoming changes. @zzgvh could you generate a list of such projects in RSR?

@stellanl please review the above with regard to RSR Up app.

**Comment by stellanl** [comment]
The app currently does not distinguish between different kinds of indicators. It is all "data". It will need to start parsing that from the API and of course display and submit two values for the calculated percentages.

**Comment by AkvoAnt** [comment]
Introducing ‘calculated percentages’: 

- For existing partners using the Results Framework and that have indicators with simple percentage calculations – they will remain the same until the completion of the project, although with the new UI design.

- Partners creating a new Results Framework, and using percentage indicators, will use ‘calculated percentages’ as the default. 

- For both cases – the work flow is done in the backend, i.e. the User is not making a selection of either ‘simple percentages’ or ‘calculated percentages’. Instead, if the Results Framework belongs to a project already in implementation (i.e. before introducing ‘calculated percentages), then it continues seamlessly with ‘simple percentage’ calculations; **although in the new UI.** 

For new Results Frameworks (i.e. once ‘calculated percentages’ is released), indicators for which ‘Percentage’ is selected in the ‘Indicator Measure’ field will automatically use the new ‘calculated percentages’, i.e. they will need to provide a numerator and dominator when submitting an indicator reporting value. 

- This requires that the UI design accommodates both ‘states’ in the Results Framework:
1) the current ‘simple percentage’ view in the new UI
2) the new ‘calculated percentage’ view in the new UI

**Comment by punchagan** [comment]
Closed with #2791
