### ISSUE TITLE
Change layout of RSR Results (estimate: 16)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2447]
### Outstanding items to be fixed for first release of the new Results interface

- [ ] Decide if indicator update comments are needed. Comments are implemented but not the updating of them
- [ ] Implement notifications
- [ ] Implement error handling fully, particularly for backend calls, this overlaps soome with notifications
- [ ] Implement permissions
- [ ] Only allow editing of unlocked periods (part of permissions)
- [ ] Include missing data on some levels

**Comment by stellanl** [comment]
I think the accordion is the musical instrument that expands and compresses.

**Comment by nadiagorchakova** [comment]
Partnership team wanted to make sure that the overview includes all the fields that are visible in the framework right now, for instance, indicator description:

<img width="1190" alt="screen shot 2016-11-18 at 11 24 02" src="https://cloud.githubusercontent.com/assets/21127166/20426971/ecec8188-ad81-11e6-86a5-357ea314f3ce.png">

This way, M&E managers will not miss any crucial information regarding their results.

**Comment by punchagan** [comment]
@zzgvh Can this issue be closed? Or do we close after BETA is released? Or after we are out of BETA?

**Comment by punchagan** [comment]
Work for this has been done and we have decided to close this issue.  We create a new issue to bring the new results framework out of beta.
