### ISSUE TITLE
RAIN IATI import creates new organisations even when they exist

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2448]
The RAIN IATI import that is run weekly in some cases creates new organisations in RSR even if they already exist. Example: the project [Appui à l'amélioration des conditions de vie](http://rsr.akvo.org/en/project/4384/) has the partner [CAEB](http://rsr.akvo.org/en/organisation/632/), but the import has created a linked to this [new instance of the same organisation](http://rsr.akvo.org/en/organisation/3795/).

**Comment by zzgvh** [comment]
After some investigation this is what I've found. 

The functionality to identify RAIN projects via the ```participating-org@akvo:ref``` attribute was removed [here](https://github.com/akvo/akvo-rsr/pull/2284/commits/8617d3cdc1766758dbd8f5580a0241c42625febd#diff-67b5a57223acb39ba3a2e3ef1fb67a36) (part of [this PR](https://github.com/akvo/akvo-rsr/pull/2284)). And it looks like importing projects using the [current general IATI import method](http://rsr.akvo.org/en/admin/rsr/iatiimport/15/) started to be used [a couple of weeks before](http://rsr.akvo.org/en/admin/rsr/iatiimportjob/10/) this change, so presumably everyone was on-board with the change.

Regardless, there is a workaround. The best way of identifying organisations is to use and IATI org ID. It needs to be filled in for the org in the RSR admin and then used in the ```participating-org@ref``` attribute of the IATI XML. Failing this the import identifies organisations using the __name__ and __long_name__ fields. One of these has to match exactly. The problem with the example above is that the [org's name __and__ long_name are both _CAEB_](http://rsr.akvo.org/en/admin/rsr/organisation/632/) and the value of ```participating-org/narrative``` in the IATI XML is _CAEB Conseils et Appui pour l'Education à la Base_. So this can be fixed by either setting the long name to _CAEB Conseils et Appui pour l'Education à la Base_ in the RSR admin or the narrative value of the participating-org to _CAEB_ in the IATI XML.

**Comment by nadiagorchakova** [comment]
As I understood from Gabriel and Annabelle, Annabelle will fill in the Long Name field for RAIN projects in RSR admin. This will prevent new organisations being created during the next IATI import.

**Comment by zzgvh** [comment]
Closing this as it is a data input problem resolved by submitting data that correctly identifies RSR organisations.
