### ISSUE TITLE
Make tests run faster on Travis

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2450]
The tests on `Travis` first run the migrations and then call `runserver` to start the server as a background process.  This doesn't really add much confidence in the code, since the reviewer is expected to verify and test the code, anyway.  The tests are actually run without running the time-taking migrations, and not starting the server would save a lot of time each time the tests are run.

**Comment by zzgvh** [comment]
The problem with not running the migrations is that we then have no testing of any new migrations. OTOH even when they're run, it will be on an empty database so any problems with e.g. data migrations data messing things up will not be caught. 

Tricky problem actually, ideally we'd want to have the code for new migrations tested somehow. We should research this to see if there's anyone else out there that's had the same thoughts.

**Comment by punchagan** [comment]
The approach [described here](https://www.caktusgroup.com/blog/2016/02/02/writing-unit-tests-django-migrations/) looks promising for testing migrations.  From the comments section on this page, we also found a package for this: [django migration testcase](https://github.com/plumdog/django_migration_testcase). 

But, this still doesn't work around the fact that running all the migrations takes very long.  "Resetting" our migrations and starting afresh seems like a good idea.

**Comment by punchagan** [comment]
Instead of skipping running migrations on Travis, we could use [stages feature](https://docs.travis-ci.com/user/build-stages) to gain some speedups.
