### ISSUE TITLE
Partial exemption of IATI import, keeping existing data

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2452]
#### Background
RAIN uses the IATI XML import but some of the projects imported are part of the WASH alliance, where results/indicators are input using the Project editor. This results in the data for results/indicators being overwritten each time the RAIN IATI import is run.

To avoid this we need to be able to flag certain parts of the XML so that the IATI import ignores those parts.

#### Suggested solution
To support the use case of RAINs IATI import we should check each "top level" tag of the IATI XML for ```akvo:import="false|f|no|0"```. A top level tag is one of the tags that is an immediate child of the iati-activity tag.

In the case of RAIN all result tags should look like this: ```<result akvo:import="false">```

If _any_ top level tag of a certain kind has the akvo:import="false" attribute _all_ data of that kind should be ignored and any data already present in the system should _remain unchanged_.

The akvo:import attribute is of boolean type, and is considered to be true by default.

**Comment by zzgvh** [comment]
When this change goes in [the wiki](https://github.com/akvo/akvo-rsr/wiki/IATI-Import-mapping) should be fixed.

**Comment by punchagan** [comment]
Closed in #2460
