### ISSUE TITLE
Add honeypot hidden field to RSR Registration page (estimate: 4)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2454]
During implementation of #2340, we noticed that there are a lot of spam bots who used the RSR Register page and ended up in RSR database.

To avoid that in the future, we need to add captcha to the Register page.

**Comment by punchagan** [comment]
[This package](https://github.com/praekelt/django-recaptcha) and [blog post](http://www.yaconiello.com/blog/integrating-google-recaptcha-to-django/) can be useful when we finally get around to implementing this.

**Comment by zzgvh** [comment]
I think we can try with just adding a hidden field to the registration form. If the field contains data we silently delete the registration. This should keep simple registration bots out and is much lighter than a full captcha.

If we implement this we can run it for a month and then evaluate if it's good enough.

**Comment by punchagan** [comment]
What would our evaluation criteria be? Do we know the rate at which we get spam accounts created now? What would be an acceptable rate of spam? :smiley:

**Comment by punchagan** [comment]
Are we also going to delete the existing junk usernames, to see how effective this fix is?  Should we write a management command or a migration script for this?
