### ISSUE TITLE
Results and Indicators Overview report

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2456]
The order of results and indicators in pdf report 'Results and Indicators Overview' is wrong for project 3981 in RSR Live. I'm attaching the copy of the report.

And here's a screenshot:

<img width="936" alt="screen shot 2016-11-23 at 17 33 39" src="https://cloud.githubusercontent.com/assets/21127166/20570215/0c1ceabe-b1a3-11e6-8648-3cbe525a8ecb.png">

In My Results and Project Editor the order is as follows:
1
3
5
6
7
...
In pdf Report the order is different:
1
10
18
19
2
... 

The report should ideally mirror the order of results and indicators in My Results.

[201611231707_Project results and indicators - Project results and indicators.pdf](https://github.com/akvo/akvo-rsr/files/609377/201611231707_Project.results.and.indicators.-.Project.results.and.indicators.pdf)

**Comment by stellanl** [comment]
I see, the report sorts them in lexicographical order, not numerical. Somewhere the numbers are treated as strings.

**Comment by stellanl** [comment]
Apparently there is now an order column in the rsr_result table. Sorting on that looks like the right thing to do.

**Comment by stellanl** [comment]
The database however has no values in the order column.

**Comment by stellanl** [comment]
Ok, the web sort order is order-column followed by is (primary key). No clever special treatment of numbers in string; the author just entered them in order. Duplicating that for the report.

**Comment by stellanl** [comment]
Test plan: run the Results & Indicators report on project 3981.
Results titles should be in numerical order (until someone reorders them manually in MyRSR).

**Comment by punchagan** [comment]
Closed in #2459

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/results-in-the-reports-are-not-the-same-order-as-in-rsr
Assignee: Nadia Gorchakova
