### ISSUE TITLE
Results Type in 'Results and indicators table' report

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2457]
'Results and indicators table' in My Reports has a column 'Results type'.
Right now it shows a number (1, 2, 3, 9) instead of a string (Output, Outcome, Impact, Other). 
The column should show a string as some partners have trouble understanding it.

**Comment by stellanl** [comment]
Template uploaded and tested on the test reportserver

**Comment by stellanl** [comment]
Test plan:
Run a "Results Simple Table" report.
The type column should have no 1s, 2s, 3s or 9s.

**Comment by stellanl** [comment]
I implemented this trough the BIRT "Map" function. It work on all formats on my local computer, and all formats *except* Excel on ReportServer 2 and 3.  I will have to do it in SQL instead.

**Comment by stellanl** [comment]
Deployed to reportserver.test.akvo-ops.org
