### ISSUE TITLE
RSR Report: Projects overview

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2465]
The RSR report: Projects overview has conflicting data in section 'Published project statistics by country'. Looks like this data is coming from some other source.

If we take the example of organisation [AMREF Kenya](http://rsr.akvo.org/en/organisation/94/) (organisation id 94), it has the total of 9 projects, all of them in Kenya. The report, however, shows more projects and related updates (in a variety of countries) that the organisation does not have. 

You can see it in the attachment. 
[201611281550_Organisation project overview - Organisation project overview.pdf](https://github.com/akvo/akvo-rsr/files/616721/201611281550_Organisation.project.overview.-.Organisation.project.overview.pdf)

**Comment by stellanl** [comment]
Apparently the live server has not been deployed with the improved version of that report. It looks much better on the test server.

**Comment by stellanl** [comment]
Now updated on the live server.

**Comment by punchagan** [comment]
Verified that this is fixed on the live server.
