### ISSUE TITLE
'Expand All' feature in RSR Results (estimate: 8)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2467]
As part of new design implementation, we need to implement the 'Expand All' feature. According to our mockups it should look something like that:

Step 1 - click on the four-arrow button at the top:

<img width="1038" alt="screen shot 2016-11-29 at 12 05 07" src="https://cloud.githubusercontent.com/assets/21127166/20707637/7fb47fa4-b62c-11e6-9f4e-f2516d71a292.png">

Step 2 - the harmonica-style list is expanded:

<img width="721" alt="screen shot 2016-11-29 at 12 05 21" src="https://cloud.githubusercontent.com/assets/21127166/20707675/a18c2c44-b62c-11e6-9337-e719351e5e4b.png">

The 'Expand All' feature is an important prerequisite for upcoming 'Bulk actions' feature. Without the possibility to expand all the indicators and indicator periods at once, it will be difficult to check off items to apply a bulk action. 

The full mock-up can be found here:
https://projects.invisionapp.com/share/4N9E8TNG7#/screens/203154725

Related issue in Product & Design rep: akvo/akvo-product-design#220

**Comment by punchagan** [comment]
Done as a part of #2447
