### ISSUE TITLE
"Recently modified projects" table in Organisation Summary report is strange

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-rsr#2472]
In second section - a table titled "Most recently modified projects" - there are results for all organisations, not just the one the report is about. This seems wrong, and Geert thought so, too.
I don't know if this report is actually exposed to any users in My Reports.

**Comment by stellanl** [comment]
Test plan: 
Run a "data quality" report on any organisation.
The recently changed projects table should only contain projects for that org.

**Comment by stellanl** [comment]
Deployed to test server since the commit

**Comment by nadiagorchakova** [comment]
Hi @stellanl, Geert and me tested it and it didn't seem to return correct information. 
So we didn't deploy this fix to live report server today. Please have a look at it.

**Comment by stellanl** [comment]
I just tested it on the test server, and it crashed, so I redeployed it from this branch. It now runs. What information was wrong?
We have to start noting who deploys a report, when and from which branch or we could waste much time on things already done.

**Comment by nadiagorchakova** [comment]
Hi Stellan, 'Most recently modified projects' showed info from unrelated projects. @Geerts ran tests on the test server. I agree, next time we should keep notes on when and from which branch we deploy a report.

**Comment by Geerts** [comment]
Hi Stellan, the project counts were still for all organisation, not this specific organisation. I also hide all empty titled projects from the different queries. Guess we are good to go now.

**Comment by stellanl** [comment]
I deployed organisation_summary.rptdesign from this branch to the test server on Feb 16th. If no one protests I will deploy it to live, too.

**Comment by stellanl** [comment]
The report currently only shows projects where the org is the primary org, but the report should count in the same way it’s done on the org page.
This will require redesign of the db queries to include every project connected through the rsr_partnerships table.

**Comment by stellanl** [comment]
The web org page only counts projects that are published. Should this report also do so? For the lists, too?

**Comment by stellanl** [comment]
Deployed to both test and live servers
