### ISSUE TITLE
Akvoapp pages missing Piwik web analytic ids

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#2486]
When a new akvoapp partner/partner page is added someone needs to request a Piwikid.  This has not been done for a number of akvoapp.org pages.

As per the attached, please update the piwik tracking variable in the RSR database.

[rsr_partnersite_piwik_missing_ids.txt](https://github.com/akvo/akvo-rsr/files/656973/rsr_partnersite_piwik_missing_ids.txt)

In future could RSR prompt the user adding the new akvoapp.org page to request/require a Piwikid?

**Comment by nadiagorchakova** [comment]
The user adding a new akvoapp.org page is always someone from Akvo, right? @Lynngre

**Comment by punchagan** [comment]
Also, from where/how is this done, usually?

**Comment by Lynngre** [comment]
@nadiagorchakova as far as I understand, this is created in the backend by an Akvonaut, yes.

@punchagan previously a developer has uploaded the Piwikid's into the database. The javascript tracking code is inserted into the footer of rsr.akvo.org & loads a variable depending on which akvoapp.org page is loaded (so standard rsr.akvo.org is idsite '1', for example.  

<script type="text/javascript">
  var pkBaseURL = "https://analytics.akvo.org/";
  document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
  try {
    var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
    piwikTracker.trackPageView();
    piwikTracker.enableLinkTracking();
  } catch( err ) {}
</script>
<noscript>
  <p>
    <img src="https://analytics.akvo.org/piwik.php?idsite=1" style="border:0" alt="" />
  </p>
</noscript>




This changes to idsite '44' for example if washalliance.akvoapp.org is loaded:

<script type="text/javascript">
  var pkBaseURL = "https://analytics.akvo.org/";
  document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
  try {
    var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 44);
    piwikTracker.trackPageView();
    piwikTracker.enableLinkTracking();
  } catch( err ) {}
</script>
<noscript>
  <p>
    <img src="https://analytics.akvo.org/piwik.php?idsite=44" style="border:0" alt="" />
  </p>
</noscript>



The relevant idsite needs to be uploaded into the relevant RSR table.  

The Piwik ids are created on analytics.akvo.org when you add a new site to track via the admin.

**Comment by zzgvh** [comment]
Re-opening this since we need a more permanent solution, where a PiWik ID is fetched when a new Pages site is created.

**Comment by Lynngre** [comment]
https://developer.piwik.org/api-reference/reporting-api#SitesManager  may be useful?

**Comment by punchagan** [comment]
For starters, what if we make the field non-nullable in the DB?

**Comment by Lynngre** [comment]
@punchagan I agree that as a start it would be good to ensure it's a required field.

**Comment by punchagan** [comment]
The following sites still seem to be missing piwik ids, after the last fix.

```
afrialliance
akvorsr
simavidemo
unicefpacific
watershed
```

We'll need to add some ids to these, if and when we make the DB field non-nullable.

**Comment by Lynngre** [comment]
afrialliance = 146
akvorsr = 36
simavidemo = ? not sure if we could just give a dummynumber here re it being a demo?
unicefpacific = 147
watershed = 148

**Comment by punchagan** [comment]
Thanks! Yeah, I wonder what would happen if we gave it a 0 or a -1.

**Comment by punchagan** [comment]
Closed with #2499
