### ISSUE TITLE
Create report for Onedrop

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-rsr#2493]

**Comment by stellanl** [comment]
First cut committed (forgot a # in the commit msg).

**Comment by Geerts** [comment]
Please install these fonts on the liveserver after upgrading @stellanl 



[onedrop_fonts.zip](https://github.com/akvo/akvo-rsr/files/738692/onedrop_fonts.zip)

**Comment by Geerts** [comment]
Feedback from onedrop: 

If a result has several indicators, do not repeat the title of the result and organize it the following way: 

Result 1
Indicator 1.A
Indicator 1.B

**Comment by stellanl** [comment]
Transferred to new akvo/akvo-reporting-templates repo.
