### ISSUE TITLE
504s when opening project editor for big projects

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2496]
Large projects with lots of results and indicators seem to be timing out when trying to open the project editor for them. 

Upon investigation, found that there are a bunch of things that are slow, and need to be fixed.  The couple of things with the most performance gains seem to be:

1. Add missing relations from `prefetch_related` in the `project_editor` view.
2. Try to cache the validations, and avoid making a DB query for each field and each `ProjectEditorValidation`.

**Comment by nadiagorchakova** [comment]
please hot fix it when ready. was told that partners are waiting

**Comment by Geerts** [comment]
Kind of this week or we need to find a workaround to acces/edit the projects.

**Comment by punchagan** [comment]
Closed in #2504
