### ISSUE TITLE
Create RSR report for PPP end report

### ISSUE THREAD

**Issue by akvotender** [akvo/akvo-rsr#2500]

**Comment by Geerts** [comment]
Status update. To do:

- Negative targets
- Programme report instead of project report
- Handle qualitative values in the graph. e.g. Available / Not available.

**Comment by Geerts** [comment]
> Handle qualitative values in the graph. e.g. Available / Not available.

Tried to do it like this but it doesn't work. 
```
Finance.percent( row["baseline_value"] ?
  Math.round((row["actual_value_number"]-row["baseline_value"]) * 100 / (row["target_value_number"] - row["baseline_value"]))
 : Math.round(row["actual_value_number"] * 100 / row["target_value_number"])
```

Original:
` Finance.percent(row["target_value_number"],row["actual_value_number"],-1)`

**Comment by Geerts** [comment]
At this moment we do not handle "available" / "not available" in the progress graph. I propose to use 0% and 100% for this. Do you have any idea how we could implement this? @stellanl

**Comment by stellanl** [comment]
It kinda opens a can of worms, when it comes to translating "value" words into numbers.
Other than that, the obvious place is in the results_table, where the binding to the data set calculates a results_pct column. That code could start by trying to compare the value to some string constants, before testing by making it an integer.

(row["actual_value"] == "available" )
?
100
:
(row["actual_value"] == "not available" )
?
0
:
(row["actual_value_number"] > -1 && row["target_value_number"] > -1 )
?
 ( row["baseline_value"] ?
  Math.round((row["actual_value_number"]-row["baseline_value"]) * 100 / (row["target_value_number"] - row["baseline_value"]))
 : Math.round(row["actual_value_number"] * 100 / row["target_value_number"])
 )
 :
null

**Comment by Geerts** [comment]
Works like a charm, just changed the case. Thanks @stellanl

**Comment by stellanl** [comment]
You may want to do it like this to be case-insensitive:
(row["actual_value"].toLowerCase() == "available" )
?
100
etc.
:

**Comment by Geerts** [comment]
@stellanl when you have time could you please add the attached fonts to dev and live server?


[Fonts.zip](https://github.com/akvo/akvo-rsr/files/813520/Fonts.zip)

**Comment by stellanl** [comment]
Added to both servers

**Comment by Geerts** [comment]
@stellanl please let me know when you have pushed the alternating rows and humungous value breaking our report, I would like to finish it off tomorrow.

**Comment by Geerts** [comment]
Completed.
