### ISSUE TITLE
Problems saving Results Framework

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2508]
Created via Reamaze:

Link: https://rsrsupport.reamaze.com/admin/conversations/problems-saving-resultframework
Assignee: Puneeth 

Message:
Hi RSR team,

I’m currently translating the WAI results framework into French, by adding translations to the indicator, result and target descriptions. However, I have trouble saving the pages. I save them every time I’ve translated a result, but of the 4 project pages I’m working on every time at least one fails to save in a normal time frame. While the rest of the pages saves in about 10 secs, the other takes very long - for now I reload the page, which means the information is lost, and I need to do the whole translation again. Often when I redo the translation a second time the problem is solved. It’s about the following pages:

http://rsr.akvo.org/en/myrsr/project_editor/4386/
http://rsr.akvo.org/en/myrsr/project_editor/4385/
http://rsr.akvo.org/en/myrsr/project_editor/4383/
http://rsr.akvo.org/en/myrsr/project_editor/4384/

Cheers,
Annabelle Poelert
Project Officer

Akvo • 's-Gravenhekje 1A • 1011 TG • Amsterdam (NL)
T +31 20 8200 175 • S Annabelle.akvo • T @annabellepoel I www.akvo.org &lt;http://www.akvo.org/&gt;

**Comment by nadiagorchakova** [comment]
Hi @punchagan, do you think your work on https://github.com/akvo/akvo-rsr/issues/2496 will help Annabelle with saving times for her projects?

**Comment by punchagan** [comment]
Yes, one of the fix deployed as a part of #2496 did actually address an issue with saving sections of a project from the project editor.

**Comment by punchagan** [comment]
@nadiagorchakova can you confirm if this issue is fixed and close this?

**Comment by nadiagorchakova** [comment]
Yes, Annabelle confirmed the issue was fixed. Closing..
