### ISSUE TITLE
Add Sentry notifications for Nginx errors

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2525]
See http://stackoverflow.com/a/34887326 for a starting point

**Comment by punchagan** [comment]
Hey @dlebrero, Does Stack Driver also look at nginx logs too? I'm specifically looking for ways to be  notified about 5xx errors - especially timeouts from RSR.

**Comment by dlebrero** [comment]
Do you want to know about each and every 5xx? Or if it is above a threshold?

**Comment by dlebrero** [comment]
We are planning to add that kind of alert at the platform level, but it will take at least a couple of months before we are there.

**Comment by punchagan** [comment]
Cool, I'll close this ancient issue in favor of that, then.
