### ISSUE TITLE
Filter by country in EUTF akvo site (estimate: 16)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2527]
EUTF would like to be able to filter by country using Advanced filters on their akvo site (http://eutf.akvoapp.org).

Currently, the only option in the location filter is 'world':

<img width="1101" alt="screen shot 2017-02-06 at 16 23 56" src="https://cloud.githubusercontent.com/assets/21127166/22653101/d1dd6c72-ec88-11e6-9291-6c07c7cff5b4.png">

I checked akvo sites for other partners like Washalliance, and the country filter works there, see: 

<img width="1222" alt="screen shot 2017-02-06 at 16 25 57" src="https://cloud.githubusercontent.com/assets/21127166/22653214/0a86f9d0-ec89-11e6-8981-c2aa8091cc81.png">

Should be on EUTF akvo site as well. @Lynngre could you please have a look too?

**Comment by punchagan** [comment]
This is a manifestation of #2466.  `ProjectLocation` for these projects do not have a `Country` set, and the location filter tries to look at the country values to provide filters.
