### ISSUE TITLE
Sync number of projects on Organisation page

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2532]
**Context**

It was noticed by our partner EUTF that project stats on the Organisation page include unpublished and private projects. When you click on the stats to drill down to the projects - it returns a different number of (visible) projects.

<img width="692" alt="screen shot 2017-02-14 at 15 46 56" src="https://cloud.githubusercontent.com/assets/21127166/22933785/f286ff5c-f2cc-11e6-810c-0b984d8e1b83.png">

<img width="907" alt="screen shot 2017-02-14 at 15 49 38" src="https://cloud.githubusercontent.com/assets/21127166/22933897/4beab52a-f2cd-11e6-8918-b1e25a81047a.png">

**Problem**

Organisation page stats seem to misrepresent the number of projects that can be viewed by website visitors.

**Suggested solution**

Project stats on Organisation page should include only published and public projects

**Comment by punchagan** [comment]
May be related to #2435

**Comment by nadiagorchakova** [comment]
Yep, plus unpublished projects in this case.

**Comment by punchagan** [comment]
Closed with #2647

**Comment by punchagan** [comment]
Closing issue that should've been closed long ago.
