### ISSUE TITLE
Webpage speed

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#2533]
While working with rsr.akvo.org & especially akvoapp.org pages I noticed that they seem to be taking longer to load than before (I can't say from when exactly as I haven't been keeping note of it as such).  I'm not sure whether this is currently being worked on, I approached Puneeth who suggested I add the issue.

I ran some webpagetest.org speed tests (as we did for Akvo.org recently) & the results are poor.  Caching & compression are not fully utilised & with poor load times.

![screen shot 2017-02-15 at 09 42 08](https://cloud.githubusercontent.com/assets/2675262/22966801/1956a4b0-f364-11e6-9dfa-168db7640f2a.png)

https://www.webpagetest.org/result/170215_BQ_CP9H/1/details/#waterfall_view_step1

![screen shot 2017-02-15 at 09 42 15](https://cloud.githubusercontent.com/assets/2675262/22966800/1955beba-f364-11e6-9ec6-4161395fc368.png)

https://www.webpagetest.org/result/170215_2P_CJKM/1/details/#waterfall_view_step1

**Comment by punchagan** [comment]
> While working with rsr.akvo.org & especially akvoapp.org pages I noticed that they seem to be taking longer to load than before (I can't say from when exactly as I haven't been keeping note of it as such). I'm not sure whether this is currently being worked on, I approached Puneeth who suggested I add the issue.

I just realized that this could be because of the new rate limits that @orifito had setup to thwart the attacks we were having.  We may have to re-calibrate these rate-limits, apart from improving on some of the most obvious things that we can!

**Comment by orifito** [comment]
yes, definitely conservative rate limits decreased RSR webpage speed. I've re-calibrated them now and load time has been halved

**Comment by nadiagorchakova** [comment]
Thanks @orifito!

**Comment by orifito** [comment]
RSR load time down to 11s

**Comment by punchagan** [comment]
Closing the general issue for now.  Will create more specific issues for specific performance problems.
