### ISSUE TITLE
Searching in the Admin on a foreign project number

### ISSUE THREAD

**Issue by CharlotteSoed** [akvo/akvo-rsr#254]
As an RSR admin-level user, I want to be able to search for projects in the Admin by means of other organisation's project-IDs, so that I can easily find projects that were added via an external PMS (that are so far linked to RSR projects through the partner's project-ID). Partners generally communicate their own organisation's project-IDs, and not the Akvo project-IDs, so this feature will save us a lot of time in finding projects in the RSR Admin that our partners are communicating about.

**Comment by kardan** [comment]
Because of #1519 this will be reverted. If we still need this functionallity bad we will have to invent some other way to solve it.
