### ISSUE TITLE
Dynamic filtering (estimate: 64) 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2552]
Advanced filter should be dynamic in a way that if you select just one implementing partner as a keyword, the options for location should be narrowed down to the ones this implementing partner is active in.

**Comment by zzgvh** [comment]
@punchagan here are some links on the matter of countries and region codes. I'm thinking [this](http://vocabulary.unocha.org/json/beta-v1/countries.json) might be the best source for a country list, it is the first download on [this page](http://vocabulary.unocha.org/).

Problem is that getting a good m49 region codes list seems harder. [This page](https://unstats.un.org/unsd/methodology/m49/) is the source for the data, but I just cannot find any download link on that page in any format!

**Comment by punchagan** [comment]
This issue is not closed by #2552 since we should ideally have dynamic filters on the project update and the organisation directories too.  We could create separate issues for them and close this one, though.

**Comment by punchagan** [comment]
- [ ] The main project listing should move to the right when the advanced filters pane is open?
- [ ] Locations have this weird 'space' before the name after being selected, which looks weird. 
- [ ] The UI is twitchy - apply filter reloads the page, and the current scroll position in the page is lost.

**Comment by punchagan** [comment]
- [ ] FF could have a bug w.r.t the scroll when filters are applied.

**Comment by punchagan** [comment]
The organisations page has just one advanced filter, and doesn't need a dynamic filter. 
We need to see if the two filters for Updates really need a dynamic filter.

**Comment by punchagan** [comment]
This issue is unnecessarily being dragged along.  I think we can close it, and create new issues for any specific requests w.r.t advanced filters.
