### ISSUE TITLE
Bulk action in Results (estimate: 16)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2558]
Once expanding several Results' items in the accordion, it should be possible to apply bulk actions to preselected items:

- unlock all selected indicator periods
- request updates for selected indicators
- approve selected indicator values
- 'share as webform' for selected indicators that require an update (https://github.com/akvo/akvo-product-design/issues/153) 

Here's a screenshot from the mock-up showing a bulk action - see bottom of the screen:

<img width="1228" alt="screen shot 2017-02-27 at 16 11 04" src="https://cloud.githubusercontent.com/assets/21127166/23369165/bcb4c906-fd10-11e6-84b2-44d2dcddcb2a.png">

A link to the clickable mockup by Kiarii: https://projects.invisionapp.com/share/4N9E8TNG7#/screens/200666373

**Comment by punchagan** [comment]
Work for this has been done and we have decided to close this issue.  We create a new issue to bring the new results framework out of beta.
