### ISSUE TITLE
Indicator update - Actual Value Comment (IATI content) (estimate: 8)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2563]
Created via Reamaze:

Link: https://rsrsupport.reamaze.com/admin/conversations/deleted-result-comment-still-showing-and-missing-iati-content
Assignee: Geert Soet

Message:
Hi product team,

This morning I had a call with SNV Kenya and we noticed some things in Akvo RSR that seemed to be off:

1) Once you’ve deleted an indicator update, it still shows the comment of that update under actual value comment (see below)

2) In the hortimpact project also documents and images are included in the indicator updates, but the links to these images/docs don’t show up in the IATI report. Can we include these fields (in the same way as the main project picture) in the IATI file?

3) Another issue I found is that indicator descriptions do not show up in the IATI report. This is about project 3992:
First screen shot is of an indicator incl description, second screen shot is the same indicator in the IATI report.

 

Cheers,
Annabelle Poelert
Project Officer

Akvo • 's-Gravenhekje 1A • 1011 TG • Amsterdam (NL)
T +31 20 8200 175 • S Annabelle.akvo • T @annabellepoel I www.akvo.org &lt;http://www.akvo.org/&gt;

**Comment by nadiagorchakova** [comment]
Comments from Geert:

1. Confirmed.
2. I guess we could do this at one moment, I know it is for example also mandatory in the DFID IATI guidelines. More documentation here; http://iatistandard.org/202/activity-standard/overview/linked-documents/
3. This is indeed missing and is part of the IATI standard.

@punchagan could you have a look please?

**Comment by zzgvh** [comment]
I'm reopening this since there are parts of the issue that weren't addressed by the code changes in #2584
