### ISSUE TITLE
SNV HortIMPACT - Report

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-rsr#2564]
Creating a custom report for SNV HortIMPACT (http://rsr.akvo.org/en/project/2602/)

**Comment by Geerts** [comment]
- @stellanl  custom fields added to http://rsr.akvo.org/en/admin/rsr/organisation/881/.
- Please add fields to http://rsr.akvo.org/en/project/2602/

**Comment by stellanl** [comment]
Fields added

**Comment by Geerts** [comment]
@stellanl just had the call with the partner, we are on the right track. Only two fields that would need to be added are: 
* Executive summary
* Conclusions and Recommendations

I already added them to http://rsr.akvo.org/en/admin/rsr/organisation/881/. If you could add them again to http://rsr.akvo.org/en/project/2602/ that would be great.

**Comment by Geerts** [comment]
Almost good to go, just have the "Can not convert the value of Infinity to Integer type" bug left, related to the (copied) results table.

**Comment by Geerts** [comment]
@stellanl could you add the attached two fonts to test and live reportserver? Cheers. 
[vag_fonts.zip](https://github.com/akvo/akvo-rsr/files/827771/vag_fonts.zip)

**Comment by stellanl** [comment]
Fonts installed. In the long run we need a more ordered process. I suggest we make a directory on the support fileserver and then Puppet can copy them from there.

**Comment by Geerts** [comment]
Thanks Stellan. Sounds like a plan to me.

**Comment by Geerts** [comment]
Remaining issues: 

1. Pagenumbering does not increment well on RS, does on report preview. (added via footer in masterpage).
2. Text overlaps (3 sentences at one row). Seems to be related to this: http://developer.actuate.com/community/forum/index.php?/topic/37180-html-text-overlap-problem/

**Comment by Geerts** [comment]
Completed, can be found on live rs.
