### ISSUE TITLE
Project images not displaying on homepage of rsr.akvo.org 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2585]
Seems a couple of projects are not correctly displaying their posted pictures. The top one could be that they actually uploaded a 'black box', but the bottom seems to be a small bug: 

<img width="1370" alt="screen shot 2017-03-20 at 16 45 35" src="https://cloud.githubusercontent.com/assets/26227538/24108718/b88a0984-0d8e-11e7-9988-999c1c2e8332.png">

**Comment by punchagan** [comment]
Once a project has been published, mandatory fields can be deleted and still the project remains published.  This is a bug, that needs to be fixed.
