### ISSUE TITLE
Advanced filter improvements

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2598]
The advanced filter on the directory pages (projects, organisations and updates) could be improved in several ways.

When you apply a filter the page is reloaded and the filtered results are shown. But the filter "tab" itself is hidden. This is both confusing and annoying. And since we have the filter parameters in the URL it should be easy to set the select boxes to the current filter and show them.

Ideally the choices available in the filter select boxes should also adapt to choices already made. This however requires more work as callbacks or client side filtering of options will be needed to populate the filter select boxes dynamically.

**Comment by punchagan** [comment]
Closed in #3154
