### ISSUE TITLE
Redirecting the CNAMEs Page domains

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2599]
The order of events prevents the current scheme for redirecting http requests to the Pages sites using their CNAME domains from working. Here's what I think happens:

  * a request is made for http://cname.partnerdomain.org
  * nginx gets the request and replies "301, location: https://cname.partnerdomain.org"
  * the browser looks at https://cname.partnerdomain.org and thinks "this doesn't match *.akvoapp.org or any other domain the cert is valid for, raise the alarm!"

The redirect code in the Django middleware thus never comes into play until it's too late.

I can think of two solutions. 

1) the blanket redirect from http to https of all requests made to the server i changed to only include *.akvo.org and *.akvoapp.org. The request above would then be handled by the Django middleware which redirects to http://partnerdomain.akvoapp.org and then nginx would do its job and we end up at https://partnerdomain.akvoapp.org.

2) the individual CNAMEs are handled directly in the nginx config so that we map each CNAME to its corresponding akvoapp.org domain. After all they aren't that many (I have a spreadsheet with 10 domains, but I think some of them may be obsolete) and I think we'll have to handle them individually anyway eventually, when they have their own certificates. 

Thoughts?

**Comment by punchagan** [comment]
Your diagnosis of the problem seems correct, and ignoring the SSL warning on the browser gets the site to work. 

I would vote for 1 just because adding a new CNAME would be easier.  

If the partner had an SSL cert for that domain, though, I don't know which of these solutions would be easier to work with and how exactly we get things working.
