### ISSUE TITLE
Custom styles for Pages problems

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2602]
A number of Pages sites have problems with the custom css style sheets now that we use https. This is because some of the partner's sites don't support https so we can't fetch "their" included objects, i.e. fonts and images.

I think we have to bring those resources in-house, and host them ourselves. There are only a handful of web fonts and pics that we have to serve. 

We need to figure out how to manage this. Fonts may have licenses. And we need an interface to administer it all.

**Comment by AkvoAnt** [comment]
Ultimately resolved with Loic. Standardisation of Pages sites enforced.
