### ISSUE TITLE
General performance improvements of RSR for low bandwidth areas 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2613]
Quick(er) solutions to improving performance of RSR in areas of lower bandwidth and other similar issues. 

- [ ] Research pain points from Partner perspective 

- [ ] Research best testing options

**Comment by punchagan** [comment]
This is a useful reference: 
https://www.dabapps.com/blog/api-performance-profiling-django-rest-framework/

**Comment by punchagan** [comment]
More reference: https://blog.disqus.com/scaling-django-to-8-billion-page-views

**Comment by punchagan** [comment]
Using progressive scan jpgs might be nice too
http://designingforperformance.com/optimizing-images/

**Comment by punchagan** [comment]
This blog post by Yelp has a bunch of things to try to make images smaller, yet look good enough. 
https://engineeringblog.yelp.com/2017/06/making-photos-smaller.html
