### ISSUE TITLE
Partners tooltip bad behaviour

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2627]
The "partners popup" that displays a javascript driven tooltip with partners to a project on the project directory and the project main page is really annoying. As soon as you leave the small button-like area saying "+ 5 partners" a timer starts and after three seconds the popup disappears!

![popup](https://cloud.githubusercontent.com/assets/142613/24866163/a467afe8-1e09-11e7-932e-61ebdcda8d19.png)

The expected behaviour, to me, is that as long as you hover over the tooltip it remains visible and only disappears when you mouse out of it.

Also when you walk down a page looking at partners a previous tooltip should close immediately when you hover over a new one.

**Comment by punchagan** [comment]
This is no longer valid with the changes in #3046
