### ISSUE TITLE
Related links should open in new tab

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2656]
Created via Reamaze:

Link: https://rsrsupport.reamaze.com/admin/conversations/akvorsr-support-request-number-56093-from-g-dot-vanseggelen-at-spaceoffice-dot-nl

Adding related links with projects is nice. However, it is very annoying these links do not open in a new tab. Please add this function. You do not want to click back and forth between different sites, but have them next to each other.

**Comment by zzgvh** [comment]
I actually disagree here. Links should be links. If I want it in a new tab it's just a middle mouse click away!

**Comment by punchagan** [comment]
I agree that it's just a middle click away, but in most places where we already have links to external pages, we already open them in a new tab.  Opinions are mixed on what is the best practice for this, but I think a consistent behavior across the site is reasonable to expect.

**Comment by zzgvh** [comment]
Ya...sigh.

**Comment by punchagan** [comment]
Closed in #2657
