### ISSUE TITLE
Adding a document category doesn't work correctly

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2658]
Created via Reamaze:
Link: https://akvoo.reamaze.com/admin/conversations/akvorsr-support-request-number-56121-from-g-dot-vanseggelen-at-spaceoffice-dot-nl

I want to save 09 - Links and documents. It says "saved succesfully". But when I want to close the page it says I did not save this section.I think the problem is in the document category....

**Comment by zzgvh** [comment]
When trying to replicate the bug on test I fail. Probably need more info to reproduce.

**Comment by punchagan** [comment]
To reproduce: 

1. Go to https://rsr.test.akvo.org/en/myrsr/project_editor/5302/
2. In section 9, select one of the project documents 
3. If the document already has any associated Project document categories, delete them
4. Add a new document category and Save section 9.  Wait for the save to complete. 
5. Reload the page or Close the tab -- you are shown an alert saying that there are unsaved changes. 

With this fix, you shouldn't see the warning about unsaved changes.
