### ISSUE TITLE
Indicator description included in the new Results Framework (estimate: 4)

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2668]
In the old Results Framework you could have an indicator description included when viewing an indicator (see EUTF example below):

<img width="1211" alt="indicator description" src="https://cloud.githubusercontent.com/assets/26227538/26156461/baf9a304-3b16-11e7-963d-398f9bd06804.png">

**Comment by punchagan** [comment]
Fixed in #2702
