### ISSUE TITLE
Solution (e.g. work flow) for when an M&E Manager rejects an indicator update. 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2669]
Currently in the 'Approval Work Flow' of the new results framework when an M&E manager is reviewing Indicator Updates (via the 'Pending Approval' tab) and rejects, for whatever reason, an update that was submitted by the field M&E officer (via 'Needs Reporting) there is no way to 'send'' the indicator 'back to' 'Needs Reporting' to revise the update and resubmit.

**Comment by zzgvh** [comment]
This is now fixed so I'm closing this issue. There are issues around the workflow still, discussed in #2733.
