### ISSUE TITLE
User 'stamp' for 'approved' indicator results in new results framework (estimate: 8)

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2670]
![approval user stamp](https://cloud.githubusercontent.com/assets/26227538/26158401/0c4deb0c-3b1c-11e7-994b-8dc13d8c4291.png)

**Comment by punchagan** [comment]
Add information about who approved the period. 

Also, add information about who reviewed it and sent it back for reporting again. 
created by, approved by, etc should move below the 'Actual value' line.

**Comment by punchagan** [comment]
Closed in #2702 and #2704
