### ISSUE TITLE
Script to mark projects as complete

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2671]
The WASH alliance has 100+ projects that need to be set as complete. I suggest a management command that sets all projects with a certain keyword to complete. This will be immediately useful for the above task (the projects have one of two keywords), and can also be used in the future for similar cases.

**Comment by zzgvh** [comment]
Alternatively an admin action could be created for this. It's probably a better solution since it allows for greater flexibility in choosing the projects affected by the change, and it could be made to set a group of projects to any status.

**Comment by punchagan** [comment]
Closed in #2673
