### ISSUE TITLE
Show updates folded in the 'Approved' tab (estimate: 32)

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2676]
**Currently you have:** 

<img width="1206" alt="screen shot 2017-05-19 at 11 46 11" src="https://cloud.githubusercontent.com/assets/26227538/26242514/02a37d06-3c89-11e7-82d4-21ca7f318d8e.png">

**What we need is:** 

<img width="1196" alt="screen shot 2017-05-19 at 11 49 25" src="https://cloud.githubusercontent.com/assets/26227538/26242590/40e717e4-3c89-11e7-9ebe-8fd88fa6a4ad.png">

**Comment by punchagan** [comment]
@zzgvh and @punchagan are going to use this issue as a prop for knowledge transfer between the two of them.  The plan is for Gabriel to give me an overall idea of the data model and how data flows through the UI, and then trying to come up with a non-hacky solution for this.
