### ISSUE TITLE
Test framework for client side code

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2735]
The client side code of RSR needs tests as we develop it further. We should focus on writing tests for new code as it is developed and for the existing code base when we do additions and refactoring.

**Comment by zzgvh** [comment]
Here are some links relating to the setup of the testing env.

### Helpful

[This](https://daveceddia.com/getting-started-with-tdd-in-react/) and [this](http://www.teejayvanslyke.com/how-to-set-up-a-test-runner-for-modern-javascript.html) helped me get a sense of what's needed in terms of testing libraries and roughly how to set things up.

I tired to follow [this post](http://www.albertgao.xyz/2017/04/23/setting-up-react-with-babel-mocha-chai-enzyme-and-webpack/) to set up hot module reloading, and while that was ultimately a failure, the post itself holds much of the basis of the final setup.

### Django related

[This](http://geezhawk.github.io/using-react-with-django-rest-framework) is an interesting blog on setting up Django and react. Might be something to try to integrate later. Uses [django-webpack-loader](https://github.com/ezhome/django-webpack-loader)

### Dead ends

[This looked so good](https://github.com/zinserjan/mocha-webpack) but I could never get it working. I also tried implementing [react-hot-loader](https://github.com/gaearon/react-hot-loader) directly too, looking at [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate) but there was always something that didn't work.

**Comment by zzgvh** [comment]
## Usage

### First time

cd into `akvo/rsr/static`. Run `npm install`. 

### When developing

Write tests under `akvo/rsr/static/tests`, copying the folder structure under `static`.

Run the following in `akvo/rsr/static`:

  * `npm run build` to build the javascript bundles using webpack. The destination folder for those are `akvo/rsr/static/dist`.
  * `npm run watch` to run the previous command in watch mode
  * `npm run test` to run the javascript tests.
  * `npm run testw` to run the javascript tests in watch mode.

**Comment by punchagan** [comment]
Closed in #2768
