### ISSUE TITLE
Adding logo for new partners fails silently

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2742]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/logos-for-new-partners

Could you have a look at the below issue? S from aqua for all tried to upload logo’s while creating new organisations by choosing ‘+add new partner’ in the project editor. The organisations came through, but the logo’s didn’t and she didn’t get a notification that the logo’s could not be uploaded.

**Comment by zzgvh** [comment]
I'm updating the branch with the debug code I used to try to trace through the code as the uploaded logo is saved. However I couldn't see any difference here between when the upload was successful and when it fails. The one clue I saw was that the actual image file was always uploaded, but it is the field on the Organisation model that fails to acquire the file name of the logo. I'm giving up on this for now.
