### ISSUE TITLE
Qualitative indicators: database (module) for tags/themes for qualitative indicators 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2763]
Create a small database of the themes/tags assigned to qualitative indicators assigned by a Partner to enable easy queries for custom RSR reports.

**Comment by AkvoAnt** [comment]
Extend the RSR data model to support qualitative indicators.

**Comment by punchagan** [comment]
Duplicate of https://github.com/akvo/akvo-rsr/issues/2772
