### ISSUE TITLE
Add 'Indicator Progress' field to the Project Editor 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2765]
To allow Partners to choose which type of 'Indicator Progress' measurement they would like to employ for their Results Framework. 

- For all new Results Frameworks (post-release of feature) they need to choose which Indicator Progress type they would like to employ for their project:: 

<img width="869" alt="screen shot 2017-07-14 at 12 44 37" src="https://user-images.githubusercontent.com/26227538/28263640-b4c52d04-6ae7-11e7-98da-24aee5e7dd7f.png">

**Note:** for existing project which have provided baseline data for their Results Framework this feature will be ‘automatic’.

**Comment by zzgvh** [comment]
This choice impacts how doughnuts are rendered in the reports too I think, thus we need to coordinate with the report server team so they use the same calculation when renedering doughnuts in reports.
