### ISSUE TITLE
Add labels to indicators

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2772]
Organisations want to be able to group indicators with a common label ("Theme"). This requires several additions and changes to RSR. This is an umbrella issue for the development needed to accomplish this.

- [ ] Create UI/UX designs supporting the creation of themes and adding them to indicators
- [ ] Create the models and API endpoints supporting themes
- [ ] Project editor UI changes. This includes an interface for managing themes, and adding them to indicators
- [ ] Reports changes to use themes

**Comment by zzgvh** [comment]
After discussions with Anthony it was decided that we create an interface in the Django admin to add and change labels. Labels are associated with an organisation and the primary organisation of a project determines what labels are available.

In the project editor the labels created in the admin should be available to "tag" indicators. This will be done by selecting labels from a list.

Anthony suggested that we set a limit of two labels per indicator as a simplification. Gabriel will investigate if this does in fact simplify things or if an interface where an arbitrary number of labels can be added is easier or as easy to implement as it's a generally better solution.

At this stage labels added to indicators will only be shown in the project editor and are to be used to group indicators in reports. The report templates will need work to implement this.

**Comment by zzgvh** [comment]
@AkvoAnt I have a question around the indicator labels. I'm assuming that labels are inherited along with the rest when a results framework is imported. But it'd be good to have confirmation on that. That would also mean labels can't be edited on a child project that has imported results.

**Comment by punchagan** [comment]
Closed in #2835
