### ISSUE TITLE
Adding ‘Approve & Publish’ publish to the indicator reporting flow 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2774]
This issue is related to the upcoming changes to the 'Results' tab of the project page. 

A number of Partners would like to have control over which approved results are made public, i.e. shown in the 'Results' section of their project page. Some projects are working with vulnerable populations (e.g. refugees and trafficked individuals) and they feel that some data, if public available, could pose unintended and unwanted issues.

**Comment by punchagan** [comment]
These permissions need to be incorporated in reports/IATI export/etc. too. I don't think this is restricted just to the 'Results' tab. 
The reason private projects were introduced was precisely this.  I think users should be encouraged to use private projects for any projects that have such data, until we take a comprehensive look at permissions.
