### ISSUE TITLE
Remove IndicatorPeriodUpdate.relative_data

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2789]
IndicatorPeriodUpdate.relative_data is a field that is no longer used in practice. It is a boolean field with the default value of True. A survey of the DB shows that all IndicatorPeriodUpdate objects but one has the value True for this field.

I don't know how it was intended to be used originally. However it occurs in quite a few places in the code, but I can find no place where it can be changed. The only place where it was possible to change the value is [here](https://github.com/akvo/akvo-rsr/blob/19fe46ad80dad1e56ef6587c05d55ff2221ad178/akvo/rsr/static/scripts-src/my-results.js#L594) and that code has been commented out for over a year.

Thus I think it's safe to remove this field.

**Comment by zzgvh** [comment]
@AkvoAnt I'm going ahead with this refactoring. It'd be good if you could check with the partner team that this is in fact something that's not used (which is currently the case in the actual code) but also that it's not a feature that's somehow missing and that it should be re-instated.

**Comment by punchagan** [comment]
I vote :+1: for it!  For quantitative %age measures we have already disabled updates and made only one update possible, making this option meaningless.  Qualitative indicators will have updates which will over-ride each other, again making this option meaningless.  

Quantitative unit measures are the only case where this option will make sense, and I wonder if it would be better to make the default to be the equivalent of `relative_data` being `False` just to be consistent with the above two cases.  This change could possibly happen later, if we decide to do so.

**Comment by punchagan** [comment]
Closed in #2790
