### ISSUE TITLE
Update Project custom fields

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2826]

**Comment by zzgvh** [comment]
## Initial investigation of the current implementation of custom fields

There are two models that support custom fields, OrganisationCustomField and ProjectCustomField. OrganisationCustomField serves as the template for an organisation's custom fields, and ProjectCustomField instantiates the set of fields for a project.

AFAICT custom fields are only added to a project when it's created in the project editor. This is done by calling [addCustomFieldsToProject()](https://github.com/akvo/akvo-rsr/blob/8fbbbb427e492d864c36df4a55b2b42e22f296ac/akvo/rsr/static/scripts-src/my-projects.js#L131) after the project has been created. addCustomFieldsToProject() in turn calls [addCustomFieldToProject()](https://github.com/akvo/akvo-rsr/blob/8fbbbb427e492d864c36df4a55b2b42e22f296ac/akvo/rsr/static/scripts-src/my-projects.js#L61) for each field. The list of fields is to be found in[defaultValues.new_project_custom_fields](https://github.com/akvo/akvo-rsr/blob/8fbbbb427e492d864c36df4a55b2b42e22f296ac/akvo/rsr/static/scripts-src/my-projects.js#L90) which is created in the [my_projects.html](https://github.com/akvo/akvo-rsr/blob/8fbbbb427e492d864c36df4a55b2b42e22f296ac/akvo/templates/myrsr/my_projects.html#L135) template.

The data models for custom fields should be revised, and here I think we have two choices.

It seems that an organisation's projects should have the same set of custom fields. If this is the case, then we only need to store the *values* of the fields for each project. Currently the ProjectCustomField is a full copy of OrganisationCustomField with the addition of the value field!

Alternatively each project can be customized from the template of custom fields that is copied from the more complex solution is that when the project is created. This is a more complex solution that requires the creation of an interface to be able to edit the custom fields for each project.

I suggest replacing the current very awkward way of adding custom fields with post_save signals on Project and Organisation to update the ProjectCustomField objects from the OrganisationCustomField template objects. With this method, a project's custom fields would automatically be updated whenever the templates are edited.

**Comment by zzgvh** [comment]
This commit adds a management command that updates the project custom fields for organisations with their IDs listed in the arguments when running the command.

The update only happens for project custom fields that have a match in the organisation custom fields, where a match is determined by the name and section fields being identical.

The main purpose of this management command is to be able to add/edit the help texts for the fields, but can also be used to change other fields. The type field cannot be changed.
