### ISSUE TITLE
Migrate to PayPal REST API client

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-rsr#283]
Currently we use the zombie `django-paypal` app which has not been maintained for a long time. 

In the meantime, PayPal have also unveiled a new HTTP REST API which we should migrate to.

They have an official Python client for this REST API here: https://github.com/paypal/rest-api-sdk-python

We should use this.

**Comment by KasperBrandt** [comment]
Instead of upgrading the current donations, we'll move to a different solution (provide the partners to enter a link to their own donation / crowdfunding platform probably).
