### ISSUE TITLE
Problems with (un)escaped characters in the project editor

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2848]
The custom fields help text snippets are not escaped leading to the editor breaking if the wrong characters are included in a help text.

This became apparent when trying to include a help text that contained **"<Title of Outcome>"**.

Also there's a problem with the custom field titles if they include an ampersand, "&". There seems to be double escaping or something since the ampersand is rendered as **&amp;amp;**. This was revealed by the title **Monitoring & evaluation**.  I suspect that leads to the JS code not finding the title if it's matching for the un-escaped title value.

**Comment by punchagan** [comment]
Old PE issue. Shouldn't be a problem with the new one, though, custom fields are yet to be implemented.
