### ISSUE TITLE
Show related links even when a caption has not been entered?

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#2864]
Links created without a caption are not displayed in the project page. 
Either the caption field should be made mandatory, or links should be displayed with a fragment of URL used as the caption.

**Comment by zzgvh** [comment]
Also the URL field is _not_ mandatory. What's the use case for creating a link without a URL?

**Comment by punchagan** [comment]
The URL field has `blank=True`, but `null=False`. So, essentially the form validation allows empty values, but since we are using out own validation set based form validations, this may be alright. What we really need is a change in the validation sets to make this field mandatory, I think.

**Comment by punchagan** [comment]
I removed the `blank=True` for the model from the `url` field. The REST call from the Project Editor gets validated by DRF, and fails if there is no URL specified.

I have also deleted all the Link objects that don't have a URL associated.

Also, I have added a validation set rule to make `rsr_link.url` mandatory.  The user should now get feedback on the client side.
