### ISSUE TITLE
SSL (estimate: 64)

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#29]
Expansion of this should be included here.

**Comment by KasperBrandt** [comment]
Current to do items:
- [ ] Set up a test instance (will be done by @peeb)
- [ ] Test RSR
- [ ] Test Akvo Pages
- [ ] Test Akvo Pages with CNAME

**Comment by nadiagorchakova** [comment]
As I gathered from the description, the issue was raised mainly in relation to 'Donate' button. As we are planning to remove 'Donate' button in the future and just provide a link to organisation's website for donation instead, is this issue still relevant?

**Comment by peeb** [comment]
As a side note, the donation library used in RSR is out of date and deprecated by a native Python library provided by Mollie themselves. If the Donate buttons are being removed then this is, of course, no longer an issue also. If you'd like me to write a separate issue for this, let me know @nadiagorchakova

**Comment by nadiagorchakova** [comment]
Thanks @peeb for flagging this issue! The plan is to remove the Donate button in September, so no need for a separate issue.

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#151

**Comment by nadiagorchakova** [comment]
Discussed with Gabriel - we'll need input from @peeb on this and probably Oriol too (as far as I know they did a similar exercise for Flow already.

**Comment by nadiagorchakova** [comment]
Agreed at the standup today that we push this issue to the next release. The effort is too big to fit it in the current release.

**Comment by nadiagorchakova** [comment]
We decided to prioritise the issue following the news that starting from January 2017 Chrome will mark HTTP pages that collect passwords or credit cards as non-secure.
It's also a dependency for Akvo Sites & Akvo.org as they can't load data from API or from RSR generally as https won't accept http.

**Comment by nadiagorchakova** [comment]
Lynn prepared a document outlining what has to be done to make sure we deploy the changes safely:

https://docs.google.com/document/d/1oqfktsHWEDmPC3uizW0wj60KvjqyeqdoDBPDLEt2r2Q/edit

**Comment by zzgvh** [comment]
I did a quick search for "http://" in the code base. There are a lot of links we need to fix. Primary examples are .txt templates and reports (.rpsdesign) but there are a number of others.

**Comment by punchagan** [comment]
I pushed a bunch of changes to remove http:// values from wherever I could find.  Wasn't sure how to fix scripts in `akvo/scripts/cordaid/`
