### ISSUE TITLE
New user password set-up via User Management not functioning properly 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2920]
New users are not receiving a password set-up email when being added via User Management. Some members of the partnership team add new users by the User Management option, particularly for trainings, but there is an issue that is not allowing the password set-up email to trigger. 

<img width="1309" alt="screen shot 2017-10-12 at 09 47 15" src="https://user-images.githubusercontent.com/26227538/31535534-b83a4db2-affb-11e7-99f2-6a16db96da2b.png">

**Comment by zzgvh** [comment]
Given the somewhat scant info I've tried to replicate the problem. I can't.

The following tests have been made:

1.
* Create a user via the registration page.
* Use the activation link in the email.
* Invite the user to Akvo in MyRSR using the form above

2.
* Create the user via the registration page
* Invite the user to Akvo in MyRSR using the form above

3.
* Create the user via the registration page
* Expire the registration, by changing the date_joined to be more than 14 days past
* Invite the user to Akvo in MyRSR using the form above

4.
* Create the user via the registration page
* Expire the registration, by changing the date_joined to be more than 14 days past
* Use the activation link, this results in getting the error that the account has expired
* Invite the user to Akvo in MyRSR using the form above

5.
* Invite the user to Akvo in MyRSR using the form above

In all the cases above, all expected emails are sent and the user could log in. 

All tests were made on **rsr.test.akvo.org**. There is still the possibility that **rsr.akvo.org** for some reason doesn't send email as it should. Seems unlikely tho...

**Comment by punchagan** [comment]
The actual bug hasn't been found, really.  We are closing this ticket, until we find another report of this, etc.
