### ISSUE TITLE
File type bug in project editor

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2933]
In section 9, Links and documents, in the project editor the Document format list (shown when the IATI validation set is used) displays the wrong field of the underlying code list, FILE_FORMAT.

![doc_type](https://user-images.githubusercontent.com/142613/31770993-a4988c18-b4da-11e7-8cea-517d4e5ee3d2.png)

The **code** field should be used rather than the **category**.

**Comment by punchagan** [comment]
![image](https://user-images.githubusercontent.com/315678/31875048-fed674bc-b7e9-11e7-884a-6faf82ec9cfb.png)

Unable to reproduce this in my Chrome/FF browser. Could this be a browser specific issue?

**Comment by punchagan** [comment]
Unable to reproduce it in the latest Safari, either. 
![image](https://user-images.githubusercontent.com/315678/31875166-9549fcf2-b7ea-11e7-899c-bcd633de2133.png)

**Comment by zzgvh** [comment]
The problem shown above is not limited to the Document format field, there are other fields affected, like the Finance type field. The fix applies to all affected fields.
