### ISSUE TITLE
Show disaggregation values in public Results view

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2948]
The Results view tab in the project page (the "public" Results view) does not include updates and thus disaggregation "meta values" are not accessible.

Those values should somehow be visible in the public Results view.

**Comment by zzgvh** [comment]
When looking at this I realize I need more info to be able to work on this.

At what level are disaggregations to be shown? Is there going to be some kind of aggregation of the disaggregations, and if so at what level? What about narrative disaggregations?

**Comment by punchagan** [comment]
Closed in #2997
