### ISSUE TITLE
Baseline values not appearing 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2964]
The baseline values for _My Results_ and the _Results_ tab for project ID #5296 (and possibly others G4AW projects) are not visible although a Baseline year and Baseline value has been added:

<img width="1430" alt="g4aw akvoapp baseline example" src="https://user-images.githubusercontent.com/26227538/32814836-b6bace7a-c97e-11e7-8b7c-f2be8d83327a.png">

**Comment by zzgvh** [comment]
This is a general change that was introduced in release 3.32. I'm not sure it was intentional, but the reason is [this](https://github.com/akvo/akvo-rsr/commit/696347e301030485e9b8a0cb90778880b436b065#diff-27b486d16decb2db03e8e3d956fe07b4R4417).
