### ISSUE TITLE
React markdown introduced to RSR Updates

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2976]
Partners using RSR Updates would like to be able to format their indicator updates.

https://github.com/andrerpena/react-mde

![react markdown](https://user-images.githubusercontent.com/26227538/32952380-1ba623cc-cb7b-11e7-9d31-ec0007714d67.png)

**Comment by punchagan** [comment]
Project updates already support Markdown - Updates can be formatted using markdown.

**Comment by punchagan** [comment]
Once #3045 is completed, this should become much more easier. I suggest we do this along with/after adding an Updates tab under the Project.

**Comment by punchagan** [comment]
Closed in #3045
