### ISSUE TITLE
Proper data management of indicator dimensions

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2985]
As seen in #2984 we already have data quality issues with the disaggregations. This will only worsen with time and more use of the feature.

The current solution for indicator dimensions is a hack 😛. Instead of dimensions being added as strings for each indicator, they should be set up for the project or maybe for all projects of the primary organisation as proper database objects. Those objects are used as choices when creating dimensions for the individual indicators.

Because of how the project editor works the implementation of this will be a bit of a challenge, but I think we run the risk of many data integrity issues if use of the current solution continues and becomes widespread.

**Comment by punchagan** [comment]
Should be fixed with #3153 (See #3040)
