### ISSUE TITLE
Hide field labels from the qualitative indicator update for IUCN

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2989]
IUCN uses qualitative indicators for regular narrative reporting. They would like to avoid potential confusion for their Users by removing field names referring to a qualitative indictor. 

Also, the 'Actual' field label will be changed to 'Narrative Reporting'. 

![iucn labaling slide](https://user-images.githubusercontent.com/26227538/33184248-f013b070-d07b-11e7-82f4-7eb5a2cf63ec.png)

**Comment by punchagan** [comment]
Close #3035
