### ISSUE TITLE
Custom reports removed from 'Reports'  general view

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2990]
Remove custom reports from 'Reports' general view, i.e. Plan Finland or EUTF reports are not visible for other partners. 

![custom reports included](https://user-images.githubusercontent.com/26227538/33214973-4bf3ce5e-d12e-11e7-8a73-d5f3221f3b30.png)

**Comment by punchagan** [comment]
Isn't this only visible because you are an admin, @AkvoAnt ?  Or is there an issue reported by someone not from these organisations?

**Comment by AkvoAnt** [comment]
This was reported by a partner and the partnership team.

**Comment by punchagan** [comment]
> This was reported by a partner and the partnership team.

I suspect that the member of the partnership team is an RSR admin, and is therefore able to view all reports. I have written tests, and double checked the code. 

I would like to see the report from the partner to get more details into the problem, if indeed there is one.

**Comment by AkvoAnt** [comment]
Confirmed with a YEP user that custom reports are not visible to a 











































































































































Confirmed - custom reports are not visible for users who are **_not_** part of the organisation. Tested with a YEP participant. 

Closing.
