### ISSUE TITLE
Redirect http requests to https on the RSR API

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2991]
The web site requests have been redirected, and partners have been given a deadline to move their clients using the API to https.  If the deadline has passed, we should redirect all http requests to the RSR API to https.  Most clients should handle this correctly, but if there are any clients that don't handle this, the onus would be on our partners to make the switch, since they have already been intimated of the upcoming change. 

This is important for security reasons.

**Comment by punchagan** [comment]
Can we confirm on the deadline given to users to move their clients to HTTPS?  We need to ensure that the deadline has passed, before making this change.

**Comment by punchagan** [comment]
We would like give a 2 week notice before doing this. Hence, we won't be able to work on this, in the current Milestone. Moving this to the next one.

**Comment by punchagan** [comment]
This has been deploy by @orifito
