### ISSUE TITLE
Style issues with target value tooltip

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3003]
The target value tooltip is acting up:

![screenshot_225](https://user-images.githubusercontent.com/142613/33381489-700e3cae-d51e-11e7-9ad6-5a5426260648.png)

The picture above is from [this project on UAT](https://rsr.uat.akvo.org/en/myrsr/results/3992/) when adding an update to the first indicator of the first period.

**Comment by zzgvh** [comment]
@loicsans if you have the time to look at this it would be great. Please create a branch from release/candidate if you do.

**Comment by punchagan** [comment]
Closed in #3004
