### ISSUE TITLE
Narrative reporting feature added to the RSR results framework 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3012]
Partner requires a narrative reporting feature added to the results framework. Data saved with feature will be used the partner's, One Drop, custom report. 

![narrative reporting image](https://user-images.githubusercontent.com/26227538/33488717-d11d0f68-d6b1-11e7-880a-704978bab481.png)

**Comment by punchagan** [comment]
Closed in #3018
