### ISSUE TITLE
Redirect project title link on 'My Projects'

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3013]
Redirect project title link on 'My Projects' from the Project Editor to the actual project page. 

You should not be taken directly to the Project Editor, this confusing to most Users. 

![myprojects - project title jump](https://user-images.githubusercontent.com/26227538/33558485-38dea15c-d90a-11e7-8e09-feb8606f3c41.png)

**Comment by punchagan** [comment]
#3045 will make this issue moot.
