### ISSUE TITLE
Display notification encouraging project creators to add non-mandatory information at a later date

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#303]
Anna-Marthe has raised a few possible improvements that could be made to the project creation process and the project update process which I think make sense - I'm raising an issue just to log these but feel free to close if they aren't desirable.

When a project creator chooses to not populate non-mandatory fields (i.e. goal objects, project photo, photo caption, photo credit, location details, budget items, benchmarks) it could be helpful to display a notice saying something like “Your project has been created - however you have not completed the fields of […] & […] which can provide very useful information about your project. If possible please take some time to add these project fields.”

**Comment by adriancollier** [comment]
I like this feature, but with the introduction of the Form based system for entering IATI/RSR data to RSR (https://github.com/akvo/akvo-product-design/issues/77), I think this is better covered there rather than making usability improvements within the existing Admin.
