### ISSUE TITLE
Disaggregation/dimensions inherited by child project from parent 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3040]
**What:** Copying of indicator dimensions (disaggregation of indicator values) to child projects + aggregation of child projects' disaggregated actual values to parent project. 

**Why:** To understand how child projects contribute to the total. If this feature is not there, you have to create separate indicators for males/females (doubling the indicators in the result framework).

**Comment by zzgvh** [comment]
# Roadmap for disaggregations in RSR

After discussion with @stellanl and @punchagan here is a draft of a "roadmap" for the refactoring and improving of disaggregations in RSR.

### 1. Data migration and change of existing fields

There is a need to harmonize how we represent data for baseline, target and actual values. The following changes are needed:
- Indicator:
  - baseline_value is changed to be a Decimal field
  - baseline_narrative is added to support baselines for qualitative indicators
  - baseline_numerator and baseline_denominator are added to support percentage baselines
- IndicatorPeriod:
  - target_value is changed to be a Decimal field
  - target_narrative is added to support targets for qualitative indicators
  - target_numerator and target_denominator are added to support percentage targets
- IndicatorPeriodData:
  - the fields value, narrative, numerator and denominator are renamed by prepending actual_

These name changes make it clear what a value represents while maintaining a coherent naming scheme for similar fields in the different models. They also pave the way for adding disaggregations for baseline and target in the future.

There is a snag here however. To be able to change the data types of baseline_value and target_value a data migration is needed to preserve any textual data currently in those fields. For qualitative indicators this should be done by moving the data to the corresponding _narrative field, but for quantitative indicators with non-numeric values the situation is less clear.

### 2. Add the new models

The new models defined in this branch will be added and used with a few modifications: 
- change the name of the Disaggregation model to DisaggregatedValue
- add a de-normalized field **name** to the DimensionValue model, that takes its data from the associated Dimension object.

The code includes migrating existing dimensions and disaggregated values to the new data structures.

### 3. Implement Postgres views

Posgres views, used to calculate aggregates, should be used in all places where we "add things up". This way we eliminate the duplication of code that calculates the aggregates, and thereby eliminate the risk of calculating in different ways in different places.

### 4. Refactor all "consumers"

All places where we use calculated values need to be updated to use the new models and views. This includes the reports, the results framework, and the IATI export (I think).

**Comment by zzgvh** [comment]
Leaving this open as it's being discussed how to proceed.

**Comment by punchagan** [comment]
Closing as done
