### ISSUE TITLE
Update analytics siteid for split from akvo.org

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#3041]
In our Piwik web analytics system, rsr.akvo.org's visits have always been combined with https://akvo.org 's visits.

As we went to better track https://akvo.org we are splitting RSR's stats away from the main site running on akvo.org domain.

As of the 1st -3 rd January the Siteid for rsr.akvo.org must be updated to: 159
Below is the example snippet from the system but I believe we have our own in the footer of RSR.

<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDomains", ["*.rsr.akvo.org"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=((document.location.protocol === "https:") ? "https://akvo.piwikpro.com/" : "http://analytics.akvo.org/");
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 159]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//analytics.akvo.org/piwik.php?idsite=159" style="border:0;" alt="" /></p></noscript>

**Comment by punchagan** [comment]
Closed in #3078
