### ISSUE TITLE
OrganisationIndicatorLabelViewSet inherits from the wrong parent

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3058]
**OrganisationIndicatorLabelViewSet** mistakenly inherits from **PublicProjectViewSet** instead of **BaseRSRViewSet** leading to errors [here](https://github.com/akvo/akvo-rsr/blob/1c0592af97e000a830907ed652a3eef1dbd5f6ca/akvo/rest/viewsets.py#L150) since there is no relation to a project.

**Comment by punchagan** [comment]
See also #3053

**Comment by punchagan** [comment]
Closed in #3059
