### ISSUE TITLE
Reports section under a project

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-rsr#3075]
@AkvoAnt We need to define what exactly goes under a project reports tab in the new myrsr section:
![screen shot 2018-01-08 at 14 58 47](https://user-images.githubusercontent.com/1717219/34671922-23051276-f485-11e7-845a-5687b5f47b8d.png)

**Comment by punchagan** [comment]
This needs discussion. Moving it to the next release

**Comment by punchagan** [comment]
Wireframe design is here: https://xd.adobe.com/view/b9327f66-e4c1-4bda-9928-9046be0f0ded/

**Comment by zzgvh** [comment]
Does this mean that we can delete some templates and javascript files for the old reports page?

**Comment by punchagan** [comment]
Not yet. We still need to deal with org level reports.
