### ISSUE TITLE
Improve IATI error messages to make it easier to find offending indicators/results

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3081]
The IATI export creation page shows the errors in the projects, but the results and indicators are identified by their ids, and the error messages are not really helpful in finding the offending objects.

**Comment by zzgvh** [comment]
Same thoughts from another angle: #3104

**Comment by zzgvh** [comment]
And #2643

**Comment by zzgvh** [comment]
It would be nice to highlight the object linked to in the project editor, similar to how Github highlights a line of code linked to.
