### ISSUE TITLE
Links into the project editor

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3104]
It would be very useful to be able to create links "into" the project editor. By that I mean a link that opens a project in the project editor and then opens the relevant section/subsection(s) and scrolls to (and maybe also highlights?) a particular piece of information.

Example: The IATI export validator reports on errors in the IATI export of a project, e.g. 

```- Error: Indicator period (id: 33203) has no actual value, but does have an actual comment, actual location(s) or actual dimension(s)```

A link of the kind described above would allow the user to click on a link in the error report that would open the project editor and show the problem period. As it is now the error information is very hard to use since the project editor doesn't display IDs of its objects.

(I think there is a limited form of this currently, but it only allows links that open a certain section of the project editor.)

**Comment by punchagan** [comment]
Closed with #3175
