### ISSUE TITLE
One Drop project introduced  “nameless indicators” to their results framework 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3109]
There seems to be a bug that created 'nameless indicators' to the Lazos de Agua project of One Drop: 

<img width="1209" alt="screen shot 2018-01-26 at 19 22 14" src="https://user-images.githubusercontent.com/26227538/35454447-575484c4-02ce-11e8-891d-44e2ba098ef5.png">

Example project: #5560

**Comment by zzgvh** [comment]
I've tried to recreate this bug for an hour+ now, but I can't. I suggest deleting the "rogue" indicators by hand. As always, better bug reporting would help 😉
