### ISSUE TITLE
Script to introduce additional reporting periods for One Drop project - Lazos de Agua

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3110]
Additional reporting periods must be added to **output level** indicators, so that all output indicators have 9 reporting periods:

1 July 2017 - 31 Dec. 2017 
1 Jan 2018 - 30 June 2018 
1 July 2018 - 31 Dec. 2018 
1 Jan 2019 - 30 June 2019 
1 July 2019 - 31 Dec. 2019
1 Jan 2020 - 30 June 2020 
1 July 2020 - 31 Dec. 2020 
1 Jan 2021 - 30 June 2021
1 July 2021 - 31 Dec. 2021

Indicator 1101 of project #5562 can be used as example

**Comment by zzgvh** [comment]
Most indicators have 2 or 5 periods at the moment. Should these periods be deleted and replaced with the list above? If so, are the periods we delete guaranteed to not hold any data that is lost in the process, or is this something that we need to verify. And if we're to verify, what to do if we find e.g. target values or even updates?

**Comment by zzgvh** [comment]
Also, running this on 5562 means the children will be changed in the same way, so we have to make sure there's no data on the children that might be lost.

**Comment by zzgvh** [comment]
Above you've written **output level** indicators, but I'm fairly sure you mean **outcome**, right? (The example, 1101 is an outcome)

**Comment by AkvoAnt** [comment]
Project closed.
