### ISSUE TITLE
Search bar redesign

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3126]
Home page, all updates and all organisations pages need their advanced filters to be re-designed.

**Comment by punchagan** [comment]
This needs to be implemented on the "All Updates" and the "All Organisations" page.

**Comment by AkvoAnt** [comment]
![advanced filter_1](https://user-images.githubusercontent.com/26227538/36590568-59ea0d68-188f-11e8-85bc-9c152bd238d7.png)

![advanced filter_2](https://user-images.githubusercontent.com/26227538/36590572-605b2128-188f-11e8-8d24-a512f2021bec.png)

![advanced filter_3](https://user-images.githubusercontent.com/26227538/36590576-634e184a-188f-11e8-9d7b-6042e8448841.png)

![advanced filter_4](https://user-images.githubusercontent.com/26227538/36590579-666bee30-188f-11e8-8023-399419b7685d.png)

![advanced filter_5](https://user-images.githubusercontent.com/26227538/36590585-6aebe0aa-188f-11e8-89bf-73949dcb073c.png)

**Comment by punchagan** [comment]
> This needs to be implemented on the "All Updates" and the "All Organisations" page.

- We decided to remove the advanced filters on the All updates & All organizations page
- The search bar on the all updates page, goes into the right half of the page, above the map.

**Comment by punchagan** [comment]
Closed in #3197
