### ISSUE TITLE
Location id '6178' missing iso country code - 'gh'

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#3130]
**Context**

When trying to add the F4W project updates to their Akvo Site via the RSR API, the update https://f4winternational.akvoapp.org/en/project/6178/update/21247/ would not appear whereas project update https://f4winternational.akvoapp.org/en/project/6177/update/21236/ would.

Example API call used:
https://rsr.akvo.org/rest/v1/project_update/?filter={%27project__partners__in%27:[f4waterids]}&project__primary_location__country__iso_code=gh&format=json&image_thumb_name=big

Did not provide data for project :
https://f4winternational.akvoapp.org/en/project/6178/update/21247/

**Problem or idea**

It seemed that location '6178' didn't have a country specified. Even though lat/long exists. It should be iso country code 'gh' for Ghana.

**Solution or next step**

Apparently a similar issue was fixed recently but this one was missed.

@punchagan fixed this on live RSR to allow for the Akvo Site to show the F4W project updates correctly. This still needs to be fixed permanently.

**Comment by punchagan** [comment]
Added a data fixing script #3487
