### ISSUE TITLE
Error when you using Search Bar in redesigned MyRSR 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3144]
When you search for a project using the search bar, e.g.: 

![sbar_1](https://user-images.githubusercontent.com/26227538/36662426-a9ff376e-1ade-11e8-90ac-6b1cc5836e30.png)

![sbar_2](https://user-images.githubusercontent.com/26227538/36662430-b0cac5e0-1ade-11e8-9c12-1c108d8ad794.png)

You don't have the option to return back to 'My Projects' as you do when you click on a project from My Projects, e.g.: 

![sbar error_3](https://user-images.githubusercontent.com/26227538/36662440-b80bfefa-1ade-11e8-81b8-0738d7f446a5.png)

**Comment by punchagan** [comment]
Closed in #3198
