### ISSUE TITLE
UI refactoring branch

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3196]
We need a branch where we can continue developing the UI independent of develop 😉

**Comment by zzgvh** [comment]
### A pair of small UI bugs on the home page

![screenshot_263](https://user-images.githubusercontent.com/142613/37973806-a090dbec-31db-11e8-988b-27bdcd244db3.png)

There are cases when a project takes up too much space in some way, breaking the layout.

![screenshot_264](https://user-images.githubusercontent.com/142613/37973480-e13025be-31da-11e8-8c4b-8be70768a01d.png)
When you scroll to the end of the project list and then go to the next page using the pagination buttons, the scroll position of the list remains at the bottom. Should return to the top.

**Comment by punchagan** [comment]
Merged in #3248
