### ISSUE TITLE
Support CSV format for the API end-points

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3200]
Currently, Lumen supports only CSVs since they are easy to translate to the 2D datasets that Lumen uses. It is tricky to support any arbitrary JSON format, since the translation to a 2D data structure automatically would be hard. 

But, to be able to use RSR data in Lumen visualizations it would be useful to support CSV format using the [django-rest-framework-csv](https://github.com/mjumbewu/django-rest-framework-csv) package, which provides a renderer similar to the json and xml renderers that we already have enabled.

**Comment by zzgvh** [comment]
### How to import CSV into Excel

Here's a recipe for how to import a CSV with linebreaks into an Excel sheet on a Macintosh (Excel for Mac 2011):

In this example I'm using data from the Akvo test project https://rsr.akvo.org/rest/v1/project/2/?format=csv

- Open the downloaded CSV in TextEdit
![screenshot_288](https://user-images.githubusercontent.com/142613/40915113-1a99d416-67fb-11e8-8022-7425f04b4ada.png)

- Open a new Excel sheet
- Copy all of the text (Cmd-A to select all) from TextEdit into the top left cell of the sheet
![screenshot_289](https://user-images.githubusercontent.com/142613/40915189-6a4cf628-67fb-11e8-8d58-a85cb34140e2.png)

- Switch to the Data tab in the Excel toolbar, click on Text to columns
![screenshot_290](https://user-images.githubusercontent.com/142613/40915279-c42d5df4-67fb-11e8-9157-f9fd053a5109.png)

- In the wizard, choose Delimited in step one, Comma as delimiter in step two. Click Finish
![screenshot_291](https://user-images.githubusercontent.com/142613/40915323-ec138fc8-67fb-11e8-93e3-b9c1f28bed6f.png)

![screenshot_292](https://user-images.githubusercontent.com/142613/40915332-f0eb4d56-67fb-11e8-976f-0c332989e64b.png)

- The data will move around a bit, but will still not be put in the correct cells
- Go back to the Home view
- Select all data (Cmd-A or click the space top left of the sheet itself with an arrow facing down and to the right)
![screenshot_294](https://user-images.githubusercontent.com/142613/40915430-53b08866-67fc-11e8-9197-2ad9743b1c4c.png)

- Click the Clear button and choose All. You should now have what looks like an empty sheet. But it's not quite empty, beacuse it remembers where to put items from the CSV...
![screenshot_296](https://user-images.githubusercontent.com/142613/40915610-0805cad8-67fd-11e8-9919-8132be6bb51b.png)

- Paste again. This should paste the text from TextEdit and it'll magically put the data into the correct cells. Ain't Excel great?!? 👿  
![screenshot_297](https://user-images.githubusercontent.com/142613/40916038-89aca59c-67fe-11e8-9d9f-27b326035d12.png)
