### ISSUE TITLE
Use Jinja2

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3207]
# Proposal

This is a proposal to switch to the Jinja2 template language for RSR.

## Project editor is very slow

The project editor is dog-slow. The project editor is built using a set of template snippets that are assembled according to the data structure of the current project. This results in a lot of template fragments being loaded and rendered. For large projects, particularly projects with large results frameworks, this can result in hundreds of template fragments being used to render the full project in the editor. Since the default Django template engine is slow the rendering of large projects becomes very slow.

Rebuilding the project editor using some other underlying core solution is such a large task that investigating improvements that require less effort than a complete rewrite might be a more viable way forward. One idea is to use the Jinja2 template framework.

## Why Jinja2?

The main reason for using Jinja2 in RSR is because it is much faster. Exactly how much faster is impossible to say, but the Jinja2 site says "The benchmarks from the testsuite show that Jinja2 has a similar performance to Mako and is between 10 and 20 times faster than Django’s template engine or Genshi. These numbers should be taken with tons of salt as the benchmarks that took these numbers only test a few performance related situations such as looping."

Jinja2 is also a more sophisticated template language although there are also drawbacks that we may have to take into account. See below the links on switching to Jinja2.

Jinja2 is a stand-alone python template language. Django 1.8+ integrates back-end support for Jinja2 and I think its also possible to use it with Django 1.7 although it might require a little more work to set it up.

## Drawbacks

A switch to Jinja2 would require a fair amount of work. However I think it's possible to switch for only parts of RSR and if so, we could start with the project editor and if that proves successful we could continue the switch for the rest of the templates as time permits.

### Links

[Jinja2](http://jinja.pocoo.org/docs/2.10/)
[Jinja2 FAQ](http://jinja.pocoo.org/docs/2.10/faq/)
[Django 1.8 support](https://docs.djangoproject.com/en/1.8/releases/1.8/#multiple-template-engines)

#### Switching to Jinja2
https://www.linkedin.com/pulse/pain-jinja2-hongbin-zuo
https://djaodjin.com/blog/django-porting-templates-to-jinja2.blog.html
http://splike.com/wiki/Convert_Django_Templates_to_Jinja2
https://stackoverflow.com/questions/37723547/django-with-jinja2-using-custom-context-processors

**Comment by punchagan** [comment]
We've moved away from using the template based project editor. Other pages may benefit a little bit from this, but all the other pages are relatively small and the gains are probably not worth it.
