### ISSUE TITLE
Data privacy/personal data issue: partner contact email address visibility

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#3241]
Under the 'Full report' tab for a Project published in RSR, we publish a section titled 'Project Contacts', we publish partner's team members full email addresses.

For both GDPR compliance (data privacy) & just general best practice re anti-spam, this should be removed from published data by default.

Example:
https://eutf.akvoapp.org/en/project/5359/#report
<img width="1127" alt="screen shot 2018-05-15 at 12 06 41" src="https://user-images.githubusercontent.com/2675262/40050796-c7a1454a-5838-11e8-8f6e-af5471342e42.png">

<img width="1277" alt="screen_shot_2018-05-15_at_12_03_18" src="https://user-images.githubusercontent.com/2675262/40050910-2dedca26-5839-11e8-91f2-6f3c95b23714.png">

**Comment by stellanl** [comment]
But what if they want it visible? After all this is more or less advertising for the project.

**Comment by Lynngre** [comment]
It's there by default currently.  No consent for sharing has been given.

It's also not good practice to provide contact details in this way in general.

**Comment by zzgvh** [comment]
This is not part of any user account data. It's an email address entered for this particular use specifically. That means (I think) that it's the responsibility of the partner to have the consent to use the email address. We might add help text to emphasize this, but I don't think we need/should remove the address.
