### ISSUE TITLE
Duplication of partners in the project editor

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3243]
When adding organisations as partners in the project editor the result sometimes is duplicates of the partners. See https://sentry.io/akvo-foundation/rsr-live/issues/559070440/ which resulted in a number of duplicate partners on project 7122.

What I think happens is that there is an error when the partners section is saved in the project editor, but the partners are saved. When the user sees this, (s)he clicks Save again resulting in the partners that were just added being added once more, since there is no unique constraint preventing this.

The stopgap fix is to add a unique constraint on Partnership.Meta of ('organisation', 'project', 'iati_organisation_role'). This should be combined with a data migration that removes existing duplicates.

We should also investigate why saving partners in the project editor fails.

**Comment by punchagan** [comment]
Old project editor issue. Closing as stale.
