### ISSUE TITLE
Change UI interaction after a user has entered and saved/approved an indicator reporting update

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3246]
Currently when a user saves or approves an indicator reporting update the UI interaction works so that the user is 'taken' to the just saved/approved indicator and the associated Result: 

![rf ui interaction issue](https://user-images.githubusercontent.com/26227538/40789265-535c89c6-64f2-11e8-8b02-f30ed8fe200c.png)

This interaction in itself is good as the user can review the indicator reporting update that they've just made. However, it's not useful if the user wants to easily update other indicators for the same Result. Currently the user instead needs to use the 'Full View' feature, re(find) the Result, then go to the 'next' indicator, and start from there. 

It would be more helpful if the interaction/view for the user, after they've saved/approved an indicator reporting update took them back to the Result and displayed all of the indicators for that Result. This way the user could easily and quickly access the other indicators and make updates.

**Comment by zzgvh** [comment]
Leaving this open as the suggestion has not been implemented.
