### ISSUE TITLE
Pagination not correct on organisation listing page

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3249]
When searching or filtering on the organisation listing page, the pagination is not in sync with the results. It always shows as if all organisations are in the search result.

Page 1:
![screenshot_304](https://user-images.githubusercontent.com/142613/41106272-016851d0-6a70-11e8-8950-9b6a0cb4c2fd.png)

Page2:
![screenshot_305](https://user-images.githubusercontent.com/142613/41106280-057b5344-6a70-11e8-91a7-b03fd288f95a.png)

**Comment by punchagan** [comment]
Closed on #3254
