### ISSUE TITLE
Layout issues on mobile

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3250]
### Filter alignment

The filter widgets are not aligned correctly when viewed on mobile phones. The view below is Chrome on a Moto G5:

![screenshot_20180607-163532](https://user-images.githubusercontent.com/142613/41107469-b14368b8-6a72-11e8-8deb-530d3263e3ea.png)

### Pagination widget font size

The pagination widget font size doesn't scale with the rest of the page on mobile:

![screenshot_20180607-163651](https://user-images.githubusercontent.com/142613/41107620-fee888aa-6a72-11e8-823d-616527a6e57c.png)

### Inner scroll area removal

Also the inner scroll area for the actual list of projects should be disabled on mobile, and the page should be one tall scollable page instead.

**Comment by zzgvh** [comment]
Leaving this open as the problems remain.

**Comment by punchagan** [comment]
Closed in #3515
