### ISSUE TITLE
results-simple-table called without a project ID

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3251]
On the report tab of the project page in Myrsr, the call to the Report server for the report named **Results and indicators table**, aka *results-simple-table* is missing the project ID. A full example URL is ```https://rsr.akvo.org/en/reports/project_results_simple_table/undefined?format=excel&download=true```

Example project with the problem: https://rsr.akvo.org/en/myrsr/my_project/7151/

**Comment by zzgvh** [comment]
The project_updates_simple_table report suffers from the same problem.

**Comment by punchagan** [comment]
Closed in #3253
