### ISSUE TITLE
Update of indicator creates it in child

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3258]
EUTF reports that when one of their "core" indicators, in the result named **EUTF indicators**, was updated, was updated, the indicator appeared in all child projects that had imported the framework, _even in those where the indicator had previously been deleted_.

This is the wrong behaviour I think, and it's also surprising. We even have a test that makes sure deleted indicators are not re-instated, but that test is only for when _re-importing_ a framework, not when a parent indicator is "merely" updated.

After a quick look at the code I think that Indicator.save() needs check if the indicator is new and only then run the loop calling child_result.project.add_indicator(child_result, self) [here](https://github.com/akvo/akvo-rsr/blob/develop/akvo/rsr/models/result/indicator.py#L107). this is just a quick assessment, and I may well be wrong in part in in all 😉

**Comment by punchagan** [comment]
Closed with #3262
