### ISSUE TITLE
Notes on activating single reporting period for EUTF

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3259]
To set up EUTF with single periods the management script single_period_indicators.py needs to be run like so:
```python single_period_indicators.py EUTF all```

This will run the script in dry-run mode outputting all changes that would be undertaken if the --live option was included.

Copy the output to a spreadsheet and look for errors. Eliminate the errors and run again. If there are no errors left, it should be GTG.

Also the setting for period_start and period_end in SINGLE_PERIOD_INDICATORS in 30_rsr.conf are probably incorrect and should be adjusted after getting the correct ones from EUTF.

As an extra precaution, run all of the above on UAT first and check that everything works 😉

**Comment by zzgvh** [comment]
@stellan:

Reports for projects that are children of EUTF need to "fake" the period_start and period_end dates. Instead of the dates in the period the period start should be shown to be the same as the project start, and the period end same as the project end. In both cases use the actual project date if it is present, otherwise use the planned date, and as a last resort use actual dates of the period.

**Comment by stellanl** [comment]
What is the criterion for "children of EUTF"?
Project 4401 has it as child and/or it has project 4401 as parent?

**Comment by punchagan** [comment]
> Project 4401 has it as child and/or it has project 4401 as parent?

[Yes](https://github.com/akvo/akvo-rsr/blob/develop/akvo/settings/30-rsr.conf#L101)

**Comment by stellanl** [comment]
Check. The template work will be tracked in akvo/akvo-reporting-templates#25.
Is this just for the EUTF report, eutf_project.rptdesign, or the regular results reports, too? 
(project-results-simple-table.rptdesign, org-results-simple-table.rptdesign and project-results-with-narrative.rptdesign)

**Comment by stellanl** [comment]
Anthony: The discussions were focused on the EUTF report but I’ll confirm with them whether or not they anticipate using any of the standard template reports. When we met they weren’t using the standard reports.
