### ISSUE TITLE
(re) Introduce the 'Edit' function to Project Updates 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3277]
After feedback from both partners and the Akvo support team it's been decided to allow Project Updates to be edited. 

Key things consider when creating a solution: 

- Editing permission should be restricted to the creator of the update and to the Admin of the org only;
- Some kind of record of the original update should be kept in the DB in the event an update has been edited/modified; 
- If possible, it would be great if Akvo Super Users were able to both edit _and_ delete Project Updates, (at the request of the partner only) _inside_ RSR (i.e. not in the old admin.)

**Comment by punchagan** [comment]
Closed in #3282
