### ISSUE TITLE
Pagination of projects is incorrect

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3289]
On the home page, the pagination is off for large sets of projects. 

#### Example
Select the EU trust fund for Africa in the organisations filter. The pagination widget shows that there are 22 pages of projects, but the last [two are empty](https://rsr.akvo.org/en/projects/?organisation=3394&page=22)!

**Comment by punchagan** [comment]
I suspect the bug is due to the [wrongly hard-coded default value](https://github.com/akvo/akvo-rsr/blob/develop/akvo/rsr/static/scripts-src/directory-utils.jsx#L552) of no. of projects in a page.  The server side setting needs to be propagated to the client.
