### ISSUE TITLE
Percentage signs (%) not displayed for disaggregations 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3298]
When you tell the system an indicator is to be answered in percentage, you will see the % sign in the total value. However in the disaggregated total value the percentage sign doesn’t show (see the difference in the grey bars in the screen shots below).

![image](https://user-images.githubusercontent.com/26227538/42098680-daa57b88-7bbb-11e8-9162-36ca5ca7f387.png)

**Comment by punchagan** [comment]
Closed in #3579
