### ISSUE TITLE
Issue(s) when inviting a User to an organisation 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3302]
The email received after a User has been invited to an organisation states a different organisation than the one that has actually been invited to. 

However, when you view the User on the User Management page they do appear has having been added to the organisation. 

Also possible that although the User appears as having been added in the User Management page (i.e. front end) that they actually haven't been added (i.e. back end).

**Comment by punchagan** [comment]
This was a false positive issue
