### ISSUE TITLE
Create test dataset for RSR

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3338]
Some of the tests create a dummy database using FactoryBoy. We could look at extending this, or create a fixture.

**Comment by zzgvh** [comment]
Leaving this open as there is no test dataset. All we have is the API expected responses JSON. We also need a dataset for local dev that is representative while at the same time is not using the "real" dataset. Maybe those two tasks can be combined?

**Comment by punchagan** [comment]
Duplicate of #3517
