### ISSUE TITLE
Improve Front-End build (JS + CSS + static) 

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3340]

**Comment by zzgvh** [comment]
See #3353 for earlier work on the issue/3340_unified_webpack branch.

This is a first cut of using webpack to build all our client side code. It works, with some workarounds.

The biggest issue is that I haven't been able to import style sheets in our React code. the wrokaround is to import them in main.scss instead. This solves the issue, but the code gets "spread around" in a way that's not ideal.

Also in webpack.config.js there is a class MiniCssExtractPluginCleanup defined. This is a hack to remove dist/main.js that is output as a side effect of processing mian.scss. I found several threads on this, but no clean solution.

Note that many babel packages are version 6.26.x and babel-loader is v 7.1.5. Both those "bundles" now have +1 versions, which might resolve the problems above.

**Comment by zzgvh** [comment]
Actively worked on. Leaving open.

**Comment by zzgvh** [comment]
## Replace Pipeline with Webpack

Webpack now manages most of our javascript and css files (some are still served directly via &lt;script&gt; tags), transpiling and packaging both for development and production mode delivery.

All uses of Django-pipeline's `javascript` and `stylesheet` tags in the templates has been replaced by the Django-webpack-loader tag `render_bundle`. See the [docs for details](https://github.com/owais/django-webpack-loader#django-webpack-loader).

There are two ways of running the pipeline using node commands: `npm run dev` and `npm run prod`. Both are run automatically via the docker configuration.

In both cases the output artifacts, both .js and .css files are placed in `akvo/rsr/static/dist`. When in development, a *.map file is generated for each source.

### `webpack.config.*.js`

The webpack configuration consists of a base file, `webpack.config.base.js`, the main purpose of which is to define the mapping between all managed files and their output bundle's identifiers. The base is then imported into `webpack.config.dev.js` and `webpack.config.prod.js` to allow for the two modes of running the pipeline.

### Development mode: `npm run dev` and `npm run devw`

In development mode, on `docker-compose up`, we check if `akvo/rsr/static/node_modules` is present, if not `npm install` is run.

Next we look for `akvo/rsr/static/dist/vendors.js` and if that file isn't present `npm run dev` is run to fully populate `akvo/rsr/static/dist`. The choice of `akvo/rsr/static/dist/vendors.js` is arbitrary, but if it is missing we can assume that a full build should be run. 

Last `npm run devw` is run setting webpack in watch mode, rebuilding as needed when a file is changed. In my experience this is so quick you can save a file and immediately reload the browser.

Unfortunately hot module reloading is not implemented. In theory it works, and I almost got it working, but I could not get webpack  and django-webpack-loader to play nicely. It falls down when trying to serve image files referred to in main.scss. I would say this can be attempted again when the webpack 4 ecosystem has stabilized a bit more but it may also be needed to patch django-webpack-loader.

### Production mode: `npm run prod`

The main difference when building for production is that the `/dist` folder is fist cleaned out, using clean-webpack-plugin (I'm not sure this is strictly necessary, if the container is being rebuilt every time) and that all files are decorated with a hash to bust any caching. `npm install` is always run before running `npm run prod`

### `django-webpack-loader`

django-webpack-loader provides the link between Webpack and and Django. When the the npm build commands are run the file `akvo/rsr/static/webpack-stats.json` is generated. This file provides the mappings between the names of resources used in the template tag `render_bundle` and the actual files loaded.

### File organisation

All "old" javascript files have moved from `akvo/rsr/static/script-src` to `akvo/rsr/static/script-src/classic/(js|jsx)` depending on type.

## Future development

There are a number of things that can be improved with our javascript environment. On top of my list  is to remove all external library dependencies and use `import` instead in the  "classic" files. This would allow the use of [tree shaking](https://webpack.js.org/guides/tree-shaking/) that is supported by Webpack 4 and may well shrink the javascript payloads considerably.
