### ISSUE TITLE
user_is_me_manager context variable gets the wrong value

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3348]
The **user_is_me_manager** context in my_rsr.my_project() relies on the **rsr.do_me_manager_actions** permission. This permission went missing [in this commit](https://github.com/akvo/akvo-rsr/commit/cfae65db742968989f751273a54760e864980c29). 

I don't understand why there is no trace of the change to __init__.py. The [two](https://github.com/akvo/akvo-rsr/blob/ccbb14825fbca729aecf8eacb526c239300c4134/akvo/rsr/models/__init__.py#L217) [parent](https://github.com/akvo/akvo-rsr/blob/e0a84df5a03ba656f1483f8e8fba0e86ebe817dc/akvo/rsr/models/__init__.py#L214) commits are clearly different so why does the change not show in the [diff](https://github.com/akvo/akvo-rsr/commit/cfae65db742968989f751273a54760e864980c29#diff-40a3a89377750288f9a182b28ef79dd4)?

The fix is of course trivial.

**Comment by punchagan** [comment]
Closed in #3349
