### ISSUE TITLE
EUTF aggregation bug

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3374]
EUTF reports that aggregation from the CTR projects, where updates are made, to the root EUTF project, 4401, doesn't work correctly.

After much digging and false starts I realised it's because there are a few indicators that don't have the correct parent indicator. Or rather they don't have any parent indicator. In most cases it seems liekly that the indicators were added by hand.

The projects with problems are 5363, 5438 5640

### 5363
[5363](https://rsr.akvo.org/en/myrsr/project_editor/5363/), indicator title "Number of people benefiting from professional trainings (TVET) and/or skills development"

The  parent project is [5396](https://rsr.akvo.org/en/myrsr/project_editor/5396/)

When you look at the EUTF results in the two projects it's pretty clear that the indicator was added by hand, as there is no corresponding indicator in the DEC level project.

Project 5363 (CTR level)
![screenshot_346](https://user-images.githubusercontent.com/142613/45677341-3794eb00-bb34-11e8-938f-c537d5753d00.png)
Project 5396 (DEC level)
![screenshot_347](https://user-images.githubusercontent.com/142613/45677348-3c599f00-bb34-11e8-807f-e2c7e273a5b9.png)

There are 15 indicators for the "EUTF indicators" result in the CTR project. In the DEC project there are only 14 indicators and the "Number of people benefiting from professional trainings (TVET) and/or skills development" indicator is not one of them

### 5438

[5438](https://rsr.akvo.org/en/myrsr/project_editor/5438/) has three indicators that have no parent indicator:
- Number of social infrastructure built or rehabilitated
- Number of cross-border cooperations initiatives created / launched or supported
- Number of strategies, policies and plans developed and/or directly supported

The last three indicators have no parent:
![screenshot_348](https://user-images.githubusercontent.com/142613/45677823-711a2600-bb35-11e8-85b8-3125a300b44b.png)

Here it's also pretty clear that the indicators were added by hand as they originate in the "EUTF indicators -new" group of indicators.

### 5640

[5640](https://rsr.akvo.org/en/myrsr/project_editor/5640/) Two indicators 

- "Number of staff from governmental institutions, internal security forces and relevant non-state actors trained on security, border management, CVE, conflict prevention, protection of civilian populations and human rights"
- "Number of activities/events explicitly dedicated to raising awareness and sensitivity of general public regarding migration"

![screenshot_349](https://user-images.githubusercontent.com/142613/45678161-1fbe6680-bb36-11e8-844a-fcb185ddb45b.png)
![screenshot_350](https://user-images.githubusercontent.com/142613/45678164-21882a00-bb36-11e8-9550-19c749d8d022.png)

I'm not sure why these indicators are not part of the hierarchy, as they are in a DEC project and would have been part of the import form 4401.

**Comment by zzgvh** [comment]
To detect this problems of this kind we can add a script that runs once per day, detecting any indicators or periods in the results *EUTF indicators* and *EUTF indicators - new* that do not have a parent.

The script would send an email when problems are found. The recipients of such emails should be determined.

**Comment by punchagan** [comment]
Closed in #3379
