### ISSUE TITLE
Description of the issue with project 6392

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3389]
Project 6392, **CTR - Accompagner la réinsertion économique et sociale des migrants tunisiens de retour, de façon à garantir la dignité des personnes et la pérennité de leurs projets de réinsertion.**, is not correctly set up in the EUTF results framework. After discussing with Stellan and some digging in the database these are my conclusions.

The root cause of the problems with the project stems from the fact that when it was created, project 4401, **EUTF Results Framework**, was set as its parent. The results framework was then imported to 6392. Later the project parent of 6392 was changed to its current value, project 6016, **DEC - Favoriser la mise en œuvre de la stratégie nationale migratoire de la Tunisie**.

When the results framework is imported, all data that keeps track of how the results, indicators and periods relate to each other in the hierarchy are set up. This data cannot be changed, resulting errors in the configuration if the parent project is changed after the results framework has been imported.

### Investigation details

Stellan told me that in project 6392 the indicator **Number of jobs created** seemed to have project 4401, EUTF results framework, as its parent. Since 6392 is a CTR level project it should have a DEC project as its parent.
In the console I checked if the indicator actually had project 4401 as its parent, and it did:
```
>>> project = Project.objects.get(pk=6392)
>>> indicator = Indicator.objects.get(result__project=project, title='Number of jobs created')
>>> indicator.parent_indicator.result.project
<Project: EUTF Results Framework>
```
Stellan was correct.

I then checked if this was the case for all indicators. It was. The whole results framework has 4401 as its parent.

How did this happen?

I looked at the log records for database events related to the projects involved. Those records don't record everything, but enough was there to tell the story.

My suspicion was that the parent project of 6392 had changed. I started looking at edit events for project 6392:
```sql
SELECT * from django_admin_log where (content_type_id = 12 and object_id = '6392')
```
In the result I found these relevant records:

192020	2017-08-02 16:04:41.07927	40055	12	6392	CTR - Accompagner la réinsertion économique et sociale des migrants tunisiens de retour, de façon à garantir la dignité des personnes et la pérennité de leurs projets de réinsertion.	2	*Project editor, changed: Related project (id: 1842): related_project, relation.*
192060	2017-08-02 17:57:56.837244	40055	12	6392	CTR - Accompagner la réinsertion économique et sociale des migrants tunisiens de retour, de façon à garantir la dignité des personnes et la pérennité de leurs projets de réinsertion.	2	*Project editor, changed: Related project (id: 1839): relation.*

The relevant parts are in *italics*. This shows that the project relation was changed twice. But of the relation objects, with IDs 1842 and 1839, only one remained:
```sql
select * from rsr_relatedproject where id = 1839
```
1839	6392	6016	1	

```sql
select * from rsr_relatedproject where id = 1842
```
returns nothing.

Looking at the log for events for the rsr_relatedproject object with ID 1842:
```sql
SELECT * from django_admin_log where (content_type_id = 192 and object_id = '1842')
```
192019	2017-08-02 16:04:41.075144	40055	192	1842	EUTF Results Framework	2	Project editor, changed: related_project, relation.

This shows that this relation was initially set to the EUTF results framework project.

Events for  the rsr_relatedproject object with ID 1839:
```sql
SELECT * from django_admin_log where (content_type_id = 192 and object_id = '1839')
```
191925	2017-08-02 11:00:27.692353	40055	192	1839	DEC - Favoriser la mise en œuvre de la stratégie nationale migratoire de la Tunisie	2	Project editor, changed: related_project, relation.
192059	2017-08-02 17:57:56.831428	40055	192	1839	DEC - Favoriser la mise en œuvre de la stratégie nationale migratoire de la Tunisie	2	Project editor, changed: relation.

Here we see that the object was created at 11.00, but it was later edited at 17.57. We cannot see what the initial value was, but we know that the end result was a relation between projects 6392 and 6016.

My conclusion is that project 6392 was initially set up with EUTF results framework as its parent, then the results framework was imported and only after that was the correct parent assigned. Unfortunately the logs do not include the actual importing event, so this is as far as the investigation can go.

**Comment by punchagan** [comment]
Closing, as this is an investigation report, and there's not really any action to be taken as of now.
