### ISSUE TITLE
Actual project dates should not be mandatory

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3391]
In the project editor, the project actual start and end dates are marked as mandatory. This seems incorrect in relation to IATI export where the actual dates should not be in the future.

**Comment by punchagan** [comment]
These fields have an OR condition with the `planned` start/end dates, i.e., only one of the fields -  planned end date or actual end date, is mandatory.

**Comment by punchagan** [comment]
For IATI compatibility, projects that have not yet been completed should not fill in the actual end date.
