### ISSUE TITLE
Script to restrict user access to EUTF projects

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3410]
To limit the access of the projects of the EUTF hierarchy of users not under EUTF's control, create a management script that sets up access restrictions for the "external" users. This will not be a complete isolation as admins in external organisations will still have access.

**Comment by zzgvh** [comment]
Three last commits should have referenced #3427.

**Comment by punchagan** [comment]
EUTF is not using the project access restriction, and we are working on a better implementation.
