### ISSUE TITLE
Could not resolve host: files.akvo-ops.org when running vagrant

### ISSUE THREAD

**Issue by raarts** [akvo/akvo-rsr#3424]
Hi,

I tried to install rsr locally on my mac and the following happened:

```
Rons-MBP:vagrant raarts$ vagrant up --provision
==> vagrant: A new version of Vagrant is available: 2.2.1!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'rsr-dev-20150209' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'rsr-dev-20150209' (v0) for provider: virtualbox
    default: Downloading: http://files.akvo-ops.org/rsr-dev-20150209.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Could not resolve host: files.akvo-ops.org
```
Tried replacing with `files.akvo.org` but then I got a `404 - Not Found`.

**Comment by dlebrero** [comment]
Thanks a lot for trying RSR. We are in the process of migrating the dev environment to docker-compose. Could you please try the issue/3337-dockerize-django branch?

We haven't up update the dev instructions but it should be:

     docker-compose up

After that you should have an RSR running at http://localhost/en/projects/. The existing user credentials are superme:passwd

**Comment by raarts** [comment]
Ok, this works, except, when I sign in the superme:passwd do not work, it asks for an email address, not a username.

Also the Google maps does not load: `Google Maps JavaScript API error: RefererNotAllowedMapError, Your site URL to be authorized: http://localhost/en/projects/`, but you probably know about that one right?

**Comment by punchagan** [comment]
Thanks for reporting the issue @raarts and sorry for letting this issue go stale. If you are still interested in trying RSR, and have problems, feel free to get in touch. I'm closing this issue for now, since we have made quite some progress with the docker setup and RSR dev environment since this issue was opened. 

Thanks again for trying RSR.
