### ISSUE TITLE
Management script creating "shadow" organisations for the EUTF hierarchy

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3427]
This is a sub task of #3417

To grant EUTF full control over the users in the EUTF hierarchy of projects, create new organisations in RSR for organisations that are partners in EUTF hierarchy projects, but not content owned by EUTF.

The new "shadows" will replace the original organisations as partners in the EUTF projects. For each new organisation created, set up an employment with the new organisation for all non-admin employments in the original organisation.

The new organisations should also be recorded in a new model, that will be used when creating IATI exports for EUTF.

The script can be based on the work done in #3410

**Comment by zzgvh** [comment]
Crap, I kept the old ID when renaming the branch, and thus the commits ended up in #3410.

**Comment by punchagan** [comment]
Closing as done.
