### ISSUE TITLE
Standardize markdown in RSR including reports

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3443]
RSR uses markdown, but only in a few places, currently only the project updates and text fields of narrative indicator updates. The project descriptive fields used to support markdown, but they don't do that any more.

The Report server now supports markdown using the [Showdown package](https://www.npmjs.com/package/showdown). Showdown is also the parser used in the narrative updates, but the project updates are rendered as HTML server-side using django-markup. (We also have the Markdown library in the requirements, but I can find no use of it.)

It seems like a good idea to use one way of parsing markdown to guarantee the same resulting HTML everywhere. Since the report server now uses Showdown with (preliminary) good results this is likely the best option as a non-javascript based solution for the reports is not possible.

If we want to start supporting markdown for the descriptive project text fields again it would probably not be a lot of extra work to change how we render markdown to HTML in project updates since we would use the same pattern in both places.

**Comment by punchagan** [comment]
Would be a good thing to tackle, as we move away from the report-server.
