### ISSUE TITLE
Scripts to fetch data to local docker

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#3466]
Create two scripts, `update-local-db-from-live.sh` and `update-local-db-from-test.sh` fetching data from live and test respectively.

Usage: 
- `update-local-db-from-live.sh -f`: fetch data from live and store in dump file `rsr.dump.live.gz`. Replace existing rsr_db data with the fetched data.
- `update-local-db-from-live.sh`: Replace existing rsr_db data with the fetched data using an existing `rsr.dump.live.gz` dump file.
- Same functionality for `update-local-db-from-live.sh` using `rsr.dump.test.gz`.

**Comment by punchagan** [comment]
We want to move away from fetching data from prod, and the way to fetch data using ElephantSQL dumps works reasonably well.
