### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by martinchristov** [akvo/akvo-rsr#3531]
## Summary

UX reference: https://xd.adobe.com/view/38f0885f-c357-4a4f-7920-a9789541dc13-4ec1/

## API differences

/project - ok

/project_contacts - ok

/partnership
	missing field: amount

/budget_item
	The FE props of the new UI are: amount:int, info:string and type:int (and possibly currency:string).
	The currently existing endpoint has several fields (14) most of which would not be used in the new UI, and the properties that would be used have very confusing names.
	Can we please make a new version of this with less confusing property names?

/recipient_country
	The new FE will work only with a single field: country_code

### A general note
	I see two undesirable patterns throughout the API.
	1) field names:
		taking as our example /recipient_country
		a) since we already have the context of "country" field names should not be prefixed with "country_" as is the case of "country_label"
		b) Then there are ambiguous fields, such as the field "country" which actually contains the country_code. It should have been simply "code".
		c) Then the rest of the fields are not prefixed with "country_" therefore we have mixed naming patterns as well.
	2) Labels (display texts) should not be part of the DB / data models
		in the case of /recipient_country there is a "country_label" field which is a display field and should not be part of the stored data in DB in the same way that i18n files aren't. The same is the case with the fields "label_label" and "currency_label" of /budget_item and with "vocabulary_label" of /sector

/sector

	The situation is similar to /budget_item
	There is an ambiguous parameter "vocabulary", there is a vocabular_label which should not exist. There seems to be a duplicated field: code_label (a duplicate of sector_code).
	The following fields are to be deprecated: percentage, vocabulary_uri, text, code_label

/links - ok

/documents - ok

/label
	should work with label ids only. the actual text of the labels should not be part of the requests

loan terms & loan status?
Are there endpoints for those?

/crs_add_other_flag
	this endpoint responds with an empty array? do we have no entries?!

FSS (extraction date, phaseout year, priority)
	do we have endpoint for this?

/legacy_data - ok

**Comment by punchagan** [comment]
Can we close this issue? Or is there anything from here that hasn't still been fixed in the API?
