### ISSUE TITLE
Allow for more than one 'Dimension value' to be added per 'Indicator Dimension'

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3559]
Currently you can only add one 'Dimension value' per 'Indictor Dimension'. To add another 'Dimension value' you have to add another 'Indicator Dimension' with the same name and then add the additional 'Dimension value'. 

We want the enable to the user to be to add multiple 'Dimension values' per 'Indicator Dimension' at the same time, i.e. without having to add several 'Indicator Dimensions' with the same name.

**Comment by punchagan** [comment]
Done in #3564
