### ISSUE TITLE
Include the dimension values in the aggregation math

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3566]
Dismensions are currently meta-data, not currently adding values, i.e. it's not doing the math.

**Comment by punchagan** [comment]
To allow for partners being unable to collect all the data that they would've liked to collect, we have decided not to include dimension values in the aggregation math.  We've added a flag to mark incomplete disaggregations, and this can be used in future to highlight incomplete/missing data.
