### ISSUE TITLE
Use number fields instead of char 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#3567]
Some work has been done previously (issue to be found and linked)

**Comment by punchagan** [comment]
Make sure that the reports are in sync with these changes.

**Comment by punchagan** [comment]
https://github.com/akvo/akvo-rsr/issues/3153 has some related work that could be useful.

**Comment by punchagan** [comment]
https://github.com/akvo/akvo-rsr/pull/3076 actually did it for the IndicatorPeriodData. We need to make a call on whether we want to do this up the hierarchy, or leave things as is.
