### ISSUE TITLE
Results tab in project view not loading

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-rsr#3591]
Url https://rsr.akvo.org/en/project/7868/#results doesn't load at all. Other projects that also have the Results tab do not load either.

Looking at the dev tools, it seems that https://rsr.akvo.org/rest/v1/project/7868/reports/?format=json is returning a 403. Probably related.

![Screenshot 2019-05-23 at 18 02 16](https://user-images.githubusercontent.com/2147539/58268009-f15bef80-7d84-11e9-8fea-eb6d3a06f785.png)

**Comment by punchagan** [comment]
Closed in #3592
