### ISSUE TITLE
Customizations on public pages

### ISSUE THREAD

**Issue by martinchristov** [akvo/akvo-rsr#3655]
- [x] **logo**
improve design of client pages with custom logos
ex: https://eutf.akvoapp.org/en/projects/
https://mcf.akvoapp.org/en/projects/
*Per-client CSS targeting might be needed*

- [ ] **title**
make it possible for clients to change the page title (currently "Monitor, report and share with ease")

- [ ] **primary color**
have the client choose a color, which would then be used to change the color of the map dots and other elements

- [x] **organization listing**
Change the UI of what is currently under "Primary organization" at https://eutf.akvoapp.org/en/project/7886/
To add an additional label: "Partner organizations" with the full list of partners visible

**Comment by punchagan** [comment]
Closed in #3659
