### ISSUE TITLE
Sector dropdown doesn't support vocabularies other than DAC-3 correctly

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3773]
The new project editor Section-8 shows the same list of codes, irrespective of which vocabulary has been chosen. Vocabulary 1 and 2 have codelists that we support. For other vocabularies, we should allow users to enter the codes directly.

**Comment by martinchristov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sector drop down doesn't support vocabularies](https://trello.com/c/ncbo79SN/31-sector-drop-down-doesnt-support-vocabularies)
