### ISSUE TITLE
Upgrade containers to the latest version of Python 2.7

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-rsr#3820]
When moving to k8s, we tried to upgrade Python version, but we rolled back because we didn't want to change too many things at once, and we noticed some problems with the project feed (`/rss/updates/1711/`).  

Running on the old container has caused us to spend a bunch of time trying to work with the old OS, `pip` and `node` versions. It would be worth spending some time fixing issues we find and upgrading to a newer container, with newer `pip` and `node` versions.

**Comment by punchagan** [comment]
The change looks stable enough from our testing, though the test scripts that compare responses between two instances of RSR could use some work. We can go ahead and release this change, and work on other improvements as we need them.

**Comment by dlebrero** [comment]
>  though the test scripts that compare responses between two instances of RSR could use some work. 

Now I am offended 😄

**Comment by punchagan** [comment]
But, I can point you to your own message listing problems with these scripts! :)

**Comment by dlebrero** [comment]
I hate git!
