### ISSUE TITLE
Qualitative indicators

### ISSUE THREAD

**Issue by martinchristov** [akvo/akvo-rsr#4069]
![Web 1920 – 45.png](https://images.zenhubusercontent.com/5e4557a5503aa44462db194d/5697b518-ecec-4450-88ef-f0f192d43843)

**Comment by loicsans** [comment]
I just spotted a mistake while testing: there are 3 updates, but the total reads a total of 2.
Also 
![Screenshot 2020-04-01 at 9.19.23.png](https://images.zenhubusercontent.com/5cc0217556993227e2467464/c5e1c9aa-c198-49b5-92d5-0893f61fa3c4)

An other thing, it will be good to remove the separating line, it's confusing as to what the 2 updates below are connecting: 
![Screenshot 2020-04-01 at 9.24.43.png](https://images.zenhubusercontent.com/5cc0217556993227e2467464/0b4215ba-9ce9-478b-9519-f2e4475d50a1) to

**Comment by martinchristov** [comment]
Resolved
