### ISSUE TITLE
Outages due to too many too slow PATCH requests

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-rsr#4156]
On 29th Apr at 14:30 and 16:46 RSR was unavailable, returning 502. 

Kubernetes restarted the RSR backend at that time due to failing health check:

```
W 2020-04-29T12:45:49Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T13:53:59Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:44:59Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:45:09Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:45:19Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:45:29Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:45:39Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:45:49Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:45:59Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:46:09Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:46:19Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:46:29Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:46:39Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
W 2020-04-29T14:46:49Z Liveness probe failed: Get http://10.4.0.32:8000/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
I 2020-04-29T14:46:49Z Container rsr-backend failed liveness probe, will be restarted 
```

We see at that time a spike on the DB CPU and transactions, spike on the backend CPU usage and network usage. 

Number of http requests does NOT have a spike.

Looking at the http requests around the time of both outages we found (times in UTC):

|                                               :url | :http-code | :backend-time |    :end-time |  :start-time |
|----------------------------------------------------|------------|---------------|--------------|--------------|
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        12.882 | 14:45:10.034 | 14:44:57.153 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        13.849 | 14:45:10.999 | 14:44:57.150 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |        19.008 | 14:45:16.153 | 14:44:57.146 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |        21.738 | 14:45:18.892 | 14:44:57.155 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |        21.838 | 14:45:18.980 | 14:44:57.142 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |        21.857 | 14:45:19.017 | 14:44:57.161 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        23.359 | 14:45:20.522 | 14:44:57.163 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |        32.298 | 14:45:29.472 | 14:44:57.174 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        33.049 | 14:45:30.228 | 14:44:57.180 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        33.545 | 14:45:30.723 | 14:44:57.178 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |         39.04 | 14:45:36.217 | 14:44:57.178 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |        41.038 | 14:45:38.215 | 14:44:57.178 |
|  PATCH /rest/v1/project_document/1540/?format=json |        200 |        42.648 | 14:45:39.836 | 14:44:57.188 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        43.228 | 14:45:40.429 | 14:44:57.201 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        44.512 | 14:45:41.719 | 14:44:57.207 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        44.872 | 14:45:42.081 | 14:44:57.210 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        51.016 | 14:45:48.230 | 14:44:57.215 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        52.435 | 14:45:49.663 | 14:44:57.228 |
|  PATCH /rest/v1/project_document/1540/?format=json |        400 |        56.311 | 14:45:53.548 | 14:44:57.238 |
|                 GET /rest/v1/my_projects/?limit=16 |        499 |        55.385 | 14:45:54.321 | 14:44:58.937 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.232 | 14:44:57.232 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.237 | 14:44:57.237 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.238 | 14:44:57.238 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.238 | 14:44:57.238 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.239 | 14:44:57.239 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.248 | 14:44:57.248 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.248 | 14:44:57.248 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.248 | 14:44:57.248 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        59.999 | 14:45:57.248 | 14:44:57.249 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        59.999 | 14:45:57.248 | 14:44:57.249 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.250 | 14:44:57.250 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.253 | 14:44:57.253 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.254 | 14:44:57.254 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.255 | 14:44:57.255 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.012 | 14:45:57.272 | 14:44:57.260 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.013 | 14:45:57.272 | 14:44:57.260 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.272 | 14:44:57.272 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.278 | 14:44:57.278 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.278 | 14:44:57.278 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.278 | 14:44:57.278 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.278 | 14:44:57.278 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.278 | 14:44:57.278 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.278 | 14:44:57.278 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.280 | 14:44:57.280 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.281 | 14:44:57.281 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.281 | 14:44:57.281 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.283 | 14:44:57.283 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.283 | 14:44:57.283 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.283 | 14:44:57.283 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.284 | 14:44:57.284 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |          60.0 | 14:45:57.284 | 14:44:57.284 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.285 | 14:44:57.285 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.285 | 14:44:57.285 |
|  PATCH /rest/v1/project_document/1540/?format=json |        504 |        60.001 | 14:45:57.285 | 14:44:57.285 |
| GET /rest/v1/project/?ordering=last_modified_at... |        504 |        60.001 | 14:46:02.686 | 14:45:02.686 |
| GET /rest/v1/project/?ordering=last_modified_at... |        504 |        60.002 | 14:46:04.292 | 14:45:04.290 |
|  GET /en/projects/?organisation=1647&iati_status=4 |        504 |        60.001 | 14:46:08.292 | 14:45:08.292 |
|                                          GET /logo |        499 |        37.743 | 14:46:27.340 | 14:45:49.597 |
|                                    GET /rest/v1/me |        499 |        37.653 | 14:46:27.340 | 14:45:49.688 |
|                 GET /rest/v1/my_projects/?limit=16 |        499 |        37.664 | 14:46:27.345 | 14:45:49.681 |
|                         GET /dev/translations.json |        499 |        37.686 | 14:46:27.346 | 14:45:49.660 |
|                          GET /en/translations.json |        499 |        37.752 | 14:46:27.412 | 14:45:49.660 |
|                                              GET / |        504 |          60.0 | 14:46:31.547 | 14:45:31.547 |
|                              GET /es/project/2089/ |        504 |        60.001 | 14:46:31.916 | 14:45:31.916 |
|                                              GET / |        504 |          60.0 | 14:46:33.047 | 14:45:33.047 |
|                 GET /rest/v1/my_projects/?limit=16 |        499 |        55.006 | 14:46:34.012 | 14:45:39.006 |
| GET /rest/v1/my_projects/?country=za&page=1&lim... |        499 |        44.506 | 14:46:34.015 | 14:45:49.509 |
|                   GET /organisation/4143/iati-org/ |        504 |        60.002 | 14:46:45.521 | 14:45:45.519 |

Outage at 14:30 shows a similar profile but with "PATCH /rest/v1/project_document/1155/?format=json".

All the PATCH requests come from the same IP and same user agent and all happen within a second, so very very likely that they are all from the same user.

Two things need to be fixed:
1. Performance of the PATCH endpoint. 
1. Front end should not be sending 50 PATCH requests within a second.

**Comment by punchagan** [comment]
Both the backend and the front-end have addressed this. I think we can close this for now.
