### ISSUE TITLE
Handle session expiration better

### ISSUE THREAD

**Issue by martinchristov** [akvo/akvo-rsr#4167]
This has been annoying me for a while. I want to open a URL but then I get logged out and upon login my URL is lost.
There are two things that can be done:

- [ ] prevent session expiration
renew the session upon user activity so that expiration will never be experienced by frequent users

- [ ] store the last URL before session expiration redirects to login, then send the user back there

Obviously this is not a priority, but it would be really nice to have. At least one of those.

**Comment by punchagan** [comment]
Django already supports next URLs. https://localhost/sign_in/?next=/en/myrsr/my_project/2/ works, for instance. 

Not sure what causes the redirect, right now. Is Django doing that? Or the front-end code doing that, when it detects that the session has expired?

**Comment by martinchristov** [comment]
Just noticed you had commented. Unfortunately since we're not using Trello which has proper notifications, we must not rely on these threads for communication at all. Unless perhaps we mention each other @punchagan ?

So you're saying the FE has to pass a param next huh? Damn we could have fixed this 5 months ago.
