### ISSUE TITLE
JS and CSS should be served by the nginx

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-rsr#4240]
The new project-directory assets are being served by the backend container while they should be served by the nginx container.

Example: https://rsr.akvo.org/project-directory/main.73ea027ffbef227a477b.js

Check also the project editor to see if it is also the case.

**Comment by punchagan** [comment]
Wow, thanks for catching this, @dlebrero!  @zuhdil would you have time to look into this, or do you want me to look into this?

**Comment by punchagan** [comment]
@dlebrero, I looked through the logs and I wasn't able to confirm that this is actually the case. Could you give a little info on how you caught this?

**Comment by dlebrero** [comment]
My bad. 

I was expecting that there are no logs for the files served by nginx (https://github.com/akvo/akvo-rsr/blob/972e28ce78db9c9d305b5fffe58cb8695ed9926f/nginx/default.conf#L87), but now I see that project directory and the project editor have a special rule (https://github.com/akvo/akvo-rsr/blob/972e28ce78db9c9d305b5fffe58cb8695ed9926f/nginx/default.conf#L22-L21)

Apologies!
