### ISSUE TITLE
Notes on the organisation import data format

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#425]
The XML format we use for importing Organisations is based on the XML format of django-tastypie. This issue is for the discussion of the template format and the reporting of problems around it.

The template can be found here: https://github.com/akvo/akvo-rsr/blob/wiki-docs/docs/RSR%20Features/API/Sample-XML-Files-for-API-Load.md#organisation-file

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/cascade-not-mandetory
Assignee: Geert Soet

Message:
Hi,

Incoming issue regarding cascade data that is not filled fully (so for example only the first two levels) while the question is mandatory.

https://m3p-eva-rdc.akvoflow.org/admin/
Enquête M3P finale 
Questionnaires villages 
V2A_Comité MeO

G
