### ISSUE TITLE
Enumerator form shows all indicators instead of those that are assigned

### ISSUE THREAD

**Issue by martinchristov** [akvo/akvo-rsr#4432]
The following form for Anthony's user is supposed to show only a single indicator (the one he has been assigned to in project 9581).
However the entire RF is loaded instead.

Here is a link to a form:
https://rsr.akvo.org/my-rsr/projects/9581/results/?rt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtYXgiOjE1MCwic3ViIjoid2ViLWZvcm1zIiwibW9kIjoiciIsImp0aSI6MSwiYXVkIjo0MDQzOCwiZXhwIjoxNjQzOTcyNjE0LCJpYXQiOjE2MDc0NDMwODh9.VYSejex_sfCS85quuXh1nXd5zMHdfozEHWDavckOh_0

The RF is loaded via:
https://rsr.akvo.org/rest/v1/project/9581/results_framework/?rt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtYXgiOjE1MCwic3ViIjoid2ViLWZvcm1zIiwibW9kIjoiciIsImp0aSI6MSwiYXVkIjo0MDQzOCwiZXhwIjoxNjQzOTcyNjE0LCJpYXQiOjE2MDc0NDMwODh9.VYSejex_sfCS85quuXh1nXd5zMHdfozEHWDavckOh_0

**Comment by punchagan** [comment]
The filtering happens only for Enumerators, and super users don't see filtered views. 
This is the relevant commit. https://github.com/akvo/akvo-rsr/commit/03c1848919906fcf52c6693a30280df0559b5145#diff-0b8dffaf8fb14dfb442fd31e34e40e759fd779a0b39272b3a820519385f28fef

**Comment by punchagan** [comment]
https://akvo.zulipchat.com/#narrow/stream/131441-rsr/topic/Enumerator.20form.20showing.20entire.20RF has more discussion on this.
