### ISSUE TITLE
Actions & notifications

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#444]
This is a recap issue from past work on #229, #144, #396 and recent discussions with the team. This issue will not cover everything from past issues but be a pragmatic way forward.

# Context
There goes a lot of **manual labour into supervising projects in RSR**. To be on top of *your interests* as a RSR admin, partner admin or project editor you need to scan RSR in a pull way (manually polling RSR). RSR users crave for notifications & monitoring tools to help them manage *their* projects & organisations.

# Problem
RSR users often need to act when another RSR user performs an action in RSR. One example of this is when a project reaches *fully funded* status, and a partner admin needs to manually set the project to *active* and transfer collected funds to the partner. **Today there are no tools in RSR that helps with this manual labour**. Further, RSR admins have requested a way to easily edit email going out to users. Problems summary:

- Users need to act based on events from other users actions
- Users want to be able to get an overview of activities in their projects
- RSR admin want to be able to customize emails we send out

There have also been a request for periodic *digest* emails based on these events, this would enable to view "no actions" on projects & organisations.

# Idea
For performance reasons we don't want to deal with sending emails in the Django request/response cycle. What we would like to do is to hand of events and let the Django response back quickly to the user. **We also want to be future proof and support the possibility of new services**. Hence we should create a **new service that transforms events from services to notifications that are then pushed to the user**. Users can configure if they want notifications via email and/or in the web UI.

## Goals
- A user should be able to subscribe to projects and organisations
- A user should be able to view notifications in a web UI
- A user should be able to get notified via email
- A user should be able to configure emails to be sent as summaries.

## Non-goals
- All use cases will not be supported in the first phase

# Product design

## Follow project
On a project page we need to allow authenticated users to subscribe to the project.

## Events
RSR needs to emit events with the following data:
- service (akvo-rsr)
- entity (project, organisation, user, ...)
- type (donation, ...)
- body (tailored based on type (donation would require amount, datetime, currency...)
- meta (when event was emitted)

## Notification UI (myAkvo)
Need to query the notifications service for notifications and show them in myAkvo. Further out we should also be able to set user preferences for notifications in myAkvo via the API.

## Product design
Since we have the need for a generic solution 
- [Issue](https://github.com/akvo/akvo-product-design/issues/12)
- [Functional design](https://github.com/akvo/akvo-product-design/blob/master/RSR/Features/12-ActionBasedNotifications/FunctionalDesign/ActionBasedNotifications.md)
- [Technical design](https://github.com/akvo/akvo-product-design/blob/master/RSR/Features/12-ActionBasedNotifications/TechnicalDesign/ActionBasedNotifications.md)

**Comment by kardan** [comment]
With the initiative to bring a unilog system to Akvo this needs to be reviewed and adapted.

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#160
