### ISSUE TITLE
Docker build - akvo-rsr_web_1 exited with code 127

### ISSUE THREAD

**Issue by ronna** [akvo/akvo-rsr#4503]
PS E:\Github\akvo-rsr> docker-compose up --build
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Building web
failed to get console mode for stdout: The handle is invalid.
[+] Building 14.0s (15/15) FINISHED
 => [internal] load build definition from Dockerfile-dev                   0.7s
 => => transferring dockerfile: 36B                                        0.5s
 => [internal] load .dockerignore                                          0.3s
 => => transferring context: 35B                                           0.1s
 => [internal] load metadata for docker.io/library/python:3.8.1-buster    12.7s
 => [internal] load build context                                          0.1s
 => => transferring context: 296B                                          0.1s
 => [ 1/10] FROM docker.io/library/python:3.8.1-buster@sha256:3322c368377  0.0s
 => CACHED [ 2/10] RUN set -ex; apt-get update &&     apt-get install -y   0.0s
 => CACHED [ 3/10] RUN curl https://bootstrap.pypa.io/get-pip.py -o get-p  0.0s
 => CACHED [ 4/10] RUN curl -fsSLO --compressed "https://nodejs.org/dist/  0.0s
 => CACHED [ 5/10] RUN addgroup akvo && adduser --disabled-password --hom  0.0s
 => CACHED [ 6/10] WORKDIR /var/akvo/rsr/code                              0.0s
 => CACHED [ 7/10] COPY scripts/deployment/pip/requirements/2_rsr.txt ./   0.0s
 => CACHED [ 8/10] RUN pip install --no-cache-dir -r 2_rsr.txt             0.0s
 => CACHED [ 9/10] COPY scripts/deployment/pip/requirements/3_dev.txt ./   0.0s
 => CACHED [10/10] RUN pip install --no-cache-dir -r 3_dev.txt             0.0s
 => exporting to image                                                     0.2s
 => => exporting layers                                                    0.0s
 => => writing image sha256:1c123dfa521e211f03f81ee850fdbea69dfb02151a295  0.0s
 => => naming to docker.io/library/akvo-rsr_web                            0.0s
Successfully built 1c123dfa521e211f03f81ee850fdbea69dfb02151a29546900b74f8fc66e2977
Building reports
failed to get console mode for stdout: The handle is invalid.
[+] Building 3.3s (15/15) FINISHED
 => [internal] load build definition from Dockerfile-dev                   0.4s
 => => transferring dockerfile: 36B                                        0.1s
 => [internal] load .dockerignore                                          0.2s
 => => transferring context: 35B                                           0.1s
 => [internal] load metadata for docker.io/library/python:3.8.1-buster     1.9s
 => [ 1/10] FROM docker.io/library/python:3.8.1-buster@sha256:3322c368377  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 296B                                          0.0s
 => CACHED [ 2/10] RUN set -ex; apt-get update &&     apt-get install -y   0.0s
 => CACHED [ 3/10] RUN curl https://bootstrap.pypa.io/get-pip.py -o get-p  0.0s
 => CACHED [ 4/10] RUN curl -fsSLO --compressed "https://nodejs.org/dist/  0.0s
 => CACHED [ 5/10] RUN addgroup akvo && adduser --disabled-password --hom  0.0s
 => CACHED [ 6/10] WORKDIR /var/akvo/rsr/code                              0.0s
 => CACHED [ 7/10] COPY scripts/deployment/pip/requirements/2_rsr.txt ./   0.0s
 => CACHED [ 8/10] RUN pip install --no-cache-dir -r 2_rsr.txt             0.0s
 => CACHED [ 9/10] COPY scripts/deployment/pip/requirements/3_dev.txt ./   0.0s
 => CACHED [10/10] RUN pip install --no-cache-dir -r 3_dev.txt             0.0s
 => exporting to image                                                     0.5s
 => => exporting layers                                                    0.0s
 => => writing image sha256:1c123dfa521e211f03f81ee850fdbea69dfb02151a295  0.0s
 => => naming to docker.io/library/akvo-rsr_reports                        0.0s
Successfully built 1c123dfa521e211f03f81ee850fdbea69dfb02151a29546900b74f8fc66e2977
Starting akvo-rsr_mainnetwork_1   ... done
Starting akvo-rsr_rsrdbhost_1     ... done

Starting akvo-rsr_nginx_1         ... done
Starting akvo-rsr_web_1           ... done
Starting akvo-rsr_reports_1       ... done
Attaching to akvo-rsr_mainnetwork_1, akvo-rsr_rsr-memcached_1, akvo-rsr_rsrdbhost_1, akvo-rsr_nginx_1, akvo-rsr_reports_1, akvo-rsr_web_1
reports_1        | /usr/bin/env: ‘bash\r’: No such file or directory
rsrdbhost_1      |
rsrdbhost_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
rsrdbhost_1      |
rsrdbhost_1      | LOG:  database system was shut down at 2021-04-28 06:40:18 UTC
rsrdbhost_1      | LOG:  MultiXact member wraparound protections are now enabled
rsrdbhost_1      | LOG:  database system is ready to accept connections
rsrdbhost_1      | LOG:  autovacuum launcher started
web_1            | /usr/bin/env: ‘bash\r’: No such file or directory
akvo-rsr_reports_1 exited with code 127
akvo-rsr_web_1 exited with code 127

**Comment by ronna** [comment]
Pointers  on how to solve the issue will be greatly appreciated

**Comment by iperdomo** [comment]
Hi @ronna thanks for trying out Akvo RSR.

The usual problem with Windows machines is the end of line. If you're not familiar with that, you can check this one: https://en.wikipedia.org/wiki/Newline

The problem is that when you clone the repo, your git client converts the files to your host operating system *eol* and that is why you're getting this particular error messages:

> reports_1 | /usr/bin/env: ‘bash\r’: No such file or directory
> web_1 | /usr/bin/env: ‘bash\r’: No such file or directory

That extra character `\r` is **not** correct.

@zuhdil @punchagan the usual trick for this is to *force* the `.sh` files to use `LF` for eol, via `.gitattributes`

```
*.sh           text eol=lf
```
More examples: https://github.com/alexkaratarakis/gitattributes/blob/c9e0391fd0f045478a3d122979eeb23d2311e21a/Common.gitattributes#L53

**Comment by ronna** [comment]
Hi @iperdomo 

Thanks for the warm welcome.

I have moved to Linux, Ubuntu 18.04 and I am getting a different error. I will open a new issue
