### ISSUE TITLE
Admin username and password - Akvo-rsr Docker

### ISSUE THREAD

**Issue by ronna** [akvo/akvo-rsr#4510]
I want to try Akvo-rsr using docker, what is the admin username and password? I have created an account is it possible to grant admin privileges to that account?

**Comment by punchagan** [comment]
You should be able to use the Django shell to make your user a super user. 

You can start a Django shell by running the following command:
```sh
docker-compose exec web python manage.py shell
```

And then run the following Python code in the shell. 

```py
from akvo.rsr.models import User
email = 'foo@example.com'  # The email ID of your user
u = User.objects.get(email__iexact=email)
u.is_active = True
u.is_superuser = True
# u.set_password('password')  # If you want to set the password
u.save()
```

**Comment by ronna** [comment]
Hi @punchagan 
Thanks, that worked

**Comment by ronna** [comment]
Hi @punchagan 

Sorry, I don't seem to get full admin access, I can not access the menu's that I think I should access as an admin. As a workaround, I tried to login into the Django admin and got the below error. Your assistance will be greatly appreciated

![image](https://user-images.githubusercontent.com/1917293/116894475-5e938300-ac32-11eb-9614-b135ca58f6d7.png)

**Comment by ronna** [comment]
Please ignore, I have managed to create the Django super user.
