### ISSUE TITLE
Code cleaning Front End with linter 

### ISSUE THREAD

**Issue by ifirmawan** [akvo/akvo-rsr#4525]
## Summary
I already setup my text editor automatically fix JS code with linter, to avoid any changing by linter in the future I decide to make it clean first.

**Comment by punchagan** [comment]
Is this something standard like `prettier`? Can we run this in CI to ensure we don't commit more such code?

**Comment by ifirmawan** [comment]
yes @punchagan, I have no experience using CI but I will try to find out how.
