### ISSUE TITLE
WCARO New landing page

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-rsr#4549]
Build and replace the current RSR homepage for the WCARO project following the current structure.
Content is to be provided.![Web 1366 – 25.png](https://images.zenhubusercontent.com/5cc0217556993227e2467464/40ad9ec2-5922-4c5e-9186-bb3d9e2a32e2)

**Comment by ifirmawan** [comment]
## Template
- [ ] Top Navbar
- [ ] Heading Title
- [ ] Heading Filter
- [ ] Banner
- [ ] Implement Program Countries API
- [ ] Implement Program Updates API (_Stories_)
