### ISSUE TITLE
Self hosted production install best practices

### ISSUE THREAD

**Issue by ronna** [akvo/akvo-rsr#4553]
We are planning on self-hosting what best practices and install method do you recommend? Is there documentation for a production install

**Comment by punchagan** [comment]
@ronna Akvo uses Kubernetes to host RSR. You can find (templates for) the configuration in `ci/k8s`. RSR was previously hosted on a Cloud VPS using supervisord and gunicorn. We've switched over to using Kubernetes for managing the deployments a couple of years ago. I'd recommend using any of the methods depending on what you are most comfortable with running and debugging.  We have a grafana to track system metrics, and comes in handy when trying to debug some slow queries/API calls, etc. We don't have detailed production documentation, unfortunately.

**Comment by ronna** [comment]
Hi @punchagan 

Thanks for the response. I am still learning docker and Kubernetes. I have a DigitalOcean account and I am going to create a Kubernetes cluster. Looking at the files in ci/k8s what config settings should I use for storage. I am not going to use Google Storage.  Pointers to online resources that I can use will be greatly appreciated. Thanks.

**Comment by punchagan** [comment]
I think the default settings would use the disk - which is what we use locally, for development, if I'm not wrong. Also, if you are able to get a postgres db and an nginx running, you could get the setup running without all the Kubernetes stuff. It is convenient for us (Akvo) to use k8s since we use it with other products too, but not strictly necessary to run RSR.

**Comment by ronna** [comment]
Morning @punchagan 

Thank you so much for the responses. I want to try the PostgreSQL, Nginx route. Once I have the database and Nginx up and running how do I go about running the akvo rsr code?

**Comment by punchagan** [comment]
> Thank you so much for the responses. I want to try the PostgreSQL, Nginx route. Once I have the database and Nginx up and running how do I go about running the akvo rsr code?

`prod/start-django.sh` is the entry point that we use to start the Django server. That should explain everything you need?
