### ISSUE TITLE
Use a real queue worker

### ISSUE THREAD

**Issue by zuhdil** [akvo/akvo-rsr#4680]
Currently, RSR uses cronjobs to handle one-time background tasks. Using a proper queue worker opens up the possibility to defer tasks to the queue such as sending email and processing data that was previously done in the request handler.

**Comment by MichaelAkvo** [comment]
There are multiple available choices. The most known one is probably Celery and maybe Apache Kafka.

| Name        | active | Task end signal | Uses django ORM | python package | Ease of use | setup costs |
|-------------|--------|-----------------|-----------------|----------------|-------------|-------------|
| [celery]    | yes    | yes             | yes             | yes            | medium      | medium      |
| [django-q]  | no     | no              | yes             | yes            | easy        | low         |
| [dramatiq]  | yes    |                 | no              | yes            |             | medium      |
| [kafka]     | yes    |                 |                 | no             | difficult   | high        |
| [python-rq] | yes    |                 | no              | yes            | easy        | medium      |


[celery]: https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html
[django-q]: https://django-q.readthedocs.io/en/latest/index.html
[dramatiq]: https://dramatiq.io/
[kafka]: https://kafka.apache.org/intro
[python-rq]: https://python-rq.org/

**Comment by MichaelAkvo** [comment]
Celery requires rabbitMQ or some other message queue. Seems like an unnecessary hassle for what we want to do (run a few jobs async). It's not like we're some high throughput application. Should we require high performance, multiple workers, and 5 9s for async tasks, we can talk about rabbitmq, kafka, etc.
