### ISSUE TITLE
Can't delete periods copied from defaults with targetsAt == "indicator"

### ISSUE THREAD

**Issue by MichaelAkvo** [akvo/akvo-rsr#4754]
# Scenario

Given a parent project / program that has targets at indicator level

![image.png](https://images.zenhubusercontent.com/615f039319c1f837a3cdece3/e5b5dd30-4d2e-4edc-bb0e-8303ba9a8f39)

and a child project, in the child project:

 - Create a new result (Outcome) with a quantitative indicator (shouldn't matter)
 - Setup period defaults
 - Copy the defaults
 - Try to delete a period

### Expected

The period is deleted

### Actual

An error message is shown and the period disappears, but is present on a refresh.

![image.png](https://images.zenhubusercontent.com/615f039319c1f837a3cdece3/80ab6f3b-0a22-4c71-8cdc-28d0438093aa)

See video

https://images.zenhubusercontent.com/390217/2e35d988-b965-4a83-a36d-3cd5224f08b9/delete_a_period.mp4

**Comment by MichaelAkvo** [comment]
This looks like a problem in the frontend

![image.png](https://images.zenhubusercontent.com/615f039319c1f837a3cdece3/9a5ef75c-ca38-4dbe-a952-fe279d694b47)

The request to delete the copied, default period is missing an ID

**Comment by ifirmawan** [comment]
I'm working on this issue
