### ISSUE TITLE
Bug: Upload document not working in section 9

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#4814]
### What were you doing?

Partner was trying to upload a document in section 9 of the Project Editor and could not. 

https://rsr.akvo.org/my-rsr/programs/10189/editor/links-n-docs

### What should've happened?

The partner should have been able to upload a document from their desktop. 

### My environment

unknown.

**Comment by MichaelAkvo** [comment]
The problem is the missing upload field

![image](https://user-images.githubusercontent.com/91939214/151952964-db141a03-ff77-4e0d-b73e-225046563df1.png)

*Notice the missing field where users can drop a file*
