### ISSUE TITLE
Bug: Plan Finland Report hardcoded on the Reports page

### ISSUE THREAD

**Issue by ronna** [akvo/akvo-rsr#4897]
### What were you doing?

It looks like the Plan Finland Report is hardcoded on the reports page: http://localhost/my-rsr/projects/3/reports

![image](https://user-images.githubusercontent.com/1917293/158165431-17a16c73-2db2-45fd-af1e-96ef0871bfea.png)

### What should've happened?

I don't have access to the Plan Finland project thus, I should not see that report menu. Unfortunately, I can no download the report due to #4896

**Comment by MichaelAkvo** [comment]
Needs confirmation if we already removed it, but in general this might become a bigger task to migrate away from the custom report server.

**Comment by gdeflaux** [comment]
Does not affect production
