### ISSUE TITLE
Bug: UI issue with Hierarchy tab

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#4910]
### What were you doing?

I selected a different sub-program in the Hierarchy tab but the originally selected sub-program remained highlighted in addition to the newly selected sub-program.  

![Description field testing_22](https://user-images.githubusercontent.com/26227538/159513251-24a46181-5489-492f-8e29-c8a7154d65fe.gif)

### What should've happened?

The UI should only highlight one sub-program at a time, the most recent one the user has selected.

**Comment by ifirmawan** [comment]
## Invalid selected card
http://localhost/my-rsr/projects/8798/hierarchy

## Fix title alignment / position
<img width="1433" alt="Screen Shot 2022-09-14 at 09 55 16" src="https://user-images.githubusercontent.com/20871229/190048543-d73732f2-6257-4d34-9c73-34c0024a304b.png">
