### ISSUE TITLE
Bug: Some IATI validation errors not shown when exporting

### ISSUE THREAD

**Issue by zuhdil** [akvo/akvo-rsr#4923]
### What were you doing?

Partner reports their IATI file has the following errors
- Budget Period must not be longer than one year.
- The actual must have a value when the indicator measure is non-qualitative (e.g. 1 = unit, 2 = percentage, 3 = nominal, 4 = ordinal).
- Recipient country or recipient region should be declared for either the activity or for all transactions.
- The baseline must have a value when the indicator measure is non-qualitative (e.g. 1 = unit, 2 = percentage, 3 = nominal, 4 = ordinal).

### What should've happened?

Show the errors when exporting IATI file

**Comment by MichaelAkvo** [comment]
Already resolved
