### ISSUE TITLE
[Hierarchies] FE Remove dependency on `related_projects`

### ISSUE THREAD

**Issue by MichaelAkvo** [akvo/akvo-rsr#4969]
In #4710, we remove the backend depedency on RelatedProjects, but the frontend does still depend on it.

# TODO

## Replace dependency on `RelatedProject`  in FE

The most likely candidates can be found by searching [`relatedProject`](https://github.com/akvo/akvo-rsr/search?l=JavaScript&q=relatedProject)

## Remove call to `related_projects` in FE

Currently it breaks the project editor

```
Uncaught (in promise) Error: Request failed with status code 404
    createError createError.js:16
    settle settle.js:17
    handleLoad xhr.js:62
    dispatchXhrRequest xhr.js:37
    xhrAdapter xhr.js:13
    dispatchRequest dispatchRequest.js:52
    promise callback*request Axios.js:61
    wrap bind.js:9
    get api.js:47
    fetchSet project-init-handler.js:43
    _callee$ project-init-handler.js:63
    Babel 10
    fetchSection project-init-handler.js:18
    fetchNextSection project-init-handler.js:69
    ProjectInitHandler project-init-handler.js:97
    React 6
    wrapped scheduler-tracing.development.js:207
    React 4
```

Probably the call in https://github.com/akvo/akvo-rsr/blob/master/akvo/rsr/spa/app/modules/editor/project-init-handler.js#L43

--------------

A related task might probably be #4934

**Comment by ifirmawan** [comment]
I leave comment here, just to remember how to run migration
https://github.com/akvo/akvo-rsr/pull/4970#issuecomment-1208242522
