### ISSUE TITLE
Add a language choser

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#5]
The language choser will sit in the top right corner.

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-4972-from-geertsoet-at-gmail-dot-com
Assignee: Unassigned

Message:
[AKVOFLOW] Support request #4,972 from geertsoet@gmail.com 
 
  
    
 
    Geert Soet (https://akvoflow.supporthero.io)   
  
 
  
 
 
    
 
 User email: geertsoet@gmail.com 
 Request Info 
Device:  Personal computer 
Browser:  Chrome 46.0.2490.80 
OS:  OS X 10.10.5 
IP Address:  95.97.154.90 
URL:  http://flowsupport.akvo.org/article/show/can-i-import-data-into-a-registration-form 
 User name 
Geert 
 Request Info 
Hey , how I import a cascade? 
 
  
   
 
 
 Notification sent by Supporthero.io - 11/9/15 12:27 PM (http://www.supporthero.io)
