### ISSUE TITLE
Bug: Editor not loading/Long delays before loading

### ISSUE THREAD

**Issue by ifirmawan** [akvo/akvo-rsr#5073]
### What were you doing?

On Firefox there are long delays but the editor eventually loads. This specifically happens when you navigate to the page directly e.g. [https://rsr.akvo.org/my-rsr/projects/10397/contacts](http://url/) Screenshot of what the users are experiencing

![image](https://user-images.githubusercontent.com/20871229/184268973-d253a436-91bf-4de8-aeaa-086761119fd7.png)

### What should've happened?

project editor must hide loading indicator after data is loaded.

**Comment by ifirmawan** [comment]
![Uploading Screen Shot 2022-10-21 at 18.42.13.png…]()

**Comment by ifirmawan** [comment]
**Invalid timezone in certain project**

<img width="613" alt="Screen Shot 2022-10-21 at 19 34 35" src="https://user-images.githubusercontent.com/20871229/197196799-8f040000-7218-4b1d-b1aa-6781140f9899.png">

**Comment by MichaelAkvo** [comment]
Fixed long ago
