### ISSUE TITLE
Bug: Some project not visible in public

### ISSUE THREAD

**Issue by ifirmawan** [akvo/akvo-rsr#5085]
### What were you doing?

I'm trying to open a public project page with 2 scenarios

## Logged user
> it's Work

### Project Editor
1. Login with my account
2. Go to published project
3. Move to project editor 
4. Click *View project page*

### Landing page
1.  Click any project from project list

## Anonymous User
> Seems doesn't work

1.  Open project by URL directly
[http://localhost/dir/project/10256](http://localhost/dir/project/10256)

4. I got response like this from this end point 
> http://localhost/rest/v1/project/10256/?format=json
```
{"detail":"Not found."}
```

### What should've happened?

Published projects should be publicly visible without any exceptions

**Comment by MichaelAkvo** [comment]
@ifirmawan looks like the project is private

![image](https://user-images.githubusercontent.com/91939214/186440371-ae7ae184-5855-4e03-a9fe-3e4e509e5fd6.png)


Setting it to public should solve the issue. Keep in mind though, there's a 1 day cache, so the change might take 24h to be visible on public pages.

**Comment by ifirmawan** [comment]
ah okay @MichaelAkvo , will do
