### ISSUE TITLE
Feature Request: Cumulative indicator updates support for reports

### ISSUE THREAD

**Issue by zuhdil** [akvo/akvo-rsr#5129]
### What are you trying to do?

Adjust reports to support the cumulative indicator updates feature

### Describe the solution you'd like

Reports that need to be adjusted
- results_indicators_with_map_pdf_reports.py
- results_indicators_excel_report.py
- kickstart_word_report.py
- eutf_org_results_table_excel_report.py
- program_overview_pdf_report.py
- program_period_labels_overview_pdf_report.py
- program_overview_excel_report.py
- project_results_indicators_excel_report.py

**Comment by MichaelAkvo** [comment]
Fixed in https://github.com/akvo/akvo-rsr/pull/5130
