### ISSUE TITLE
REST framework on https

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#634]
This is a suggestion to get us started on https. The new Django Rest Framework based API would make a good candidate for using https. Using a separate domain, e.g. api.akvo.org would make it "easy" to set up since there are few complications like those I suspect we'll have with partner sites and media for the rest of RSR.

As much of the work here lies on the deployment/ops side it'd be good to hear thoughts from @osgl  and @carlio.

**Comment by KasperBrandt** [comment]
@zzgvh @orifito For the partners that are currently using the API, you think we can redirect them from http:// to https:// ?

**Comment by orifito** [comment]
@KasperBrandt @zzgvh @osgl Yes, it's fine with us to setup SSL on RSR API. We could use a separate domain, or simply use the nginx's map to define a set of URIs and their preferred protocols.

**Comment by KasperBrandt** [comment]
@zzgvh @peeb Is there anything we should do in RSR itself for this?

**Comment by zzgvh** [comment]
We've decided to try do SSL for all or RSR in one go. See #29 for more info.
