### ISSUE TITLE
New user registration - sent to anke?

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-rsr#736]
HI does anyone know how/where RSR gets the email addresses to fill the below "new user registration' receivers?  Anke@vanlenteren.com has been included & we're not sure why.

Begin forwarded message:

> From: noreply@rsr.akvo.org
> Subject: A new user has registered with Akvo
> Date: 18 September 2014 12:21:15 PM GMT+02:00
> To: gabriel@akvo.org, thomas@akvo.org, peter@akvo.org, luuk@akvo.org, daniel@fraction4.com, mark@akvo.org, olivergl@akvo.org, gvh@concinnity.se, m.t.westra@gmail.com, anke@vanlenteren.com, kathelyne@akvo.org, daniel@akvo.org, jo.pratt@akvo.org, laura@akvo.org, anna-marthe@akvo.org, charlotte@akvo.org, frodo@akvo.org, amitangshu@akvo.org, lissy@akvo.org, josje@akvo.org, adrian@akvo.org, alcollier@gmail.com, linda@akvo.org, loic.sans@gmail.com, phylis@akvo.org, RSR_partner_admin_test@akvo.org, stellanl@akvo.org, henry@akvo.org, lynn@akvo.org, stefan@akvo.org, isha@akvo.org, elma@akvo.org, francis@akvo.org, emeline@akvo.org, rajashi@akvo.org, joyce@akvo.org, pelleaardema@gmail.com, carl@akvo.org, ruarcc@gmail.com, akvoqa@gmail.com, dagmar@akvo.org, tim.janssen@akvo.org, kendra@akvo.org, andrew@akvo.org, Giel@akvo.org, siem@zimmermanzimmerman.nl, kasper@akvo.org, dan@akvo.org, stefan.kraus@akvo.org, marten@akvo.org, emily@akvo.org
>
> Organisation: Akvo
>
> A new user has registered under your organisation in the Akvo RSR system.
>
> Name: Samuel Rajkumar
> Username: srajkumar
> Email: srajkumar@ternup.com
>
> Please check the credentials of this user and then activate here:
> http://rsr.akvo.org/admin/rsr/userprofile/1849/
>
> Thank you,
> Akvo.org

**Comment by adriancollier** [comment]
After the v3 changes we plan on doing an update to the support process. This will be to ensure that users have the correct access when supporting partners as well as finally putting control over receiving this email or not into the hands of users.
