### ISSUE TITLE
Add server info to response header

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#749]
For debugging purposes the Up app (and possibly other clients too) could use the RSR version info, like the one that's visible in the admin. 

Suggested implementation of this is as a custom response header using the same format as in the admin:

X-RSR-Version: &lt;version tag&gt; (&lt;commit hash&gt;) [&lt;branch name&gt;]

A small middleware class is one way to implement this across all server responses. But I'd like to hear from @carlio or @osgl if this could be added at an even "lower" level in the webserver configuration.

**Comment by kardan** [comment]
What's the status on this?

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN a request to RSR
WHEN a response is given
THEN the response header in the form of X-RSR-Version: tag={tag}, commit={commit}, branch={branch} is returned
