### ISSUE TITLE
RAIN Import logging feedback

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#767]
Had a meeting with Basja, and there are a few things that we should look into wrt delivery of logging information that would help RAIN a great deal:

1. At the moment the CSV files seem to be strangely encoded, and do not separate into columns when opening in Excel.
2. Are we able to create an additional version of post_import with only the "errors" present?
3. Do we need to provide also a list of "this is currently published in RSR"? We will confirm this need next week.

**Comment by KasperBrandt** [comment]
Talked to Riny, the current summary of the import is fine.
