### ISSUE TITLE
Editing permissions of organisations other than your own.

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#795]
## Test plan
GIVEN the MyRSR user management page (/myrsr/user_management)
WHEN logged in as an organisation admin or user manager
THEN you should be able to see and approve/decline all users from your organisation __AND__ the organisations that have your organisation as a content_owner __AND__ organisations being content owned by that organisation, etc.

GIVEN the old organisation admin (/admin/rsr/organisation/)
WHEN logged in as an organisation admin or project editor
THEN you should be able to see and edit your organisation __AND__ all organisations that have your organisation as a content_owner __AND__ organisations being content owned by that organisation, etc.

## Issue description
This issue is a result of talking to Uddy who's implementing the PIND data import into RSR using the API. I think we need to extend the organisations users belonging to the Partner Admin group is allowed to access to those organisations that have the **content_owner** field set to the organisation of the user.

**Comment by KasperBrandt** [comment]
There's a bug when the organisation is it's own content_owner, causing an endless loop. See http://sentry.support.akvo-ops.org/rsr/test/group/621/.

**Comment by KasperBrandt** [comment]
Fixed in #1844
