### ISSUE TITLE
Review RSR tests

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#809]
Right now the tests break on the vagrant box. The first issue is that there is no test database setup and when that is created migrations break. We need to fix this to be able to write tests.

**Comment by kardan** [comment]
@osgl @rumca @zzgvh Anyone got a idea of the current state of RSR tests, and can chat with me about it?

**Comment by kardan** [comment]
Almost forgot, on the vagrant box we need to enable the rsr ROLE to create dbs
```sql
ALTER USER django CREATEDB;
``

**Comment by kardan** [comment]
Tests can be run from scripts/devhelpers with ./manage.sh test akvo.rsr

**Comment by kardan** [comment]
Tests now work but required some heavy lifting (since they exposed that the Akvo pages broke after the Django 1.7 upgrade). So new dispatch middleware that make sure the correct data is available based on the partner site object.

**Comment by KasperBrandt** [comment]
## Test plan
As @kardan mentioned, automated tests can now be run from scripts/devhelpers with ```./manage.sh test akvo.rsr```
