### ISSUE TITLE
FocusArea -> SectorCategory & Category -> Sector ?

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#872]
Would it make sense from an IATI point of view to move towards this?
http://iatistandard.org/codelists/SectorCategory/
http://iatistandard.org/codelists/Sector/

**Comment by adriancollier** [comment]
Yes.

- [ ] map the current entries for Focus Area to the IATI 3 digit sector code. (https://trello-attachments.s3.amazonaws.com/542951293a830a4f384d0260/542951329181301b811252c4/d36e1f4e5d6ed42cf2bca3ab51a4e8af/rsr_oecd_focusarea_sector.xlsx)
- [ ] map the current entries for Category for IATI 5 digit sector code. (https://trello-attachments.s3.amazonaws.com/542951293a830a4f384d0260/5429513cc9bdde6938579ada/a3d4c0cfa088f7bd354ea7f6f712419d/RSR_oecd_category_sector_analysis.xlsx)

- [ ] display 3 digit sector codes on the project list page
- [ ] display both 3 and 5 digit codes on the project page
