### ISSUE TITLE
User Upload Image

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#898]
When a user is uploading an image, often their image is the wrong shgape or size and cannot be displayed the way they wish within the frame we use.

Additionally, with the RSR v3 redesign, we are changing the frame shape slightly to fit a more modern web experience.

In order to ensure that we can help users with this process we should provide some additional functionality to assist on upload.

Something like this could be used: http://codecanyon.net/item/closify-powerful-flexible-image-uploader/full_screen_preview/8292742 (though I think this is PHP and need not be the actual implementation used).

User Story:
https://trello.com/c/gXTRr9PZ

**Comment by lauraroverts** [comment]
@KasperBrandt this issue has been solved with RSR 3.0, rights?

**Comment by KasperBrandt** [comment]
@lauraroverts Nope, but I don't think this item is very urgent. Users can upload any kind of image and it will look good on RSR. There's no real need for an "edit your image" function.
