### ISSUE TITLE
I can add an update to a different organisations' project

### ISSUE THREAD

**Issue by CharlotteSoed** [akvo/akvo-rsr#908]
Hi guys,

Browser: Safari
URL: http://gnwp.akvoapp.org/en/project/2233/update/

I can add an update to this GNWP project with my Akvo account. This shouldn't be possible, as Akvo is not a partner of the project. 

![screen shot 2014-11-10 at 15 34 44](https://cloud.githubusercontent.com/assets/4288835/4977381/cbcf4be8-68e6-11e4-940f-a0cd68f5fa66.png)

**Comment by adriancollier** [comment]
No longer valid after the v3 release.
