### ISSUE TITLE
Make pages valid html5

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#935]
At the moment pages are not valid html5. Quick research points to the piwik template tag. A guess is that the noscript tag that now is in the head should not include a `<p>`. But I know noscript is allowed in the <head> in html5, but maybe not with p children? As I said, this was just a guess - but pages should be valid!

**Comment by adriancollier** [comment]
Is this still an issue @kardan ? Is there anything we might need from Piwik to resolve?

**Comment by kardan** [comment]
A quick review revels more issues now. So we should probably review pages and make sure they are valid. Looks like most are simple things to fix, like escaping & characters in URL and issues like that.

**Comment by kardan** [comment]
We should extend the "pages" (https://github.com/akvo/akvo-rsr/tree/develop/akvo/rsr/tests/pages) tests to validate response and not just look for response code.
