### ISSUE TITLE
Duplicate benchmarks

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#937]
A number of projects have benchmark duplicates, meaning the Benchmark bojects have the same foreign key value for name, category and project. Running this SQL shows all projects where this is a problem:

```sql
select project_id, category_id, name_id, value, count(*)
  from rsr_benchmark
  group by project_id, category_id, name_id
  having count(*) > 1
```

The main source of this problem looks to be the Cordaid IATI XML; there are activities with the same result/indicator/title (the tag we map to benchmark names), resulting in multiple benchmark objects with identical FKs to Project, Category and Benchmarkname. I haven't checked if all projects that have this problem are Cordaid projects.

The technical fix for this is to add a unique_together constraint to the Benchmark model. However this will likely break the next Cordaid import following after applying such a fix so either Cordaid's XML has to be fixed or we need some strategy for identifying dupes in the XML source. This is complicated by the fact that in some cases the Cordaid data is "legitimate" but our interpretation of it results in duplicates. 

Example from activity NL-KVK-41160054-107205, there is both an exact copy and a relult that is different but we interpret it as same:

```xml
    <result type="2">
      <title>Organizations with increased capacities re DRR</title>
      <indicator measure="1" akvo:indicator-id="130">
        <title>Local organizations with increased capacity in (CM)DRR</title>
        <period>
          <period-start iso-date="2012-01-01"></period-start>
          <period-end iso-date="2013-06-30"></period-end>
          <target value="6.00" />
        </period>
      </indicator>
    </result>
    <result type="2">
      <title>Organizations involved in collaborations re DRR</title>
      <indicator measure="1" akvo:indicator-id="130">
        <title>Local organizations with increased capacity in (CM)DRR</title>
        <period>
          <period-start iso-date="2012-01-01"></period-start>
          <period-end iso-date="2013-06-30"></period-end>
          <target value="6.00" />
        </period>
      </indicator>
    </result>
...
    <result type="1">
      <title>Communities implementing measures to reduce vulnerability</title>
      <indicator measure="1" akvo:indicator-id="130">
        <title>Local organizations with increased capacity in (CM)DRR</title>
        <period>
          <period-start iso-date="2012-01-01"></period-start>
          <period-end iso-date="2013-06-30"></period-end>
          <target value="22.00" />
        </period>
      </indicator>
    </result>
```

**Comment by KasperBrandt** [comment]
We've switched from goals/benchmarks to results/indicators, so this should be no issue anymore.
