### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-rsr#948]
We should add translations back into RSR v3:

- [x] Mark all strings as translatable
- [x] Translate strings
  - @lauraroverts manages this, French and Spanish will be done by May 22nd
- [x] UI for selecting a language  (@loicsans?)
- [x] Implement translations into RSR
- [x] Configure Nginx to not rewrite supported languages

## Test plan
GIVEN all RSR pages
WHEN viewing the page
THEN a language selector is present in the project header

GIVEN that RSR is displayed in a language
WHEN viewing the language selector
THEN this language should be indicated by a flag
AND this language should not appear in the dropdown list

GIVEN the language selector
WHEN a language is switched
THEN the user should stay on the same page
AND the page should be shown in the selected language

GIVEN the three unsupported languages (ru, nl, de)
WHEN the user tries to visit those (e.g. through /ru/projects/)
THEN the user should be redirected to the English version

**Comment by KasperBrandt** [comment]
Duplicate of #1421

**Comment by lauraroverts** [comment]
Spanish and French translations in Transifex are ready to be published

**Comment by kardan** [comment]
@loicsans the back end stuff is soon done. Just wanted to say that we soon need a way to select RSR language.

**Comment by kardan** [comment]
I guess we can just remove supported languages from 
https://github.com/akvo/akvo-provisioning/blob/master/puppet/modules/rsr/templates/nginx-extra-server.conf.erb#L5

There is some questions:
- we also talked about redirecting non supported languages to the default en. 
- should we allow "naked" calls without a language, or also redirect those to /en/..

**Comment by kardan** [comment]
Issue for Nginx conf: https://github.com/akvo/akvo-provisioning/pull/172

**Comment by rumca** [comment]
I've found a few places where the translations don't seem to be quite right. Things I've noticed so far:

* Content on the advanced filters either isn't translated or sometimes doesn't appear correctly. For example the country filter occasionally doesn't appear translated for French or Spanish. I've also seen the french country list occasionally appear in Spanish.
* I think this one can't be fixed (assuming it takes sectors directly from the admin) but the advance filter "Sector" drop down is always in English.
* On project listings on update listings, when you click to show the map (this string is correctly translated) the "Hide Map" isn't translated, and once you have clicked it and the map is minimised the "Show Map" string reverts to english.
* On the view all updates page the "by <Username>" string isn't correctly translated. Same on the actual update page, where you can see the list of other updates on the right hand-side. The actual update itself has the string translated.

**Comment by rumca** [comment]
Also, not sure if it's intentional or not but clicking the akvorsr logo in the top left corner always resets the language to English (as it links to the `/en/projects`)

**Comment by rumca** [comment]
This one could be correct, but for the "Registration" and "Sign in" pages we translate everything except the page headers. So for example we still have Sign in across the top for Spanish and French (whereas I was expecting Enregistrement and Registro). Please disregard if OK.
