### ISSUE TITLE
Update how images are presented

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#953]

**Comment by adriancollier** [comment]
We have these requirements for images:

- [ ] Make it possible to access the original high res version of the image
- [ ] Create a set of standard thumnails that can be used for all images
- [ ] Ensure we can handle the display of different aspect ratios
- [ ] Make images responsive to the screen size
- [ ] Ensure users can upload a high res image (larger file size limit, currently 2MB, suggesting maybe 8MB?)

**Comment by kardan** [comment]
We need to config 
**Nginx**
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
https://github.com/akvo/akvo-provisioning/blob/develop/puppet/modules/rsr/manifests/config.pp#L34

**RSR**
https://docs.djangoproject.com/en/1.6/ref/settings/#std:setting-FILE_UPLOAD_MAX_MEMORY_SIZE

**Comment by kardan** [comment]
https://github.com/akvo/akvo-provisioning/pull/129 will enable 8mb in Nginx
