### ISSUE TITLE
Aidstream+ work

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#954]
to collect items from the 2 day workathon

**Comment by kardan** [comment]
Should https://github.com/akvo/akvo-rsr/tree/954_aidstream be spared the guillotine?

**Comment by adriancollier** [comment]
I think we can remove this now, the useful work related to the DRF endpoints has already been salvaged. (I think)

**Comment by kardan** [comment]
@KasperBrandt @zzgvh you agree with @adriancollier ?

**Comment by KasperBrandt** [comment]
I do, yes
