### ISSUE TITLE
Update view on redesign

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#980]
A request came in from a partner to be able to connect a project update with more than one project.

After some discussion it seems that the issue here is where projects are related, updates are often copied from one to the other to ensure that this can be seen.

To resolve the requirement "To be able to see project updates from related projects" I suggest the following:

In the update view (e.g. http://rsr.redesign.akvo-ops.org/project/2042/update/5895/) we have a list of updates as present labelled: Latest updates from this project
Additionally on this page, we have another list of updates labelled: Latest updates from related projects.

To populate this list we should use the connection information that is presented within the hierachy (http://rsr.redesign.akvo-ops.org/project/2486/hierarchy/) and identify whether each update comes from a Parent, Sibling or Child project.

This would result in 2 lists on the page - we could combine them also, but we will need to look at 2 main considerations:

1. Projects where related project updates are not desired (we should be able to turn this off somewhere - probably at Akvo Pages setup level).
2. How we clearly distinguish updates from different projects (iconography)

**Comment by lauraroverts** [comment]
Won't be done
