### ISSUE TITLE
Content Owner ID and Organisation Account Types

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#988]
We have a content owner flag within RSR on both Projects and Organisations. At the moment this is not utilised often, but we have several situations that would benefit from having this populated.

1. Every project in RSR should have a Content Owner.
This flag should take the place of the existing contractual link that is understood as Support Partner in Akvo.
This will NOT replace the presence of a Support Partner on projects.
This WILL show us who is responsible for the project content and under which contract the project is being published.

2. Every organisation in RSR should have a Content Owner.
This flag should determine who has given us the information about the organisation.
An organisation should be able to "Claim" their organisation page (we will need a process for this, but could remain manual in the short term).
Content on an organisation provided by the organisation itself should take precendence over content delivered by 3rd parties.

3. The Organisation Account Type of an organisation should determine if the organisation can be a content owner.
Free accounts should not be Owner enabled.

4. Users should only be able to assign the Owner ID of their organisation (or the Content Owner of their Organisation) to new projects and organisations.

5. The API should have permissions setup based on the Content Owner ID.

6. Akvo Pages should be modified to allow for the option to populate with only Content Owner ID projects.
This should allow for the situation in which a partner is the content owner of a project and has the project listed within their Akvo Pages, but they are not a working partner on the project themselves.

**Comment by nadiagorchakova** [comment]
This issue was moved to akvo/akvo-product-design#168
