### ISSUE TITLE
Add Data Export Options

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#993]
- [x] Link to an XML / JSON API call to see all the project data for this project
- [x] Link to IATI file of a project
- [x] Link to download this information as PDF

**Comment by adriancollier** [comment]
We should add links to the Project Extrta resource:"
http://rsr.akvo.org/rest/v1/project_extra/576/?format=xml
http://rsr.akvo.org/rest/v1/project_extra/576/?format=json

**Comment by KasperBrandt** [comment]
Don't know where we are going to place this exactly ( @loicsans / @gabemart ), but I think we can also include a link to the (on-the-fly generated) IATI file of the project.

**Comment by adriancollier** [comment]
:+1:

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN the project main page
WHEN viewing the project footer
THEN four data export options should be visible: RSS, XML, JSON and IATI

GIVEN the XML and JSON data exports
WHEN the user is not logged in
THEN the user should be redirected to the login page first
