### ISSUE TITLE
Map Pop Ups

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-rsr#999]
Define and implement the pop up elements to be displayed when clicking on an icon on maps:

- [x] Project pop up
- [x] Organisation pop up
- [x] Update pop up

1st cut of the requirements here - we can review and add to these later on:

Project should include:
- Thumbnail image from the core project image
- Title of the project
- Link to the project page

Organisation should include:
- Thumbnail image of the org logo
- Name of the organisation
- Link to the organisation page

Update should include:
- Thumbnail of the media (image or video)
- Title of the update
- Link to the update page

**Comment by adriancollier** [comment]
This is implemented and working.

**Comment by KasperBrandt** [comment]
No test plan needed, popups stayed the same as before (same as v2 as well)
